eclipse/smarthome

bundles/config/org.eclipse.smarthome.config.core/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

Suggestion for type converting the fields in configuration classes and support for fields in superclasses.
Also fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=456320

Added superclass fields and configuration type conversion

---

bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext

Signed-off-by: Alex Tugarev <telekom@tugarev.de>

Support for thing ids starting with numeric characters in Thing DSL. #455969

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

Fixed integer primitive type in configuration

---

bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java

Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com> (github: paulianttila)

Improved UPnP implementation to find service from correct namespace

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandlerFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Fixed the following 3 bugs:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=456016
https://bugs.eclipse.org/bugs/show_bug.cgi?id=456214
https://bugs.eclipse.org/bugs/show_bug.cgi?id=456528

ThingHandler & Thing Manager Bugfixes

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/console/InboxConsoleCommandExtension.java
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/link/ItemChannelLinkOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/setup/ThingSetupManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingLinkManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/AbstractLinkRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/InboxResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

Incorporated review comments for item-extensions PR.

---

docs/sources/howtos/bindings.md

fix location of thing XML files

---

bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericItemChannelLinkProvider.java

#457808: Fixed NPE in GenericItemChannelLinkProvider.

---

bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java

If the OSGi framework is shut down I get NPEs for a few jUPnP threads.
The member upnpService is null, so the call to
upnpService.getControlPoint() causes the NPE.
I added some more tests to be more safe.
Exception in thread "jupnp-66" java.lang.NullPointerException
at org.eclipse.smarthome.io.transport.upnp.UpnpIOServiceImpl$UpnpSubscriptionCallback.ended(UpnpIOServiceImpl.java:75)
at org.jupnp.controlpoint.SubscriptionCallback$2.ended(SubscriptionCallback.java:216)
at org.jupnp.model.gena.RemoteGENASubscription.end(RemoteGENASubscription.java:82)
at org.jupnp.protocol.sync.SendingUnsubscribe$1.run(SendingUnsubscribe.java:83)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) …

UPnP transport: fix NPE on ESH shutdown

---

targetplatform/esh-clean-up.xml
targetplatform/esh-formatter.xml

This configuration files for the formatter and the clean up function of the Eclipse IDE should help that we are using the same coding style.

add eclipse formatter and clean up config

---

docs/sources/architecture/index.md
docs/sources/architecture/thing-definition.md
docs/sources/development/faq.md
docs/sources/index.md

added new faq section and fixed a few minor issues in the docs

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/setup/ThingSetupManagerResource.java

Signed-off-by: Thomas Höfer <t.hoefer@telekom.de>

Added operation to update home group label

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

Signed-off-by: Alex Tugarev <telekom@tugarev.de>

Added missing "unbind" method parameters

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/beans/ThingTypeBean.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/setup/ThingSetupManagerResource.java

Extended ThingTypeBean with bridge information.
Added setGroups in ThingSetupManagerResource.
Changed path for setLabel in ThingSetupManagerResource.

Extended REST API for Thing Types and ThingSetupManager

---

bundles/model/org.eclipse.smarthome.model.persistence/OSGI-INF/persistencemanager.xml

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=460278

add event.topics property for persistence manager

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchService.java
bundles/model/org.eclipse.smarthome.model.core/OSGI-INF/folderobserver.xml

Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=460280
Signed-off-by: Kai Kreuzer <kai@openhab.org> (github: @kaikreuzer)

Added immediate=true and fixed a potential NPE

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com> (github: paulianttila)

Improved binding configuration handling

---

binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java

Fixed wrong unit initialization: will now work with Celsius/Fahrenheit

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

Signed-off-by: Alex Tugarev <telekom@tugarev.de>

ThingSetupManager returns created Thing instances

---

bundles/core/org.eclipse.smarthome.core.library.test/src/test/java/org/eclipse/smarthome/core/library/types/PointTypeTest.java
bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/CoreItemFactory.java
bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/items/LocationItem.java
bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java
bundles/model/org.eclipse.smarthome.model.item.ui/src/org/eclipse/smarthome/model/ui/contentassist/ItemsProposalProvider.xtend
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

Introducing PointType and LocationItem

---

bundles/model/org.eclipse.smarthome.model.thing.tests/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueThingHandlerFactoryX.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueThingTypeProvider.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest2.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend

If a ThingHandlerFactory is removed, the Things created by it will not be removed.
If a ThingHandlerFactory is added, Things will be created/updated.

Fix Bug #461153

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/InboxOSGITest.groovy

timing issues - test was not reliable

removed InboxOSGiTest#"assert that expiration thread is working" 

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandlerCallback.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Added possibility to send commands from a binding.

---

docs/sources/development/guidelines.md
docs/sources/index.md

created some initial coding guidelines

---

docs/sources/architecture/thing-definition.md
docs/sources/howtos/bindings.md

Updated documentation for thing properties

---

bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/discovery/MDNSDiscoveryService.java

fixes bug in mDNS discovery as described here
https://github.com/openhab/openhab2/pull/164

Bugfix: add thingDiscovered() calls on initialization

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

New PR for https://github.com/eclipse/smarthome/pull/253

Added REST interface to save item bean

---

bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueThingHandlerFactory.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext

Signed-off-by: Thomas Eichstädt-Engelen <thomas@openhab.org>

Fixes 461662 - Hyphen not supported in thing files

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java

Added 'getStatus' method to thing interface for backward compatibility.

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

Bug 465340: BaseThingHandler.updateThing() method default function override

Fixed 465340 : Changed thing in BaseThingHandler to protected.

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

As per the discussion here https://www.eclipse.org/forums/index.php/t/1066032/ and bug 465481

Remove child things/items when deleting a bridge

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameterBuilder.java

I've added setter methods to this class as there are (currently) 15 parameters in the constructor which I think is too many - it makes the code difficult to read and is more prone to error.

Added setter methods to config parameter

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java

removeOlderResults may return null, check for null added

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/setup/ThingSetupManagerOSGiTest.groovy

Test for https://github.com/eclipse/smarthome/pull/270.

Added test for recursive removal of things in ThingSetupManager.

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/META-INF/MANIFEST.MF

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=465765

mqtt transport: fix import-package

---

bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

made valueOf static as it cannot be found by the TypeParser otherwise

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/BindingBaseClassesOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandlerFactory.java

Fixed #465762: Can not updateStatus() in bridgeHandlerInitialized()

---

docs/sources/development/contributing.md

corrected a few formulations

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingStatusInfo.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ThingStatusInfoBuilder.java

Added null checks to ThingStatusInfo and ThingStatusInfoBuilder.

---

bundles/core/org.eclipse.smarthome.core.library.test/src/test/java/org/eclipse/smarthome/core/library/types/PointTypeTest.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java
bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/Sitemap.xtext
bundles/ui/org.eclipse.smarthome.ui.classic/META-INF/MANIFEST.MF
bundles/ui/org.eclipse.smarthome.ui.classic/OSGI-INF/mapviewrenderer.xml
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/mapview.html
bundles/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/MapviewRenderer.java

Adding MapView to display Location items in Sitemap as done in OH1

---

bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/types/ArithmeticGroupFunction.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

This calculates the number of items in the group matching the regular expression passed in parameter
* Group:String:COUNT(".") will count all items having a string state of one character
* Group:String:COUNT("[5-9]") will count all items having a string state between 5 and 9
Remove unwanted files

Adding COUNT operator to Group item (reported from OH1)

---

docs/sources/architecture/configuration.md

Changes advanced from attribute to element to correctly reflect implementation

Update documentation regarding parameter.advanced

---

bundles/core/org.eclipse.smarthome.core.thing/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingStatusInfo.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Beautified the thing status logging

---

bundles/ui/org.eclipse.smarthome.ui.classic/OSGI-INF/webappservlet.xml
bundles/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/servlet/WebAppServlet.java

make default sitemap name configurable

---

bundles/model/org.eclipse.smarthome.model.persistence/.project
bundles/model/org.eclipse.smarthome.model.persistence/OSGI-INF/persistenceextension.xml

fixed package name that was forgotten in a refactoring

---

bundles/core/org.eclipse.smarthome.core.library.test/src/test/java/org/eclipse/smarthome/core/library/items/DimmerItemTest.java
bundles/core/org.eclipse.smarthome.core.library.test/src/test/java/org/eclipse/smarthome/core/library/items/SwitchItemTest.java
bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/items/DimmerItem.java
bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/items/RollershutterItem.java

This commit also contains work of 'Chris Jackson <chris@cd-jackson.com>'
who started the SwitchItemTest and DimmerItemTest implementation.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=467739

enhance getStateAs for DimmerItem and RollershutterItem

---

addons/binding/org.eclipse.smarthome.binding.yahooweather/README.md

added readme for Yahoo weather binding

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/OSGI-INF/sitemaprest.xml

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=468298

removed outdated reference to modelRepository

---

docs/sources/architecture/configuration.md

Update documentation for parameter.groupName

---

addons/binding/org.eclipse.smarthome.binding.yahooweather/about.html

PLEASE DO NOT MERGE YET - pending approval of the IP team!

Provided Yahoo dependency information

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java

Adding Items, Links and Things safely in ThingSetupManager.

Catching Throwable instead of Exception in AbstractRegistry.

---

tools/archetype/binding/src/main/resources/archetype-resources/META-INF/MANIFEST.MF
tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java

Manifest imports updated
Signed-off-by: YordanDZhelev <zhelev.yordan@gmail.com>

Unused imports removed from the HandlerFactory

---

bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/test/ThingTypesTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/ConfigDescriptionsTest.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/ThingTypesTest.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/BridgeTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelGroupTypeConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelGroupTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingDescriptionReader.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Channel.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ChannelBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/BridgeType.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelDefinition.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingType.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/beans/ChannelBean.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/beans/ChannelDefinitionBean.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/util/BeanMapper.java

As discussed here -: https://www.eclipse.org/forums/index.php/t/1015656/
I want to do more testing before this is merged - I've added a test case and it seems ok, but I'd also like to do a real-life test in a few days (hopefully!).
Feel free to review...

Add support for properties in channel definitions

---

docs/sources/development/guidelines.md

a few additions to the guidelines

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

Added addThing with properties to ThingSetupManager

---

addons/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeDiscoveryParticipant.java

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466236

removed TTL from discovery result, jUPnP takes care of TTL itself

---

docs/css/styles.css
docs/js/init.js

Fixed linkage of h3 elements in the documentation.

---

bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/types/ArithmeticGroupFunction.java

Fixing typo in comments on Count Operator

---

bundles/core/org.eclipse.smarthome.core.library.test/src/test/java/org/eclipse/smarthome/core/library/types/PointTypeTest.java
bundles/core/org.eclipse.smarthome.core.library/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

Correction of toString() bug

---

docs/_includes/documentation-menu.html
docs/documentation/concepts/discovery.md
docs/documentation/development/bindings/discovery-services.md

#467177: Documented inbox and discovery concepts

---

extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC020.xml
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/HueBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Added support for Hue Go (LLC020) to hue binding

---

bundles/ui/org.eclipse.smarthome.ui.classic/snippets/text_link.html
bundles/ui/org.eclipse.smarthome.ui.classic/web/WebApp/Design/Render.css

Tested with several sitemaps, issue mentioned in #375 should be fixed.

Fix Classic UI CSS issues mentioned in #375

---

bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/bindingresource.xml

remove incorrect service reference

---

docs/documentation/community/downloads.md

Fixed bug 472987: download links to Designer 0.8.0 SNAPSHOT are broken

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java
docs/documentation/development/bindings/thing-definition.md

Add battery-level system channel

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandler.java

fix wording in JavaDoc of handleRemoval

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Fixed bug 473784: fix status updates for reachable=true/false

---

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/__bindingIdCamelCase__BindingConstants.java
tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/handler/__bindingIdCamelCase__Handler.java

Bug 472753 fixed: enhance maven archetype for status handling

---

docs/documentation/development/bindings/thing-definition.md
docs/documentation/development/bindings/xml-reference.md

Update documentation to support HTML in labels

---

bundles/io/org.eclipse.smarthome.io.console/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/ItemConsoleCommandExtension.java

I have added commands to clear and remove items.
Bug: 474990

Fixed bug 474990: adding console commands to clear and remove items

---

extensions/transform/org.eclipse.smarthome.transform.map/OSGI-INF/mapservice.xml
extensions/transform/org.eclipse.smarthome.transform.map/src/main/java/org/eclipse/smarthome/transform/map/internal/MapTransformationService.java

* remove reference to non-existing deactivate method
* apply formatter (remove all that trailing whitespaces)

transform map service reference to missing method

---

bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/AbstractAsyncBundleProcessor.java
bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java

The implementation of config.xml made use of bundle.getEntryPaths() which only looked for bundle-internal resources, but not for resources contained in fragments. So a patching of these resources was not possible. This PR changes the resolving behavior of xml resources to also find them in fragments.

make bundles with config.xmls patchable

---

bundles/io/org.eclipse.smarthome.io.console.eclipse/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.console.karaf/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.console.rfc147/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.wemo/META-INF/MANIFEST.MF

* console bundles
* wemo binding
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476024
This commit does not solve the bug completely, but four bundles.

remove require-bundle

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/PointTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

Correction of bug #476377

---

extensions/binding/org.eclipse.smarthome.binding.wemo/OSGI-INF/WemoHandlerFactory.xml

removed declared service dependency which is not required anymore

---

docs/documentation/concepts/events.md

Docu, Events: Fix some typos.

---

bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/ItemConsoleCommandExtension.java

set items console command default to list

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/items/ItemUpdaterOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core/OSGI-INF/itemupdater.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemUpdater.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemStateChangedEvent.java
distribution/smarthome/logback_debug.xml
docs/documentation/concepts/events.md

Introduced ItemStateChangedEvent.

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/link/LinkEventOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ItemChannelLinkRegistry.xml
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ItemThingLinkRegistry.xml
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/LinkEventFactory.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemThingLinkRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/dto/AbstractLinkDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/dto/ItemThingLinkDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/AbstractItemChannelLinkRegistryEvent.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/AbstractItemThingLinkRegistryEvent.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/ItemChannelLinkAddedEvent.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/ItemChannelLinkRemovedEvent.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/ItemThingLinkAddedEvent.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/ItemThingLinkRemovedEvent.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/LinkEventFactory.java
bundles/io/org.eclipse.smarthome.io.rest.core/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/itemchannellinkresource.xml
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/link/ItemChannelLinkResource.java
docs/documentation/concepts/events.md

Fixed #464953 : Added events for links.

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/events/ThingEventFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/events/ThingStatusInfoChangedEvent.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
distribution/smarthome/logback_debug.xml
docs/documentation/concepts/events.md

Added ThingStatusInfoChangedEvent.

---

bundles/io/org.eclipse.smarthome.io.transport.upnp.test/.classpath
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/.project
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/.settings/org.eclipse.jdt.core.prefs
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/.settings/org.eclipse.jdt.groovy.core.prefs
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/about.html
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/build.properties
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/pom.xml
bundles/io/org.eclipse.smarthome.io.transport.upnp.test/src/test/groovy/org/eclipse/smarthome/io/transport/upnp/test/UpnpIOServiceTest.groovy
bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOService.java
bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java
bundles/io/pom.xml

added methods to unregister participants, unsubscribe from a GENA subscription and remove status polling threads from the upnp transport bundle

Fix the upnp transport bundle

---

CONTRIBUTING

Signed-off-by: YordanDZhelev <zhelev.yordan@gmail.com>

Non working url in CONTRIBUTING file updated.

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Addressing issue
https://bugs.eclipse.org/bugs/show_bug.cgi?id=465480

fix wrong status update for bridge child things

---

pom.xml

Signed-off-by: VentsislavIliev <ventsislav.iliev@musala.com>

New build profile added for JavaDoc generation.

---

bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/test/ThingTypeI18nTest.groovy

Fixed failing i18n tests.

---

extensions/binding/org.eclipse.smarthome.binding.ntp/.classpath
extensions/binding/org.eclipse.smarthome.binding.ntp/.project
extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/binding/binding.xml
extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.ntp/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.ntp/OSGI-INF/ntpDiscovery.xml
extensions/binding/org.eclipse.smarthome.binding.ntp/OSGI-INF/ntpHandlerFactory.xml
extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
extensions/binding/org.eclipse.smarthome.binding.ntp/build.properties
extensions/binding/org.eclipse.smarthome.binding.ntp/pom.xml
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/NtpBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/discovery/NtpDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/internal/NtpHandlerFactory.java

NTP Binding initial contribution

---

bundles/io/org.eclipse.smarthome.io.rest.test/src/test/groovy/org/eclipse/smarthome/io/rest/test/filter/CorsFilterTest.groovy
bundles/io/org.eclipse.smarthome.io.rest/OSGI-INF/corsfilter.xml
bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/Constants.java
bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/filter/CorsFilter.java
bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/resources/RootResource.java
distribution/smarthome/conf/smarthome.cfg

Corresponding Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=478037
Signed-off-by: Antoine Besnard <stratehm@hotmail.com>

Add compatibility with HTTP CORS requests

---

features/org.eclipse.smarthome.feature.designer/feature.xml

Fixes https://www.eclipse.org/forums/index.php/t/1071222/

fixed Designer dependencies

---

extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java

fixes a potential NPE if no refresh parameter is configured

---

bundles/ui/org.eclipse.smarthome.ui.classic/snippets/mapview.html

Fix "mixed content" warning on mapviews
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>

Fix "mixed content" warning on mapviews

---

bundles/core/org.eclipse.smarthome.core/OSGI-INF/OSGiEventManager.xml
bundles/core/org.eclipse.smarthome.core/OSGI-INF/itemupdater.xml

Changed ItemUpdater and OSGiEventManager to "immediate" DS components.

---

bundles/model/org.eclipse.smarthome.model.rule/pom.xml
bundles/model/org.eclipse.smarthome.model.sitemap/pom.xml

* Remove dependencies that resolve to the same artifact
* Use property for groupId

pom cleanup of model

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/Activator.java

fixed a minor typo in activator of config core bundle

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ChannelStateDescriptionProvider.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Channel.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ChannelBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTOMapper.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingTypeRegistry.java
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend

Added channel type UID to Channel.

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/dto/ConfigDescriptionDTOMapper.java

Provided access to ConfigDescriptionDTOMapper methods

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/items/LocationItemTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/PointTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/LocationItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

- LocationItem delegates distanceFrom calculation to PointType
- Moving distanceFrom calculation details in PointType
- Enhancing PointType constructor as in PR #3410 of OH1
- Splitted tests between respectives tests classes for LocationItem and PointType

Bug #482188 modification :

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightDiscoveryServiceOSGITest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightState.groovy
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/PAR16_50_TW.xml
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/HueBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Added OSRAM PAR16 50 TW bulbs (autodiscovery is possible) and some workaround code for correct On-Off management of these specific bulb type.

Bug 481802 - Osram Lightify PAR16 50 Tunable White not autodiscovered and not manageable

---

bundles/ui/org.eclipse.smarthome.ui.icon/OSGI-INF/iconservlet.xml

The modified function is not declared to be called if a modification of the configuration is done.

declare modified function

---

bundles/core/org.eclipse.smarthome.core.test/ESH-INF/i18n/resourceName.properties
bundles/core/org.eclipse.smarthome.core.test/ESH-INF/i18n/resourceName_en.properties
bundles/core/org.eclipse.smarthome.core.test/ESH-INF/i18n/resourceName_fr.properties
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/i18n/I18nProviderOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/i18n/I18nProvider.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java
docs/documentation/features/internationalization.md

Added getText operation with arguments in I18nProvider

---

bundles/model/org.eclipse.smarthome.model.persistence.tests/src/test/java/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensionsTest.java
bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensions.java

Re-added previousState from OH1 and added some tests.
Signed-off-by: Manfred Bergmann <mb@software-by-mabe.com>

added previousState method to PersistenceExtensions including tests.

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/UID.java

Fixed thing deserialization with serialized channel type UID.

---

bundles/ui/org.eclipse.smarthome.ui.icon/pom.xml
bundles/ui/org.eclipse.smarthome.ui/pom.xml

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=464662

use consistent group id for UI bundles

---

extensions/binding/pom.xml
extensions/pom.xml
extensions/transform/pom.xml
extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/pom.xml
extensions/ui/iconset/pom.xml
extensions/ui/org.eclipse.smarthome.ui.basic/pom.xml
extensions/ui/org.eclipse.smarthome.ui.classic/pom.xml
extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml
extensions/ui/pom.xml

fix group id of extensions (use singular similar to binding(s))

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/mapview.html

Signed-off-by: Hakan Tandogan <hakan@tandogan.com> (github: hakan42)

Fix mixed content warnings on mapviews in basic ui too

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/dialog.linkchannel.html

Paper UI: Sorting and filtering item list in channel link dialog.

---

extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/discovery/WemoDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/internal/WemoHandlerFactory.java

Fix #606: Potential NPE in wemo discovery

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

Bug: https://github.com/eclipse/smarthome/issues/663

Implement hashCode and equals in PointType

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

store returned objects to prevent multiple creations

---

docs/documentation/community/contributing.md

Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

Update contributing instructions after move to GitHub repository

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightState.groovy
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Fixes #686 .
Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

Make sure the workaround for Osram lightbulb is not applied to other lights as well

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationTest.groovy

Issue #698  get AutomationIntegrationTest more stable

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Rule.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuntimeRule.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ModuleTypeGSONParser.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/AutomationResourceBundlesEventQueue.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/RuleResourceBundleImporter.java
bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java
bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/dto/EnrichedRuleDTO.java
bundles/automation/org.eclipse.smarthome.automation.sample.handler/ESH-INF/automation/rules/DemoScriptRule.json
bundles/automation/org.eclipse.smarthome.automation.sample.handler/ESH-INF/automation/rules/SampleRuleByTemplate.json

Fix the rule creation by template

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationTest.groovy

Signed-off-by: Marin Mitev <marin.mitev@gmail.com>

refix tests for item state change events

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingTypeRegistry.java

fix dropped localization

---

targetplatform/EclipseSmartHome.setup

increase xtext version range for IDE setup

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/JSONResponse.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedGroupItemDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

Do some format cleanups
Related to: https://github.com/eclipse/smarthome/pull/505

formatter cleanups

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

reverted accidental change of #505

---

targetplatform/EclipseSmartHome.setup

increase valid range for mwe plugins

---

targetplatform/EclipseSmartHome.setup

fix version ranges

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.configuration.js

Related to: https://github.com/eclipse/smarthome/pull/559

paper ui: thing cfg page shows only first channel of group

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/groovy/org/eclipse/smarthome/io/rest/core/test/item/ItemResourceOSGiTest.groovy
bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/groovy/org/eclipse/smarthome/io/rest/core/test/item/ItemResourceOSGiTestWithTransformTest.groovy
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/binding/BindingResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/setup/ThingSetupManagerResource.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java

add more localization to the REST API

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/extensions/ExtensionEventFactory.java

fixed the deserialisation of extension failure events

---

bundles/ui/org.eclipse.smarthome.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/AbstractResourceIconProvider.java
extensions/ui/org.eclipse.smarthome.ui.classic/ESH-INF/config/config.xml
extensions/ui/org.eclipse.smarthome.ui.classic/OSGI-INF/webappservlet.xml
extensions/ui/org.eclipse.smarthome.ui.classic/build.properties
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/buttons.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/colorpicker.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/group.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/selection.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/setpoint.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/text.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/text_link.html
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/WebAppConfig.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/ColorpickerRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/GroupRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/PageRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SelectionRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SetpointRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SliderRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/TextRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/servlet/WebAppServlet.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/render/WidgetRenderer.java

- fixed Classic UI to correctly request icons with format parameter
- added possibility to configure the icon format
- added the Classic UI as a configurable service, so that is appears as a service in the Paper UI
See problems mentioned in https://community.openhab.org/t/various-icon-woes/4895/6

Classic UI fixes regarding icons

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuntimeRule.java

The rule engine has to set default values for missing configuration values.

fix for Request failed while updating a rule #708 and #706

---

docs/documentation/development/testing.md

added Logging configuration to testing documentation

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandlerCallback.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Throw Exception in case the ManagedThingProvider cannot handle an update

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/ESH-INF/automation/templates/SimpleTestTemplate.json
bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationTest.groovy

fix for issue #740 get automation integration tests stable

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/BindingBaseClassesOSGiTest.groovy

fixed just a minor typo.
groovy... :santa:

fixed typo in BindingBaseClassesOSGiTest

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/BindingBaseClassesOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

revert the configuration if updateConfiguration() fails

---

bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AbstractCommandProvider.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommand.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandEnableRule.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandExport.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandImport.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandList.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandRemove.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommands.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandsPluggable.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/CommandlineModuleTypeProvider.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/CommandlineRuleImporter.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/CommandlineTemplateProvider.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/Printer.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/Utils.java

Improve automation console commands

---

tools/ref-tag/create.sh

Create tag to reference a specified commit with a version modifier assigned.

create ref-tag creation script

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.rules.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/shared.properties.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/dialog.addmodule.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/include.config.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/rules.html

New user interface for working with rules. Allows to add, update and delete rules. Also allows to configure multiple triggers/actions/conditions in a rule.

Initial Rule Editor

---

bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/ruleengine.xml
bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/RuleRuntime.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/RuleRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java
bundles/model/org.eclipse.smarthome.model.script.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.script.runtime/OSGI-INF/scriptengine.xml
bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/ScriptRuntime.java
bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/internal/ScriptRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/internal/engine/ScriptEngineImpl.java

The rule engine depends on a started rule runtime.

fix service dependencies

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/main.html

Fixes issue mentioned in openhab/openhab2#548

BasicUI: force disable compatibility mode for IE

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/colorpicker.html
extensions/ui/org.eclipse.smarthome.ui.basic/snippets/group.html
extensions/ui/org.eclipse.smarthome.ui.basic/snippets/main.html
extensions/ui/org.eclipse.smarthome.ui.basic/snippets/rollerblind.html
extensions/ui/org.eclipse.smarthome.ui.basic/snippets/selection.html
extensions/ui/org.eclipse.smarthome.ui.basic/snippets/setpoint.html
extensions/ui/org.eclipse.smarthome.ui.basic/snippets/text_link.html
extensions/ui/org.eclipse.smarthome.ui.basic/web/material-icons.css

This commit changes HTML entities used for icons to match the version of
the icon font being used.

Change icon font character codes

---

bundles/core/org.eclipse.smarthome.core.test/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java

this fixes eclipse/smarthome#592 and openhab/openhab#2945.
Signed-off-by: Thomas Eichstädt-Engelen <thomas@openhab.org>

port changes of DateTimeType to ESH, added DateTimeTypeTest

---

extensions/ui/org.eclipse.smarthome.ui.classic/ESH-INF/config/config.xml
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/WebAppConfig.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java

This is one PR of a series of PRs to sync classicui to ESH.
Relevant PR in oh1: https://github.com/openhab/openhab/pull/2126/files

Add classicui property to disable HTML cache

---

.gitignore
bundles/io/org.eclipse.smarthome.io.console.karaf/pom.xml
features/karaf/pom.xml
features/karaf/src/main/feature/feature.xml
features/pom.xml
pom.xml

Also-By: Markus Rathgeb <maggu2810@gmail.com>

added Karaf feature definitions

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/constants.js

allow hiding of groups menu entry

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/LinkConsoleCommandExtension.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/SetupConsoleCommandExtension.java

Fix mixed console command descriptions

---

features/karaf/src/main/feature/feature.xml

fixes https://github.com/openhab/openhab-distro/issues/30

increase start level for mode.core

---

features/karaf/src/main/feature/feature.xml

fixed fsinternetradio feature by adding upnp dependency

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java

Fix for  #705. 409 Conflict while adding a new rule 

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightState.groovy
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LCT001.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LCT002.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LCT003.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LCT007.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC001.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC006.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC007.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC010.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC011.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC012.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC013.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LLC020.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LST001.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LST002.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LWB004.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LWB006.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LWB007.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LWL001.xml
extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/HueBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStateConverter.java

Alert and Effect added to the Hue binding.

Hue binding alert and effect

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

also applied code formatter on the class

fixes #810

---

bundles/core/org.eclipse.smarthome.core/META-INF/MANIFEST.MF

fixes https://github.com/eclipse/smarthome/issues/836
Signed-off-by: Daniel Walters <danielwalters1@hotmail.com>

Fix missing import

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java

If there is one thing with a channel that references to a non existing
channel type, there is no thing type returned (caused by a NPE).
This change will omit thing types that channel(s) reference(s) to a non
existing channel type and returns the remaining ones.
Without this change one corrupt XML leads in a whole non working system.

make the thing-type API more robust about errors

---

extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml

This updates node and NPM to the latest version in the LTS release cycle. 
Signed-off-by: Grady Duncan <gradyduncan@gmail.com>

Update node and npm

---

features/karaf/src/main/feature/feature.xml

added upnp dependency to demo

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Channel.java

improved javadoc on deprecated methods

---

extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/channels.xml

Signed-off-by: YordanDZhelev <zhelev.yordan@gmail.com>

Property readOnly="true" removed form alert channel states.

---

bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/internal/PersistenceManager.java

fixes #863

---

bundles/automation/org.eclipse.smarthome.automation.event.test/src/test/groovy/org/eclipse/smarthome/automation/event/RuleEventTest.groovy

Signed-off-by: Marin Mitev <marin.mitev@gmail.com>

fix issue #878 for rule events - concurrent modification exception

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.rules.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/dialog.ruletemplate.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/rules.html

Allows creation of rules from templates as described here: https://github.com/eclipse/smarthome/issues/773

Allow rule creation from template

---

bundles/config/org.eclipse.smarthome.config.dispatch/OSGI-INF/configdispatcher.xml
bundles/core/org.eclipse.smarthome.core.transform/OSGI-INF/transformationaction.xml
bundles/ui/org.eclipse.smarthome.ui/OSGI-INF/chartprovider.xml

added immediate activation to components

---

bundles/automation/org.eclipse.smarthome.automation.sample.handler/ESH-INF/automation/templates/SampleTemplateDefinitions.json

improved sample template

---

bundles/io/org.eclipse.smarthome.io.multimedia/OSGI-INF/tts_mac.xml

immediately activate mac tts service

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java

Deprecate ItemChannelLinkRegistry.getBoundThings().

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

Deprecate ThingSetupManager.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Allows rendering of Items in configurations as described here https://github.com/eclipse/smarthome/issues/898.

Item support in configurations

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/package.json

This PR adds `gulp serve` so that you can test the UI changes without having to build the jar.

Adding gulp serve

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/handler/BaseModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/BasicModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/internal/Activator.java
bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptModuleActivator.java
bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/factory/ScriptModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.module.timer/src/main/java/org/eclipse/smarthome/automation/module/timer/factory/TimerModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.module.timer/src/main/java/org/eclipse/smarthome/automation/module/timer/internal/Activator.java
bundles/automation/org.eclipse.smarthome.automation.sample.handler/src/main/java/org/eclipse/smarthome/automation/internal/sample/handler/Activator.java
bundles/automation/org.eclipse.smarthome.automation.sample.handler/src/main/java/org/eclipse/smarthome/automation/internal/sample/handler/SampleHandlerFactory.java

Automation API should not prevent the use of Declarative Services #912

---

bundles/automation/org.eclipse.smarthome.automation.java.api.demo/src/main/java/org/eclipse/smarthome/automation/java/api/demo/WelcomeHomeRulesProvider.java
bundles/automation/org.eclipse.smarthome.automation.java.api.demo/src/main/java/org/eclipse/smarthome/automation/java/api/demo/handler/WelcomeHomeHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.java.api.demo/src/main/java/org/eclipse/smarthome/automation/java/api/demo/template/AirConditionerRuleTemplate.java
bundles/automation/org.eclipse.smarthome.automation.java.api.demo/src/main/java/org/eclipse/smarthome/automation/java/api/demo/type/StateConditionType.java
bundles/automation/org.eclipse.smarthome.automation.java.api.demo/src/main/java/org/eclipse/smarthome/automation/java/api/demo/type/TemperatureConditionType.java
bundles/automation/org.eclipse.smarthome.automation.java.api.demo/src/main/java/org/eclipse/smarthome/automation/java/api/demo/type/WelcomeHomeActionType.java
bundles/automation/pom.xml

Apply last changes to this bundle.
Bug: https://github.com/eclipse/smarthome/issues/929

fix automation's Java API demo

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Added select box for integer and decimal type with options as described here: https://github.com/eclipse/smarthome/issues/910.

Select box for integer type with options in configurations

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ChannelStateDescriptionProvider.xml
bundles/core/org.eclipse.smarthome.core/OSGI-INF/itemregistry.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java

Order StateDescriptionProviders by service ranking.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html

corrected location of edit button on modules

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/Activator.java

aligned registerServiceCall for older OSGi versions

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy

Fixed timing issue in test case.

---

bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/GenericCondition.json
bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/ItemModuleTypeDefinition.json

The only functional change is the added "options" list.
The other diffs are due to formatting (removed tabs)

added option information to compare conditions

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

don't call handler on removal if it does not exist

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/SafeMethodCaller.java

In case of a TimeoutException in the SafeMethodCaller, issue a log statement with the current execution position.
So far, we could only see the stack trace of the calling side, but did now have any insights on why the call took so long. Now we at least can see the current execution position, like e.g.:
```
16:18:52.213 [main] DEBUG o.e.s.core.common.SafeMethodCaller - Timeout of 5000ms exceeded, thread ESH-safeCall-3 (25) in state BLOCKED is at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.setCallback(BaseThingHandler.java:168).
```

Log where a TimeoutException occurred

---

targetplatform/smarthome.target

updated TP to use recent versions of JAX-RS Connector and JUPnP

---

bundles/core/org.eclipse.smarthome.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/BindingInfoReader.java

Add support for parameter groups to binding xml

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/storage/ManagedItemProviderOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ManagedItemProvider.java

fixed item loading issue in case the item factory gets added late

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

Signed-off-by: Daniel Walters <danielwalters1@hotmail.com>
Fixes https://github.com/eclipse/smarthome/issues/945

Fix HTTP response code

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SelectionRenderer.java

BasicUI: escape selection HTML attributes, fixes #875

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

Allows grouping of parameters based on the groupName in the configurations. Related issue is https://github.com/eclipse/smarthome/issues/566

Supports parameters grouping in configurations

---

extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SelectionRenderer.java

ClassicUI: escape selection HTML attributes, fixes #874

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

Add null protection when saving item

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTOMapper.java

https://github.com/eclipse/smarthome/issues/981
Channel configuration is now available with this PR.

Add configuration object to ChannelDTO

---

docs/documentation/development/rules/ModuleTypes_schema.json
docs/documentation/development/rules/Rules_schema.json
docs/documentation/development/rules/Templates_schema.json
docs/documentation/features/rules.md

automation json schemas

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

Allows grouping of channels by their groups as described here https://github.com/eclipse/smarthome/issues/561.

Support channel groups

---

extensions/ui/org.eclipse.smarthome.ui.paper/build.properties

removed non-existent entries in bin.excludes

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js

corrected tinycolor location to be correctly added to the packaging

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTOMapper.java

addresses https://github.com/cdjackson/HABmin2/issues/120

add missing label & description to channelDTO

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.itemcontrol.html

Added saturation slider in color widget item as described here https://github.com/eclipse/smarthome/issues/567.

Saturation control in color items

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Rule.java

Add utility constructor without specifing uid of rule. See #882

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

fixes https://github.com/openhab/openhab-distro/issues/124

fixed potential NPE

---

docs/documentation/features/rules.md

This pull request contains the same changes from #1025.

Refactored docs/features/rules.md

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ColorpickerRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/ColorpickerRenderer.java

Added to esh per request from @teichsta. See PR https://github.com/openhab/openhab/pull/4021.

Fixed javascript that was breaking the colorpicker.

---

extensions/ui/org.eclipse.smarthome.ui.basic/ESH-INF/config/config.xml

defined default values for mandatory parameters

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/PointTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

Correction of tests
Review PointType constructor and arguments handling
Code cleanup
Finalized IllegalArgumentException for PointType and DecimalType along with according tests
Code refine
Code refine

Thinking on how to handle unknown values Bug #589

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java

...which sometimes is helpful for troubleshooting

Print groups in item console command

---

docs/documentation/features/rules.md

fix json scheme links

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/InboxOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/factory/ManagedThingProviderOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/setup/ThingSetupManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ManagedThingProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/GenericThingBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingDTOMapper.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/ThingConsoleCommandExtension.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/setup/ThingSetupManagerResource.java
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
distribution/smarthome/conf/things/demo.things
docs/documentation/features/dsl.md
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueBridgeHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightDiscoveryServiceOSGITest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.removething.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.thingconfig.html

Added a label so that users can name their Things

---

features/org.eclipse.smarthome.feature.runtime.automation/feature.xml

removed sample from automation feature

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

paperUI add label to configuration parameters with dropdowns

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.integration.test/pom.xml
bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/build.properties

added ESH-INF to build.properties and json sample to integration tests

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html

reverted Paper UI changes from #768 as they break the thing page

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html

the revert-of-the-revert
...now including a refresh after the ThingType has been fetched in order to show the channels
Also-by: Aoun Bukhari <bukhari@itemis.de>

adapt PaperUI to #768 changing of ThingTypes

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/dto/DiscoveryResultDTOMapper.java

avoids npe in case the DiscoveryResult does not have a thingType defined

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationJsonTest.groovy

Fix Eclipse SmartHome Automation Integration Test - 'assert that a rule from json file is executed correctly'

---

bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/JSONResponse.java

Signed-off-by: Bas Huisman <bhuism@odee.net>

Added exeption logging to REST Exception handler

---

bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/JSONResponse.java

Signed-off-by: Bas Huisman <bhuism@odee.net>

removed static from logger

---

bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/test/ThingTypesTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/ThingTypesTest.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/BridgeTypeConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/BridgeTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingTypeDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/BridgeType.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingType.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/DumbThingTypeProvider.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueThingTypeProvider.java
docs/documentation/development/bindings/thing-definition.md
docs/documentation/development/bindings/xml-reference.md
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js

(Un)listing of ThingTypes

---

extensions/ui/org.eclipse.smarthome.ui.classic/snippets/text.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/text_link.html
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/TextRenderer.java

Correction of Issue #1034

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/BridgeType.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingType.java

fixed build

---

bundles/io/pom.xml

Signed-off-by: Tilman Kamp <tilmankamp@posteo.de>

Changed pom file entry from multimedia to voice.

---

bundles/io/org.eclipse.smarthome.io.voice/src/main/java/org/eclipse/smarthome/io/voice/internal/extensions/InterpretConsoleCommandExtension.java

Signed-off-by: Tilman Kamp <tilmankamp@posteo.de>

Removed String.join (Java 8) dependency

---

features/org.eclipse.smarthome.feature.designer/feature.xml

Signed-off-by: Tilman Kamp <tilmankamp@posteo.de>

Fixed designer's pom.xml

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Registry.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

Fix bug - Missing response for newly created rules without UIDs #1047

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
docs/documentation/development/bindings/thing-handler.md

Notify Things about Bridge status changes.

---

bundles/config/org.eclipse.smarthome.config.xml/META-INF/MANIFEST.MF

Fixes #1147
Signed-off-by: Christoph Schauer <christoph@schauer-itconsulting.de>

Added export packages for xstream

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

REST: added documentation for retrieving the config status of a thing

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelDTOMapper.java

fixes #1151

---

bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/ModuleTypeManagerMockup.java
bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/RuleEngineTest.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

Rule auto mapping implementation #886

---

extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/bridge.xml
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/HueBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java

Add polling interval config for bridge

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/constants.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/main.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js

I had missed these files in #1160 since the formatter does not seem to work if it is executed on a folder and not on an individual file.

applied code formatter Javascript files on Paper UI

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/config/ConfigDescriptionResource.java

Add support for JSONResponse to configuration resource

---

distribution/smarthome/conf/things/demo.things
extensions/binding/org.eclipse.smarthome.binding.yahooweather/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java

- changed type of parameter location from text to integer
- added min attribute for refresh parameter

updated yahoo weather thing type definition

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

fix setup page

---

docs/documentation/development/bindings/how-to.md

documentation updated because of #1164

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

Allows updating the thing label as described here: https://github.com/eclipse/smarthome/issues/1168
Additional information can be easily added to the same request in the future.

Allows thing label update

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.approveinboxentry.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.groupselection.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.thingconfig.html

Groups are removed from things as described here https://github.com/eclipse/smarthome/issues/1014.

Removed groups from things

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js

Related to: https://github.com/eclipse/smarthome/pull/1019#issuecomment-195765624

Paper UI: app.js refers removed groups configuration

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactory.java

Related to: https://github.com/eclipse/smarthome/pull/1172

improve error logging

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/ChangeThingTypeOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ChannelUID.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingFactoryHelper.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingTypeRegistry.java

This is my alternative suggestion to https://github.com/eclipse/smarthome/pull/1177

Changed creation of channels to not require a thing type

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryResultImplTest.groovy
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryResultImpl.java

...which were created before #768

stay compatible with old inbox result entries

---

bundles/core/org.eclipse.smarthome.core.autoupdate/src/main/java/org/eclipse/smarthome/core/autoupdate/internal/AutoUpdateBinding.java

Eclipse SmartHome does not depend on openHAB

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

Saves language selection in the local storage.

Fixed language selection

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

Prevent null pointer exception when there are no channels inside Thingtype in local repository.

Channels bug fix

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

1) Removed top margin between input field and label.
2) Removed default label for text/integer fields.

Parameter config UI modification

---

bundles/core/org.eclipse.smarthome.core/.project

Eclipse SmartHome differs from openHAB

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ChannelUID.java

fixed deprecation annotations

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/handler/FSInternetRadioHandler.java

Channel#isLinked is deprecated, use BaseThingHandler#isLinked

---

bundles/config/org.eclipse.smarthome.config.discovery.test/build.properties

remove unused (non-existing) source reference

---

bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java

In the log message the newArgument is dereferenced but could be null.

fix potential NPE

---

bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/ConfigDescriptionConverter.java

remove unused suppress warning annotation

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

avoided deprecated ChannelUID constructor

---

extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoMakerHandler.java

wemo: use non-deprecated channel UID constructor

---

bundles/model/org.eclipse.smarthome.model.persistence/META-INF/MANIFEST.MF

use nice manifest (as its one for the other ESH manifests)

---

bundles/core/org.eclipse.smarthome.core.extension.sample/META-INF/MANIFEST.MF

set execution environment

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

thing resource: drop usage of deprecated channel uid constructor

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

Code Formatting as a bonus.
Signed-off-by: Karel Goderis<karel.goderis@me.com>

Add synchronize(this) to onValueReceived()

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SwitchRenderer.java

Fixes #1235.

---

targetplatform/EclipseSmartHome.setup

Related to: openhab/openhab-distro#160

add a working set that contains all tests

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

sonos: fix potential null pointer access

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAlarm.java

sonos: remove unused imports (+formatter)

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/status/test/ConfigStatusServiceOSGiTest.groovy

fixed tests because of #1238

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/validation/test/ConfigDescriptionValidatorTest.groovy
bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/validation/test/ConfigValidationExceptionTest.groovy
bundles/config/org.eclipse.smarthome.config.core/ESH-INF/i18n/configdescriptionvalidation.properties
bundles/config/org.eclipse.smarthome.config.core/ESH-INF/i18n/validation.properties
bundles/config/org.eclipse.smarthome.config.core/ESH-INF/i18n/validation_de.properties
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/ConfigDescriptionValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/ConfigValidationException.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/ConfigDescriptionParameterValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/ConfigDescriptionParameterValidatorFactory.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/MessageKey.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/MinMaxValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/PatternValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/RequiredValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/TypeIntrospections.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/TypeValidator.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

- added min / max validator
- added pattern validator
- added data type validator

extended static config description validation

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/BindingBaseClassesOSGiTest.groovy

additional fix for #1238

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java

Before, every Hue light state which was checked for equality resulted in true (=equal) if the light did not support color or alert.
This is not the full truth: Thanks to the `&&` expression, the isEqual() order of equal checking was:
1. alert
2. isOn
3. effect
4. brightness
5. color mode
6. ...
So it only fails if nothing before color mode was not equals.

HueBridgeHandler: Fix isEqual(state,state) Method

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java

- Shrink code of pollingRunnable, which should make it more readable
- Add notifyStatusListeners() Method

Refactrings for HueBridgeHandler

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/util/ConnectionValidator.java

Reverts eclipse/smarthome#1212

Revert "Fix #1211"

---

bundles/io/org.eclipse.smarthome.io.audio/.classpath
bundles/io/org.eclipse.smarthome.io.audio/.project
bundles/io/org.eclipse.smarthome.io.audio/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.audio/build.properties
bundles/io/org.eclipse.smarthome.io.audio/pom.xml
bundles/io/org.eclipse.smarthome.io.audio/src/main/java/org/eclipse/smarthome/io/audio/AudioCodec.java
bundles/io/org.eclipse.smarthome.io.audio/src/main/java/org/eclipse/smarthome/io/audio/AudioContainer.java
bundles/io/org.eclipse.smarthome.io.audio/src/main/java/org/eclipse/smarthome/io/audio/AudioException.java
bundles/io/org.eclipse.smarthome.io.audio/src/main/java/org/eclipse/smarthome/io/audio/AudioFormat.java
bundles/io/org.eclipse.smarthome.io.audio/src/main/java/org/eclipse/smarthome/io/audio/AudioSink.java
bundles/io/org.eclipse.smarthome.io.audio/src/main/java/org/eclipse/smarthome/io/audio/AudioSource.java
bundles/io/org.eclipse.smarthome.io.audio/src/main/java/org/eclipse/smarthome/io/audio/UnsupportedAudioFormatException.java
bundles/io/pom.xml
features/karaf/src/main/feature/feature.xml
features/org.eclipse.smarthome.feature.runtime.core/feature.xml

Initial version of audio API for #584 
See Issue #584 
Also-By: @kdavis-mozilla
Signed-off-by: harald.kuhn@gmail.com

Initial version of audio API for #584 

---

bundles/io/org.eclipse.smarthome.io.audio/build.properties

fixed build.properties

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html

Safari md-icons fix

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css

Customised buttons with icons to have different widths.

md-button size customised

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/package.json
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.bindinginfo.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

Allow html tags in description as described here: https://github.com/eclipse/smarthome/issues/565
Uses Angular library "angular-sanitize" version 1.3.13.

Support html tags in item description

---

extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java

Fix #1243 - WeMo LED lights not going ONLINE

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/link/ItemChannelLinkResource.java

improved return codes for items/links

---

bundles/io/org.eclipse.smarthome.io.transport.mdns/OSGI-INF/mdns.xml
bundles/io/org.eclipse.smarthome.io.transport.mdns/OSGI-INF/mdnsclient.xml
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSClientImpl.java

Hopefully fixes https://github.com/openhab/openhab-distro/issues/162

make sure mDNS services are fully started under Karaf

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/BindingBaseClassesOSGiTest.groovy

made BindingBaseClassesOSGiTest more robust wrt timing

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/InboxResource.java

inbox.approve returns null which causes an exception in the inbox resource. This adds a check for this and instead returns 409. I've also modified the resources to return JSONResponse.

Update inbox resource to use JSONResponse and fix null response from approve

---

extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java

fixes #1273

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/sitemaps_list.html
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/PageRenderer.java

BasicUI: drop OpenHAB references in UI, fixes #1300

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/AbstractWidgetRenderer.java
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ListRenderer.java
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/PageRenderer.java
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SelectionRenderer.java
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SwitchRenderer.java

BasicUI: escape widget titles and values for HTML (fixes #1293)

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

I don't think a "404 Not Found" response is appropriate when a binding doesn't support the config status interface. Instead, the interface should respond with an empty config status.
In chrome at least, a 404 is treated as an error, and is logged in such a way. In my opinion, this is not an error - it simply means that the binding isn't supporting this interface and since there's no way to find this out (right?) we shouldn't be producing errors.
This change returns 404 if the thing doesn't exist. If the config status doesn't exist, it returns an empty set.

Change response to config/status REST interface

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueBridgeHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightDiscoveryServiceOSGITest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Fixes https://github.com/eclipse/smarthome/issues/1309
Still, on my local tests I have a couple of tests failing with "thing status is INITIALIZING, but expected ONLINE" - I am not sure if this is somehow related to https://github.com/eclipse/smarthome/issues/1075#issuecomment-203873291?

adapted hue tests

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/test/ConfigurationTest.groovy
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

Made configuration null-tolerant

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy

...in order to prevent testing against a "used" thing.
fixes #1308

Waiting for proper cleanup in hue test

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingConfigDescriptionProvider.java

Fix potential NPE in thing config description provider

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/binding/BindingResource.java

Return empty config instead of 404

---

bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/groovy/org/eclipse/smarthome/io/rest/core/service/test/ConfigurableServiceResourceOSGiTest.groovy

fix tests for #1316

---

docs/_includes/documentation-menu.html

added rule samples to documentation menu

---

bundles/automation/org.eclipse.smarthome.automation.module.script/ESH-INF/automation/moduletypes/ScriptTypes.json

improved meta data of script action

---

bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/AutomationResourceBundlesEventQueue.java

fix for R4 Compatibility

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Added new input field( text area) for configuration fields of context type 'script'.
fixes issue https://github.com/eclipse/smarthome/issues/1325.

Multi-row textarea for scripts

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy

Improve test stability (related to #1334)

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java

fixes https://github.com/eclipse/smarthome/issues/1340

ignore empty configurations on merge

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/WebAppConfig.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/WebAppConfig.java

fixes https://github.com/openhab/openhab-distro/issues/165

also accept Boolean values instead of Strings in the configuration

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

fixes https://github.com/eclipse/smarthome/issues/1350.

Support html tags in config parameters

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html

fixes https://github.com/eclipse/smarthome/issues/1349.

Show rule description in rule list

---

bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtilTest.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtil.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuntimeRule.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/AbstractCompositeModuleHandler.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeActionHandler.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeConditionHandler.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.integration.test/ESH-INF/automation/templates/TestTemplateRuleWithReferences.json
bundles/automation/org.eclipse.smarthome.automation.integration.test/ESH-INF/automation/templates/TestTemplateWithCompositeModules.json
bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationJsonTest.groovy
bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/GenericCondition.json
bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/ESH-INF/automation/moduletypes/SampleModuleTypeDefinition.json
bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/ESH-INF/automation/rules/SampleRuleDefinition.json
bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/ESH-INF/automation/templates/SampleTemplateDefinitions.json
bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/handler/SampleActionHandler.java

issue: https://github.com/eclipse/smarthome/issues/1247

Implemented Complex Resolving feature

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/test/ConfigurationTest.groovy
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

Fix concurrent modification exception when updating configuration properties

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Parse the options in configDescription parameters as Integer if Integer tag is present on the parameter.

Support integers in select box

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js

fixes https://github.com/eclipse/smarthome/issues/1356.

Set default values in rule template config

---

bundles/automation/org.eclipse.smarthome.automation.module.script/ESH-INF/automation/moduletypes/ScriptTypes.json

corrected script options (defined through mime-type)

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java

Fix https://github.com/eclipse/smarthome/issues/1280 and https://github.com/eclipse/smarthome/issues/1332

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

Fix https://github.com/eclipse/smarthome/issues/862

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationJsonTest.groovy

https://github.com/eclipse/smarthome/issues/1370

Fix automation integration test - filtering rules by correct tags

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/layer.html

BasicUI: escape character data in XML output, fixes #1366

---

targetplatform/smarthome.target

updated jupnp version to 2.2.0

---

extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/WebAppConfig.java

avoid NPE if no config is set

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java

removed obsolete code

---

bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptModuleActivator.java

also catch other exceptions besides ScriptException

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/PortableBase64.java

reduced logging to debug, since it is irrelevant for users

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1301

Send null instead of empty string in configurations

---

bundles/automation/org.eclipse.smarthome.automation.module.core/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.parser.gson/META-INF/MANIFEST.MF

drop lazy activation of automation modules

---

.gitignore
features/karaf-tp/pom.xml
features/karaf-tp/src/main/feature/feature.xml
features/karaf-verify/pom.xml
features/karaf/src/main/feature/feature.xml
features/pom.xml

add Karaf target platform and verify

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java

fixes https://github.com/openhab/openhab-distro/issues/177

avoid ConcurrentModificationException

---

extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java

ntp fix readme & improve logging

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

fixes https://github.com/eclipse/smarthome/issues/1381

allow colon in tag names on DELETE

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtil.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/RuleResourceBundleImporter.java

Improve logging

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

Show rules tab only if rules rest endpoint is available

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/LifxBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java

made fade time configurable and increased default to 300ms

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.channelconfig.html

fixes https://github.com/eclipse/smarthome/issues/827

Supprt channel configuration

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/common/CronExpressionTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/common/DateExpressionTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/common/RecurrenceExpressionTest.java
bundles/core/org.eclipse.smarthome.core/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/ThreadPoolManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/CoreActivator.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpressionPart.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/DateExpression.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/Expression.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionPart.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/RecurrenceExpression.java

Initial contribution of the  bespoke scheduler infrastructure for ESH

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/DateExpressionTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/RecurrenceExpressionTest.java

moved tests to the correct package

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Toggle button color fix and removed 'remove' button from services

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Parse boolean values in configurations

---

bundles/io/org.eclipse.smarthome.io.voice/src/main/java/org/eclipse/smarthome/io/voice/internal/extensions/SayConsoleCommandExtension.java
extensions/pom.xml
extensions/voice/org.eclipse.smarthome.voice.mactts/.classpath
extensions/voice/org.eclipse.smarthome.voice.mactts/.project
extensions/voice/org.eclipse.smarthome.voice.mactts/META-INF/MANIFEST.MF
extensions/voice/org.eclipse.smarthome.voice.mactts/OSGI-INF/TTSServiceMacOS.xml
extensions/voice/org.eclipse.smarthome.voice.mactts/build.properties
extensions/voice/org.eclipse.smarthome.voice.mactts/pom.xml
extensions/voice/org.eclipse.smarthome.voice.mactts/src/main/java/org/eclipse/smarthome/voice/mactts/internal/TTSServiceMacOS.java
extensions/voice/pom.xml
features/karaf/src/main/feature/feature.xml

moved MacOS TTS service into an extension bundle

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngineCallbackImpl.java

avoid npe if triggered is called after disposal

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/normalization/NormalizerTest.groovy
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/AbstractNormalizer.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/BooleanNormalizer.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/DecimalNormalizer.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/INormalizer.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/IntNormalizer.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/ListNormalizer.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/NormalizerFactory.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/TextNormalizer.java
bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/thingresource.xml
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

added config normalization

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java

Bug: https://github.com/eclipse/smarthome/issues/1414

discovery: fix check if configuration key is present

---

docs/_includes/documentation-menu.html
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/pom.xml
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/DeviceHandler.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/SceneHandler.java
extensions/binding/pom.xml
features/karaf/src/main/feature/feature.xml

added digitalSTROM binding to build, feature and docs

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.addmodule.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.approveinboxentry.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.configureservice.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.linkchannel.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.ruletemplate.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.thingconfig.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html

Resolved responsivness issues

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Should fix https://github.com/eclipse/smarthome/issues/1441

Fixed bug: select box considering integer 0 as null

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Rule.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuntimeRule.java

Remove unused scopeIds from Rule and RuleEngine

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngineCallbackImpl.java

Add debug message when a rule is triggered.  #1432

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js

Should fix https://github.com/eclipse/smarthome/issues/1429

Navigate to rule list after rule is completely created/updated

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js

Show thingType label only if binding is available

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java

Remove wrong JavaDoc

---

bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/RuleEngineTest.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/template/TemplateManager.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/type/ModuleTypeManager.java

Right behavior of getByTags(Set<String> tags) method #1413

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.thingconfig.html

Removed check 'if thing has an item' while editing label

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java

create Bridges instead of Things, if the input is a Bridge

---

extensions/ui/org.eclipse.smarthome.ui.paper/package.json

Gulp inject in package.json

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Bug fix: Set dropdown options value according to context

---

bundles/config/org.eclipse.smarthome.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java

do not remove configuration entries that are already present

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Apply default configuration if parameter is not present.

---

bundles/core/org.eclipse.smarthome.core.binding.xml.test/src/test/groovy/org/eclipse/smarthome/core/binding/xml/test/BindingInfoTest.groovy
bundles/core/org.eclipse.smarthome.core.binding.xml.test/src/test/resources/test-bundle-pool/BundleInfoTestNoAuthor.bundle/ESH-INF/binding/binding.xml
bundles/core/org.eclipse.smarthome.core.binding.xml.test/src/test/resources/test-bundle-pool/BundleInfoTestNoAuthor.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.binding.xml.test/src/test/resources/test-bundle-pool/BundleInfoTestNoAuthor.bundle/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.binding.xml/binding-1.0.0.xsd
bundles/core/org.eclipse.smarthome.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/BindingInfoConverter.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfo.java

Make author optional in binding.xml

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingLinkManagerOSGiTest.groovy

Fixed test case.

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandler.java

Mark ThingHandler methods as deprecated.

---

bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/AbstractAsyncBundleProcessor.java
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

...as they got broken by #1419

fixed tests & reduced logging spam

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js

fixes https://github.com/eclipse/smarthome/issues/1489

Sort extensions by label

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

* configurations of type "decimal" are not handled
* the step width is currently not used

PaperUI: config: add support for DECIMAL and step width

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/Activator.java
bundles/automation/org.eclipse.smarthome.automation.module.timer/src/main/java/org/eclipse/smarthome/automation/module/timer/factory/TimerModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/AbstractResourceBundleProvider.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/Activator.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/AutomationResourceBundlesEventQueue.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/ModuleTypeResourceBundleProvider.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/RuleResourceBundleImporter.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/TemplateResourceBundleProvider.java

#1498 - fix the processing of automation resource queue

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy

fixed test that was accidentally reverted by #1288

---

bundles/automation/org.eclipse.smarthome.automation.module.timer/src/main/java/org/eclipse/smarthome/automation/module/timer/handler/CallbackJob.java
bundles/automation/org.eclipse.smarthome.automation.module.timer/src/main/java/org/eclipse/smarthome/automation/module/timer/handler/TimerTriggerHandler.java

fix issue #1425 cron timers context - different rulenginecallback for each timer
Signed-off-by: Marin Mitev <marin.mitev@gmail.com>

fix issue #1425 cron timers context

---

extensions/ui/org.eclipse.smarthome.ui.basic/README.md

slightly improved documentation to have correct syntax and be neutral

---

bundles/core/org.eclipse.smarthome.core.thing/ESH-INF/config/config.xml
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingLinkManager.xml
bundles/core/org.eclipse.smarthome.core.thing/build.properties
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java

- added config meta-data
- fixed correct handling of configuration setting
- fixed potential NPE in ChannelItemProvider

Improvements and fixes on the ThingLinkManager

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

fixes https://github.com/eclipse/smarthome/issues/1534

Maintain previous view state when thing's channel updated

---

extensions/binding/org.eclipse.smarthome.binding.digitalstrom/README.md
extensions/binding/org.eclipse.smarthome.binding.wemo/README.md

Fix a small typo in documentation

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.linkchannel.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.removeitem.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.itemcontrol.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/navigation.menu.html

1) Allow add/update/delete on Items.
2) Allow creation of an item while linking a channel.
fixes https://github.com/eclipse/smarthome/issues/1488, https://github.com/eclipse/smarthome/issues/1490

Support item configuration

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

fixes https://github.com/eclipse/smarthome/issues/1495

Added tabs on services page

---

extensions/binding/org.eclipse.smarthome.binding.sonos/README.md
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

fixed potential NPE and updated documentation for Sonos binding

---

extensions/binding/org.eclipse.smarthome.binding.digitalstrom/META-INF/MANIFEST.MF

add missing Import-Package instructions

---

extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/thing-types.xml

added lighting tags

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ColorItem.java

added correct handling of getStateAs(PercentType) for ColorItems

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

fixes https://github.com/eclipse/smarthome/issues/1492

Show thing's properties

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1549

Added a utility function to check if object has properties

---

docs/documentation/features/rules.md
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/README.md
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md
extensions/binding/org.eclipse.smarthome.binding.hue/README.md
extensions/binding/org.eclipse.smarthome.binding.lifx/README.md
extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
extensions/binding/org.eclipse.smarthome.binding.wemo/README.md
extensions/binding/org.eclipse.smarthome.binding.yahooweather/README.md
protocols/enocean/README.md

https://github.com/openhab/openhab2-addons/issues/956

update readme files to have proper formatting in OH docu site

---

protocols/enocean/README.md

Signed-off-by: Marcel Verpaalen marcel@verpaalen.com

fix formatting in enocean

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css

fixes https://github.com/eclipse/smarthome/issues/1558

Trim select box text

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/Activator.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ItemChannelLinkRegistry.xml
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingRegistry.xml
bundles/core/org.eclipse.smarthome.core/OSGI-INF/itemregistry.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java

#1528 - Registration of multiple ManagedProvider services

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js

fixes https://github.com/eclipse/smarthome/issues/1556

Show discovery page only if binding supports discovery

---

features/org.eclipse.smarthome.feature.dependencies.designer/feature.xml
features/org.eclipse.smarthome.feature.designer/feature.xml
targetplatform/smarthome.target

changed Designer to use gson 2.2.4

---

pom.xml
products/org.eclipse.smarthome.designer.product/pom.xml

fixing plist entry for Mac Designer app

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

Config channel issue: pass event explicitly

---

targetplatform/smarthome.target

increase sequenceNo to make the target platform re-resolve

---

docs/getting-started.html

updated links to openHAB 2

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.itemcontrol.html

Paper UI: show slider only if item is not read only

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/items/CallItemTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/StringListTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/CoreItemFactory.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/CallItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringListType.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

Signed-off-by: sysadmin <glhopital@gmail.com>

Importing CallType and Item

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/Activator.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleUtils.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuntimeRule.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/template/TemplateManager.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/RuleResourceBundleImporter.java

Move template resolving from RuleEngine to RuleRegistry

Move template resolving from RuleEngine to RuleRegistry. fixes #1561

---

extensions/binding/org.eclipse.smarthome.binding.sonos/README.md

First revision of Sonos binding documentation (#1598). Needs some more work.

Added new channels

---

bundles/model/org.eclipse.smarthome.model.item/OSGI-INF/genericitemprovider.xml
bundles/model/org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/Rules.xtext
products/org.eclipse.smarthome.designer.product/org.eclipse.smarthome.designer.product.product

corrections of startup behavior of Designer components

---

bundles/designer/org.eclipse.smarthome.designer.core/plugin.xml

fixed progress indicator on startup

---

docs/_includes/base.html
docs/_includes/footer.html
docs/documentation/community/downloads.md
docs/getting-started.html
docs/index.html

added trademark info as required by Eclipse trademark guidelines

---

bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/BasicModuleHandlerFactory.java

This change does not change the method but re-structure the code that it
is (IMHO) more readable.

sort the trigger by their types

---

docs/documentation/features/rules.md

fixes #1624 - Rule JSON template documentation wrong
Signed-off-by: Marin Mitev <marin.mitev@gmail.com>

fixes #1624 - Rule JSON template documentation wrong

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/BundleProcessor.java

@sjka Can you have a look at, if the documentation is correct?

add documentation for isFinishedLoading

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/ChangeThingTypeOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandlerFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

fixed concurrency issue within changeTingType and improved logging

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1632

Allow filtering of items

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

fixes https://github.com/eclipse/smarthome/issues/1559

Allows adding module outputs to script field

---

tools/ref-tag/create.sh

The tool consumes only one argument now.
The argument defines the commit ID that the work should be based on.
The new version number could be controlled by using environment
variables.
* VERSION_NEW_MMR: the major.minor.revision of the new version
if not set the old one is kept.
* VERSION_NEW_QUALI: the new qualifier
Here some examples and the new version:
```
OLD: "0.8.0-SNAPSHOT"
MMR: "0.8.0", QUALI: "b1" => "0.8.0.b1"
MMR: "", QUALI: "b1" => "0.8.0.b1"
MMR: "0.9.0", QUALI: "SNAPSHOT" => "0.9.0-SNAPSHOT"
MMR: "0.8.0", QUALI: "" => "0.8.0"
```

rtt: add more files and improve new versioning

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

fixes https://github.com/eclipse/smarthome/issues/1576

Support date,time color and thing configuration

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingFactoryHelper.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelType.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfo.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/channel/ChannelTypeResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java

fixes #1062

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1646

Filter items after promise is resolved

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

Working for manual thing creation.

Redirect to things list after thing creation

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

refresh channel after linkage

---

docs/documentation/community/downloads.md

updated download site for 0.8 release

---

docs/_includes/documentation-menu.html
extensions/binding/org.eclipse.smarthome.binding.sonos/README.md

added Sonos to documentation

---

docs/pom.xml

fixed mvn clean mechanism on docs

---

extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/NtpBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java

Additional string channel that allows proper timezone representation
Resolves issue #1666

NTP string channel

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java

avoid npe in case of no channel type

---

bundles/designer/org.eclipse.smarthome.designer.core/src/main/java/org/eclipse/smarthome/designer/core/config/PluginProjectCreator.xtend

Include core type package for rules and scripts

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java

LIFX : Add support for RefreshType.REFRESH

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/LocaleProviderImpl.java

improved logging

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GroupItemTest.groovy
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/TestItem.java

stabilise tests

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

bug fix: convert configuration parameter only if type=boolean

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy

waitForAssert will wait for NPEs, too.

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/GenericThingBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
docs/documentation/features/dsl.md

Added a location field to Things according to #1083

Thing location

---

bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/RESTActivator.java

use service tracker constructor with string class name injection

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/HostFragmentSupportTest.groovy

fix failing tests because of default locale

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java

make the system channel 'low-battery' read-only

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/RuleTemplate.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/FilterCriteria.java

Bug: https://github.com/eclipse/smarthome/issues/1736

add no-arg constructor

---

bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/bindingresource.xml
bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/configurableserviceresource.xml
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/binding/BindingResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/service/ConfigurableServiceResource.java

...as they were missing so far.
This also was the cause for #1692 
fixes #1692 

added normalization for service and binding configuration

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

1) Localized month names based on selected language.
2) Customized color widget to allow unsetting color.
3) Select default color to 'white' when clicked on widget.
4) Allow date format changing between normal and expert mode.
5) Dropped seconds support in 'time' widget.

Widgets customization

---

targetplatform/EclipseSmartHome.setup

bump Groovy repo to the Neon one

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/common/ThreadPoolManagerTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/ThreadPoolManager.java

fixed tests for #1744

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/i18n/LocaleProviderOSGiTest.groovy

wait until locale has been cleared before the tests are executed

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingDTOMapper.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java

added Thing location to the REST API

---

extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/src/main/java/org/eclipse/smarthome/ui/iconset/classic/internal/ClassicIconProvider.java

fixed icon provider for Windows

---

extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml

place npm cache and tmp to the build directory

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

Related issue is: https://github.com/eclipse/smarthome/issues/1083

Add location while creating thing

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/thing-types.xml

LIFX: Add brightness channel to colorlight

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

Reverted ThingRegistry method's signature and added location

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/thing-types.xml

This reverts commit 2eca6b88aabff137ec24235f27f3bdfa13cbf1ee.

Revert "LIFX: Add brightness channel to colorlight (#1777)"

---

extensions/ui/org.eclipse.smarthome.ui.basic/ESH-INF/config/config.xml
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

1) fixes https://github.com/eclipse/smarthome/issues/1665
2) Highlights fields (red border) that have a validation error.

Implements day of week and highlights fields with errors

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.addmodule.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

fixes https://github.com/eclipse/smarthome/issues/1774

Bug fix: adding thing/module with no configParams

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java

LIFX : Add support for PercentType and OnOffType on the colour channel

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

fixes potential NPE

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java

also consider location when updating a Thing

---

extensions/binding/org.eclipse.smarthome.binding.hue/README.md

Signed-off-by: Joerg Kling <joerg.kling@gmail.com>

Enhancement to Hue binding documentation

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightDiscovery.java

LIFX : Fix #1778 #1788

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryResultBuilder.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryResultImpl.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java

and also added modelId to the properties of a discovered hue bulb

added modelId as property for a hue light discovery result

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1802

bug fix: config value replaced by default value for type Decimal

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Improved the property settings in HueLightHandler. This should also fix the not working OSRAM hack.
Fixes: #1792

Fixed the failing tests 

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Validate number input field on page load

---

extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml

This should hopefully fix Hudson build failures.

moved configuration so that it is used for all executions

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/QueueingThreadPoolExecutor.java

reduced logging

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java

added operation addRegistryChangeListeners for channel item provider

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

fixes https://github.com/eclipse/smarthome/issues/1832

show thing label in thing details

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

fixes https://github.com/eclipse/smarthome/issues/1808

Removed toggle button from dimmer widget

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

fixes https://github.com/eclipse/smarthome/issues/1831

Redirect to inbox/search on new discovery result

---

docs/index.html

replaced Yetu by Jung in reference section on homepage

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/ModuleTypeDTOMapper.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/RuleTemplate.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ModuleType.java
bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/Printer.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/type/ModuleTypeManager.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ModuleTypeGSONParser.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/ModuleTypeResourceBundleProvider.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/TemplateResourceBundleProvider.java

Fixed #1830 Wrong method name in RuleTempalte

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/ActionDTOMapper.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/ActionTypeDTOMapper.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/ConditionDTOMapper.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/ConditionTypeDTOMapper.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/TriggerDTOMapper.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/TriggerTypeDTOMapper.java
bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/ModuleTypeResource.java

Fix generics for new Automation DTO Mappers #1801

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java

Refactore #1841

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/WidgetDTO.java
bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/Sitemap.xtext
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/VideoRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/VideoRenderer.java

See https://community.openhab.org/t/video-in-sitemap-breaks-ui/8542

ported mjpeg video support from openHAB 1

---

targetplatform/smarthome.target

Follows: https://github.com/eclipse/smarthome/pull/1858

add unit bundles

---

bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/AbstractAsyncBundleProcessor.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Fixes https://github.com/eclipse/smarthome/issues/1847

avoid duplicates in vetoer list

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Hue binding: fix initialization (issue #1869)

---

bundles/core/org.eclipse.smarthome.core.thing.xml/META-INF/MANIFEST.MF

removed lazy activation

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Fixes https://github.com/eclipse/smarthome/issues/1885

Accept zero as valid input

---

bundles/core/org.eclipse.smarthome.core.thing.test/pom.xml
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingLinkManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingLinkManager.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/events/AbstractTypedEventSubscriber.java

call channelLinked() on newly initialised handlers

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1895

Password context based input

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Member bridgeHandler was not reset to null in dispose().

Hue binding: fix 1880

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/BridgeBuilder.java

Bug: https://github.com/eclipse/smarthome/issues/1908

override methods to keep type information

---

docs/documentation/development/guidelines.md

added a hint about periodically executed jobs

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ConfigStatusBridgeHandler.java

added ConfigStatusBridgeHandler

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Related to: https://github.com/eclipse/smarthome/pull/1897/files#r71873859

use context equals case insensitive for password

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java

re-added support for dimmable plug-in units

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.state.dropdown.html

fixes https://github.com/eclipse/smarthome/issues/1886

Support state options in control UI

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1927

Bug fix: Input type text

---

extensions/ui/org.eclipse.smarthome.ui.paper/package.json

added gulp-util, which has been missing

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PercentType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringListType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringType.java

added default constructors

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateService.java

changed log level for config validation

---

bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlChannelTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java

fixed concurrency issues

---

bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSServiceImpl.java

don't register service if client has already gone

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingManager.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingTypeMigrationService.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingTypeMigrator.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandlerCallback.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

implemented the ThingTypeMigrator service

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

- Update the currettitle and currenttrack channels with metadata from radio station even if opmlUrl is not set

Sonos binding: title channel for radio

---

targetplatform/smarthome.target

switched to composite update site for JmDNS

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html

fixes https://github.com/eclipse/smarthome/issues/1934

Group item configuration

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html

Adapted PaperUI in accordance with https://github.com/eclipse/smarthome/pull/1979.

Item types changed

---

extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

It should work after https://github.com/eclipse/smarthome/pull/1921 is merged.

Tests for rendering model in configService

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js

ColorItem control fix

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js

fixes https://github.com/eclipse/smarthome/issues/1975

Use timeout returned by discovery scan

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/BasicModuleHandlerFactory.java

Fixes #1641 multiple triggers

---

extensions/binding/org.eclipse.smarthome.binding.digitalstrom/pom.xml

Bug: https://github.com/eclipse/smarthome/issues/1997

use consistent artifact names

---

extensions/io/org.eclipse.smarthome.io.javasound/pom.xml

Bug: https://github.com/eclipse/smarthome/issues/1999

fix groupId of javasound

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceOSGiTest.groovy

fix firmware update service test that failed during nightly build

---

bundles/core/org.eclipse.smarthome.core/OSGI-INF/i18nprovider.xml

added unbind locale provider operation for I18nProvider

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java

isReachable() checks did not find out, that a bridge is really disconnected. Status was "OFFLINE (CONFIGURATION_ERROR): Authentication failed...". 

Hue bridge is in OFFLINE state, when bridge is not connected

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.system.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/navigation.menu.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/system.configuration.html

1) Moved system services.
2) Removed unused code to add new service configurations.

New navigation entry for system services

---

targetplatform/smarthome.target

This should fix one of the problems of the failing nightly build - #2003.

Jetty HttpClient version downgraded in the TP

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java

Related to: https://github.com/eclipse/smarthome/issues/2009#issuecomment-240402717

map only stuff from item dto that is defined

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.state.dropdown.html

fixes https://github.com/eclipse/smarthome/issues/1976

Show only state for disabled control items

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

Close linkRegistryServiceTracker in unsetBundleContext

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html

fixes https://github.com/eclipse/smarthome/issues/2009

Bug fix: item creation

---

tools/ref-tag/create.sh

Related to: https://github.com/eclipse/smarthome/pull/1923

remove obsolete EnOcean file handling

---

features/karaf-tp/src/main/feature/feature.xml

Bug: https://github.com/eclipse/smarthome/issues/2027

bump JmDNS (Karaf ESH TP)

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

fixes https://github.com/eclipse/smarthome/issues/2025

Bug fix: creating item while linking channel

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js

There is a script error while creating group with type 'none'. This commit fixes that.

bug fix: function name undefined error in group item

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.system.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/system.configuration.html

Fixes https://github.com/eclipse/smarthome/issues/2026

Hide system services with no config-description

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java

isReachable also returns false for NoRouteToHostException

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchService.java

Fixes #2034 
Signed-off-by: Christoph Schauer <christoph@schauer-itconsulting.de>

Added follow symlink option to abstract watch service.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

fixes https://github.com/eclipse/smarthome/issues/2019

Removed unused thingTypes request

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/FirmwareRegistry.xml
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/FirmwareUpdateService.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateService.java

use locale provider in firmware services

---

extensions/transform/org.eclipse.smarthome.transform.exec/pom.xml
extensions/transform/org.eclipse.smarthome.transform.javascript/pom.xml
extensions/transform/org.eclipse.smarthome.transform.jsonpath/pom.xml
extensions/transform/org.eclipse.smarthome.transform.map/pom.xml
extensions/transform/org.eclipse.smarthome.transform.regex/pom.xml
extensions/transform/org.eclipse.smarthome.transform.scale/pom.xml
extensions/transform/org.eclipse.smarthome.transform.xpath/pom.xml
extensions/transform/org.eclipse.smarthome.transform.xslt/pom.xml

Fixes: https://github.com/eclipse/smarthome/issues/2058

use consistent naming

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/FirmwareUpdateService.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateService.java

immediate firmware status initialization of a thing after it went online

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

Bug fix: show value of dimmer item's slider

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

fixes https://github.com/eclipse/smarthome/issues/2060#issuecomment-243054588

Bug fix: button icons alignment in ControlUI

---

features/karaf/src/main/feature/feature.xml

Please have a look at:
* https://lists.apache.org/thread.html/ee80f8bc2f03b368ca20beffa8f41c12ce6b12959992d4ef6a75ed0e@%3Cdev.karaf.apache.org%3E
* https://lists.apache.org/thread.html/20524e4ecde622cc9e263ced9ac2ac3f2c3c90dcfc516165ae2b41c8@%3Cdev.karaf.apache.org%3E

add capabilities to feature because it is missing in the bundle manifest

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.state.dropdown.html

fixes https://github.com/eclipse/smarthome/issues/2024

Number widget overlapping fixed

---

bundles/core/org.eclipse.smarthome.core.persistence/build.properties

added ESH-INF folder to binary bundle

---

bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/VoiceManager.java

avoid NPE if default TTS cannot be found

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/util/ConnectionValidator.java

#2103 Fix in ConnectionValidator. Throwing IAE in the wrong place.

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.module.timer.test/src/test/groovy/org/eclipse/smarthome/automation/module/timer/internal/RuntimeRuleTest.groovy

After a rule has been executed, it state is set to IDLE.
This is done regardless if the rule has been deactivated before (at the time it has been executed).
@danchom, @marinmitev Can you have a look at the fix?
Fixes: #1757, #2057

demonstrate that disable of rule fails some times

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html

1) Receive rule events and update local repo accordingly.
2) Rely more on rule repository (local) than rule service (remote).
3) Added Status info of rule.
fixes https://github.com/eclipse/smarthome/issues/2049

Support receiving rules events

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.ruletemplate.html

Disable rule template form submission on errors

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

fixes https://github.com/eclipse/smarthome/issues/2118

Toggle for advance config parameters

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

We must not check if the status is ... (IDLE in this case) and set it to another status (RUNNING in this case) without using synchronization. At least this does not work.
```java
if (ruleStatus == RuleStatus.IDLE) {
try {
// change state to RUNNING
setRuleStatusInfo(uid, new RuleStatusInfo(RuleStatus.RUNNING));
```
If between the above lines the rule status has been set to disabled, this change has been lost and the rule is enabled again.

fix another rule status change

---

targetplatform/smarthome.target

Fixes: https://github.com/eclipse/smarthome/issues/2128

remove old JmDNS bundle from TP

---

extensions/binding/org.eclipse.smarthome.binding.yahooweather/README.md

fixed example configuration on Yahoo weather binding

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/AbstractRuleRegistryEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleAddedEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleEventFactory.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleRemovedEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleUpdatedEvent.java

Fixes: https://github.com/eclipse/smarthome/issues/2137
This PR has not been tested by myself but I assume @aounhaider1 you can cherry-pick the PR and report it.

use rule DTO for rule events

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js

fixes https://github.com/eclipse/smarthome/issues/2135

Color widget: Send updated slider values on timeout

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/2140

Exactly match topic

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

removed duplicate field

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/2040

Allow integer type input for context date & time

---

features/karaf-tp/src/main/feature/feature.xml

* Remove whitespace in front of UPnP description
* Add description for JAX-RS providers
* Fix indentation

fix karaf-tp feature descriptions

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html

fixes https://github.com/eclipse/smarthome/issues/2072

Replaced button-icons with clickable icons

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html

fixes https://github.com/eclipse/smarthome/issues/2153

Resolved responsiveness issues

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

fixes https://github.com/eclipse/smarthome/issues/2150

Show state of readonly string item

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js

fixes https://github.com/eclipse/smarthome/issues/2091

Thing update event

---

tools/ref-tag/create.sh

@maggu2810 Not sure if this script worked for you in the past, but I had to do a few adaptions for building a 0.9.0.b1 - if I am missing something, please let me know!

replaced CLASSI by QUALI parameter to make the script work as expected

---

targetplatform/smarthome.target

h2 targetplatform: add h2 bundle

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.system.js

Bug fix: system config save

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js

Color widget: set white only when color is null

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Fixes:
1) Invalid date problem on Safari/Firefox
2) Clickable-icon size on Safari.

Invalid date bug

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

If a group has both normal and advance parameters then separate the parameters into two groups.

Separate groups for advance parameters

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html

Removed recursive item call

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/internal/http/WemoHttpCall.java

Fixes https://github.com/eclipse/smarthome/issues/2097

makes response handling more robust in case the encoding is received within quotes

---

docs/documentation/development/rules/ModuleTypes_schema.json
docs/documentation/development/rules/Rules_schema.json
docs/documentation/development/rules/Templates_schema.json

Resolving the #1862 (Update json scheme of rules, module-types and templates)

---

extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY3.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY5.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/ZonePlayer.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/README.md
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/SonosBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

Sonos binding: add SHUFFLE and REPEAT controls

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Bug fix: show error message on failed rest request

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

fixes https://github.com/eclipse/smarthome/issues/2182

Use thingTypeUID field for thing's icon character

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

fixes https://github.com/eclipse/smarthome/issues/2184

Bug fix: item unlinking on Firefox

---

bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java

Hi,
this PR fixes https://github.com/eclipse/smarthome/issues/2206.

Fixed removing rules from the RuleTriggerManager.

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java

made provider tracker of abstract registry OSGI R4.2 compatible

---

docs/documentation/concepts/events.md
docs/documentation/development/bindings/thing-definition.md
docs/documentation/development/bindings/thing-handler.md
docs/documentation/development/bindings/xml-reference.md
docs/documentation/features/dsl.md

Hi,
this PR adds the documentation for the trigger channels (which are implemented in https://github.com/eclipse/smarthome/pull/1936)

Documentation for the trigger channels

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

fixes https://github.com/eclipse/smarthome/issues/2192

Prevent config form from expanding
