bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java

If a rule is triggered by a received command without specified command
(e.g. "Item &lt;item> received command", so missing optional argument
[&lt;command>]) the rule is not executed.
If a optional command is given "ct.getCommand()" should differ from "null", if
the optional is missing "ct.getCommand()" should be null.
So fix the logic to find a rule (so it is similar to the logic used for
a state update).

fix execution of rules with command trigger

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingLinkManager.java

Implement the all items changed handler of the item registry listener
used in the thing link manager.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=457808

fix all items changed handler

---

bundles/config/org.eclipse.smarthome.config.xml/META-INF/MANIFEST.MF

The bundled xstream library is added to the classpath of the config xml
bundle. So the MANIFEST of xstream is not evaluated by OSGi.
So we have to add the imported packages necessary for the used xstream classes
to the import package section of the config xml bundle.
I added some imports, that are currently used on a ESH instance with the
Yahoo Weather binding running.
I do not know, why this is currently working with Equinox, perhaps
caused by this one:
https://wiki.eclipse.org/index.php/Equinox_Boot_Delegation
But this is something that should be fixed.

add imports used by bundled libs

---

bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/resources/RootResource.java

This PR will unbind the configuration to the rest bundle, so it could used by other ones.
This is done to "fix" the following error message using Felix OSGi framework:
Cannot use configuration com.eclipsesource.jaxrs.connector for [org.osgi.service.cm.ManagedService, id=99, bundle=51/file:base/repo/oh2/com.eclipsesource.jaxrs.publisher_4.1.0.201407131319.jar]: No visibility to configuration bound to file:base/repo/esh/plugins/org.eclipse.smarthome.io.rest_0.8.0.201501261711.jar
Is this okay, or should the error ignored.

rest: do not bind configuration to bundle

---

binding/org.eclipse.smarthome.binding.yahooweather/META-INF/MANIFEST.MF
binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/discovery/YahooWeatherDiscoveryService.java

Fixed https://bugs.eclipse.org/bugs/show_bug.cgi?id=459611
YahooWeatherBinding does require Apache HttpClient 3.x

Fix YahooWeatherBinding to get rid of HttpClient 3.x

---

binding/org.eclipse.smarthome.binding.hue/META-INF/MANIFEST.MF
binding/org.eclipse.smarthome.binding.lifx/META-INF/MANIFEST.MF
binding/org.eclipse.smarthome.binding.wemo/META-INF/MANIFEST.MF
binding/org.eclipse.smarthome.binding.yahooweather/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.core/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.dispatch/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.autoupdate/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.rest.core/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.rest/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.item/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.rule/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.script/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.thing/META-INF/MANIFEST.MF
bundles/storage/org.eclipse.smarthome.storage.mapdb/META-INF/MANIFEST.MF
tools/archetype/binding/src/main/resources/archetype-resources/META-INF/MANIFEST.MF

Fixed bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=459608
MANIFEST entry "Service-Component: OSGI-INF/*" will raise warnings in some OSGi frameworks

Fixed all entries of OSGI-INF/* to be OSGI-INF/*.xml

---

binding/org.eclipse.smarthome.binding.hue/.classpath
binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/Classic_A60_RGBW.xml
binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/Surface_Light_TW.xml
binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/HueBindingConstants.java
binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

Added support for 2 OSRAM Lightify LEDs to Philips Hue binding.
* Classic A60 RGBW: supports color, color temperature
* Surface Light TW: supports color temperature only
* also moved src folder to be first classpath entry

Added OSRAM LED support to Hue binding

---

targetplatform/esh-formatter.xml

The previous line wrapping policy for enum constants was set to "Do not
wrap" and the force split was unset, too.
This could result in a non-readable code.
With the new setting "Wrap all elements, every element on a new line"
and the activated "force split" every enum value gets its own line.
Here a short example with the old and new setting:
old
```java
public enum DeviceParameter {
BUTTON_DIM_A("BUTTON_DIM_A", RockerSwitchAction.class), BUTTON_DIM_B("BUTTON_DIM_B", RockerSwitchAction.class), ENERGY_WS(
"ENERGY_WS", Long.class), HUMIDITY_PERCENT("HUMIDITY_PERCENT", Double.class), ILLUMINATION_LUX(
"ILLUMINATION_LUX", Double.class), MOTION("MOTION", Boolean.class), OCCUPANCY_BUTTON("OCCUPANCY_BUTTON",
Boolean.class), POSITION_PERCENT(Integer.class), POWER_W(Long.class), …
```

change line wrapping policy for enum constants

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingLinkManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/AutoUpdateGenericBindingConfigProvider.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/BindingConfigReader.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericItemChannelLinkProvider.java

- when links are added, REFRESH commands are sent by the registry
- ItemRegistryImpl.allItemsChanged now informs downstream listeners about diffs only
- GenericItem.equals and .hashCode now also considers label, category and tags
- BindingConfigReaders get start/stop information on parsing configs for a context
As a result, on a "touch" of an items file, no unnecessary reprocessing is triggered anymore.
Sorry for not implementing additional tests, I was really struggling with that and gave up...

improved lifecycle behaviour in a few points

---

bundles/core/org.eclipse.smarthome.core.thing.xml.test/pom.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/test/SystemWideChannelTypesTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannels.bundle/ESH-INF/binding/binding.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannels.bundle/ESH-INF/i18n/SystemChannels_de.properties
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannels.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannels.bundle/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsNoThingTypes.bundle/ESH-INF/binding/binding.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsNoThingTypes.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsNoThingTypes.bundle/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsUser.bundle/ESH-INF/binding/binding.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsUser.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsUser.bundle/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/yahooweather.bundle/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing.xml/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/AbstractDescriptionTypeConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/Activator.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelTypeConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlProvider.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlHelper.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlSystemChannelTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/DefaultSystemChannelTypeProvider.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/SystemChannelTypeProvider.java
docs/sources/architecture/thing-definition.md

binding. There are default system channel types and every binding can
define its own through XML.
Signed-off-by: IVAN GEORGIEV ILIEV <ivan.iliev@musala.com>

Introduced support for System wide Channel Types that can be used in any

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttConnectionObserver.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttMessageConsumer.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttMessageProducer.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttSenderChannel.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttWillAndTestament.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttBrokerConnection.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttBrokerConnectionHelper.java

I started playing around with the mqtt transport.
I kept the commits separate, so you could check them separately.
style only:
* The first one applies the ESH clean up (remove trailing whitespaces).
* The second cleans up manual line breaks in the javadoc. The formatter does not remove manual line breaks, but I cleaned it manually and started the clean up again - so all fine.
feature:
* The third commit adds a method to the interfaces (consumer / producer) that informs the implemented clcass about the current state of the connection.
After a broker connection is established it is a common case to transmit the current state of all items, to inform subscribers about the current state (and guarantees that not a state change keeps not transmitted). 
bugfix:
* The fourth commit fix a …

mqtt transport: fix reconnect and improve producer handling

---

binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueBridgeDiscoveryParticipantOSGITest.groovy
binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeDiscoveryParticipant.java
binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java
binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/discovery/YahooWeatherDiscoveryService.java
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryResultImplTest.groovy
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryServiceMock.groovy
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/DynamicThingUpdateOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/InboxOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryResult.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryResultBuilder.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryResultImpl.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/beans/DiscoveryResultBean.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/util/BeanMapper.java

Currently discovery results contain only labels as human readable information to inform about new  things that were discovered. However solutions based on ESH might require an id property to give the solution´s UI a hint how to represent the unique id of the discovered thing. For this reason the discovery result was extended by a representation object containing the unique id and its type like IP address, MAC address, serial number, ...

Added discovery result representation

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

Changed GenericItemProvider to catch all exceptions caused by badly behaving bindings.
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com> (github: paulianttila)

Improved GenericItemProvider

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/setup/ThingSetupManagerResource.java

Currently, when you update the label in the linked thing, the 'thing updated' event responds with the updated information being the same as the old information. This is because the thing is updated before the item, so we send incorrect information.
This PR reverses the order - the thing information is updated after the item, so the item changes are now correctly presented in the SSE event.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=465079

Move update of thing to after update of item to ensure information is correctly presented

---

bundles/ui/org.eclipse.smarthome.ui.classic/snippets/main.html

Caused by a bug in (at least) Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=664720) the onmouseup is not triggered if a synchronous Ajax request made in the onmousedown does not complete soon enough.
Anyway the use of synchronous HTTP Requests seems to be deprecated.
Same PR as https://github.com/openhab/openhab/pull/2473
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=465239
Signed-off-by: Dominic Lerbs <promguard-github@yahoo.de>

Fix Bug 465239: Make changing of state asynchronous

---

docs/sources/development/contributing.md
docs/sources/index.md

Moved How-To Contribute documentation from https://www.eclipse.org/smarthome/community.html#HowToContribute into markdown file and added more infos for bug tracking.

Added documentation how to contribute.

---

bundles/config/org.eclipse.smarthome.config.xml/META-INF/MANIFEST.MF

This package is used by the zwave binding, so adding this avoids having to include xstream library into the bundle.

Add additional xstream export to manifest

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameter.java
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/ThingFactoryTest.groovy

This fixes a bug in one of the constructors of ConfigDescriptionParameter which is probably only used in this test since I modified most of the rest of the code to use the builder.
It also fixes the failed tests.
However I note that other tests are failing, but I reverted back to an older code and they still fail so I don't think it's associated with my change.

Fix config parameter thing tests

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/GenerateItems.mwe2

It doesn't consider potentially existing items that have equal names from the item provider. But for now it at least checks duplicate names within the loaded Xtext files.
Bug: 436533
Change-Id: Ibd65bc863f795729345b76029abfadfb28819ef6
Signed-off-by: Philip Langer <planger@eclipsesource.com>

Activates NamesAreUniqueValidator for Item files

---

pom.xml

Fix the xtend generator to generate java classes with source level 1.7, so that it matches the tycho compiler configuration.
This happens only when running maven with JDK 8.
Bug: 470282

fix xtend generator to generate 1.7 compliant sources

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

This simply checks that the status has actually changed before performing an update.

Only act on status changes where there is actually a change

---

bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/ConfigDescriptionsTest.bundle/ESH-INF/thing/thing-types.xml
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelConverter.java

The ChannelConverter inherited from AbstractDescriptionTypeConverter. Therefore it used to override the automatically inferred config description URI which was stored in the unmarshalling context.
As channels don't contain config descriptions themselves, this mechanism is not needed at all, so the inheritance from AbstractDescriptionTypeConverter is not required.
Bug: 470901

Fix XML parsing for thing types with channels and config description

---

bundles/ui/org.eclipse.smarthome.ui.classic/web/WebApp/Design/Render.css

As of 2015, the majority of browsers supports `border-radius` CSS property without any vendor-specific prefixes. Therefore, `-webkit-` prefix was removed from `-webkit-border-radius` property. Non-prefxed version of `border-image` was added (Android 4 only supports this property with `-webkit-` prefix).

Classic UI CSS fixes for non-webkit browsers 

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/test/ConfigDescriptionRegistryOSGiTest.groovy
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionRegistry.java

This will merge configuration from the same URI from multiple config description providers
As discussed on the [Eclipse forum](https://www.eclipse.org/forums/index.php/m/1699697/#msg_1699697)
This hasn't yet undergone intensive testing. I checked that the existing tests work, and made a quick test to see that multiple providers for the same URI result in a single response, and this works ok. I suspect it therefore works, but it needs more tests to ensure the data is really merged.
Please let me know what you think - if you're generally happy with this approach (finally :) ) then I'll finish it off...

Allow multiple config description providers

---

bundles/ui/org.eclipse.smarthome.ui.classic/snippets/buttons.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/colorpicker.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/group.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/rollerblind.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/selection.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/selection_row.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/setpoint.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/slider.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/switch.html
bundles/ui/org.eclipse.smarthome.ui.classic/snippets/text.html
bundles/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java
bundles/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/ColorpickerRenderer.java
bundles/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/FrameRenderer.java
bundles/ui/org.eclipse.smarthome.ui.classic/web/WebApp/Action/Logic.js
bundles/ui/org.eclipse.smarthome.ui.classic/web/WebApp/Design/Render.css

This commit improves Classic UI browser compatibility. After this fix, Classic UI should be displayed correctly in Firefox. Flexbox model (both old and new syntax) is used to lay out elements. When element label is too long, ellipsis (…) is shown.
* `AbstractWidgetRenderer.java`: wrap label name in a `<span>`. It is hard to apply any styles to a text node in between of other blocks.
* `FrameRenderer.java`: instead of trying to remove html tags from label, this function may just call item registry. Also, previously mentioned change requires this change too.
* `ColorpickerRenderer.java`: same as above.
* `snippets/*.html`: Layout changes, mostly additional classes and element order. Changed snippets also were reformatted (it's hard to edit and debug one-line code).
* `Render.css`: …

Improve Classic UI cross-browser compatibility

---

docs/documentation/development/testing.md

Removed old 'org.eclipse.smarthome.core.library' dependencies.

Test documentation update

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/setup/RemovalTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/setup/ThingSetupManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingSetupManager.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingTracker.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

with this change, ThingHandlers get the chance to handle the removal of things explicitly before they actually get removed from the ThingRegistry.
Bug: 471761

remove-handling of things

---

pom.xml

...in a dedicated "QA" profile, which can be activated with
mvn clean install -P QA
Bug: 472700

Added jacoco maven plugin

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java

This posts the event that the thing has been added before notifying listeners. This ensures that the events are sent in the correct order (ie thing added, then items added).
https://bugs.eclipse.org/bugs/show_bug.cgi?id=473565

Reorder events when thing added

---

bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelConverter.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Channel.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ChannelBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelDefinition.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java

This allows the label and description in the channelType to be overridden in the channel. This allows the same channelType to be used for multiple channels.
The XML reader reads the new members and passes this into the channel description. When a thing is created, and the channels enabled, we first read the channel description to see if there is a label set - if so, it's used for the linked item, otherwise the info in the channelType is used.
There is a problem in that if the channel is disabled, and then re-enabled, there is no reference to the thing, and therefore no reference to the channel description, so we can only use the label from the channelType when re-creating the item.
I personally think that disabling channels should be done in a different way (ie by disabling the channel, …

Channel label/description override

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttBrokerConnection.java

When MQTT Broker URI or Client Id has been changed, MqttBrokerConnection fails to remove previous instance of Paho client. 
Since URI or client ID can only be set during creation of the Paho client instance, old values will be kept even after MqttBrokerConnection has been updated by owners and other values are updated on the client.
Now, updating either of those 2 values would cause new connection anyway, so deleting the old instance seems to be only solution.
This might seem like a minor deal, but I'm working on a MQTT plugin for OH2 (please see the SmartHome forum thread https://www.eclipse.org/forums/index.php/t/942318/  ), and without this patch configuring MQTT bridge dynamically won't be possible. 
Thanks!

Fix for MQTT transport service: Updates in Broker URI and Client ID not propagated correctly

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

* but status detail will be at NONE as this is the expected state
* See https://github.com/eclipse/smarthome/pull/407

Fixed Bug 473784: added review comment for better text message

---

extensions/transform/org.eclipse.smarthome.transform.javascript/META-INF/MANIFEST.MF
extensions/transform/org.eclipse.smarthome.transform.xpath/META-INF/MANIFEST.MF
extensions/transform/org.eclipse.smarthome.transform.xslt/META-INF/MANIFEST.MF

The OSGi specification mandates that a bundle declare all package
depenencies using either Import-Package or Require-Bundle. The one
exception to this rule is the java.* packages which is always delegated
to the boot classpath. All other packages dependencies must be declared
in the bundle's manifest file.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=474843

fix missing imports

---

bundles/ui/org.eclipse.smarthome.ui.classic/META-INF/MANIFEST.MF

* We should use "Import-Package" instead of "Require-Bundle".
* Remove some unused imported packages.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=475876

classicui: fix package imports, drop bundle req.

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightState.groovy
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStateConverter.java

Set maximum values for brightness and saturation to comply with the
official Hue API (254 instead of 255).
Extend HueLightHandlerOSGiTest test to include Increase/Decrease type.
Fix two tests of HueLightHandlerOSGiTest where incorrect channel was used.
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=470117
Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

Adjust max. brightness and saturation for Hue API

---

bundles/ui/org.eclipse.smarthome.ui.icon/META-INF/MANIFEST.MF

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=476161

remove version constraints for ui.icons

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightState.groovy

Fixes two issues introduced to hue test classes with pull request #342:
1. HueLightState.groovy: I thought I could directly return the String instead of assigning it to a def variable first. Unfortunately the placeholder expressions are only evaluated if the toString() method is called (if anybody is interested, see [documentation here](http://docs.groovy-lang.org/latest/html/documentation/#_string_interpolation)). This doesn't happen if the String is directly returned.
2. HueLightHandlerOSGiTest.groovy: A [change commited](https://github.com/eclipse/smarthome/commit/d260f5d969a841f2ad37c5526fab76e2c90ee393) after I made the pull request had been overwritten again. This was probably not detected by git because the respective line was moved to a seperate method. I also checked that nothing …

Fix issues in hue binding test classes

---

bundles/model/org.eclipse.smarthome.model.item.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.persistence.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.rule.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.script.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.sitemap.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.thing.runtime/META-INF/MANIFEST.MF

The model.*.runtime bundles must be started automatically, we need them
running for ESH.
The lazy bundle activation will retain the execution of the activator's
start method until a class is accessed first. This will result in not
started bundles and missing functionality (e.g. a bundle does not export
a package or no one use an exported package).
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477075

model.*.runtime must not use lazy activation

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingLinkManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Channel.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingLinkManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemThingLinkRegistry.java

Marked getLinkedItems and isLinked as deprecated.
Bug: 473567

Fixed linked item reference at the thing, if an item is updated.

---

extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/discovery/NtpDiscovery.java

* run discovery at the start of background discovery
* remove pattern from the channel to ensure visibility in paperUI
* Fixed possibe issue for Java.lang.Integer cannot be cast to
java.math.BigDecimaljava.lang error at start of binding

Improvements ntp binding

---

extensions/binding/org.eclipse.smarthome.binding.wemo/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/WemoBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/discovery/WemoDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java

== Fixes Wemo motion sensors not showing up in Thing discovery ==
Wemo motion sensors changed from 'Motion' to 'Sensor' ThingID.
Verfied with local Openhab2 + ESH setup.
== Testing Done ==
Verified that the new device is showing up in the Openhab console.
```
2015-11-13 21:39:24 [DEBUG] [e.s.b.wemo.handler.WemoHandler:232  ] - item 'wemo:motion:Sensor-1_0-221219L0101073' is located at 'http://192.168.2.49:49153'
2015-11-13 21:39:24 [DEBUG] [e.s.b.wemo.handler.WemoHandler:276  ] - New binary state '0' for device 'wemo:motion:Sensor-1_0-221219L0101073' received
2015-11-13 21:39:24 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'wemo:motion:Sensor-1_0-221219L0101073' updated: ONLINE
2015-11-13 21:39:24 [DEBUG] [e.s.b.wemo.handler.WemoHandler:285  ] - New state 'OFF' for device …
```

new ThingTypeUID for WeMo motion.

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java

The argument uri for the function getConfigDescription of the
ConfigDescriptionRegistry must not be null.
So if we want to use the configu description URI of a thing type, we
have to check if there is one first.

check for config description URI

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/constants.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.extension.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/js/services.repositories.js
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/extensions.html
extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/preferences.html

* Default route can be configured
* Installing and Uninstalling extensions clears binding and thing type cache
* Extension type tabs are sorted by the type definition from REST
* Existing enable/disable channel buttons are also used to link and unlink channels
* Further small fixes

Fixed a few things in the Paper UI:

---

bundles/core/org.eclipse.smarthome.core.id/src/main/java/org/eclipse/smarthome/core/id/internal/UUIDResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/binding/BindingResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/config/ConfigDescriptionResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/DiscoveryResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/InboxResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/extensions/ExtensionResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/link/ItemChannelLinkResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/service/ConfigurableServiceResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/setup/ThingSetupManagerResource.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java
bundles/io/org.eclipse.smarthome.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/SseResource.java

The Swagger UI requires the "value" parameter on the API annotation in order to group the methods of a resource within the UI.

added path to swagger annotations

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

If we use a channel group type multiple times in a thing type, we assign
different channel group ids to them.
Let's consider a thing that is using the channel group type "magic"
twice.
```text
...
<channel-groups>
<channel-group id="magic-1" typeId="magic" />
<channel-group id="magic-2" typeId="magic" />
</channel-groups>
...
```
A hyphen is a valid character for an ID, but it is not a valid character
for an item name.
If we are using the channel-group ID to generate an item name, we have
to call toItemName also for the ID.

channel group id can contain illegal item chars

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.configuration.js

The getChannels function iterates over all channels of a thing.
For every channel the channel it uses the getChannelTypeById function
to get a channel object supplied by the thing type.
This channel object is then further processed.
The getChannelTypeById looks for the given channel by the supplied
channel id in the channel array of the thing type only.
So all channels that are part of a channel group of the thing type are
missing.
We have to also look for the channel in the channel groups of the thing
type.

paper ui: thing cfg page miss channels of groups

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/test/ConfigDescriptionParameterBuilderTest.groovy

Fix for import error in ConfigDescriptionParameterBuilderTest.groovy
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=482684

Bug 482684 - ConfigDescriptionParameter methods should not return null

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/test/ConfigOptionRegistryOSGiTest.groovy
bundles/config/org.eclipse.smarthome.config.core/OSGI-INF/ConfigDescriptionRegistry.xml
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionRegistry.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigOptionProvider.java
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingConfigDescriptionProvider.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingConfigDescriptionProvider.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

As described [here](https://www.eclipse.org/forums/index.php?t=msg&th=1066227&goto=1711614&#msg_1711614).
This PR allows a binding to provide custom options in a config description. This information is provided within the CD request through a `GET thing/{thingUID}/config` REST interface.

Initial implementation of ConfigOptionProvider interface

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingConfigDescriptionProvider.xml

The ThingConfigDescriptionProvider DS file does reference not existing
functions.
Thas is realted to #495

ThingConfigDescriptionProvider fix DS

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingSetupManager.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

A label is assigned to the channel group type. But that label is not
assigned to the created items for a specific group.
If we want to show a label for every item group, we need that
information.
Preparation for e.g. #561

set label for channel group items

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/partials/control.html

The control view of the Paper UI cannot handle items that has been created for Things with channel groups correctly.
Instead of display the channels of the channel group, only the channel group themselves is visible, no channel of that group.
This has been fixed by this commit.
It also using the formatter, so some indentation has been changed.

Paper UI: control, add support for channel groups

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/HSBTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java

Currently there are methods to return RGB from HSB, but no constructor/method to create HSB from RGB.
I've found myself needing this for ZWave and BLE lights recently, so it seems like it might be useful as a constructor rather than putting it into my bindings...

Add constructor to create HSB from RGB.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web/js/controllers.extension.js

Avoid error that prevents the display of all the extensions
TypeError: Cannot read property 'extensions' of undefined
at controllers.extension.js:16
at Object.r [as forEach] (angular.min.js:7)
at controllers.extension.js:14
at angular-resource.min.js:10
at angular.min.js:112
at n.$eval (angular.min.js:126)
at n.$digest (angular.min.js:123)
at n.$apply (angular.min.js:127)
at l (angular.min.js:81)
at F (angular.min.js:85)

fix for missing bindings in karaf build extensions view

---

.gitignore

The directory is created and an uuid is placed there at test execution.
Git should ignore the whole userdata directory of that module.

ignore the core.id.test userdata

---

targetplatform/smarthome.target

The url of the jmDNS update site has changed, it is therefore important to update the target platform.

updated jmdns url

---

bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSServiceImpl.java

I had exceptions like
```
java.lang.IllegalStateException: This DNS is closed.
at javax.jmdns.impl.JmDNSImpl.registerService(JmDNSImpl.java:999)
at org.eclipse.smarthome.io.transport.mdns.internal.MDNSServiceImpl$2.run(MDNSServiceImpl.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```
in the log - this fix should solve that.

catching exception when mdns service is already closed

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelTypeDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/channeltyperesource.xml
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/channel/ChannelTypeResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java

This adds a channel-type rest endpoint to provide access to the channel types as discussed [here](https://www.eclipse.org/forums/index.php?t=msg&th=1072114&goto=1715959&#msg_1715959).
This hasn't been fully tested, and is submitted for comments (it works, but I was tested briefly while sitting on a plane for 9 hours!).

Initial commit of "channel-type" REST resource

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/console/InboxConsoleCommandExtension.java
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/setup/ThingSetupManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/SetupConsoleCommandExtension.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java
bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/groovy/org/eclipse/smarthome/io/rest/core/discovery/InboxResourceOSGITest.groovy
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/InboxResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/setup/ThingSetupManagerResource.java
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy

Taken from: https://github.com/eclipse/smarthome/pull/671#issuecomment-162810507
> Note that the whole "SetupManager" is a functionality that I consider something optional (and e.g. not relevant for openHAB 2). Items should imho not be automatically created and there specifically should not be a "shadow structure" of a thing and its channels as items.
First note: It is relevant for the openHAB 2 auto approve service.
The ThingSetupManager contains seven public constructors (and one private) to allow to not explicitly set optional parameters.
If we want to add another optional attribute, we have to create a bunch of new constructors.
I created a class that holds that parameters and no there is only one public constructor.
If you create an object of that class you need only to give the two …

improve localization support

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/items/ItemUpdaterOSGiTest.groovy

There are currently two tests in the ItemUpdateOSGiTest.
* ItemUpdater sets item state
* ItemUpdater sends state changed event
The "sets item state" test triggers a changed event
* UnDefType.NULL => OnOffType.ON
The "sends state changed event" test triggers a changed event
* OnOffType.ON => OnOffType.OFF
The first test does not check / reset the event.
The second test checks for the ON => OFF event.
If the first event is stored to "last event" but the second on is not
yet received, the check for "ON => OFF" will fail.
The receiving of the event is done asynchron, so we have to use correct
sync mechanism, too.

fix timing dependend test execution

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/items/ItemUpdaterOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GenericItemTest.groovy
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GroupItemTest.groovy
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/TestItem.java
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/events/ItemEventFactoryTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemUpdater.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/GroupItemStateChangedEvent.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemStateChangedEvent.java

Assertions:
If a member of a group is changed then notify the observers of the member as well as the observers of the group about the changes.
If a member is added or removed from a group then notify the observers of the group about the added or removed member.
Observers of the group are informed about the name of the changed, added or removed member.
If one member is added or removed then one group change is fired.
If one member changes two changes are fired: one change for the member itself and one for the group.
Implementation:
GroupItems hold a State of type GroupType which contains the name of the added, removed or changed member and the type of the change as enumeration constant of type GroupChange (ADDED, REMOVED, CHANGED)
If a member is added, removed or changed the group notifies …

Add GroupItemStateChangeEvent #596

---

tools/ref-tag/create.sh

The parameter "-e" for readlink is not available on OS X.

ref-tag: add function to get aboslute path

---

bundles/model/org.eclipse.smarthome.model.item.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.item.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.item.runtime/build.properties
bundles/model/org.eclipse.smarthome.model.item.runtime/src/org/eclipse/smarthome/model/item/runtime/internal/ItemRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.persistence.runtime/.project
bundles/model/org.eclipse.smarthome.model.persistence.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.persistence.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.persistence.runtime/build.properties
bundles/model/org.eclipse.smarthome.model.persistence.runtime/src/org/eclipse/smarthome/model/persistence/runtime/internal/PersistenceRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.rule.runtime/build.properties
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/RuleRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.script.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.script.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.script.runtime/build.properties
bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/internal/ScriptRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.sitemap.runtime/.project
bundles/model/org.eclipse.smarthome.model.sitemap.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.sitemap.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.sitemap.runtime/build.properties
bundles/model/org.eclipse.smarthome.model.sitemap.runtime/src/org/eclipse/smarthome/model/sitemap/runtime/internal/SitemapRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.thing.runtime/.project
bundles/model/org.eclipse.smarthome.model.thing.runtime/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.thing.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.thing.runtime/build.properties
bundles/model/org.eclipse.smarthome.model.thing.runtime/src/org/eclipse/smarthome/model/thing/runtime/internal/ThingRuntimeActivator.java

This is a proof of concept to have services to check if the model runtime has been started (other services could depend on them on so they are started after...).
I have a short test using openHAB 2 demo and all seems to be working.
Perhaps someone could give it a try.
Do you think this could help us?

use DS for model.*.runtime

---

bundles/automation/org.eclipse.smarthome.automation.rest/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/JSONResponse.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/RESTCoreActivator.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

Move the JSONResponce from org.eclipse.smarthome.io.rest.core.internal to org.eclipse.smarthome.io.rest.core package.

Add error message when auotmation's create rule REST call is faild.

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GenericItemTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java

GenericItem#addGroupName and #addGroupNames do not allow null as parameter. An InvalidArgumentException is thrown.

fixes #774: Guard GenericItem#addGroupName 

---

bundles/io/org.eclipse.smarthome.io.rest.core/META-INF/MANIFEST.MF

This fixes a build problem in openhab-core.
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

Make last swagger dependency optional.

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/.classpath
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/.project
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/ESH-INF/binding/binding.xml
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/OSGI-INF/FSInternetRadioDiscovery.xml
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/OSGI-INF/FSInternetRadioHandlerFactory.xml
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/about.html
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/build.properties
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/pom.xml
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/FSInternetRadioBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/handler/FSInternetRadioHandler.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/FSInternetRadioHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadio.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioApiResult.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java

This binding is based on openhab 1.x binding frontiersiliconradio and is
migrated to the new ESH API, including device discovery.

Initial version of FS internet radio binding.

---

extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml

This fixes a minor bug #844 introduced in PR https://github.com/eclipse/smarthome/pull/829
Signed-off-by: Grady Duncan <gradyduncan@gmail.com>

Force http download for node & npm

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java

1. There are several [HTTP status codes](https://www.ietf.org/rfc/rfc2616.txt) that are not considered failures besides 200 (SC_OK).
1. There are many cases where failure status codes are expected by the caller, so HttpUtil should not be logging a message at WARN level.

Correct logging for HttpUtil

---

bundles/config/org.eclipse.smarthome.config.xml.test/src/test/groovy/org/eclipse/smarthome/config/xml/test/ConfigDescriptionsTest.groovy
bundles/config/org.eclipse.smarthome.config.xml.test/src/test/resources/test-bundle-pool/ConfigDescriptionsFragmentTest.fragment/ESH-INF/config/config.xml
bundles/config/org.eclipse.smarthome.config.xml.test/src/test/resources/test-bundle-pool/ConfigDescriptionsFragmentTest.fragment/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.xml.test/src/test/resources/test-bundle-pool/ConfigDescriptionsFragmentTest.host/ESH-INF/thing/MyThingType.xml
bundles/config/org.eclipse.smarthome.config.xml.test/src/test/resources/test-bundle-pool/ConfigDescriptionsFragmentTest.host/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/AbstractAsyncBundleProcessor.java
bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java
bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/SyntheticBundleInstaller.java

AbstractAsyncBundleProcessor#isDirectoryPresent should also check attached fragments of a bundle

allow parsing of config descriptions of fragment bundles 

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/exec/ExecUtil.java

PR https://github.com/openhab/openhab/pull/3825.
`executor.setExitValue(1)` means "for any non-1 exit code, raise an exception" which then gets logged as WARN.  `executor.setExitValues(null)` [means](https://commons.apache.org/proper/commons-exec/apidocs/org/apache/commons/exec/DefaultExecutor.html#setExitValues(int[])) "skip checking of exit codes".  Otherwise the log is spammed with WARNs about non-1 exit codes.
Also, unlike OH1, other exceptions should be logged as WARN, not ERROR, since they don't effect the stability of the runtime.

ExecUtil: Sync ESH with OH 1.8.1

---

extensions/transform/org.eclipse.smarthome.transform.regex.test/src/test/java/org/eclipse/smarthome/transform/regex/internal/RegExTransformationServiceTest.java
extensions/transform/org.eclipse.smarthome.transform.regex/src/main/java/org/eclipse/smarthome/transform/regex/internal/RegExTransformationService.java

This modification allows the Regex transformation to do substitutions. A substitution pattern is specified using a syntax similar to sed, Python, Perl, etcetera. The substitution will be performed if the regex looks like "s///". The substitution can use capturing groups using the "$n" syntax supported by Java regular expressions. By default, the substitution is applied to the first match. If a "g" is appended to the regex (e.g., "s/([0-9]+)000/$1K/g"), then the substitution if applied to all matches in the source string.
Signed-off-by: Steve Bate <svc-eclipse@stevebate.net> (github: steve-bate)

Regex substitution support

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html

Removes .min from all JS files that are copied. Does not remove .min from files that were combined with other files. #918
Also makes it so that only woff fonts are copied over. #924
Signed-off-by: Grady Duncan <gradyduncan@gmail.com>

Minor gulp fixes

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.linkchannel.html

Link button enable/disable based on select value. Fix https://github.com/eclipse/smarthome/issues/857

Link channel select fix

---

extensions/ui/org.eclipse.smarthome.ui.paper/package.json

Angular material version updated to 0.10.1. Version 0.10.0 is not compatible with PaperUI.

Angular material version update

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ActionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/CompositeActionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/CompositeConditionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/CompositeTriggerType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ConditionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/Input.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ModuleType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/Output.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/TriggerType.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ParameterOption.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/dto/AbstractLinkDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/dto/ItemChannelLinkDTO.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/dto/ItemThingLinkDTO.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java

This adds an easy support for deserialization without using the
sun.misc.Unsafe class.
Bug: https://github.com/eclipse/smarthome/issues/876

add no-arg constructor

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

Currently when creating a new item, it tags or groups is null, the call fails with error 500 and it's not so easy to know what's wrong. It seems that it should be allowable to create items that don't have tags or groups, so this adds a null check which creates empty arrays for tags and groups when the item is created.

Add null checks to REST interface when creating item

---

bundles/io/org.eclipse.smarthome.io.rest.test/src/test/groovy/org/eclipse/smarthome/io/rest/test/filter/CorsFilterTest.groovy
bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/filter/CorsFilter.java

This is the fix regarding issue #903
Now the response to CORS preflight request also contains the header
"content-type":"application/json".
Therefore, the CORS request Rest APIs which post/put JSON data will also succeed.
Signed-off-by: shry15harsh <shry.harsh@gmail.com>

cors preflight content type header in response fix with reference to #903

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

1) Things configurations are now updated through /things/{UID}/config rest endpoint as described here https://github.com/eclipse/smarthome/issues/771
2) Also fixes the issue https://github.com/eclipse/smarthome/issues/960

Thing's configurations now posting to '/things/{UID}/config'

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

Setup Wizard's name changed to 'Inbox' as discussed here https://github.com/eclipse/smarthome/issues/890.

'Setup Wizard' name change

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingSetupManager.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/setup/ThingSetupManager.java

The horse is dead, long live the horse.!!!
The ThingSetupManager used to listen to ThingRemovedEvents, which are sent out not only if a Thing gets removed explicitly, but also if a ThingProvider gets removed (the ThingRegistry notifies the listeners by sending out the event). As a result, the TSM deletes will also delete Items etc. if during shutdown DS deactivates the ManagedThingProvider before the ThingRegistry, leading to data loss (i.e. room assignment and labels cannot be restored).

fix ThingSetupManager removal handling

---

bundles/io/org.eclipse.smarthome.io.console.karaf/src/main/java/org/eclipse/smarthome/io/console/karaf/internal/CommandWrapper.java

The list of arguments does not need to be string objects.
If you are using a number on the Karaf command line the object type
could be e.g. a Long class object.
Bug: https://github.com/eclipse/smarthome/issues/984

karaf console wrapper: argument list as string

---

bundles/core/org.eclipse.smarthome.core.persistence/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.persistence/OSGI-INF/persistenceresource.xml
bundles/core/org.eclipse.smarthome.core.persistence/build.properties
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/rest/ItemHistoryBean.java
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/rest/ItemHistoryListBean.java
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/rest/PersistenceResource.java
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/rest/ServiceBean.java

Initial REST interface for persistence - moved over from HABmin bundle (and not tested yet - just moved, but it was heavily tested there :) ).
This provides two interfaces
`GET /rest/persistence/` which returns a list of persistence services
`GET /rest/persistence/{service}/{item}?{starttime=}&{endtime=}` which returns persistence data from the item for the specified service. 
As discussed on the forum, this is a straight copy of what I've been using with HABmin, so I welcome comments and am happy to change if needed.  If this looks like it's roughly what you're after, I'll tidy it up...

Initial persistence REST resource contribution - moved from HABmin

---

targetplatform/EclipseSmartHome.setup

If you open "org.eclipse.smarthome.io.console.karaf" in the Eclipse SmartHome IDE, the IDE shows three errors caused by missing lifecycle mappings.
Two of them have to be disabled in the IDE settings, for the maven-compiler-plugin a m2e connector should be installed.
The search for connectors identify four connectors as usable (in combination of other features) to be installed:
* m2e-wtp - Maven Integration for WTP
* M2E connector for the Eclipse JDT Compiler
* Maven Integration for Eclipse JDT APT
* Groovy-Eclipse M2E integration

add m2e stuff

---

bundles/automation/org.eclipse.smarthome.automation.module.core/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.module.script/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.module.timer/META-INF/MANIFEST.MF

There are some bundles that name does not fit to the scheme the other bundles are using.
Before:
```text
81|Active     |    4|Eclipse SmartHome Automation API (0.8.0.qualifier)
82|Active     |    4|Eclipse SmartHome Automation commands (0.8.0.qualifier)
83|Active     |    4|Eclipse SmartHome Automation Core (0.8.0.qualifier)
84|Active     |    4|Automation Modules (0.8.0.qualifier)
85|Active     |    4|Script Automation Modules (0.8.0.qualifier)
86|Active     |    4|Eclipse SmartHome Automation Script Globals (0.8.0.qualifier)
87|Starting   |    4|Timer Automation Modules (0.8.0.qualifier)
88|Active     |    4|Eclipse SmartHome Automation GSON Parser (0.8.0.qualifier)
89|Active     |    4|Eclipse SmartHome Automation Providers (0.8.0.qualifier)
90|Active     |    4|Eclipse SmartHome …
```

fix bundle names

---

extensions/ui/org.eclipse.smarthome.ui.paper/build.properties

CQ 10013 has been approved for check-in, we therefore can now package the material design icons directly with the Paper UI.

add md-icons to Paper UI

---

bundles/automation/org.eclipse.smarthome.automation.module.timer/META-INF/MANIFEST.MF

The automation module 'timer' should be activated if present and not if
a class is used first. The lazy activation conflicts with the intention
of a module that extents some functionality.

drop lazy activation

---

bundles/automation/org.eclipse.smarthome.automation.module.timer.test/src/test/groovy/org/eclipse/smarthome/automation/module/timer/internal/RuntimeRuleTest.groovy

The current test sets an item, check if the state of the item is the set
one and then checks if the state has been changed to another one. The
state change is triggered by a timer triggered rule.
The timer activates the rule every second (using wildcard for the cron
expression statements).
If the rule is triggered between the set state and the assertion that
expects the state is the set one, the test fails.
This commit changes the logic that it disables the rule to check if the
value has been set and then enables it again afterwards before checking
if the rule has been applied.
Most stuff are changes that has been done by the formatter.
The real change is this one:
```diff
def numberOfTests = 3
for (int i=0; i < numberOfTests;i++){
+            ruleRegistry.setEnabled(rule.UID, false) …
```

automation timer test stabilization

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/servlet/CmdServlet.java

By default, Firefox tries to parse XMLHTTPRequest responses as `text/xml`. When the response is empty, it shows a warning in the console (`no element found` meaning that there is no document root element). This message is shown when items are changed through BasicUI or ClassicUI. This commit fixes it.
This is a combination of 2 commits.
* REST: Change ItemResource response content-type to text/plain
* ClassicUI: Set command servlet response content-type to text/plain

Change REST ItemResource and ClassicUI response content-type to text/plain

---

bundles/automation/org.eclipse.smarthome.automation.module.script.test/META-INF/MANIFEST.MF

This PR should perhaps not be merged immediately.
The following change is necessary on my machine to get the automation script test working.
Without this lines it fails.
The test themselves does not use this packages directly (commons-io and commons-lang) and IMHO the org.eclipse.smarthome bundles that are involved and are using this packages, does have a valid import package in their manifest.
The Eclipse IDE can run the test without this changes, but maven fails (on my machine) all the time.
Could someone help me to investigate this problem.
```text
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.automation.module.script.ScriptRuleTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, …
```

Test failure: have a workaround, need a solution

---

bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope/src/main/java/org/eclipse/smarthome/automation/module/script/defaultscope/internal/DefaultScriptScopeProvider.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java
bundles/io/org.eclipse.smarthome.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/internal/SseActivator.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioApiResult.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java
extensions/transform/org.eclipse.smarthome.transform.jsonpath/src/main/java/org/eclipse/smarthome/transform/jsonpath/internal/JSonPathTransformationService.java
extensions/transform/org.eclipse.smarthome.transform.xslt/src/main/java/org/eclipse/smarthome/transform/xslt/internal/XsltTransformationService.java
extensions/ui/org.eclipse.smarthome.ui.paper/src/main/java/org/eclipse/smarthome/ui/paper/internal/PaperUIApp.java

This is related to #1006 and will process the (simple) cases where a static logger is used but is not necessary.

use non-static logger members if not necessary

---

docs/documentation/features/internationalization.md
docs/documentation/features/rules.md

Fixes include:
- File documentation/features/**rules.md** - unnecessary space was removed which caused breaking of the bold tag.
- File documentation/features/**internationalization.md** -  structure layout from documentation/develoment/bindings/**how-to.md**  was applied (so that the files listed in ESH-INF/i18n folder are visually rendered in the same way as in the Binding How-To). This correction actually fixes a rendering bug - all _.properties_ files were displayed on the same line, together with the "ESH-INF/i18n" text.

Fixed broken and incorrect markdown syntax

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

This PR adds the capability for ModuleHandlerFactories to dynamically change their provided implementations of ModuleTypes.
This is added to allow a ScriptEngine etc. to provide additional ModuleTypes without generating a new ModuleHandlerFactory for each type.

allow ModuleHandlerFactory to dynamically add and remove types

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

This change will permit to call the method from different packages. The method is optimize version of getRule(UID) != null, because it does not create a copy of the rule, which is not needed for this check.

change visibility to public of RuleEngine.hasRule() method

---

docs/documentation/development/guidelines.md

Removed code formatter and clean up rule references in docs/development/**guidelines.md** (since esh-formatter.xml and esh-clean-up.xml were unused and thus removed, the references in the documentation were leading to files which did not exist).

Removed code formatter and clean up rule references in guidelines.md

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/BindingBaseClassesOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

...in order to break up the long call-stack which prevents service registration callbacks to get fired when adding/removing services within handler initialization.

moved thing handler initialization into a separate thread

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/ArithmeticGroupFunction.java

This allows group items who are not exactly the same base item to be included in logic operations, for example a dimmer can now be included in a group switch item.
Signed-off-by: digitaldan <dan@digitaldan.com>

Backport of https://github.com/openhab/openhab/pull/1460.

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTO.java

This guards against the case where there is no label set for a thing, but there's also no linked item.

Fix exception in EnrichedThingDTO where no label exists

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

There's currently no way to update the thing label - I assume that this should be allowed and this is just an oversight...

Allow thing label to be changed

---

extensions/ui/org.eclipse.smarthome.ui.classic/snippets/main.html

`content` must be separated with commas, not semicolons; `user-scalable=0` is undocumented and should be `user-scalable=no`.
Give me a :star: for the world's most inconsequential pull request!

ClassicUI: Incorrect format for viewport <META> tag

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/ItemRegistryOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java

Fixed ItemRegistryImpl.getItemsByTag() and added tests for that.
Signed-off-by: Sebastian Janzen <sebastian.janzen@innoq.com>

Fix getItemsByTag

---

extensions/ui/org.eclipse.smarthome.ui.classic/snippets/chart.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/image.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/image_link.html
extensions/ui/org.eclipse.smarthome.ui.classic/snippets/main.html
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/ChartRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/ImageRenderer.java

Support the `refresh=` parameter to Image and Chart widgets in all cases in the classic web UI.  Testing feedback should go in [this topic](https://community.openhab.org/t/please-help-test-fix-for-image-and-chart-refresh-in-classic-web-ui/8106).  If wider testing deems this change fit, I will add a comment.
Same change as in https://github.com/openhab/openhab/pull/4117.

ClassicUI: full image and chart refresh

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/package.json
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/material-icons.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.scan.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.itemcontrol.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/preferences.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

At the moment all fonts of https://github.com/google/material-design-icons/tree/2.0.0/iconfont are included.
Need to check if in the bundle e.g. woff only is enough.
For the Roboto font only woff is used ATM but there are errors in the Web console that there are tries to load the woff2...
Please have a look if there is something critical missing or it could be merged and pimped later

use material icons

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/material-icons.css

This will reduce the bundle size (about 268K).
```
120K	MaterialIcons-Regular.eot
108K	MaterialIcons-Regular.ttf
64K	    MaterialIcons-Regular.woff
40K     MaterialIcons-Regular.woff2
```

material icons: use woff format only

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/roboto-fontface.css

At the moment the roboto fontface css and web font is downloaded by npm.
With gulp we add the font format woff and the css to the bundle.
The css refer the whole collection of formats:
* eot
* woff2
* woff
* ttf
* svg
If we have a look at your browser console, you will see errors (at least with firefox) because files should be loaded that are not available. At least the recent Firefox tries to load the woff2 file.
If we bundle only the woff file, we should not use the unmodified upstream css file that refers to all the other files.
This PR is split into two commits.
The first one adds the unmodified css file and remove it from gulp.
The second one cleans the css file to refer only available files / the woff file.

Roboto font: fix css

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.scan.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.thingconfig.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/preferences.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

The about.html has not been reformatted, as it is no part of the web
stuff.
Related to: https://github.com/eclipse/smarthome/pull/1161

Paper UI: apply the formatter to all js and html files

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingConfigDescriptionProvider.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingConfigDescriptionProvider.java

Changes the provider to allow it to work when the thing type is different than the thing name.
Fixes #1182 

Update ThingConfigDescriptionProvider to properly use thing type

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactory.java

`thingHandlerFactory.createThing` may return null in which case NPE is thrown here when we try and access the thing. Checking for this ultimately results in the 'no binding supports the thing type' response.

Fix NPE in thing factory

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

Support displaying of channels that are not defined in ThingTypes and ChannelTypes as described here: https://github.com/eclipse/smarthome/issues/1129.

Support channels without channel types

---

bundles/core/org.eclipse.smarthome.core.transform/src/main/java/org/eclipse/smarthome/core/transform/AbstractFileTransformationService.java
extensions/transform/org.eclipse.smarthome.transform.map.test/src/test/java/org/eclipse/smarthome/transform/map/internal/MapTransformationServiceTest.java

As it seems, the events take some time to arrive on some OS/file systems...
(see #1131)
Therefore, in this change
* The test waits up to 10 seconds in order to verify the assertions
* The test first copies the property files to another place, so no versioned files get touched

Making MapTransformationServiceTest more robust

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosXMLParser.java

The code that sets the logo member is comment, the variable is present
but not used.
If we do not need logo at all (there is also no need to write that
member if it is never read) there is no need to keep that field.

sonos: comment unused variable as long as code is comment

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/status/test/ConfigStatusInfoTest.groovy
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusMessage.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusService.java
extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java

This is especially the case for states like PENDING where there might not be much to add, and no message is really needed - the user just needs to know the update is pending. This change ensures the status is provided, but without a message.

Config status should allow situation with no message

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosXMLParser.java

I don't know why it has been decided to not add a default case to the
switch statement. But we should at least handle every value of the
enum(s).

sonos: handle every case in switch

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

With this PR, the control ui of the Paper UI now shows an "All" tab and lists all available Things on it.

made control ui work without groups

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

This is neccessary if you have enableChannels=true. Because if you use inbox/approve, the links are made after the HueLightHandler is created and the first channel updates are not forwarded to any item - they're linked after that.

Fix #1159 Add channelLinked() to HueLightHandler

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/InboxOSGITest.groovy

as sometimes the (asynchronously delivered) events of the test setup were captured by the assertions, leading to false positives.

fixed InboxOSGiTest timing issues

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy

This PR does not contain any code change.
For tests I added a TIMEOUT_DFL member to this class because it is the base class for the most tests. So, we could define a default timeout at one place and use that in the other tests. We have multiple tests that fails because the timeout is to small / the machine is to slow / there is currently a high CPU load. There is no need to keep a timeout small except you want test performance. If the condition is met, a large timeout does not care. If it is small, "small" machines fails at test execution.
As stated above, this PR does not contains this change, but to prevent a more complicated diff if this change or another one is done, I prefer to use the correct format now.

use current formatter rules for OSGiTest

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html

1) Ignored results were always showed in Inbox due to a bug as reported here: https://github.com/eclipse/smarthome/issues/1190
2) Removed default shadow of buttons.

Toggle ignored results and removed buttons shadow

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusMessage.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ConfigStatusThingHandler.java

Adds processing of config updates when the binding calls updateConfiguration.

Add override of updateConfiguration for status updates

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

The function getDefaultValue should handle all types. It should not be
necessary to check for one type before and delegate the other types to
that function.

rule engine: get default value: handle all types

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

Fixes https://github.com/eclipse/smarthome/issues/1122

allow colons (and other characters) in tags in the REST request

---

bundles/io/org.eclipse.smarthome.io.audio/META-INF/MANIFEST.MF

Fixes https://community.openhab.org/t/oh2-startup-error-in-latest-build/9082

removed reference to non-existent OSGI-INF

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/events/ItemEventFactoryTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/GroupItemDTO.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedGroupItemDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java

This will allow to distinguish between switch and rollershutter item on a client to display proper control widget for a group.
Bug: https://github.com/eclipse/smarthome/issues/1252
Signed-off-by: Robert Michalak <rbrt.michalak@gmail.com>

added baseItem to group item REST response.

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/ConfigDescriptionValidator.java

The recent addition of validation has broken some features in ZWave where multiple selection parameters are used. This adds a check to see if the returned parameter is a multi select parameter, and if it is, it handles each value in the list separately so that validation is performed on all values.

Fix config validator so it handles multiple selection values

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js

Fixed toast which is showed when a thing is added manually the reported git issue is: https://github.com/eclipse/smarthome/issues/1278

Fixed thing's manual-add toast

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Fixed automatic redirection issue caused by action url in toast service. Related git issue is: https://github.com/eclipse/smarthome/issues/1277.

Fixed automatic redirection issue

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy

...in order to get rid of the occasional
java.lang.NoSuchFieldException: http
exception.

made HueBridgeLightHandlerOSGiTest more robust wrt timing

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.unlinkchannel.html

Allows confirmation before a channel is unlinked as described here: https://github.com/eclipse/smarthome/issues/1105.

Unlink channel after confirmation

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.thingconfig.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

Allow user to specify thing id while manually creating a thing. Related issue is: https://github.com/eclipse/smarthome/issues/762.

Allow specifying thing ID during manual creation

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/MinMaxValidator.java

Min/max validation should allows values outside of min/max if they are in the defined options. As an example, in Zwave we have lots of parameters that have a range of (say) 0 to 100, but have an option of setting 255 to disable. With the current implementation, I would need to set min/max to 0/255, which allows any value. It seems better to me to allow values to be outside of the range to cover this case.
This was discussed a long time ago when I added the 'limit to options' configuration in the parameter for exactly this purpose.

Allow options to be outside of min/max in validator

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/ChangeThingTypeOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

...in order to prevent a race condition when changing thing types
during initialization (see #1131).

Wait for running handler registration to complete

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/service/ConfigurableServiceResource.java

If no configuration has been set yet for a service, the REST API currently returns a 404.
If a service is present, a not set configuration should instead be considered to be an empty configuration - the web client (here the Paper UI) should not have to care about that. 

Return empty config instead of 404

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.configurebinding.html

Fixed the problem with configure button in bindings as reported here: https://github.com/eclipse/smarthome/issues/1312

Bug fix for 'configure button in bindings not working'

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Parse integer and boolean values returned as strings in configurations. 
fixes https://github.com/eclipse/smarthome/issues/1313

Parse string to integer and boolean values

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js

1) While creating a module allow only those modules types that have a visible visibility.
2) While editing a rule show only modules with a visible visibility in their module types.
fixes https://github.com/eclipse/smarthome/issues/1336.

Show only module types with visibility 'visible'

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Fixed invalid config options shown while creating a new module.
fixes https://github.com/eclipse/smarthome/issues/1346

fixes invalid configurations shown in modules

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css

Use normal font for all edit fields except for field of context type script.
fixes https://github.com/eclipse/smarthome/issues/1344

Use monospace font only in script's text area

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuntimeRule.java

JSON parses all integers to doubles, hence we have to deal with this situation as well.
It probably makes sense to merge all this validation logic with the ConfigValidation code soon.

Also allow Double if the value is an integer number

---

bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/engine/ScriptExecutionThread.java

This is related to:
https://github.com/eclipse/smarthome/issues/1393#issuecomment-211540325
Which message should be shown, the message of the exception themselves
or the message of the exception that is the cause of the excpetion.
I do not see any reason to handle all the different cases here and
generate a suitable message itself.
We should not limit the information of the exception for logging.

Do not cut of script exception

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/extensions/ExtensionResource.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

This PR also restore the function to force that the rules category is hidden by configuration (#1406).

Hide extensions tab if rest endpoint is unavailable

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

As thingTypeUID can have a custom value the get request for thingType should only be sent after thing is received. 

Get thingType only when thing is returned

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/AbstractWidgetRenderer.java

fixes https://github.com/eclipse/smarthome/issues/1410
fixes #1367

correctly escape all parts of a url (also queries, not only paths)

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/dto/ConfigDescriptionDTOMapper.java

for correct mapping of null values, String.valueOf must not be used

defaultValue must not be mapped with String.valueOf 

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/RuleResourceBundleImporter.java

A dead lock appares:
```
"Rules Storage Loading Thread (Bundle 46)":
at com.prosyst.mbs.impl.services.automation.core.provider.ModuleTypeAdminResourceBundleProvider.getModuleType(ModuleTypeAdminResourceBundleProvider.java:238)
- waiting to lock <0x00000007ac6846a0> (a java.util.HashMap)
at org.eclipse.smarthome.automation.core.internal.type.ModuleTypeManager.get(ModuleTypeManager.java:69)
at org.eclipse.smarthome.automation.core.internal.type.ModuleTypeManager.get(ModuleTypeManager.java:62)
at org.eclipse.smarthome.automation.core.internal.RuleEngine.setDefaultConfigurationValues(RuleEngine.java:1412)
at org.eclipse.smarthome.automation.core.internal.RuleEngine.validateModules(RuleEngine.java:281)
at …
```

Fix deadlock, improve synchronizations.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js

A temporary solution to script crashing error caused by sprintf library while parsing DateTimeItem with defined pattern. This solution does not consider pattern field of DateTimeItem for now.
Should fix https://github.com/eclipse/smarthome/issues/564

Manually parse DateTimeItem in Control ui

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

Internally the Keys are Strings and some methods (e.g. put(), keySet(),...) have Strings already, so I don't see why it should not be consistent...

aligned key types in Configuration

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

The advance flag is part of the channel type, not the channel.
Bug: https://github.com/eclipse/smarthome/issues/1426

fix checkAdvance(channels) implementation

---

features/karaf-tp/src/main/feature/feature.xml

The org.eclipse.xtext.xbase.jvmmodel.JvmModelCompleter class is using
javax.annotation.Generated but misses that import package statement.
Related to: https://bugs.eclipse.org/bugs/show_bug.cgi?id=492661

use a patched xtext.xbase artifact

---

features/karaf-tp/src/main/feature/feature.xml

At the moment there is a jersey-min bundle used, that is a collection of multiple other bundles.
This could involve that stuff is installed multiple times (e.g. javax apis) instead of sharing them.
This PR will drop the usage of that "mega meta" bundle and use a feature instead.

karaf-tp: drop mega bundles and use features instead

---

features/karaf-tp/src/main/feature/feature.xml

This commit does the same for swagger-all that has been done for jersey-min in #1436
This has been two really fat bundles.
* jersey-min about 4.4 MB
* swagger-all about 6.6 MB

use swagger-jersey2 feature instead of mega bundle

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

In #1433, a binary incompatible change was introduced, leading to more irritations than expected (#1437, #1446)... 
Therefore, this PR could ease the pain during the transition phase. Once all bindings in the downstream products have been compiled again, we can safely remove the deprecated methods again.

Ease the pain of the incompatible change introduced with #1433.

---

features/karaf-tp/src/main/feature/feature.xml

If the jersey modules are initiated on the same level as the ones that
registered the ServletContainer class, this could lead to errors using
asyncrhonous processing:
javax.servlet.ServletException: java.lang.UnsupportedOperationException:
Asynchronous processing not supported on Servlet 2.x container.
See e.g.
https://gist.github.com/maggu2810/ef57c2656fa9f76052042da5f70d9d2f
This could be worked around to start the Jersey components in front of
the usage.
The important module is jersey-core-server, that adds support for
servlet 3.x.

fix jersey servlet support

---

features/karaf-tp/src/main/feature/feature.xml

Without this start-level tuning you can run in a
HTTP ERROR 503: Jersey is not ready yet!
The OSGi console log could look similar to this one:
```text
2016-05-04 17:27:10,704 | ERROR | lixDispatchQueue | sse                              | 172 - org.eclipse.smarthome.io.rest.sse - 0.8.0.a16 | FrameworkEvent ERROR - org.eclipse.smarthome.io.rest.sse
org.osgi.framework.BundleException: Activator start error in bundle org.eclipse.smarthome.io.rest.sse [172].
at org.apache.felix.framework.Felix.activateBundle(Felix.java:2276)[org.apache.felix.framework-5.4.0.jar:]
at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)[org.apache.felix.framework-5.4.0.jar:]
at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)[org.apache.felix.framework-5.4.0.jar:]
at …
```

add another fine tuning of the jersey start levels

---

extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY3.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY5.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/ZonePlayer.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/SonosBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/config/ZonePlayerConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/discovery/ZonePlayerDiscoveryParticipant.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAlarm.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosEntry.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosMetaData.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosResourceMetaData.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosXMLParser.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosZoneGroup.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosZonePlayerState.java

- Added notification sound functionality
- Added slave->coordinator delegation for all relevant channels
- Delegate all relevant item state events to all group members
- Use seperate ThingTypes for each Sonos player
- Remove deadlock during GEMA subscription
- Reduce unnecessary item state updates
- Clear track metadata channels (album, artist, track) when clear playlist in the Sonos-App
- Add Sonos room name to discovery result
- Cache coordinator ThingHandler and update it during change in Sonos grouping

Update Sonos binding

---

extensions/transform/org.eclipse.smarthome.transform.scale/META-INF/MANIFEST.MF
extensions/transform/org.eclipse.smarthome.transform.scale/src/main/java/org/eclipse/smarthome/transform/scale/internal/Range.java
extensions/transform/org.eclipse.smarthome.transform.scale/src/main/java/org/eclipse/smarthome/transform/scale/internal/ScaleTransformationService.java

I think for the simple Range logic we can drop the Guava dependency at all.
It needs further tests / review, I just run the existing transform.range.tests and it succeeded.
Will report if I tested it against a previously broken system.
Fixes: openhab/openhab-distro#204

transform.scale: drop usage of Guava

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js

If the minimum / maximim is set to some value that evaluates to false
(e.g. 0, 0.0, ...) then the minimum / maximum text is not shown.
The slider element is shown only if the minimum and maximum text
evaluates to true.
So with the current test no slider is shown if the min / max is e.g. 0,
0.0, ...

fix minimum / maximum text

---

bundles/config/org.eclipse.smarthome.config.xml.test/src/test/groovy/org/eclipse/smarthome/config/xml/test/AbstractAsyncBundleProcessorTest.groovy
bundles/config/org.eclipse.smarthome.config.xml/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/AbstractAsyncBundleProcessor.java
bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingManager.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/BundleProcessor.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

This would be a short-term solution as discussed in #1143. 
Long-term, it would still make sense to have a fast-loading index, e.g. generated at build-time in order to postpone loading of the XMLs until they're needed.
fixes #1143

Deferring ThingHandler.initialize() until all XMLs have been parsed

---

features/karaf-tp/src/main/feature/feature.xml

Related to: https://github.com/maggu2810/osgi-jax-rs-connector/commit/7e35fa0f03b3aad9d7aee6a4c8715c2f07debd69
Realted to: https://github.com/swagger-api/swagger-core/issues/1788
The upstream project bumped the used swagger version from 1.5.5 to 1.5.7:
https://github.com/hstaudacher/osgi-jax-rs-connector/commit/742bf692dc0d6352293bcc698c49b71aa3d6581f
The getScanner function uses the ScannerFactory only if the value is null.
https://github.com/swagger-api/swagger-core/compare/v1.5.5...v1.5.7#diff-55650387ef7908bb46e3b090ee8460b7R232
But SwaggerScannerLocator will create a default scanner if there is no one defined and never returns null.
https://github.com/swagger-api/swagger-core/compare/v1.5.5...v1.5.7#diff-fc757da4002c12bba84c73f26e1be755R29
The previous call to the factory has been …

use modified provider-swagger for JAX-RS

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

If you edit a thing the Paper UI itself allows to edit the label, the
bridge and the configuration.
The JavaScript does not send a changed Bridge UID.

Paper UI: fix broken bridge configuration

---

bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/Sitemap.xtext
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/FrameRenderer.java
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/PageRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/FrameRenderer.java

This partially addresses #635 as it is now possible to simply use a "Default" widget with a Player item, so that the switch buttons are rendered.

introduced "Default" widget type for sitemaps that is dynamically resolved

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

Do not run through initialize method when the ThingType change is initiated.
The handler will anyway be disposed and initialized again after changeThingType() has been executed.
This change will fix an upnp issue which occures when updating the new binding version while there are
Sonos devices paired described here:  #1524

improve ThingType recreation to avoid upnp subscription issue

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css

Toast messages were invisible once the page was scrolled down.

Changed toast position to fixed

---

extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY3.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY5.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/ZonePlayer.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/SonosBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

Hi,
I added the channel for the sleep timer of Sonos.
For me it works fine. Only issue I still have is, that the classic UI (and Android App) does not show the remaining time (basic UI does). Switches works fine in both UIs.
Here the example snippets:
Items:
```
Switch DemoSwitch                          "Switch"
String SleepTimerSwitch                  "SleepTimerSwitch" 
```
Sitemap:
```
Switch item=SleepTimerSwitch mappings=[""="OFF", "00:30:00"="30 min", "01:00:00"="1h"]
Text item=SleepTimerRemain
```
Rule:
```
rule "TestSleepTimer" 
when
Item SleepTimerSwitch received update
then
sendCommand(SleepTimerRemain,SleepTimerSwitch.state.toString())
logInfo("Sonos-SleepTimer", "sleep "+SleepTimerSwitch.state.toString()))
end
```
I use the SleepTimer mainly in rules => for me the problem …

Added SleepTimer Channel

---

bundles/model/org.eclipse.smarthome.model.lazygen/src/main/java/org/eclipse/smarthome/model/lazygen/GlobalResourceSet.java

It indeed seems like @R-Edelhoff's suggestion makes the generation work again. 
I would still like to fully understand why, and we need to cleanup the lazygen stuff, but as it seems this cures the pain for a start.
Also-by: Roland Menznerowski <roland.menznerowski@itemis.de>

Quickfix for #1505

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

Channel edit button was not showing due to a bug introduced during https://github.com/eclipse/smarthome/pull/1288/files#diff-481f5f70afe05170ba047893fcaab2d8R407

Bug fix: channel edit button not showing

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js

While editing an already created module, if user changes the configuration values and press cancel the values are not reset and the updated values are stored if user saves the rule.

Reset module configurations on Cancel

---

docs/documentation/development/bindings/thing-definition.md

Fixed pattern now supports float numbers which matches a **step** definition.
Fixes #1580

Change documentation for thing-type states.

---

extensions/binding/org.eclipse.smarthome.binding.lifx/META-INF/MANIFEST.MF

Lifx binding uses class javax.xml.bind.DatatypeConverter, but does not import javax.xml.bind in manifest xml. This causes issue when running ESH in karaf (using project https://github.com/maggu2810/shk).
Signed-off-by: Satish Nikam <satniks@gmail.com>

Added missing import for javax.xml.bind in manifest file

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

So far, the order of XML processors was relevant. If the last one already fininshed loading
while others did not, the thing got initialized.
This became obvious by occasionally failing
ThingManagerOSGiTest.'ThingManager waits with initialize until bundle processing is finished'
fixes #1419

fixed deferred handler initialization

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js

This needs to be implemented throughout PaperUI.
Fixes https://github.com/eclipse/smarthome/issues/1592.

Redirect only after response on items page

---

extensions/ui/org.eclipse.smarthome.ui.paper/.project

Eclipse Neon analyzes all the JavaScript (etc.) files in this directory
and complains about a lot of errors.
The directory contains third party stuff that is downloaded by NPM
during the build phase.

exclude the node and node_modules directory

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

remove useless isRegistered() check to make sure that the polling interval will be scheduled when initializing the thingHander.

Fix Sonos thing state update issue

---

bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/EventTriggersTypeDefinition.json

The current trigger describe an state change but is using a state update
event. This PR fixes that and adds a new one, so we can use both trigger
types (change and update).

differ between change und update event

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
docs/documentation/development/bindings/thing-handler.md

Removed callback.thingUpdated(…) from BaseThingHandler#updateProperties and #updateProperty
fixes: #588

Thing properties are never persisted 

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

fixes https://github.com/eclipse/smarthome/issues/1699#issuecomment-227219992

Default text field if there is no widget for context

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy

As discussed here: https://github.com/eclipse/smarthome/pull/1704#issuecomment-227425654

increase default timeout for waitFor[Assert]

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GroupItemTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/ChangeThingTypeOSGiTest.groovy

The previous change does not really solve the problem.
`changes` is constructed before the waitForAssert instruction.
So, if events is empty, changes will be empty. Then we wait until events.size is 1... But this will not change the size of the already created `changes`.
The other test fails, so I added a waitFor there, too.

stabilize tests

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java

The problem is if you add a null value to the group item members then you will get a NPE once you invoke the getMembers operation (because of Guavas ImmutableSet.copyOf that throws NPE for null elements)

Added not null checks for GroupItem addMember and removeMember operation

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java

The ISO spec allows 2014-03-30T10:58:47.000Z as a shorthand
for +0000 (UTC). Therefore simply trying to parse ISO
timezones as a fallback.
fixes #1746

fixed parsing yyyy-MM-dd'T'HH:mm:ss.SSSZ times

---

bundles/config/org.eclipse.smarthome.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/service/AbstractWatchServiceTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchQueueReader.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchService.java
bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java

The file path, passed to the AbstractWatchQueueReader.processWatchEvent is now full (till now it was containing only the name of the target file, but not its relative to the watched directory).
Added tests for the AbstractWatchService to verify the behavior above.
**Why do we need the full path**:
When implementing the AbstractWatchService, we can provide an option to track the sub-directories by implementing the AbstractWatchService.watchSubDirectories() method. However, when the sub-directories are tracked, the AbstractWatchService.registerDirectory(Path subDir) will be called for each sub-directory. 
So we have two options - either to implement separate watch service for each of the sub-directories or to have the relative path as an argument when a watch event is detected. With this PR …

WatchService Provides File Name Instead of Relative Path

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/QueueingThreadPoolExecutor.java

reduced logging level as it is an expected behaviour to use the whole pool

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js

Renamed default tab to other and moved it to the right as described here https://github.com/eclipse/smarthome/issues/1083#issuecomment-229022730

Renamed and moved Other tab to the right on control page

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html

Inbox label position change, and 
toggle button hidden when there are no ignored items.
fixes https://github.com/eclipse/smarthome/issues/1807 & https://github.com/eclipse/smarthome/issues/1806

Inbox items label and discover result toggle changed

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/ItemsRuntimeModule.java
bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/PersistenceRuntimeModule.java
bundles/model/org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/RulesRuntimeModule.java
bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/ScriptRuntimeModule.java
bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/SitemapRuntimeModule.java
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/ThingRuntimeModule.java

This fixes an issue that wasn't easily reproducible, but occurred for some users, see also [this exception](https://github.com/eclipse/smarthome/issues/1823#issuecomment-231018514).
I found the workaround/solution for it in [this thread](https://www.eclipse.org/forums/index.php/t/825678/).

fixes IndexOutOfBoundsException in LazyLinkingResource

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/items/RollershutterItemTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/RollershutterItem.java

When setting DecimalType state for a Rollershutter item,
the state should be converted to PercentType.
Otherwise the group functions will present an error
of factor 100.
Fixes #1845
Signed-off-by: Hans Hazelius <hans@hazelius.se>

Set correct percent value for Rollershutter item

---

bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensions.java

* added sumSince (fixes #1843 replaces #376)
* changed averageSince to use BigDecimal instead of double
* changed evolutionRate to use BigDecimal instead of double
* changed deltaSince to use BigDecimal instead of double
* added check in evolutionRate method to avoid divide-by-zero error
* updated all JavaDoc headers to reflect the odd variety of return values and their reasons, in hopes of spurring discussion as to whether and how to tighten and simplify the PersistenceExtensions.
Also-By: Jan N. Klug jan.n.klug@rub.de

added sumSince (fixes #1843 replaces #376)

---

bundles/config/org.eclipse.smarthome.config.core/OSGI-INF/ConfigI18nLocalizationService.xml
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/i18n/ConfigI18nLocalizationService.java
bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/XmlConfigDescriptionProvider.java

This commit adds an OSGi service that contains the I18N logic that has
been previously implemented in the XML config description provider.
Using a service we can share the I18N logic for config descriptions and
reuse it in other config description providers.

OSGi service for I18N Config Description handling

---

bundles/io/org.eclipse.smarthome.io.console.karaf/pom.xml

The framework / product should provide the respective bundle(s) at runtime.

mark API dependencies as provided

---

bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/MDNSClient.java
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/discovery/MDNSDiscoveryService.java
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSClientImpl.java
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSServiceImpl.java

One JmDNS instance is now created for each local IP address.
Loopback and Link-local addresses are ignored.
Only network interfaces that are up at openHAB startup are considered.
This change is important when running openHAB on a machine having one IP
v4 and one IP v6. On such a machine, two things will now work correctly:
- the discovery of IP v4 services
- the publishing of openHAB services on IP v4 and IP v6

Fix mDNS discovery (bug #577 #1745)

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/NormalizerFactory.java

Up to this PR only configuration properties which has number object value were normalized to BigDecimal values. Unfortunately the boolean and string objects were not changed.
Now the automation module uses NormalizerFactory to achieve Normalizer base on its config descripion parameter meta data.

Improve usage of normalizer for configuration properties in Automation module.

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

Player UI actions are now working when applied to a slave member of a group.
Implement exception for missing zone player handler
Fix NPE when no thing is defined for the group coordinator
Change of state is fixed for GroupCoordinatorIsLocal, MuteMaster, LineInConnected and AlarmRunning.
saveAllPlayerState and restoreAllPlayerState are now considering really all Sonos players.
Deprecated calls to updateState have been updated.
Fix: method onValueReceived: add a missing break in the java switch
Fix: method updateSleepTimerDuration: onValueRecived was called with service "DeviceProperties" rather than "AVTransport"
Enhancement: add a warning message if the handler for a zone player is not found (when searching the handler of the group coordinator)
Enhancement: quick refresh of the zone name …

Sonos binding: fix issues #1875 #1900 #1902

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosXMLParser.java

Additionally, this PR improoves binding initialization by avoiding invoking UPnP actions and subscribing services while the UPnP transport service is not yet ready.
Correct/change few log messagess.
Avoid NPE due to entry not set in stateMap.
Use scheduleWithFixedDelay rather than scheduleAtFixedRate
Siged-off-by: Laurent Garnier <lg.hc@free.fr>

Sonos binding: fix issues 1600 1942 1943 1944 1045 1954

---

docs/css/styles.css

Copy of: https://github.com/openhab/openhab-docs/pull/56
------- 
Fixes https://community.openhab.org/t/documenting-openhab-2/10568/84
Sorry for piggybacking :o)
The "bug" behind Link 1 is actually a feature added by the original author of style.css to be able to look at big pictures.
I included the changes suggested by Link 2 to fix that in the right way.
However not as a class, I like this solution better after all.
Outlook: At some point in the future, if one image needs to be half size or with a pink frame, this would be possible by adding a class:

Fix scrollbar bug, add responsive images

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/events/ItemEventFactoryTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java

This fixes a bug in the ItemDTOs - the mapper incorrectly set the type in there by using the item simple class name instead of the item type constants.
CAUTION: As the ItemDTOs are used for serialization of events and in the REST API, this fix can have implications on clients that might wrongly assume that "Item" should be part of the type.
@sbussweiler As far as I can see, you implemented this originally, I hope you agree that this is a bug and not on purpose?
@aounhaider1 Could you please check the implications for the Paper UI?

fixed item types in DTOs to not contain "Item" anymore

---

bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOParticipant.java
bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/discovery/WemoLinkDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoMakerHandler.java

Allows bindings to be notified when a GENA service subscription succeeded or failed.
Wemo binding updated to be compliant with the updated interface.
Sonos binding updated to be compliant with the updated interface and to implement a retry mechanism in case the service subscriptions failed.

Updated interface for UPnP participant (enh #1941)

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryServiceMock.groovy
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryServiceRegistryOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/ExtendedDiscoveryServiceMock.groovy
bundles/config/org.eclipse.smarthome.config.discovery/OSGI-INF/DiscoveryServiceRegistry.xml
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryServiceCallback.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/ExtendedDiscoveryService.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java
docs/documentation/development/bindings/discovery-services.md

With this PR, I would like to get back to  the discussion from #1791. 
The mechanism of injecting the callback is a bit uncommon, but we use it for ThingHandlers as well. I took into consideration the following aspects:
* DiscoveryServices should get access to the "real" objects from the framework, not only to the caches they maintain themselves
* It should not require every DiscoveryService to declare additional service dependencies 
* The level of abstraction should be kept intact and no direct dependencies to the ThingRegistry/PersistentInbox should be introduced
* The API should be extensible, i.e. must not break if we want to introduce further framework access methods in future
fixes #1791 

Provide DiscoveryServices access to existing Results and Thing

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css

fixes https://github.com/eclipse/smarthome/issues/1970

Reduced size of header tags in parameter description

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java

This probably should close #2020 since ThingManager checks that the thing is initialised, so this should be the only place that this isn't caught (at least that I've found).

Don't call handleCommand if thing is not initialised

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/InboxOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java

When DiscoveryResults had been found via a Bridge, and this Bridge
was removed, so far these DiscoveryResults remained in the inbox.
However, as we assume that a Thing having a Bridge actually requires
it in order to communicate successfully, it does not make sense
anymore to keep it in the inbox without the Bridge. There won't be
any useful result when approving it, therefore we easily can clean
them up.

Cleanup discovered children if a Bridge Thing was removed

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java

...as it was accidentally called removeInbox instead of unsetInbox
fixes #2038

fix method name in DiscoveryServiceRegistryImpl

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css

Control UI Icons are not displayed correctly in Safari right now. This pull request fixes that.

Safari controlUI icon bug

---

bundles/automation/org.eclipse.smarthome.automation.module.timer.test/src/test/groovy/org/eclipse/smarthome/automation/module/timer/internal/RuntimeRuleTest.groovy

Fixes: https://github.com/eclipse/smarthome/issues/1757
I don't know if the module timer test is already fixed, but I need to use the Travis CI merge request builder to test it (it seems this CI instance fails a lot of times).

fix module timer test

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

The `Thing` interface declares its channels property as `List<Channel>`, implying that the order of Channels on a Thing is stable. This property is kept by the rest of the code, all of it, except for `ThingResource#create`.
When a `Thing` is created via the REST interface, the `Channel`s specified by the request are collected in a `HashSet`, shuffling them.
This change collects the `Channel`s in an `ArrayList` instead, guaranteeing that the order specified in the request is kept and that `Channel`s aren't randomly shuffled.

When creating Things, keep their Channels in order

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/util/ThingHelperTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java

So far, Things where those fields changed have been considered to
be equal and therefore were not updated in the registry.
fixes #2089

fixed Thing comparison to consider labels and locations

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html

partially fixes https://github.com/eclipse/smarthome/issues/2072. Icons in the header are left for now.

Replaced buttons with clickable icons in rules

---

bundles/automation/org.eclipse.smarthome.automation.module.timer.test/src/test/groovy/org/eclipse/smarthome/automation/module/timer/internal/RuntimeRuleTest.groovy

The test checks for RuleStatusInfo.status so print
RuleStatusInfo.statusDetail is not very informative
Related to: https://github.com/eclipse/smarthome/issues/2057

improve print to identify wrong rule status state

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java

Additionally, implemented a delay before the provider actively creates its items to avoid too many short living item creations.
Fixes #2095

Fixed bug, which resulted in duplicate items in the item registry.

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java

We must not iterate on a `synchronized map` without manually
synchronization statements.
See JavaDoc:
https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedMap(java.util.Map)
```text
It is imperative that the user manually synchronize on the returned map when iterating over any of its collection views:
```
```
Map m = Collections.synchronizedMap(new HashMap());
...
Set s = m.keySet();  // Needn't be in synchronized block
...
synchronized (m) {  // Synchronizing on m, not s!
Iterator i = s.iterator(); // Must be in synchronized block
while (i.hasNext())
foo(i.next());
}
```
```text
Failure to follow this advice may result in non-deterministic behavior.
```
Fixes: https://github.com/eclipse/smarthome/issues/2107

fix CME in ExpressionThreadPoolExecutor

---

bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/DumbThingHandlerFactory.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/DumbThingTypeProvider.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest3.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend

...as soon as they become available. So far, they simply
were replaced, hence losing the data coming from the DSL.
fixes #2042
relates to #365

Merge things loaded from DSLs with info from ThingTypes

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/internal/engine/ScriptImpl.java

- Make sure that only loaded rule resources are used.
- When items are changed, notify the rule engine that all rules are reloaded.

Fixes startup and reload behaviour of DSL rules

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/common/osgi/ResourceBundleClassLoaderGroovyTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/osgi/ResourceBundleClassLoader.java

Fixed fragment properties loading. Prefer first fragment resource before host.
Replace this pull-request: https://github.com/eclipse/smarthome/pull/1986

Fixed fragment properties loading. Prefer first fragment resource before host.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.state.dropdown.html

fixes https://github.com/eclipse/smarthome/issues/2134

Show only values of dropdown on control page

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ItemChannelLinkRegistry.xml
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingRegistry.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/AbstractLinkRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java
bundles/core/org.eclipse.smarthome.core/OSGI-INF/itemregistry.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java

After some modifications of the ItemChannelLinkRegistry yesterday (which
have been never going upstream) I realized that the AbstractRegistry
implementation relies on an active component if provider are added (and
removed).
Using the multiple (0..n) cardinality and policy static the providers
could be added / removed if the component is active but also if the
component is not active.
Regardless if the error is currently thrown this is an error in the
design and should be fixed.
This PR introduce a service tracker to track the providers as long as
the component is active.

add / remove provider logic requires active component

---

bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationTest.groovy

Related to: #2138
I have missed to run the tests. Mea culpa...
The formatter changed most of the stuff only the four changes of UID to uid (because different member names of RuleDTO and Rule) has been done by myself.
A build (with all tests) is currently running on my machine. I will report if it succeeds.

fix failing tests (caused by usage of rule DTO in events)

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

PaperUI was only rendering parameters with item context in the first group. In all other groups item list was empty.

Bug fix: item param in multiple groups

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

Number slider should work when step is not defined in the stateDescription.

Bug fix: number slider without defined step

---

bundles/core/org.eclipse.smarthome.core/ESH-INF/config/locale.xml

The system configuration currently always shows an error, because no default value is set for the locale:
As it is not mandatory for the user to fill out something, this field should not be defined as required.
This PR fixes this.

removed required flag for locale

---

bundles/designer/org.eclipse.smarthome.designer.core/pom.xml
bundles/model/pom.xml
pom.xml

The plugin is currently executed for every artifact.
This consumes build time and wastes the log.

execute xtend-maven-plugin only for necessary artifacts

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

avoid NPE in LIFX handler if no url info is set yet

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusService.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/events/ConfigStatusEventFactory.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/events/ConfigStatusInfoEvent.java

Adapted implementation to be similar to ThingStatus events, which enables a proper toString() implementation (and thus improves event log files).

Improve logging of ConfigStatus events

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js

Item linking events cause script errors when a thing is created in simple mode. This commit fixes that.

Bug fix: initialize linked items array

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

Supports trigger channels as mentioned in https://github.com/eclipse/smarthome/pull/1936#issuecomment-244682201
Also removed function calls from view (for thingTypes) with scope variables.

Support trigger channels

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/ProgressCallbackTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/ESH-INF/i18n/firmware.properties
bundles/core/org.eclipse.smarthome.core.thing/ESH-INF/i18n/firmware_de.properties
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/FirmwareUpdateHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/ProgressCallback.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateProgressInfo.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateResult.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateResultInfo.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateService.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/ProgressCallbackImpl.java

Introducing pending state for firmware updates. Adds ability to cancel started firmware updates. 
Added pending to ProgressCallback and reverted previous changes. This
reduces the impact of the changes regarding pending updates
Introduced cancel method in FirmwareUpdateHandler
Sending FirmwareUpdateProgressInfo events for pending updates.Implemented
cancelFirmwareUpdate in FirmwareUpdateService.java
Added tests

Added ThingStatusDetail FIRMWARE_UPDATE_PENDING

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/Firmware.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateService.java

changed it from isPrerequisteVersion to isPrerequisiteVersion
Signed-off-by: Miki Jankov <miki.jankov87@gmail.com>

typo in Firmware#isPrerequisiteVersion method name

---

bundles/core/org.eclipse.smarthome.core.audio/.classpath
bundles/core/org.eclipse.smarthome.core.audio/build.properties

Without this changes the IDE complains about missing resource directory.
As an empty directory gets lost using Git, we should remove it from the build path

there is no resources directory in core.audio

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

1) Fixes https://github.com/eclipse/smarthome/issues/2235
2) Makes PaperUI run on Edge (without SSE).

JS disabled  & unavailable SSE warning

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

The values of configuration parameters is not shown on thing edit page (it currently shows only defaults). This commit fixes that.

Bug fix: Configuration parameter values in things not shown

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/ProgressCallbackTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/ProgressCallback.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/ProgressCallbackImpl.java

If ProgressCallback.next() is called and update is pending don't go to next firmware step. Resume to current instead

Fix ProgressCallback.next()

---

targetplatform/smarthome.target

Just in case I'm not the only one who sees the following when running plain unit tests within Eclipse:
```
java.lang.ExceptionInInitializerError
at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:61)
[...]
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.3.7 and you are trying to load version 2.3.10
at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510)
[...]
... 28 more
```
If I'm not mistaken, this happens because of the mismatch between the p2 repositories referenced in [smarthome.target](https://github.com/eclipse/smarthome/blob/master/targetplatform/smarthome.target) and …

adapted groovy version

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.linkchannel.html

Bug: While creating an item while linking a channel, the code only checks for existing itemName in the filtered item list of that type (String, Number). So if there is an item of same name in some other type, PaperUI lets user create new item which results in 409 conflict.

Bug fix: item creation while channel linking

---

features/karaf/src/main/feature/feature.xml

I had missed this in https://github.com/eclipse/smarthome/pull/2251.

added Karaf feature for rest.voice

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy

since the framework requires minimum OSGi version 4.2
Generics was added  to ServiceReference in OSGi v.4.3
Signed-off-by: Miki Jankov <miki.jankov87@gmail.com>

removing generics from OSGiTest base class

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/GroupItemStateChangedEvent.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemStateChangedEvent.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemStateEvent.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DecimalType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/IncreaseDecreaseType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/NextPreviousType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/OnOffType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/OpenClosedType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PlayPauseType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/RawType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/RewindFastforwardType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StopMoveType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringListType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/UpDownType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/RefreshType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/Type.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/UnDefType.java

* The full string representation must be compatible to the static `valueOf(String)` method of the respective Type implementation.
* The simple string representation does not need to be compatible to the `valueOf(String)` method of the respective Type implementation.
So, whenever you need a representation that can be consumed by `valueOf(String)` later, you should consider to use the full string representation.
Until now `toString()` returns the full string representation.
To keep backward compatibility this mechanism is unchanged.
The toString() of a type should be implemented this way:
`return TypeToStringTransitionUtils.handleStringTransition(this);`
If you don't set trace log level for `org.eclipse.smarthome.core.internal.types.TypeToStringTransitionUtils` there should not be any …

Type: differ between a full and simple string representation

---

features/karaf/src/main/feature/feature.xml

Adds for I18nProvider service capability as it is missing in the esh.core bundle manifest

add capability to feature because it is missing in the bundle manifest

---

bundles/automation/org.eclipse.smarthome.automation.module.core.test/src/test/groovy/org/eclipse/smarthome/automation/module/core/internal/RuntimeRuleTest.groovy

@plamen-peev This test was introduced by https://github.com/eclipse/smarthome/pull/1914, but it fails. In order to get the build green again, I temporarily deactivate it. Could you please look into it and come up with a fix?

temporarily ignore failing test

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

So far, it was not possible to play notification sounds without manually setting the notification sound volume at least one.
This PR fixes this and sets the notification sound volume to the current volume upon the first use, if not set manually.

Set the notification sound volume on first access instead of initialisation

---

bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioHTTPServer.java
extensions/io/org.eclipse.smarthome.io.webaudio/.classpath
extensions/io/org.eclipse.smarthome.io.webaudio/.project
extensions/io/org.eclipse.smarthome.io.webaudio/META-INF/MANIFEST.MF
extensions/io/org.eclipse.smarthome.io.webaudio/OSGI-INF/sseaudiosink.xml
extensions/io/org.eclipse.smarthome.io.webaudio/OSGI-INF/webaudioeventfactory.xml
extensions/io/org.eclipse.smarthome.io.webaudio/about.html
extensions/io/org.eclipse.smarthome.io.webaudio/build.properties
extensions/io/org.eclipse.smarthome.io.webaudio/pom.xml
extensions/io/org.eclipse.smarthome.io.webaudio/src/main/java/org/eclipse/smarthome/io/webaudio/internal/PlayURLEvent.java
extensions/io/org.eclipse.smarthome.io.webaudio/src/main/java/org/eclipse/smarthome/io/webaudio/internal/SSEAudioSink.java
extensions/io/org.eclipse.smarthome.io.webaudio/src/main/java/org/eclipse/smarthome/io/webaudio/internal/WebAudioEventFactory.java
extensions/io/pom.xml
features/karaf/src/main/feature/feature.xml
features/org.eclipse.smarthome.feature.runtime.core/feature.xml

This is a new audio sink implementation which simply creates an event with a url for the audio stream to be played from. This event can be retrieved by web clients through SSE.
As a first user of this feature, I would like to see the Paper UI as it already subscribes to all SSE events.

initial contribution of a web audio sink

---

bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioFormat.java

Removed unnecessary explicit call of parent constructor (since parent class is the Object class). As stated [here](https://docs.oracle.com/javase/tutorial/java/IandI/super.html), "...if a constructor does not explicitly invoke a superclass constructor, the Java compiler automatically inserts a call to the no-argument constructor of the superclass." In the current case, the class does not extend any other class, which means that the constructor of the parent Object class is implicitly called, making the super() call unnecessary.

Little fix of AudioFormat class

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/SitemapSubscriptionService.java

At line 116 in `SitemapSubscriptionService` the `listener` is removed whereas I think it should remove the `sitemapPage`. The `.remove(..)` works on map keys, which should be the `sitemapPage`. Whereas the `listener` is the value of the map.
See #2322 for reproduction scenario.
Signed-off-by: Wouter Born <eclipse@maindrain.net>

Fixes #2322 Basic UI no longer updates icons

---

bundles/model/org.eclipse.smarthome.model.core.test/.classpath
bundles/model/org.eclipse.smarthome.model.core.test/.project
bundles/model/org.eclipse.smarthome.model.core.test/FolderObserverTestsConfiguration.launch
bundles/model/org.eclipse.smarthome.model.core.test/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.core.test/about.html
bundles/model/org.eclipse.smarthome.model.core.test/build.properties
bundles/model/org.eclipse.smarthome.model.core.test/pom.xml
bundles/model/org.eclipse.smarthome.model.core.test/src/test/groovy/org/eclipse/smarthome/model/core/internal/folder/test/FolderObserverTest.groovy
bundles/model/pom.xml

There are 8 test cases testing the functionality of
org.eclipse.smarthome.model.core.internal.folder.FolderObserver.
They check if the correct ModelRepository's methods are invoked
when certain events in the watched directory are triggered.

Issue #2069 Implemented tests for FolderObserver

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/selection.html
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SelectionRenderer.java

This issue is that `preprocessSnippet` in `SelectionRenderer.java` already substitutes `%value%` so I've changed the name of the substituted value.
Signed-off-by: Wouter Born <eclipse@maindrain.net>

Fixes #2332 Selection sitemap item does not show current selection after Basic UI page (re)load

---

extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/test/GenericWemoLightOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/test/GenericWemoOSGiTest.groovy

`ManagedThingProvider managedThingProvider` was misspelled and said "mangedThingProvider". Successful builds of tests run after change applied.

Fixed mistyped variable for Wemo binding OSGi tests

---

extensions/binding/pom.xml

As this should be only a temporary solution I prefer to remove the whole artifact from the reactor.
Related to: https://github.com/eclipse/smarthome/issues/2345

disable NTP tests until issue is solved

---

bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
docs/documentation/features/dsl.md

in the Thing DSL it is possible to define channels manually.
However, it was not possible so far to reference a binding's
channel type which is defined in the XMLs.

allow referencing a channel type in the DSL

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/HttpServiceUtil.java

Fixes https://github.com/eclipse/smarthome/issues/2372
Note that while this fixes the NPE, the result might not always be the expected behavior as it won't be able to return the port of http services that are registered later (after the call to HttpServiceUtil). If this is not what is expected, my suggestion is that the caller makes sure that the HttpService is already registered at time of the call, e.g. by having a dependency to it.

avoid NPE if no services are found

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

fixes https://github.com/eclipse/smarthome/issues/2378

Added space above channel group name

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/DecimalTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/HSBTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/OnOffTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/OpenClosedTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/PercentTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/UpDownTypeTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/AbstractLinkRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/Item.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ItemUtil.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/internal/StateConverterUtil.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ColorItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ContactItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/DimmerItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/RollershutterItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/SwitchItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DecimalType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/OnOffType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/OpenClosedType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PercentType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/UpDownType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/Convertible.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

This PR is intended to deal with the fact that users might be so creative and link e.g. a SwitchItem to a color channel which maintains a HSBType state. In order to get these items updated successfully whenever values change, the `State` object needs to be converted into something accepted (if possible at all...).
When implementing this, 
- I needed access to the linked items (and not only their names). Therefore I changed the `AbstractLinkRegistry.getLinkedItems()` method to `AbstractLinkRegistry.getLinkedItemNames()` because that is what it actually does and introduced a `ItemChannelLinkRegistry.getLinkedItems()` method with returns what it promises. The alternative would have been to re-add the `ThingManager` -> `ItemRegistry` dependency which I assume we all are happy was dropped.
- I …

Converting state into accepted types

---

bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
docs/documentation/features/dsl.md

...as we discovered in [#2343](https://github.com/eclipse/smarthome/pull/2343#issuecomment-256919779) that this was not possible so far.

Allow to define channel labels in the DSL

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html

Fix: Script field overlaps with output field when focussed.
Before:
After:

Prevent scriptarea from overlapping with outputs

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GenericItemTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java

When the target type is identical to the current state's
type, then the current state should be returned.
fixes #2334

fix GenerericItem.getStateAs for non-Convertibles

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryServiceRegistryOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/InboxOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java

Also extended PersistentInbox#removeOlderResults to remove only the results from the source DiscoveryService
Signed-off-by: Andre Fuechsel andre.fuechsel@telekom.de

Changed PersistentInbox to remove only results created by the same discovery service

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/storage/ManagedItemProviderOSGiTest.groovy

With 1cf093e we can create group items with group functions via the REST API, but the group functions are not currently persisted: ManagedItemProvider.PersistedItem is missing affordances to store group functions and ManagedItemProvider is missing code making use of them.
This change adds a test to ensure that group functions are saved and restored correctly. The test is currently failing but might benefit the future implementer.
Signed-off-by: Martin Kühl martin.kuehl@gmail.com

WIP: Add test to ensure that group functions persist

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/preferences.html

1) Changed width of dropdown.
2) Aligned dropdown text to left.
Before:
After:

Preference page UI changes

---

extensions/binding/org.eclipse.smarthome.binding.ntp.test/src/test/groovy/org/eclipse/smarthome/binding/ntp/test/NtpOSGiTest.groovy

Fixed the bug in the NTP Binding Tests, related to returning a different time zone in different locales: https://github.com/eclipse/smarthome/issues/2376

NTP Binding Tests Localization Fix

---

extensions/binding/org.eclipse.smarthome.binding.ntp.test/src/test/groovy/org/eclipse/smarthome/binding/ntp/test/NtpOSGiTest.groovy

Fixed the bug in the NTP Binding Tests, related to the time change in the US: https://github.com/eclipse/smarthome/issues/2376

NTP Binding Tests Time Change Fix

---

extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/discovery/test/WemoDiscoveryOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/discovery/test/WemoLinkDiscoveryServiceOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/handler/test/WemoHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/handler/test/WemoLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/handler/test/WemoMakerHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/test/GenericWemoLightOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/test/GenericWemoOSGiTest.groovy

Wemo tests now use the default timeout in waitForAssert statements to
prevent test failures on slower machines.
Fixes #2392.

Wemo Tests back to default timeout.

---

bundles/test/org.eclipse.smarthome.test/META-INF/MANIFEST.MF
bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/SyntheticBundleInstaller.java

Added an option in the Synthetic Bundle installer to add only defined set of extensions. Otherwise the default extensions will be used.
Signed-off-by: Dimitar Ivanov dstivanov@gmail.com

Custom Extensions in the Synthetic Bundle Installer

---

docs/css/styles.css

Multiple changes to the style of the page. Tested at docs.openhab.org
- H4 and H5 in parallel to H2/3 http://docs.openhab.org/installation/linux.html#upgrade
- fix violated lists: http://docs.openhab.org/installation/linux.html (TOC)
- visual separator in menu: #71
- visual separator in text: http://docs.openhab.org/administration/console.html (at bottom)
Signed-Off-By: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de (github: ThomDietrich)

[Docs] Improve style.css

---

extensions/ui/org.eclipse.smarthome.ui.paper/about.html
extensions/ui/org.eclipse.smarthome.ui.paper/about_files/EVENTSOURCE_LICENSE
extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/package.json
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

fixes https://github.com/eclipse/smarthome/issues/1657

SSE support for IE 8+ and Edge

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css

Dropdown height fix on systems page

---

bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceConsoleCommandExtension.java

See also https://github.com/eclipse/smarthome/commit/70ff83d03071508839b164aef1f1011de747dd92

adapted label to be identical on console as in the UI

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/ruleengine.xml
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
bundles/model/org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/jvmmodel/RulesItemRefresher.java
bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/internal/actions/TimerImpl.java
bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/jvmmodel/ScriptItemRefresher.java

* delay cron job execution until after startup rules have been processed
* only register the rule engine as a listener on other services in activate(), which avoids concurrent execution of addRule()
* if a job already exists for whatever reason, simply replace it instead of failing with an error
* cleaned some javadoc and logging statements
See issues reported at https://community.openhab.org/t/startup-error-for-all-cron-based-rules/14405

Improvements in startup behavior for cron rules

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemThingLink.java

Fixed a typo inside the Javadoc for ItemThingLink class.

Fixed a typo inside the Javadoc for ItemThingLink class.

---

extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/binding/binding.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/README.md

Fixes https://github.com/eclipse/smarthome/issues/2452

Added documentation for audio sink support in Sonos

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/items/ColorItemTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/DecimalTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/PercentTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ColorItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/ArithmeticGroupFunction.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DecimalType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PercentType.java

It looks like #2471 was caused by the missing conversion from DecimalType to HSBType. It got lost in #2334 because it was very well hidden in the super classes (i.e. PercentType/DimmerItem).
fixes #2471

fix state conversion between HSBType and DecimalType

---

bundles/config/org.eclipse.smarthome.config.dispatch.test/.project

...as our projects usually don't have the maven nature enabled.

removed maven nature from config.dispatch.test project

---

extensions/binding/org.eclipse.smarthome.binding.ntp.test/META-INF/MANIFEST.MF

Fixes: https://github.com/eclipse/smarthome/issues/2506
It fixes the error but I don't know why it is required at all.
The bundle is a fragment for the NTP binding bundle.
The NTP binding bundle is part of the classpath.
The NTP binding bundle has the OSGi compendium API in its classpath.
Perhaps it is a "bug" in the classpath resolution of the Eclipse IDE that we could workaround by manually specify the dependency using the manifest of the test bundle.
If someone could tell me the reason... Do it :wink:

fix indirect class reference

---

bundles/core/org.eclipse.smarthome.core.extension.sample/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.extension.sample/OSGI-INF/sampleextensionservice.xml
bundles/core/org.eclipse.smarthome.core.extension.sample/src/main/java/org/eclipse/smarthome/core/extension/sample/internal/SampleExtensionService.java
bundles/core/org.eclipse.smarthome.core/OSGI-INF/extensioneventfactory.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/extension/ExtensionEvent.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/extension/ExtensionEventFactory.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/extensions/ExtensionResource.java

moved responsibility of sending a success event to the extension service
So far the Extension REST resource itself sent the "installed" events itself, once the extension service returned from the call. This prevented the extension service from doing launching installations asynchronously (and delegating this task).
This is now changed to have the installed events being sent by the extension service itself. Through this, we also have such events if installation is triggered e.g. through the console or other mechanisms than the REST API.

moved extension event classes from rest to core

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHandlerHelper.java

The BaseThingHandler, the ThingManager and the ThingLinkManager contains a method to check if a thing has been initialized.
I moved that logic to a function of the thing itself, so there is only one implementation.
I didn't remove the old (protected) method of the BaseThingHandler but marked it deprecated. So bindings using this method have some time to change their implementation.

add the isInitialized function to the thing itself

---

bundles/config/org.eclipse.smarthome.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java
bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/service/AbstractWatchServiceTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchQueueReader.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchService.java
bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java

See #2341 
-------
Fixes bug introduced by #1597 reverted with #1754.
The implementation of FolderObserver#processWatchEvent() does not get the file name correctly.
This led to duplicated directory names (see the logs in #1597).
AbstractWatchServiceTest is modified to run on different OS.
Signed-off-by: Svilen Valkanov  <svilen.valkanov@musala.com>
svilenvul )

2341-watch-service-relative-path

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/LifxBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightStateChanger.java

The binding will now use the defaults as discussed in #2551 when the current light state is unknown.

Fix #2551 LIFX throws NPE

---

bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AbstractCommandProvider.java
bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/DialogProcessor.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/osgi/ResourceBundleClassLoader.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java
extensions/transform/org.eclipse.smarthome.transform.map.test/src/test/java/org/eclipse/smarthome/transform/map/internal/MapTransformationServiceTest.java
extensions/transform/org.eclipse.smarthome.transform.map/src/main/java/org/eclipse/smarthome/transform/map/internal/MapTransformationService.java
extensions/transform/org.eclipse.smarthome.transform.scale/src/main/java/org/eclipse/smarthome/transform/scale/internal/ScaleTransformationService.java
extensions/voice/org.eclipse.smarthome.voice.mactts.test/META-INF/MANIFEST.MF
extensions/voice/org.eclipse.smarthome.voice.mactts.test/src/test/java/org/eclipse/smarthome/voice/mactts/internal/MacTTSVoiceTest.java
extensions/voice/org.eclipse.smarthome.voice.mactts/META-INF/MANIFEST.MF
extensions/voice/org.eclipse.smarthome.voice.mactts/src/main/java/org/eclipse/smarthome/voice/mactts/internal/MacTTSService.java

I've tried the static code analysis tool (https://github.com/eclipse/smarthome/pull/2440). 
Since my local build failed several times due to some bugs found by the tool, I decided to fix them.
The fixes are mainly related to closing opened streams and comparing Strings with the equals() method instead of the '==' operator.
In addition, I think that the UNUSED_PUBLIC_OR_PROTECTED_FIELD bug should have a lower  priority (it is defined in the rulesets\findbugs directory)

Fixes of some bugs found by the static analysis tool.

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy

...which caused an UnsupportedOperationException.
It is just cosmetical though because it happend during tear down only.

added missing mock method in ThingManagerOSGiTest

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/LightStateConverterOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStateConverter.java

The conversion of brightness values between PercentType (0.100) and
native hue brightness value range (0..254) should be bijective.
E.g. 67 percent should be 67 percent after converting to hue value and
back to percent.
Signed-off-by: Markus Bösling <markus.boesling@telekom.de>

2578 Round values when converting brightness

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java

...as otherwise the Thing will stay in `INITIALIZING` forever as the framework waits for the handler to set it to either `ONLINE` or `OFFLINE`.

[LIFX] give the framework a chance to detect failed initialization

---

bundles/model/org.eclipse.smarthome.model.core.test/.project
bundles/model/org.eclipse.smarthome.model.core.test/.settings/org.eclipse.jdt.groovy.core.prefs

Description: Plugin execution not covered by lifecycle configuration:
org.apache.maven.plugins:maven-compiler-plugin:3.1:compile
(execution: default, phase: compile)
Resource: pom.xml
Path: /org.eclipse.smarthome.model.core.test
Location: line 4
Type: Maven Project Build Lifecycle Mapping Problem

remove error shown in the Eclipse IDE

---

features/karaf-tp/src/main/feature/feature.xml
features/karaf/src/main/feature/feature.xml

There is not need to add the rest.auth bundle to the base feature as we can also run fine without it.

remove rest.auth from base feature

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/.project
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/.settings/org.eclipse.jdt.groovy.core.prefs

This will remove this error shown in the Eclipse IDE:
Description: Plugin execution not covered by lifecycle configuration:
org.apache.maven.plugins:maven-compiler-plugin:3.1:compile
(execution: default, phase: compile)
Resource: pom.xml
Path: /org.eclipse.smarthome.binding.fsinternetradio.test
Location: line 4
Type: Maven Project Build Lifecycle Mapping Problem

remove Maven Nature from fsinternetradio test

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java

Hue Binding: Changed the HashMap containing the lastLightStates into a ConcurrentHashMap to avoid concurrency issues

Hue Binding concurrency issue

---

bundles/io/org.eclipse.smarthome.io.rest.log/.classpath
bundles/io/org.eclipse.smarthome.io.rest.log/.project
bundles/io/org.eclipse.smarthome.io.rest.log/.settings/org.eclipse.jdt.core.prefs
bundles/io/org.eclipse.smarthome.io.rest.log/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.rest.log/OSGI-INF/loghandler.xml
bundles/io/org.eclipse.smarthome.io.rest.log/README.md
bundles/io/org.eclipse.smarthome.io.rest.log/about.html
bundles/io/org.eclipse.smarthome.io.rest.log/build.properties
bundles/io/org.eclipse.smarthome.io.rest.log/pom.xml
bundles/io/org.eclipse.smarthome.io.rest.log/src/main/java/org/eclipse/smarthome/io/rest/log/LogConstants.java
bundles/io/org.eclipse.smarthome.io.rest.log/src/main/java/org/eclipse/smarthome/io/rest/log/internal/LogHandler.java
bundles/io/pom.xml
features/org.eclipse.smarthome.feature.runtime.rest/feature.xml

As announced at [Eclipse Forum](https://www.eclipse.org/forums/index.php?t=msg&th=1072176&goto=1714706&#msg_1714706), I've implemented a UI-Log receiver.
I added a README which is normal Markdown but also a valid [API Blueprint](https://apiblueprint.org/) document, which can be used in e.g. [Apiary](https://apiary.io).
The PR for PaperUI will come later on.
Signed-off-by: Sebastian Janzen sebastian.janzen@innoq.com

Frontend log bundle

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/README.md
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/LifxBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCurrentStateUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightState.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightStateChanger.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxUtils.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/listener/LifxLightStateListener.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetLightInfraredRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/PacketFactory.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/Products.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/SetLightInfraredRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/StateLightInfraredResponse.java

Adds support for the following LIFX products:
* LIFX A19
* LIFX BR30
* LIFX+ A19
* LIFX+ BR30
* LIFX Z
Furthermore a `colorirlight` thing type has been introduced for the LIFX+ products. These things have an additional infrared channel. I've been testing with the new LIFX Z and LIFX+ A19 myself.

[LIFX] Support 2016 product line-up and infrared functionality

---

extensions/binding/org.eclipse.smarthome.binding.lifx/README.md

Adds two examples for using the `powerOnBrightness` channel configuration parameter in `.things` files.

[LIFX] Add powerOnBrightness examples to README.md

---

bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/HTTP.java

It seems that the intent was to print a string message of the exception, but since the last argument is the exception its stack trace is being dumped instead.
Noticed on the forum [here](https://community.openhab.org/t/http-binding-can-the-logging-be-tamed/2764/5?u=watou).

Correct ERROR log messages in HTTP action

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/LifxBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightOnlineStateUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxNetworkThrottler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/Packet.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/PowerState.java

The LIFX binding uses the words *light* and *bulb* interchangeably. Now that the binding also supports LED strips (LIFX Z), the word *bulb* is sometimes unsuitable. This PR replaces occurrences of *bulb* with the more generic *light*.

[LIFX] Refer to bulbs as lights

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

fixes https://github.com/eclipse/smarthome/issues/2637

Itemname empty string check while converting to camelcase

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingManager.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java
docs/documentation/development/bindings/thing-handler.md

So far, changes were allowed only to Things coming from
the ManagedThingProvider. With this change it is now allowed
to change all Things structurally, no matter where they are
from. They will simply not be persisted if its provider is not
managed.
fixes #1977

Allow changing of unmanaged Things

---

bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java

in order to avoid flooding the logs with "Invoking Action [...]" messages.
They are pretty much spamming the logs with messages like this, e.g. when using sonos:
```
Invoking Action 'GetRunningAlarmProperties' of service 'AVTransport' for participant 'RINCON_[...]'
```
Unless anybody has a good reason to keep them on DEBUG level, I would suggest to reduce them to TRACE, so if we need them we can specifically enable them.

reduce severity in io.upnp

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/binding/binding.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCurrentStateUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightState.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/AcknowledgementResponse.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/EchoRequestResponse.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetLabelRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetPowerRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetServiceRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetTagLabelsRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetTagsRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetWifiInfoRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/PowerState.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/SetLabelRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/SetLightPowerRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/SetPowerRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/StateResponse.java

* "Power on brightness" was not properly applied when switching ON/OFF White lights. There actually is no difference between switching ON/OFF Color and White lights.
* When switching ON/OFF a light, the brightness should not be changed with `handleHSBCommand` because it always switches a light ON when it is already OFF. I.e. a light that is OFF, and switched OFF again, could go ON and immediately OFF again.
* Power state polling of lights did not work properly. A `GetLightPowerRequest` was sent which results in a `StateLightPowerResponse` and not the `StatePowerResponse` that was used for updating the `PowerState`. Because the power state is also part of the `StateResponse` it is unnecessary to poll for it with a second packet.
* Because power state polling now works properly, issues in …

[LIFX] Power state bug fixes and code cleanup

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

According to https://github.com/openhab/openhab2-addons/issues/1563#issuecomment-267292201, these logs are annoying, but not dangerous, so we should not warn the user about anything.

reduced log level to debug

---

bundles/model/org.eclipse.smarthome.model.persistence.tests/src/test/java/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensionsTest.java
bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensions.java

Average since is calculated over persisted values AND the actual value.
The description describes that it is calculated over persisted values OR
the actual value (if no persisted values are found). The description is
desribes the correct behaviour, while the implementation was wrong. This
is fixed with this PR.
Bug: https://github.com/eclipse/smarthome/issues/2404

Fix averageSince calculation

---

bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/RuleEngineTest.java
bundles/automation/org.eclipse.smarthome.automation.core/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

Remove double normalization of module's configuration data.
Add normalization of rule's configuration data (It is available when rule is added by template.)

Fixes #2602. Refactor normalization of rule.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js

fixes https://github.com/eclipse/smarthome/issues/2673

Bug fix: wrong item removal dialog template name

---

bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/PropertiesTypeAdapter.java

As discussed in #2665 Gson doesn't provide access to the raw data - in the TypeAdapter class, the string value that is available has already been altered from what is in the file - so a value in the file of 50 is already 50.0. Therefore there is no way to reliably resolve a BigDecimal with scale 1, and a BigDecimal with scale 0.
This currently appears to be the best compromise.

Json storage BigDecimal scaling

---

targetplatform/smarthome.target

Replaced the unit-api 0.8 and unit-ri 0.8 bundles by unit-api 1.0 and uom-se 1.0.2 by https://github.com/eclipse/smarthome/commit/9f23b63a16fbd10ac86ab87acf39859617a09882.
This PR updates the smarthome.target to use the unit-api 1.0 now.
Unfortunately, we cannot yet add uom-se to the tp, since it has a dependency on javax.annotation 1.3.0, which is not available on Orbit. I guess we will need another CQ for it.

updated unit-api on target platform

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/persistence/PersistenceResource.java

use endtime for last datapoint in boundary query

---

bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/LocaleUtil.java

The content of the Accept-Language HTTP header variants may contain
comma-separated values. In this case the created Locale was not valid.
Now only the first parameter passed in the header is used.
Signed-off-by: Martin Herbst <mail@mherbst.de>

#2589 Support of different Accept-Language HTTP header variants

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css

fixes https://github.com/eclipse/smarthome/issues/2736

Set min width/height of text control

---

bundles/model/org.eclipse.smarthome.model.thing.tests/OSGI-INF/HueConfigDescriptionProvider.xml
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueConfigDescriptionProvider.groovy
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest.groovy
bundles/model/org.eclipse.smarthome.model.thing/OSGI-INF/genericthingprovider.xml
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend

So far, user-defined channels referencing an existing ChannelType did not
have the default configuration values set which were defined in the XML.
Now they do.

apply default configuration to channels in GenericThingProvider

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxNetworkThrottler.java

This PR adds light label discovery functionality based on the label used in the LIFX App. 
This improves the discovery user experience when working with a lot of lights.
Also the discovery process was further improved. Discovery now:
* only sends requests for missing light data
* waits 200ms before resending requests because it takes time for a response to arrive
* locks on one light only (and not all lights) when sending a packet to a specific light
With the above improvements I've seen the number of sent packets per `networkRunnable.run()` drop significantly. In my setup the number of sent packets per run has dropped by ~99% (from ~12538 to just ~177 packets, including the new label request packets).
Also the code has been reworked:
* it should be easier to add code for discovering …

[LIFX] Discover light labels, improve locking, optimize packet handling

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

issue #2371
Comment: The problem seems to be that label.indexOf is evaluated before label.trim() has been executed. In case of an empty label a space might occur before the opening square bracket. That is trimmed, but the index is 1 where it should be 0. This has been fixed by moving the .trim() to a seperate statement.

fix transformation in empty label

---

features/karaf/esh-core/src/main/feature/feature.xml

... they were left in here by mistake during the previous refactoring.

removed bindings from core feature

---

bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueChannelTypeProvider.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueConfigDescriptionProvider.groovy
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueThingHandlerFactory.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueThingTypeProvider.java
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext

...as so far such channels could not be referenced in the DSL
('#' was not allowed as part of the channel id)
fixes openhab/openhab2-addons#1264

allow overriding of channel configurations within channel groups

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/handler/ActionHandler.java

The current JavaDoc states, that a map of values should be returned.
The current implementations of that interfaces use null as a return
value, too.
Also the rule engine checks the return value and checks for null.
I personally prefer to state that the function must not return a null
value and should return an empty map instead of adding a null check in
the handling of the return value.
But if we don't want to break third party action implementations we
should at least state, that null is an allowed return value.

state that null is an allowed return value

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryServiceRegistryOSGITest.groovy
bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/ExtendedDiscoveryServiceMock.groovy
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java

When particular DiscoveryService is changed (eg. there are new properties added to the discovery results) the already discovered things are not been updated.
This is due to the cache used in DiscoveryServiceRegistryImpl:
`private HashMultimap<DiscoveryService, DiscoveryResult> cachedResults = HashMultimap.create();`
Javadoc of `HashMultimap` says: 
`Adding a new key-value pair equal to an existing key-value pair has no effect.`
Possible solution is - each time an entry is put to the map - already existing entry to be first removed from the map

DiscoveryResults not updated on DiscoveryService change

---

bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/SendConsoleCommandExtension.java

...in the "send" console command in case the given
command cannot be parsed successfully.
So instead of
```
Error: Command 'hallo' is not valid for item 'my_switch'
Valid command types are: ( OnOffType  RefreshType )
```
it would now print 
```
Error: Command 'hallo' is not valid for item 'my_switch'
Valid command types are:  
OnOffType: ON OFF 
RefreshType: REFRESH 
```
However, with this change non-enum types would continue showing as their type only, leaving it to the creativity of the users to figure out what e.g. a valid String or Decimal would be. But I assume that's not so much of a big deal.
fixes #2787

print possible values for enums

---

distribution/smarthome/conf/items/demo.items
distribution/smarthome/conf/persistence/logging.persist
distribution/smarthome/conf/rules/demo.rules
distribution/smarthome/conf/sitemaps/demo.sitemap
distribution/smarthome/conf/things/demo.things

They were removed with commit https://github.com/eclipse/smarthome/commit/d566b72aedd8822229b4d3f4bc5f21673b3b1f7b, which I assume was by accident, @maggu2810?

re-added demo files

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css

Multiselect widget width issue inside md-dialog

---

bundles/core/org.eclipse.smarthome.core.thing/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/Firmware.java

...in Firmware because they are equivalent and that's the only
usage of that Guava package (com.google.common.io).

replace Guava's ByteStreams with Apache Commons' IOUtils

---

features/org.eclipse.smarthome.feature.dependencies.designer/feature.xml
features/org.eclipse.smarthome.feature.designer/feature.xml

I just had a look at what's missing in order to let the designer start again without bundle resolution errors. This is what it took...
While some obvious bundles were missing, it certainly feels odd to add "half the internet". I can't believe that much had been missing. So if someone more designer-savvy could have a quick look this would be great.
Of course, as we are not separating api and runtime clearly, we draw lots of stuff in that would not be needed just to reference stuff within the DSLs, but that's another story and should not be addressed here. I'd rather like to focus on merely getting it running again as it is.
fixes #2813 

add missing dependencies to designer

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchQueueReader.java
bundles/model/org.eclipse.smarthome.model.core.test/src/test/groovy/org/eclipse/smarthome/model/core/internal/folder/test/FolderObserverTest.groovy
bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java

FolderObserver to be more robust wrt exceptions thrown
...as so far the endless loop got broken is the model could not get parsed correctly.
fixes #2827 

Observer stability

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js

fixes https://github.com/eclipse/smarthome/issues/2828

Set category to null if input is empty

---

.gitignore
bundles/config/org.eclipse.smarthome.config.dispatch.test/.settings/org.eclipse.jdt.groovy.core.prefs

* `bundles/storage/org.eclipse.smarthome.storage.json.test/userdata/` is created on build process
* `distribution/smarthome/userdata/` is created if you use the SmartHome launch configuration of the Eclipse IDE
* the `org.eclipse.smarthome.config.dispatch.test/.settings` directory is created while using the Eclipse IDE

git status: cleanup

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

This PR adds a toString method to the configuration to get a more readable representation of the internal state.
Imaging the following code:
```java
final Configuration config = new Configuration();
config.put("key1", Integer.valueOf(42));
config.put("key2", BigDecimal.valueOf(42));
config.put("key3", String.valueOf(42));
System.out.println(config);
```
Without this change the output will be similar to:
```text
org.eclipse.smarthome.config.core.Configuration@968207
```
After this change has been done the output will be:
```text
Configuration[{key=key1; type=Integer; value=42}, {key=key2; type=BigDecimal; value=42}, {key=key3; type=String; value=42}]
```

add a toString method to the configuration

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/ItemRegistryOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java

...as on item updates, the updated item did not get the event publisher
injected.
At the same time, I also fixed the cleanup of these references on
update (old item) and removal.
The initialize() (empty implementation) and dispose() (never called)
methods in GenericItem seem to be historic garbage. As far as I can
see they are completely useless (if called at all) and nowhere overridden.
Since they are not part if the Item interface, I simply removed them.
fixes #2846

fix service injection into GenericItem

---

bundles/automation/org.eclipse.smarthome.automation.module.script.test/ESH-INF/automation/rules/DemoScriptRule.json
bundles/automation/org.eclipse.smarthome.automation.module.script.test/src/main/groovy/org/eclipse/smarthome/automation/module/script/ScriptRuleTest.groovy
bundles/automation/org.eclipse.smarthome.automation.module.script/ESH-INF/automation/moduletypes/ScriptTypes.json
bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/handler/AbstractScriptModuleHandler.java

outputs are now available with their unprefixed id. As this can be a problem if there are multiple modules with the same output ids, the full rule context is additionally made available. This makes the following options available:
```
print(newState)
print(context.get('1.newState'))
```
fixes #2849

make outputs available to scripts and provide access to the full context

---

bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemCommandTriggerHandler.java
bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemStateTriggerHandler.java

If there are two items: itemName and itemNameExtended, the wrong trigger can be triggered.
If one adds a rule with a trigger to "itemName" and the state of itemNameExtended changes, the trigger to "itemName" will be triggered. The following PR fixes that.

fix triggers for itemName vs. itemNameExtended

---

bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingTypeI18nLocalizationService.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java
features/karaf/esh-core/src/main/feature/feature.xml

With this change the code that localize a thing type using the i18n stuff is moved from the XML implementation to a separate service so it could be reused by other code, too.

add a service to allow reuse of localized thing type creation

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/handler/BaseModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/CoreModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.module.timer/src/main/java/org/eclipse/smarthome/automation/module/timer/factory/TimerModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/handler/SampleHandlerFactory.java

...as I noticed some differences in the implemenations of internalCreate().
* some factories  where first trying to access the cache, some didn't
* some factories were writing to the cache, some didn't
Therefore I moved the cache access completely to the abstract base class,
allowing derived classes only to access it for read-only purposes.
By doing that, the cache is managed completely within the abstract
base class and this concern does not leak.

fixed inconsistent caching behavior in rule module handler factories

---

bundles/automation/org.eclipse.smarthome.automation.module.timer.test/src/test/groovy/org/eclipse/smarthome/automation/module/timer/internal/DayOfWeekConditionHandlerTest.groovy
bundles/automation/org.eclipse.smarthome.automation.module.timer.test/src/test/groovy/org/eclipse/smarthome/automation/module/timer/internal/TimeOfDayTriggerHandlerTest.groovy

...as for preparation of the configuration parameters a different locale
will create different output for the days (e.g. FR instead of FRI with
german locale).

fixed DayOfWeekConditionHandlerTest when running on non-english systems

---

bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/URLAudioStream.java

This fixes #2913 by changing the container on the MP3 AudioFormat created by URLAudioStream to "NONE".
Bug: https://github.com/eclipse/smarthome/issues/2913
Signed-off-by: Gregory Moyer <moyerg@syphr.com>

Use CONTAINER_NONE in MP3 AudioFormat in URLAudioStream

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ChannelTypeDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/channel/ChannelTypeResource.java

fixes https://github.com/eclipse/smarthome/issues/2911

Added missing advanced field in channelTypeDTO

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/extension/ExtensionService.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/extension/ExtensionType.java
bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/extensionresource.xml
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/extensions/ExtensionResource.java

...so that the REST resources consult all of them.
* ExtensionTypes are sorted alphabetically by their label
* The list of returned Extensions is stable but not sorted
* assumption: ExtensionTypes have a unique semantic (i.e. two ExtensionServices may
provide ExtensionTypes with the same ID, but have to implicitly "agree" that they
also have an identical meaning). Prefixing helps preventing undesired clashes.
* assumption: The list of extensions provided by each service is cheap to calculate,
i.e. caching is implemented by the services if needed
* assumption: If two ExtensionServices provide Extensions with an identical ID, then
it is also the same Extension and it does not matter which ExtensionService is used
for installing/uninstalling the extension. Prefixing helps.
All of the above …

allow multiple ExtensionService implementations

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Fixes https://github.com/eclipse/smarthome/issues/2911

Bug fix channelTypes: use advanced value as returned from rest

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

fixes https://github.com/eclipse/smarthome/issues/2940

Align state text to right on control page

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java

...for semantic checks:
* removed blank
* removed trailing newline
* reduced severity to "info"

improve logging of validation "errors"

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java

* There has been a lot of explicit toString() method calls that should not be done
* At some places the number of placeholders does not fit to the number of provided arguments

fix logging statements

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Fixes a bug introduced by https://github.com/eclipse/smarthome/pull/2949

Bug fix: use channel type UID for comparison in channelGroups

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js

Fixes broken modules drag-drop feature and error below:

Fixed jquery-ui ‘define’ error

---

bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioFormat.java

Since AudioFormat implements equals(), it needs to implement hasCode() as well. It is used e.g. in SonosAudioSink in a HashMap. 

AudioFormat need to implement hashCode 

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/SafeMethodCaller.java

..as so far it could happen that a ThingHandler call through the SafeMethodCaller
timed out because it was still queued, so the Handler is not to "blame".
Now the SafeMethodCall returns silently in such a case, not re-throwing the TimeoutException anymore.
relates to #2986

Stop blaming handlers for being queued

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/common/SafeMethodCallerTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/SafeMethodCaller.java

...by checking if the current thread already is running
in a SafeMethodCaller context.
relates to #2986

prevent wrapping of safe method calls

---

bundles/automation/org.eclipse.smarthome.automation.module.script.test/.settings/org.eclipse.jdt.groovy.core.prefs
extensions/binding/org.eclipse.smarthome.binding.wemo.test/.settings/org.eclipse.jdt.groovy.core.prefs

Fixes: https://github.com/eclipse/smarthome/issues/3011

set the Groovy compiler level for project to match the workspace level

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

I was unable to reproduce the exact issue https://github.com/eclipse/smarthome/issues/3000. But this makes sure that thing is up to date on thing config page.
fixes https://github.com/eclipse/smarthome/issues/3000

Refresh thing from remote

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

Now the message is clear and correct.
The problem was in the evaluation of the expression:
`"Invalid module uid: " + mId != null ? mId
: "null" + ". It must not be null or not fit to the pattern: [A-Za-z0-9_-]*"`

Fix for the unclear error message when the module id does not match the regular expression (#3023)

---

bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptModuleActivator.java

Reference: https://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html#getParent()
Returns the parent class loader for delegation. Some implementations may use null to represent the bootstrap class loader. This method will return null in such implementations if this class loader's parent is the bootstrap class loader.

prevent NPE on check for extension classloader

---

bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/CoreModuleHandlerFactory.java

I just tried a rule with an item state condition and came across
```
17:15:37.395 [ERROR] [re.handler.ItemStateConditionHandler] - The ItemRegistry is not available to evaluate the condition.
```
This PR fixes this (the relevant change is only in l. 167-169).

correctly set itemRegistry in returned handler

---

bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AbstractFileProvider.java

fixes #2854
#2855 didn't work in cases where a file was part of a subdirectory (since getName also returns the folders).

correctly handle hidden files

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java

A 404 warning is logged every time the session is expired but the binding still thinks the session is still valid. Fixed by logging warning only if re-login failed.
Related issue: https://github.com/eclipse/smarthome/issues/2548

[Issue-2548] Remove warning on expired session.

---

bundles/io/org.eclipse.smarthome.io.transport.dbus/.classpath
bundles/io/org.eclipse.smarthome.io.transport.dbus/META-INF/MANIFEST.MF

The content of 'lib/unix-0.5.jar' and 'lib/libdbus-java-2.7.jar' is already added to the bundle classpath and packages are already exported by OSGi.
The Eclipse IDE classpath settings does not mark that stuff of that files is exported. So access to e.g. org.freedesktop.dbus is not available in the Eclipse IDE.

DBus bundle: allow usage of exported libraries in Eclipse IDE

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy

If we get a service class by filter on a specific implementation class an instance of the implementation class (so the more specified) should be returned.
This is what is currently done and used.
It seems Groovy ignores the types and does not warn / error if you assign the returned serice class to an instance of the implementation class.
If you use the Java compiler it errors as expected.

OSGi test: return implementation class

---

bundles/automation/org.eclipse.smarthome.automation.parser.gson/.project
bundles/automation/org.eclipse.smarthome.automation.parser.gson/OSGI-INF/ModuleTypeGSONParser.xml
bundles/automation/org.eclipse.smarthome.automation.parser.gson/OSGI-INF/RuleGSONParser.xml
bundles/automation/org.eclipse.smarthome.automation.parser.gson/OSGI-INF/TemplateGSONParser.xml

According to the [parser JavaDoc](https://github.com/eclipse/smarthome/blob/master/bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/parser/Parser.java#L38-L42) this property should be provided in DS.

correctly specify the parser format as DS properties

---

bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/ItemTriggers.json
bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemCommandTriggerHandler.java
bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemStateTriggerHandler.java

This PR allows an action to access the underlying event in a more generic way. All triggers expose the same name: event. This can be especially useful in scripted actions.

State/Command Trigger expose event

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/link/LinkEventOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java

Fixes: https://github.com/eclipse/smarthome/issues/2357

remove wrong deprecation and ItemThingLinkRegistry references

---

extensions/transform/org.eclipse.smarthome.transform.exec/README.md
extensions/transform/org.eclipse.smarthome.transform.javascript/README.md
extensions/transform/org.eclipse.smarthome.transform.jsonpath/README.md
extensions/transform/org.eclipse.smarthome.transform.map/README.md
extensions/transform/org.eclipse.smarthome.transform.regex/README.md
extensions/transform/org.eclipse.smarthome.transform.scale/README.md
extensions/transform/org.eclipse.smarthome.transform.xpath/README.md
extensions/transform/org.eclipse.smarthome.transform.xslt/README.md

The content comes from either my original work, the source code, or [the old wiki](https://github.com/openhab/openhab1-addons/wiki) where earlier versions of the transformations resided (at commit ecae0ce585a08b3a0342fbb9a59154360c71afc2.

Add README.md files to transformations

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

fixes issue reported here: https://github.com/eclipse/smarthome/issues/3051#issuecomment-283314125

Show channel description on long press

---

extensions/binding/org.eclipse.smarthome.binding.lifx/README.md

according to @kaikreuzer, the items Switch and Dimmer are not recommended.
https://github.com/eclipse/smarthome/issues/3014#issuecomment-279943751
Signed-off-by: Christoph Wempe <cw-git@wempe.net> (github: CWempe)

removed not recommended items in lifx README

---

bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/URLAudioStream.java
bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioManagerImpl.java

I have written tests about the `org.eclipse.smarthome.core.audio` bundle: https://github.com/eclipse/smarthome/pull/2687. I have found the following problems:
1. `createInputStream()` in URLAudioStream does not reuse an already opened connection, but opens a new one:
`openStream()` method calls `openConnection().getInputStream()`, which opens an entirely new connection and does not reuse the old one. Also, `openStream()` initiates HTTP GET request: http://stackoverflow.com/questions/2778312/how-does-java-url-openstream-work. For example, this may cause a problem when we use `oneTimeStreams` in the `AudioServlet`, because `oneTimeStreams` can be requested only a single time.
This problem can be solved, if we use `getInputStream()` method on the currently opened connection.
2. …

Changes in org.eclipse.smarthome.core.audio

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DecimalType.java

According to javadoc:
Note: This is generally the preferred way to convert a double (or float) into a BigDecimal, as the value returned is equal to that resulting from constructing a BigDecimal from the result of using Double.toString(double).

Use the preferred way of creating BigDecimal from Double

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/BundleProcessorVetoManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
bundles/model/org.eclipse.smarthome.model.thing.tests/org.eclipse.smarthome.model.thing.tests.launch.launch
bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest4.groovy
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend

as we have seen in #2945 and #3015, there can be situations when a thing
is left in INITIALIZING state although the binding updated its state
correctly.
The root cause was a race condition between ThingManager and GenericThingProvider.
While the ThingManager was trying to initialize the Thing, the GenericThingProvider
tried to update the the existing thing (which already had a ThingHandler). As a
result, the existing ThingHandler updated the outdated thing, not knowing that
there actually was an update.
The key for fixing this was changing the point in time when a handler is created.
This will now also be postponed until the binding is fully loaded. Additionally,
bindings have to deal with thing updates while the thing still is in INITIALIZING
state. On the other hand, it is now …

fix race condition which could leave a thing in INITIALIZING

---

bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemStateTriggerHandler.java

This fixes a bug as the state change trigger didn't yet work for group items.

Also consider group state changed events

---

bundles/config/org.eclipse.smarthome.config.core.test/ConfigCoreTests.launch
bundles/core/org.eclipse.smarthome.core.test/CoreTests.launch
bundles/core/org.eclipse.smarthome.core.thing.test/org.eclipse.smarthome.core.thing.test.launch
bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ChannelStateDescriptionProvider.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProvider.java
bundles/core/org.eclipse.smarthome.core/OSGI-INF/itemregistry.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionProvider.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

As it turned out there is the following "circle":
StateDescriptionProvider
-> ItemChannelLinkRegistry
-> ItemRegistry
The ItemRegistryImpl opens a ServiceTracker to StateDescriptionProvider on activate().
As this last reference is not managed by DS it is not handled gracefully.
Therefore with this change I added dynamic service references into the ItemRegistry via DS.
As a side-effect I also introduced a callback interface for the items, so that the
actual service instances don't need to be injected into the items anymore, but the items
can get the most recent list via the StateDescriptionProviderAccessor interface.
fixes #3150

Fix circular service reference

---

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/__bindingIdCamelCase__BindingConstants.java

The template file does not use recommended order for the modifiers and creates an incorrect link in the docblock, which can be seen in most bindings :-(
http://stackoverflow.com/questions/16731240/what-is-a-reasonable-order-of-java-modifiers-abstract-final-public-static-e
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl> (github: martinvw)

Update the template for the BindingConstants file

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
docs/documentation/concepts/things.md
docs/documentation/development/bindings/thing-handler.md

...and making the documentation more explicit about this.
So far, bindings simply could set things to REMOVED at any time so they got
dropped from the database. Now it is ensured they can only do so after the
framework set it to REMOVING, i.e. they only are allowed to indicate that
the handleRemove() is finished, but cannot trigger the process anymore.
fixes #3199

prevent bindings from removing things

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.thingproperties.html

The primary change here is to split the thing properties table into a separate partial so that it can be overridden in a fragment. I've also modified the styling of the properties slightly as I personally think it looks a bit better, but if y'all disagree I can always change it back.

Refactor thing properties display in PaperUI

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/channel/ChannelTypeResource.java

...as so far convertToChannelTypeDTOs() used a set with no obvious reason,
hence srambling them up.
fixes #3220

retain order of channels in ChannelTypeResource

---

features/karaf/esh-tp/src/main/feature/feature.xml

Eclipse Neon.2 is on Maven Central
https://objectteams.wordpress.com/2017/01/09/eclipse-neon-2-is-on-maven-central/

use official Eclipse artifacts

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js

This is a small change to the title of thing configuration pages in the UI. I suspect this is a hangover from the time when things had items linked to them, and the items gave the thing label. For things with no items, the UID is displayed in the title and it's out of place (IMHO ;) ).
From the code, I believe it wants to display the thing.label, but it only does this if item is not null - as item is now null, it displays the UID instead. This simply corrects this, and also makes the breadcrumbs consistent.
**The current implementation...**
------------
------------
**The proposed implementation...**

Show thing label instead of thing UID in title

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

The behavior so far was not consistent, as correctly
pointed out in #3261. Now it throws IAEs also when UNKNOWN
is set after ONLINE/OFFLINE or REMOVING is not concluded
directly with a REMOVED status.
fixes #3261

fail loudly on illegal status transitions

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/groovy/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerOSGiTest.groovy

See: https://github.com/eclipse/smarthome/issues/3223
The code logic in the volume tests is simplified resulting in some new test cases.
Two of the methods are synchronized on the channel uid. That was neccessary because of some thread issues leading to inconsistent behaviour of the tests.

Fix unstable FSInternerRadioHandler tests

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

...as MessageFormat needs the indices.
In https://github.com/eclipse/smarthome/pull/3205#pullrequestreview-31052041 we both missed the point that we are talking about MessageFormat and not Logger.
relates to #3205

fix exception messages in ThingManager

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

Since ModelGroupFunction is defined as enum in xtext there will always be a function assigned to the group, to check if there is no function we can now use the new element NONE
Fixes #3161

Introduce function NONE for item groups

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java

Fixes #3192 Well maybe not a real fix, but all we can do about it. We omit the stacktrace and just print a warning instead of an error.

Print warning instead of error if config file could not be read

---

extensions/binding/org.eclipse.smarthome.binding.ntp.test/src/test/java/org/eclipse/smarthome/binding/ntp/test/NtpOSGiTest.java

...during test execution.
relates to #3231, #3280

Giving the NtpHandler a little more time to initialize

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy
bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java

...as so far the timout was the aggregated sleep time, which
led to quite long-running tests in case of nested waitForAssert
blocks.

changing waitForAssert to an absolute timeout

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java

I want to fix the generic type usage to remove the warning.
As I fixed it, I wondered, why the normalization of the collection entry itself uses a custom implementation and does not call the already existing normalization function.
Shouldn't we reuse the existing code, so there are not different places that process the normalization?

small fixes normalization in ConfigUtils

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/EnrichedThingDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java

This adds a 'managed' flag to the enrichedThingDTO. This allows UIs to know if a thing is managed or not, and provide an appropriate UI.
Currently, users are left to guess what responses might mean when they try and send updates to the system for unmanaged things, and to me at least, it makes more sense for the UI to be able to present an appropriate interface.

Add 'editable' flag to enrichedThingDto

---

bundles/config/org.eclipse.smarthome.config.dispatch.test/src/test/groovy/org/eclipse/smarthome/config/dispatch/test/ConfigDispatchTest.groovy
bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy
bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java

Usually waitForAssert is the magic healing potion for tests.
But ocasionally less is more.

Fix config dispatch test

---

tools/archetype/binding/src/main/resources/META-INF/maven/archetype-metadata.xml
tools/archetype/binding/src/main/resources/archetype-resources/ESH-INF/binding/binding.xml
tools/archetype/binding/src/main/resources/archetype-resources/ESH-INF/i18n/__bindingId___xx_XX.properties
tools/archetype/binding/src/main/resources/archetype-resources/ESH-INF/thing/thing-types.xml
tools/archetype/binding/src/main/resources/archetype-resources/OSGI-INF/__bindingIdCamelCase__HandlerFactory.xml
tools/archetype/binding/src/main/resources/archetype-resources/README.md
tools/archetype/binding/src/main/resources/archetype-resources/about.html
tools/archetype/binding/src/main/resources/archetype-resources/build.properties
tools/archetype/binding/src/main/resources/archetype-resources/cfg/__bindingId__.cfg
tools/archetype/binding/src/main/resources/archetype-resources/cfg/_bindingId_.cfg
tools/archetype/binding/src/main/resources/archetype-resources/pom.xml
tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/__bindingIdCamelCase__BindingConstants.java
tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/handler/__bindingIdCamelCase__Handler.java
tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java

Worked on a set of minor issues in the archetype:
- XML files should be formatted with tabs
- Files should have the proper copyright headers
- Java files should be formatted with spaces and follow the formatter guidelines
- Loggers should be ~~static~~ *final*
- The `BINDING_ID` is only used in this class in all (most) all bindings make it private by default
- Include the about.html in the `build.properties`
- Escape the h2-headers in the README and add it to be exported
- Include the cfg example in the generated binding
- Include the about.html in the binding (have to find out a way to override it for openHAB, maybe just a cp in the skeleton script?)
- Removed inherited `groupId` from `pom.xml`
- Also made the year of the copyright dynamic
- Made the date of the about.html the current
- …

Worked on a set of minor issues in the archetype

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Action.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Condition.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Rule.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/RuleRegistry.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/AbstractRuleRegistryEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleAddedEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleEventFactory.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleRemovedEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleStatusInfoEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/events/RuleUpdatedEvent.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/handler/ModuleHandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/RuleTemplate.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/RuleTemplateProvider.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/Template.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/TemplateRegistry.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ActionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/Input.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ModuleType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ModuleTypeProvider.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ModuleTypeRegistry.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/Output.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/TriggerType.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameterBuilder.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/ProviderChangeListener.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Registry.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/RegistryChangeListener.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/events/AbstractEventFactory.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/storage/StorageService.java

Javadoc is fixed to pass java 1.8 build. #3269
I know that the `-Xdoclint:none` statement suppress the errors but i think more clean and full javadoc is welcome.
Missing `@param` statements are added.
Some of the descriptions are fixed.

Javadoc is fixed #3269

---

extensions/binding/org.eclipse.smarthome.binding.wemo.test/org.eclipse.smarthome.binding.wemo.tests.launch
extensions/binding/org.eclipse.smarthome.binding.wemo.test/pom.xml
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/internal/http/test/WemoHttpCallOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/test/GenericWemoOSGiTest.groovy

Hoping to fix failing tests on Hudson through this.
Same change as has been done for https://github.com/eclipse/smarthome/pull/3264.

use a different jetty port for test execution

---

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java

Related to PR [#3278](https://github.com/eclipse/smarthome/pull/3278) (Worked on a set of minor issues in the archetype).
Signed-off-by: Christoph Weitkamp github@christophweitkamp.de

Changed 'final static' to 'static final' in archetype

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js

Related to: https://github.com/eclipse/smarthome/issues/3318#issuecomment-297478687
@cdjackson Do you like to have a look at?

add missing uglify for concatenated content

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js

do not uglify names in angular code to leave DI intact

Fix unglify angular code for PaperUI

---

bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/.classpath
bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/.settings/org.eclipse.jdt.core.prefs
bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/shared/RuleSupportRuleRegistryDelegate.java
bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AbstractFileProvider.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/WatchQueueReader.java
features/karaf/esh-core/src/main/feature/feature.xml
features/org.eclipse.smarthome.feature.runtime.automation/feature.xml

- changed project JRE to use default (1.8)
- removed project specific compiler settings
- updated RuleRegistry implementation to latest interface in order to resolve compilation errors
- changed folder watchers to use configuration dir as a root
- addressed exceptions in the log if folders do not exist
- added the bundle to p2 automation feature
- added new Karaf feature

cleanup for scripting rule support

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/groovy/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerOSGiTest.groovy

as in the "verify OFFLINE Thing-status and NULL Item-state when the HTTP
response cannot be parsed correctly" the property to return invalid XML
was set too late. When timing was right, the handler hat the chance to
set the item state once, therefore the assumption that it was not set
failed.
(+ whatever was wrong with the whitespaces got fixed by my formatter in the first commit)

Fix fs internet radio tests again

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/service/AbstractWatchServiceTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/WatchQueueReader.java

WatchQueueReader was "fixed" due to incorrect tests. This roles back the change and fixes the test.

fix AbstractWatchServiceTest for macOS - again

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GroupItemTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ManagedItemProvider.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

A plain group without type does NOT have a function now.
A group with a type uses the EQUALITY function by default
A group with type and function uses the specified function
Fixes #3051

Corrected and defined behavior of group functions

---

bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java

Changes in `VoiceManagerImpl.startDialog`:
- Use the default or configured keyword if not provided;
- Use the provided locale;
- Null-checking for locale and keyword.
Signed-off-by: Yannick Schaus <eclipse@schaus.net>

VoiceManagerImpl startDialog parameters

---

bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/RuleSupportScriptExtension.java

I observed that the scope has been empty in JS rules without this change. However, as there is no documentation so far, I'm not 100% sure whether I really got the idea right. 
Therefore, @smerschjohann, it would be good if you could have a quick look at this too...?

fix scope in automation script rule support

---

bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/OSGI-INF/RuleSupportScriptExtension.xml
bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/OSGI-INF/ScriptFileProvider.xml

* removed the "unbind" declarations as these methods don't exist (and as they're static dependencies they actually are not really required)
* made the ScriptFileProvider's dependency to the ScriptEngineManager static as this component does not make sense without it and it was not prepared to handle the dynamics anyway.

fixed DS declarations in automation script rule support

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/colorirlight.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/colorlight.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/colormzlight.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/whitelight.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/README.md
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/LifxBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCurrentStateUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightOnlineStateUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightState.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightStateChanger.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/listener/LifxLightStateListener.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/GetHostInfoRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/SignalStrength.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/StateHostInfoResponse.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/StateWifiInfoResponse.java

This PR adds a new `signalstrength` channel to all LIFX light Things. The channel contains the received signal strength at a LIFX light. It reuses the `system.signal-strength` typeId and is based on the `signal` value in the [StateWifiInfo](https://lan.developer.lifx.com/docs/device-messages#section-statewifiinfo-17) packet. The binding will only poll for this information when the `signalstrength` channel is linked to an item.
The lights can also send a [StateHostInfo](https://lan.developer.lifx.com/docs/device-messages#section-statehostinfo-13) packet but for some reason it always has a `signal` value of 0. The binding had mixed up the TYPE values in `GetHostInfoRequest` and `StateHostInfoResponse` so I've corrected that.
Furthermore the light online/offline detection has been improved. …

Add LIFX signalstrength channel, improve online/offline detection and exception handling

---

docs/documentation/development/notes.md
extensions/ui/org.eclipse.smarthome.ui.paper/package.json
extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml

Allow first-time frontend contributors to get started quickly by
leveraging `npm` for the frontend build, thus avoiding a global `gulp`
installation.
Also adds a missing peer dependency to support npm >= 3.

Add kickstart instructions for Paper UI contributors

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java

I've done some testing and it still works well to do a full HSBK value update in rules by first changing the temperature channel state and then immediately change the color channel state.

Fixes #3389 by setting saturation to 0% when LIFX color temperature channel changes

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/SetLightInfraredRequest.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/StateLightInfraredResponse.java

This PR fixes #3390 by using little-endian byte ordering for LIFX IR brightness values.

Fixes #3390 by using little-endian byte ordering for LIFX IR brightness values

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java

The RuleRegistryImpl is different to other registries insofar as it returns
copies of its elements instead of the actual elements.
Therefor the default streams() implementation had to be overriden for RuleRegistryImpl.
Signed-off-by: Victor Toni <victor.toni@gmail.com>

Returning only copies of rules - fixes returning actual rules.

---

bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/JsonStorage.java

Fixes #3428.
Imho backup files must only be used to restore a database, if there is indeed a corrupt file. If no database file exists, no backup should be used.

Only restore backup if there indeed was an unreadable file.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html

Label of linked items overlaps with the icon on small screens.
Before:
After:

Made linked items list responsive

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/AbstractDailyJob.java

[Astro Binding] fix NPE in case it's not really dark at night

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/LifxBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCurrentStateUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightOnlineStateUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightPropertiesUpdater.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightStateChanger.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/fields/MACAddress.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/listener/LifxPropertiesUpdateListener.java

* Update light properties when Thing goes online which fixes:
* Properties not always updated for lights defined in .things files
* Existing light Things which do not get new/updated properties from discovery (#3323)
* Don't power on IR lights when changing infrared channel brightness
* Reuse the default thing ScheduledExecutorService
* Use final Logger and ReentrantLock objects

LIFX improvements

---

targetplatform/EclipseSmartHome.setup

Add the following types for static import on content assist:
* org.junit.Assert.*
* org.mockito.Mockito.*
* org.mockito.MockitoAnnotations.*
* org.hamcrest.CoreMatchers.*

Add basic test classes for static import on content assist.

---

bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/JsonStorage.java

This changes the way the backup is written. The backup is now written at the same time as the data is stored, rather than storing a single file, and then having to rename it later. The main database file is overwritten so should not ever be removed unless the underlying filesystem is doing this (in which case there is probably nothing that can be done at Java level?).
This avoids the situation where there is no file for any period of time, and this should ensure the backup is read if the main file is corrupted due to a crash (etc).
Writing the backup at the same time as the main file avoids a (slower) read->write which would be required to copy the original file if it was done later.
This has another (arguable) advantage in that there are now two copies of the latest file, so two chances …

Write jsondb backup without renaming original file.

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GroupItemTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java

With Java 8 we can now use streams and their filter functions, so this method can retrieve any members matching a given filter
Fixes #586

New API function to retrieve members of a GroupItem

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/service/AbstractWatchServiceTest.groovy

As Travis found out [here](https://travis-ci.org/eclipse/smarthome/builds/234385901#L1778), it's not enough to use synchronized collections. They will still fail when iterating over them.
This fix is not nice performance-wise, but keeps the tests better readable than doing proper synchronization. It's just a test, after all.

fix ConcurrentModificationException in AbstractWatchServiceTest

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/CoreItemFactory.java

> - Re-ordered all item type constants in alphabetical order
> - Changed `createItem` method to make use of a switch statement (using alphabetical order)
> - Fixed broken {@inheritDoc} links

Refactored CoreItemFactory

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/events/ItemEventFactoryTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java

use toFullString when creating GroupItemStateChangeEvent

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/events/ItemEventFactoryTest.groovy
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

This removes the "Type" postfix from state types in Item specific events. PaperUI event handling is adopted. From what I can see in the code the BasicUI is not affected by this change.
Fixes #3282.

remove "Type" postfix from state types in item events

---

docs/documentation/development/ide.md
extensions/ui/org.eclipse.smarthome.ui.paper/PaperUI Setup.launch
targetplatform/EclipseSmartHome.setup

* Add a launch config for `mvn clean install` to o.e.s.ui.paper project.
* Add launch config to manual IDE setup tasks.
* Adopt ID setup documentation.
Fixes #2384.

Add PaperUI setup to IDE setup task

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

As found in #3351 and openhab/openhab2-addons#2019 the synchronization mechanism of the ThingManager had some flaws. Therefore the following changes:
* use of dedicated locks instead of synchronization by object so that synchronization by Thing keeps working even if the concrete object changes. Now we have a dedicated lock object per thing, using the ThingUID as an identifier.
* moved the handler initialization back to the caller thread (thereby reverting this aspect of #3088) and making the migrateThingType thread wait instead until the Thing's lock is available (i.e. initialize() returned). (ThingHandler.initialize() of course still is protected by the SafeMethodCaller)
* ensure thingUpdated() cannot be called in parallel with initialize() by also using the lock mechanism.
* updated …

Fix synchronization in ThingManager

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java

...as it slows down the scheduler and was used in a dangeriously
wrt thread-safety.
fixes #3505
fixes #3506

[Scheduler] Dropped usage of SimpleDateFormat for trace logging

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java

... by expanding the synchronized block to include the outer loop. 
And while being at it anyway I also vaporized the removal logic to a single line.
fixes #3504

Scheduler: fix ConcurrentModificationException

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

...in order to allow better analysis of why a thing handler was initialized.

improved logging in ThingManager.isInitializable()

---

tools/archetype/binding/src/main/resources/META-INF/maven/archetype-metadata.xml
tools/archetype/binding/src/main/resources/archetype-resources/README.md

Removed obfuscation from README so it can be both used from the archetype and is human readable, see also remark of Kai: https://github.com/eclipse/smarthome/pull/3278#issuecomment-304664364
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>

Removed obfuscation from README

---

bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/ScriptExtensionProvider.java

* `importPreset` must not return a null object if we collow the
callstack but should use an empty collection.
The returned map is forarded to the `scopeValues` method of an engine
provider. The engine provider calls `entrySet` on the given argument,
so if someone uses currently null it should already result in a NPE.
IMHO it is most of the time better to return an empty map / collection
etc. instead of null.
* I don't know what is the best approach for `get` if the type is not
supported. There is a `getTypes` method I assume that this function is
called for "supported" types only. IMHO it is okay to throw an
`IllegalArgumentException` if the `get` method is called with an
unsupported type and we could manifest that a non-null object should
be returned.
WDYT about the return values / …

fix JavaDoc of the script extension provider

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java

In the continued attempt to hunt down #3562 the static fields (and thereby also the methods) fell from grace. Ideally they should work nevertheless, but as ordering of the set/unset calls between two different instances is not guaranteed, this _could_ be a problem, potentially.

less statics in FolderObserver

---

bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/ruleengine.xml
bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/runtime.xml

Let the rule engine not even attempt to run before the Xtext/EMF stuff has been initialized.
Just for the sake of completeness: The visual effects produced by this missing dependency looked like following:
```
java.lang.NullPointerException
at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.activate(RuleEngineImpl.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
[...]
Caused by: java.lang.NullPointerException
at …
```

rule engine to depend on the Xtext/EMF setup for rules

---

README.md
docs/documentation/community/contributing.md

To simplify the entry for new contributors links to "help wanted" and "bug" issues are added to the documentation and README.MD.

Add prominent link to issues for new contributors

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java

Error logging is skipped in the AggregatingScanListener when a discovery scan is aborted (e.g. when a CancellationException is met)
Signed-off-by: Dimitar Ivanov <dstivanov@gmail.com>

Do not log CancellationException for AggregatingScanListener on Aborted Scan

---

bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/ThingConfigDescriptionProvider.xml
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingConfigDescriptionProvider.java

...so that bindings have a chance to provide channel specific config options
via a ConfigOptionsProvider in the same way as it is possible for things already.
I therefore simply extended the already existing proxy to also handle the "channel" scheme.
The PaperUI will have to be adapted to actually use them (similar as #3215 which added this feature for things). 

add support for retrieving channel specific config descriptions

---

bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/ruleengine.xml
bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/runtime.xml
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/RuleRuntimeActivator.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java
bundles/model/org.eclipse.smarthome.model.script.runtime/OSGI-INF/scriptengine.xml
bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/internal/engine/ScriptEngineImpl.java

...as without actually using them, their activate() method never gets called.
In the logs, we could see that ScriptServiceUtil is there and has all its dependencies satisfied, but still did not get activated early enough:
```
2017-06-08 13:29:48.190 [DEBUG] [thome.model.script.ScriptServiceUtil] - ScriptServiceUtil is not initialized!
ThingRegistry: {org.eclipse.smarthome.core.thing.ThingRegistry}={component.name=org.eclipse.smarthome.core.thing.ThingRegistry, component.id=78, service.id=166, service.bundleid=106, service.scope=bundle}
ItemRegistry: {org.eclipse.smarthome.core.items.ItemRegistry}={component.name=org.eclipse.smarthome.core.itemregistry, component.id=50, service.id=132, service.bundleid=99, service.scope=bundle}
EventPublisher: {org.osgi.service.event.EventHandler, …
```

make sure the service dependencies get activated

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingStatusDetail.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
docs/documentation/concepts/things.md

Currently if there's an error with the bridge, it's things will have status HANDLER_MISSING which is wrong. This adds a BRIDGE_HANDLER_MISSING to provide a more accurate error message so we know where to look for the problem...

Provide better status information when bridge is missing

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

Fixes #3570.
* align channel description for Color widget
* apply left padding for slider on DimmerWidget with switch

Fix text alignment for multi channel widgets.

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheMapTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheTest.java
bundles/core/org.eclipse.smarthome.core/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCache.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheMap.java

* Moved `ExpiringCache` from Yahoo Weather Binding to Eclipse SmartHome Core
* Replaced Interface `LoadAction` with Interface `java.util.function.Supplier`
* Added `invalidate` an `refresh` methods
* Added `ExpiringCacheMap` to support handling multiple cache values
* Added `ExpiringCacheTest` and `ExpiringCacheMapTest`
Closes #3302 
Also-by: Simon Kaufmann <simon.kfm@googlemail.com>

Moved ExpiringCache from Yahoo Weather Binding to Eclipse SmartHome Core

---

bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/internal/engine/ScriptEngineImpl.java
bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/ScriptServiceUtil.java

As it seems, #3614 made a not-so-well-hidden circular dependency between two services surface. 
The `ScriptEngine` depends on the `ScriptServiceUtil`, which in turn registers a service tracker for `ScriptEngine` during its activation. I assume it is done like this because DS would have complained about the circular dependency if it was declared in the XML.
Therefore I suggest setting it "by foot" at the moment when `ScriptEngine` gets injected the `ScriptServiceUtil` instance.
Hacky hacky, little (less) whacky...
relates to #3614

resolving circular dependency by removing SCR from the game

---

bundles/storage/org.eclipse.smarthome.storage.json/OSGI-INF/jsonstorage.xml
bundles/storage/org.eclipse.smarthome.storage.mapdb/OSGI-INF/mapdbstorage.xml

This property could be consumed e.g. by a filter to get a specific storage service injected.

add storage.format property to StorageService implementations

---

bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/GenericItemUIProvider.java

The `ModelRepository.getModel()` method _can_ return null. Almost all callers have a null-guard. Here I added the two missing ones which I could find.
fixes #3636

fix NPEs in cases where ModelRepository returns null

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java

The discovery service registry suffered from the same disease as in #3648: the object types did not match (values are `DiscoveryResult`s, not `ThingUID`s)

fixed discovery result removal

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/test/ConfigurationTest.groovy
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

...as a last resort, if it was not normalized before.
The downside is, that at this point there is no type information available,
i.e. the config description cannot be used. Therefore normalization can
happen only on a "best guess", based on the incoming type.
fixes #3527 (mostly)

normalize in configuration.put(...)

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProviderTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java

It's been a pain for tests (see https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/1936), but I think it also cannot hurt to have it switched off configurable (on remains the default).
Alternatively we could add an `isInitialized()`method. I don't mind.

configurable initial delay of ChannelItemProvider

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java

Restarting the transport layer causes all CoAP connections to create a new TCP connection with a new SSL handshake. While this for sure is required if the Gateway has been restarted, I'm not really sure whether it is the right way of doing it when using the Californium APIs. I would have expected californium to take care of such aspects and also doing it only when necessary. This is brute-force right now: Whenever there is an error, renew all sockets. 
So big disclaimer: I have no clue what I'm doing here, please help if you have a better idea!
fixes #3672

[tradfri] restart transport layer on error

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.tradfri/README.md

fixes https://github.com/eclipse/smarthome/issues/3678

fixed the type of the id parameter for Tradfri devices

---

bundles/io/org.eclipse.smarthome.io.rest.core/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/gsonprovider.xml
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/GsonProvider.java
targetplatform/smarthome.target

...in order to cleanup the GSON library version mess.
It's effectively 3 lines of trivial code that it takes.
related to #3680

implement own Jersey GSON provider

---

bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericItemChannelLinkProviderJavaTest.java
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericItemChannelLinkProvider.java

...in order to enable the entry points from service again.
As they are currently built in an add-only way, they don't
require the remval capability at the end anyway.
fixes #3686

relax transaction enforcement in GenericItemChannelLinkProvider

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
bundles/io/org.eclipse.smarthome.io.rest.test/src/test/java/org/eclipse/smarthome/io/rest/JSONResponseTest.java
bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/JSONResponse.java

also: adjust item resource API description to match the actual behavior.

Avoid creating stream for null entity in JSON response.

---

extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/config/config.xml

The XML Comprised `<` and `>` symbols that interpreted the inline words as attributes.

Fixed XML Errors

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/handler/AstroThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/AbstractJob.java

The scheduling operations schedules few jobs and executes 2 specific jobs immediately. These two jobs are executed in a different thread to prevent blocking the thread that spawns it. 
In addition, during handler initialize, channel linking and unlinking, we reschedule the jobs. And every time, before we reschedule the jobs, we remove the jobs from the ESH Core scheduler that are associated with the current thing.
As the jobs that execute immediately are handled by different threads, it is sometime noticed that while rescheduling, removal of jobs did occur after the jobs got rescheduled. This created unexpected issues in ESH Core scheduler. In this PR, we have rendered the asynchronous operations of executing immediate jobs in different threads to synchronous execution so that we can make …

Synchronous Execution of Astro Startup Jobs and minor fixes

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngineCallbackImpl.java

executor.shutdownNow() is now in privileged call

Fix the  java.lang.RuntimePermission in RuleEngineCallbackImpl #3702

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImplTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/internal/i18n/TranslationProviderOSGiTest.java
bundles/core/org.eclipse.smarthome.core/OSGI-INF/i18nprovider.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java

...in order to not pollute the "root" internal package and to make it symmetric to the interfaces (which are located in the i18n package as well).

move I18nProviderImpl into the internal.i18n package

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/AbstractJob.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/DailyJobMoon.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/DailyJobSun.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/EventJob.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/PositionalJob.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/PublishPlanetJob.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/SunPhaseJob.java

...so they are better distinguishable, e.g. in scheduler logs.
Also, hiding the thingUID from subclasses.

named astro jobs

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/RunnableWrapper.java

* increased some log statements to debug level
* additional trace logging
* using locks and conditions instead of interrupts
* wrapping given runnables so their hashcode/equals does no harm

various small improvements in the expression scheduler

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/config/config.xml
extensions/binding/org.eclipse.smarthome.binding.lifx/README.md
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightPropertiesUpdater.java

As reported in #3745 using `powerOnBrightness=` in a .things file no longer works. Such files nowadays fail validation, e.g. the following warning is logged:
```
19:04:22.457 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'test.things' has errors, therefore ignoring it: [4,49]: no viable alternative at input ']'
```
After testing it shows that removing the default for the `powerOnBrightness` parameter makes it again possible to switch lights on without changing the brightness when the `powerOnBrightness` parameter in .things files is omitted.

LIFX: Fix #3745 powerOnBrightness is ignored when empty in the things file

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigOptionProvider.java
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceServiceRegistryImpl.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicServiceImpl.java

...as several implementations return null. Also, it does not make
much sense to instantiate empty collections all the time, as the
majority of call will be returned with no results.

adapt ConfigOptionProvider javadoc to reality

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/handler/AstroThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/Job.java

The (cron) expression based scheduler is still used for the "daily" jobs
which will be executed every midnight. Those "daily" jobs however create
jobs for all kinds of events during the current day, which will have to
be executed only once. For those, it does not really make sense to convert
a timestamp to a cron expression, which the scheduler again with lots of
effort boils down again to a timestamp. Therefore they are now simply
executed with a calculated delay directly using the regular scheduler.

use classic scheduler for one-time jobs

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/README.md
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryService.java

* NPE safeguard
* Added "TRADFRI bulb GU10 WS 400lm" bulb to `COLOR_TEMP_MODELS`
* Minor fixes in README.md
Closes #3683 

[Tradfri] Avoid NPE if response doesn't contain needed JSON elements

---

extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY3.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY5.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/ZonePlayer.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/SonosBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

Sonos binding: add new channel clearqueue

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/CompositeJob.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/Job.java

The scheduler works on the unit of seconds. For range events, it can also schedule two events to be executed at the same instant. Due to parallel execution, there are inconsistency about the executions of the range events that are scheduled for same instants.
Therefore one second to the end event has been added to assure the synchronous execution of the range start and end events.

Added Composite Jobs for range events if scheduled at same instant

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/items/GroupItemTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java

Break circle dependency in GroupItem members

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/Job.java

In case your location does imply not having a valid Day or Night range the creation of trigger events failed. This PR fixes this.

[astro] fix invalid event creation

---

extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/config/config.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY3.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY5.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/ZonePlayer.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/config/ZonePlayerConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java

1. Extract the notification timeout as a thing configuration parameter
2. Increase the default notification timeout to 40 sec. (as 20 s is too short time)

Improve Sonos notification timeout handling

---

extensions/ui/org.eclipse.smarthome.ui.classic/snippets/layer.html
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/ColorpickerRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/ListRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/PageRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SelectionRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SwitchRenderer.java

Classic UI: escape HTML characters

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.firmware.html

Also: adopt PaperUI to not show FW details or an empty list of firmwares if nothing is found for the Thing.
Fixes #3791.

Return status '204: no content' if Thing has no firmware details

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/handler/AstroThingHandler.java

...in order to not keep useless references to finished jobs in the collections.
It's taking the opportunity for tidying up every time a new job gets scheduled.
In that way, the job's runnables don't have to be cluttered with these
internals of the handler.
Note: while it is in principle is similar to #3809, the current version since #3776 does not cause such troubles anymore. So this PR is mainly about freeing a little bit of memory.

[astro] Tidy up set of scheduled futures

---

bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/META-INF/MANIFEST.MF

This PR exports the rulesupport shared packages to resolve `ClassNotFoundException`s when using Groovy with the JSR-223 ScriptEngine (#3785).

Fixes #3785 class loading issues with JSR-223 Groovy ScriptEngine

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightState.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightStateChanger.java

With this PR the `LifxLightHandler` will only update the ThingStatus when there is a change.
Each received message currently always results in a `ThingStatus.ONLINE` update. This causes a lot of unnecessary `ThingStatusInfoEvent` s, logging etc. which generate unnecessary CPU load.

[LIFX] Update ThingStatus at most once a second

---

extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.md
extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.sh

Add HTML5 figure and figcaption elements to the iconset preview:
You'll find that the style is inline. I promise to move it to css as soon as style.css is unified between ESH and openhab-docs. If you insist I will look into it now.
Signed-off-by: Thomas Dietrich <Thomas.Dietrich@tu-ilmenau.de>

[Classic Iconset] Add figcaptions

---

extensions/binding/org.eclipse.smarthome.binding.lirc/.classpath
extensions/binding/org.eclipse.smarthome.binding.lirc/.project
extensions/binding/org.eclipse.smarthome.binding.lirc/ESH-INF/binding/binding.xml
extensions/binding/org.eclipse.smarthome.binding.lirc/ESH-INF/thing/bridge.xml
extensions/binding/org.eclipse.smarthome.binding.lirc/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.lirc/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.lirc/OSGI-INF/LIRCHandlerFactory.xml
extensions/binding/org.eclipse.smarthome.binding.lirc/README.md
extensions/binding/org.eclipse.smarthome.binding.lirc/about.html
extensions/binding/org.eclipse.smarthome.binding.lirc/build.properties
extensions/binding/org.eclipse.smarthome.binding.lirc/pom.xml
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/LIRCBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/handler/LIRCBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/handler/LIRCRemoteHandler.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/LIRCHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/LIRCMessageListener.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/LIRCResponseException.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/config/LIRCBridgeConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/config/LIRCRemoteConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/connector/LIRCConnector.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/connector/LIRCEventListener.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/connector/LIRCStreamReader.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/discovery/LIRCRemoteDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/messages/LIRCButtonEvent.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/messages/LIRCResponse.java
extensions/binding/pom.xml

This binding allows decoding and sending of infrared signals used by most remotes controls via LIRC (and its Windows counterpart WinLIRC).
Each remote that is known by LIRC is represented by a thing with a single channel. This channel is a String type that contains the name of the button the user pressed.
I had considered dynamically creating channels for each button on a remote, but I decided against it as most TV remotes can have upwards of of 30 or more buttons and only one can be activated at any given time.
Signed-off-by: Andrew Nagle <kabili@zyrenth.com>

Add new binding for LIRC.

---

features/karaf/esh-tp/src/main/feature/feature.xml
targetplatform/smarthome.target

Afair, we do not have any dependency on the Apache Commons HTTP client anymore.

remove apache commons http client from target platform
