- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY3.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY5.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/ZonePlayer.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/channels.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/thing-types.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/README.md
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/SonosBindingConstants.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> Sonos binding: 2 new channels currenttrackuri and currenttransporturi

- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxNetworkThrottler.java
This should fix some concurrency issues. 
@wborn If would be helpful if you could test this in your LIFX "swarm". I have put the number of retries for polling to 4. I prefer not to put that as a configurable parameter as it would clutter the simple and clean configuration interface of the bulbs, but instead I would propose to put it to the value that works for you, since you have the biggest collection of LIFX bulbs I know of ;-)
> LIFX : fix #2191, #2193 and other improvements

- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
Signed-off-by: Wouter Born <eclipse@maindrain.net>
> Fix #2155 INCREASE/DECREASE not working for LIFX

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js
fixes https://github.com/eclipse/smarthome/issues/2202
> Bug fix: module ids not unique

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/StrippedThingTypeDTO.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/StrippedThingTypeDTOMapper.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingTypeDTO.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java
Make thingTypeDTO's lighter by not setting properties, configParameters and channels
Removed unused method
Fixes #1729 part 1
Signed-off-by: Miki Jankov <miki.jankov87@gmail.com>
> Make thingTypeDTO's lighter

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.system.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.linkchannel.html
fixes https://github.com/eclipse/smarthome/issues/867 and https://github.com/eclipse/smarthome/issues/1140
> PaperUI handle multiple linked items in a channel

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceOSGiTest.groovy
> Fixed FirmwareUpdateServiceOSGiTest

- extensions/voice/org.eclipse.smarthome.voice.mactts/src/main/java/org/eclipse/smarthome/voice/mactts/internal/MacTTSAudioStream.java
- extensions/voice/org.eclipse.smarthome.voice.mactts/src/main/java/org/eclipse/smarthome/voice/mactts/internal/MacTTSService.java
> changed MacTTS to use 44.1kHz

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
Adapts PaperUI to changes introduced by https://github.com/eclipse/smarthome/pull/2199
> Adapt PaperUI to new thingType

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
fixes the bug described in the comment https://github.com/eclipse/smarthome/pull/2229#issuecomment-250422648
> Bug fix: missing event parameter

- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioManager.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioSink.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/URLAudioStream.java
> added the possibility to pass null to a sink to stop streaming

- features/org.eclipse.smarthome.feature.runtime.core/feature.xml
> added missing bundle to features

- extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
> Fix ntp timeout issue #2174

- bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java
Fixes https://github.com/openhab/openhab2-addons/issues/1283
> avoid NPE if HTTP response does not provide an encoding

- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/VoiceManager.java
> improved error logging when using TTS

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
fixes https://github.com/eclipse/smarthome/issues/2238
> Allow unsetting config values

- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/config/ConfigurationService.java
Fixes https://github.com/eclipse/smarthome/issues/2238#issuecomment-251409601
> handle removal of config params on services

- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/VoiceManager.java
- bundles/io/org.eclipse.smarthome.io.rest.voice/.classpath
- bundles/io/org.eclipse.smarthome.io.rest.voice/.project
- bundles/io/org.eclipse.smarthome.io.rest.voice/.settings/org.eclipse.jdt.core.prefs
- bundles/io/org.eclipse.smarthome.io.rest.voice/.settings/org.eclipse.pde.core.prefs
- bundles/io/org.eclipse.smarthome.io.rest.voice/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.rest.voice/OSGI-INF/voicerest.xml
- bundles/io/org.eclipse.smarthome.io.rest.voice/about.html
- bundles/io/org.eclipse.smarthome.io.rest.voice/build.properties
- bundles/io/org.eclipse.smarthome.io.rest.voice/pom.xml
- bundles/io/org.eclipse.smarthome.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/HLIMapper.java
- bundles/io/org.eclipse.smarthome.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/HumanLanguageInterpreterDTO.java
- bundles/io/org.eclipse.smarthome.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/VoiceResource.java
- bundles/io/pom.xml
- features/org.eclipse.smarthome.feature.runtime.rest/feature.xml
> expose HumanLanguageInterpreters on the REST API

- extensions/io/org.eclipse.smarthome.io.javasound/src/main/java/org/eclipse/smarthome/io/javasound/internal/JavaSoundAudioSource.java
> defer creation of sound input until its first use

- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/text/HumanLanguageInterpreter.java
- bundles/io/org.eclipse.smarthome.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/HLIMapper.java
- bundles/model/org.eclipse.smarthome.model.script/ESH-INF/config/config.xml
- bundles/model/org.eclipse.smarthome.model.script/OSGI-INF/rulehli.xml
- bundles/model/org.eclipse.smarthome.model.script/build.properties
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/internal/RuleHumanLanguageInterpreter.java
> HumanLanguageInterpreter that allows to process voice commands in DSL rules

- docs/documentation/development/bindings/dependencies.md
Related to https://github.com/eclipse/smarthome/issues/1689.
> replaced apache by jetty http client

- bundles/io/org.eclipse.smarthome.io.transport.dbus/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.transport.dbus/pom.xml
- bundles/io/pom.xml
- features/karaf/src/main/feature/feature.xml
> Dbus transport fixes

- targetplatform/smarthome.target
- targetplatform/third-party/.gitignore
- targetplatform/third-party/README.md
> easy way to add third party JARs to TP for development only

- features/karaf/src/main/feature/feature.xml
Fixes: https://github.com/eclipse/smarthome/issues/2281
> fix esh-ui-basic feature dependencies

- bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
See https://github.com/eclipse/smarthome/pull/2030#discussion_r82445533
> addressed performance worries

- bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
> Send sitemap events on sitemap visibility updates

- bundles/automation/org.eclipse.smarthome.automation.module.core.test/src/test/groovy/org/eclipse/smarthome/automation/module/core/internal/RuntimeRuleTest.groovy
- bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/RuleEnableModuleType.json
- bundles/automation/org.eclipse.smarthome.automation.module.core/OSGI-INF/BasicModuleHandlerFactory.xml
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/BasicModuleHandlerFactory.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/RuleEnableHandler.java
Signed-off-by: Plamen Peev <p.peev@prosyst.bg>
> Create an action which can enable or disable a set of rules.

- bundles/core/org.eclipse.smarthome.core.audio/META-INF/MANIFEST.MF
- bundles/core/org.eclipse.smarthome.core.audio/OSGI-INF/AudioServlet.xml
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioHTTPServer.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioServlet.java
> Introduction of an AudioServlet to provide audio streams through HTTP

- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioManager.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioSink.java
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/Audio.java
- extensions/io/org.eclipse.smarthome.io.javasound/META-INF/MANIFEST.MF
- extensions/io/org.eclipse.smarthome.io.javasound/src/main/java/org/eclipse/smarthome/io/javasound/internal/JavaSoundAudioSink.java
This is imho more in line with our other interfaces where we use our own type system.
> changed volume of AudioSink from float to PercentType

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
fixes https://github.com/eclipse/smarthome/issues/2271
> Rewind and Fast forward in player widget

- tools/archetype/binding.test/src/main/resources/archetype-resources/src/test/groovy/test/__bindingIdCamelCase__OSGiTest.groovy
- tools/archetype/binding.test/src/main/resources/archetype-resources/src/test/java/internal/__bindingIdCamelCase__InternalTest.java
- tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/__bindingIdCamelCase__BindingConstants.java
- tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/handler/__bindingIdCamelCase__Handler.java
- tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java
> updated license headers of archetype

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/SonosBindingConstants.java
> Changed ESH-PREFIX and cleaned up warnings

- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioFormat.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/FileAudioStream.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/FixedLengthAudioStream.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioServlet.java
- Introduced FixedLengthAudioStream
- Provide Content-Length in AudioServlet
- Ignore file extensions in urls in AudioServlet
- added ability to reset a FileAudioStream
> Some improvements on audio streams

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAlarm.java
> some code cleanup and NPE fixes on Sonos

- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioHTTPServer.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/ByteArrayAudioStream.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/FileAudioStream.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/FixedLengthAudioStream.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioServlet.java
> added support to serve a single AudioStream multiple times concurrently through HTTP

- bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/storage/ManagedItemProviderOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ManagedItemProvider.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java
> persisting group functions in the ManagedItemProvider

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
> Support audio events

- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
* Unlock lightCounterLock when exceptions occur
* Potential NPE in handlePowerStatus
Signed-off-by: Wouter Born <eclipse@maindrain.net>
> [LIFX] FindBugs issues fix

- extensions/binding/org.eclipse.smarthome.binding.digitalstrom/README.md
- extensions/binding/org.eclipse.smarthome.binding.hue/README.md
- extensions/binding/org.eclipse.smarthome.binding.lifx/README.md
- extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
- extensions/binding/org.eclipse.smarthome.binding.sonos/README.md
- extensions/binding/org.eclipse.smarthome.binding.yahooweather/README.md
Improved README files for all bindings (fixed typos like empty spaces, changed text where necessary to improve grammar and sense).
> Improved README file for the Hue binding

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
Partly fixes https://github.com/eclipse/smarthome/issues/2325
> Applied error class

- bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext
- bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
...in order to reflect reality. 
I think this was just missed in #1936.
> renamed channelType to channelKind in the model

- bundles/core/org.eclipse.smarthome.core.audio/ESH-INF/config/config.xml
- bundles/core/org.eclipse.smarthome.core.audio/OSGI-INF/AudioManager.xml
- bundles/core/org.eclipse.smarthome.core.audio/build.properties
- bundles/core/org.eclipse.smarthome.core.voice/ESH-INF/config/config.xml
- bundles/core/org.eclipse.smarthome.core.voice/OSGI-INF/VoiceManager.xml
- bundles/core/org.eclipse.smarthome.core.voice/build.properties
> added meta data for audio and voice services

- extensions/binding/org.eclipse.smarthome.binding.sonos/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.sonos/OSGI-INF/SonosHandlerFactory.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAudioSink.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java
Note: This PR requires https://github.com/eclipse/smarthome/pull/2305 to be merged first.
implements https://github.com/eclipse/smarthome/issues/1200
> initial contribution of Sonos AudioSink support

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/handler/FSInternetRadioHandler.java
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadio.java
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java
Some changes are made in org.eclipse.smarthome.bindig.fsinternetradio.
They are mainly related to cleaning up some unneccessary checks and
code lines that can never be reached.
> Changes in the FSInternetRadio binding.

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/DateExpression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/Expression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/RecurrenceExpression.java
> Scheduler : fix #2105

- extensions/binding/org.eclipse.smarthome.binding.ntp.test/src/test/groovy/org/eclipse/smarthome/binding/ntp/test/NtpOSGiTest.groovy
Fixed the bug in the NTP Binding, related to the time change: https://github.com/eclipse/smarthome/issues/2376
> NTP Binding Tests Fix

- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/tests/setup.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
> SetupPageController tests

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
fixes https://github.com/eclipse/smarthome/issues/2326
> Removed readOnly switch's state text

- extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/widget.multiselect.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
Support parameter with multiple true and limitToOption false. i.e. allow adding custom values.
Related issue: https://github.com/eclipse/smarthome/issues/566
> Support multiselect with custom values

- extensions/ui/org.eclipse.smarthome.ui.paper/package.json
> Use jQuery-ui from npm

- docs/documentation/development/bindings/xml-reference.md
> Supported contexts' documentation

- extensions/ui/org.eclipse.smarthome.ui.paper/.gitignore
- extensions/ui/org.eclipse.smarthome.ui.paper/.project
- extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml
I cannot grant that this is a grant fix, but I ran into #2219 now multiple times.
I used a shell while loop to restart `mvn clean install` as long as it does not succeed.
The while loop never finished since hours.
After this fix I can do a clean build again.
I don't know which code of Maven or some of the plugins clean up my target while building but I think this commit makes the situation not more wore and for me it helps (at least today).
Fixes: #2219
> fix Paper UI build

- extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
> Supports playing audio events on Safari and IE

- bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java
Signed-off-by: IVAN GEORGIEV ILIEV <ivan.iliev@musala.com>
> Added nginx proxy buffering fix to SitemapResource.java as well.

- bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/sitemap/internal/SitemapProviderImpl.java
> added a warning in case the sitemap model name does not match the filename

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAudioSink.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java
> improved the implementation for the Sonos callbackUri configuration parameter

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.linkchannel.html
1) Changed linkedItems font color.
2) Linked items left aligned.
3) Bug fix: Allow creating item while linking channel.
4) Bug fix: Newly 'created and linked' item not showing in the linked items list.
UI before:
UI after:
> Channel linkedItems bug+ui fixes

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
> Allow copying channel UID to clipboard

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
> Sorted bindings, services and service tabs

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/items/ColorItemTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ColorItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/DimmerItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/RollershutterItem.java
> fix ColorItem type conversion

- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/internal/XmlHelperTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/test/SystemChannelsInChannelGroupsTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsInChannelGroups.bundle/ESH-INF/binding/binding.xml
- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsInChannelGroups.bundle/ESH-INF/thing/thing-types.xml
- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannelsInChannelGroups.bundle/META-INF/MANIFEST.MF
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelGroupTypeXmlResult.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelXmlResult.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlProvider.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlHelper.java
> support for referencing of system channels within channel groups

- extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/AbstractWidgetRenderer.java
> BasicUI: fix possible NPE in widget renderer, fixes #2379

- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioSource.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/STTService.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/DialogProcessor.java
- extensions/io/org.eclipse.smarthome.io.javasound/src/main/java/org/eclipse/smarthome/io/javasound/internal/JavaSoundAudioSource.java
> fixed audio source interface

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
Signed-off-by: Hakan Tandogan hakan@tandogan.com
> Fixes #2428 , "mixed content" warning on Paper UI mapviews

- targetplatform/smarthome.target
> updated groovy version once again

- targetplatform/smarthome.target
> Sets groovy version back to release version.

- extensions/ui/org.eclipse.smarthome.ui.classic/ESH-INF/config/config.xml
> Classic UI: set default values for config settings

- bundles/model/org.eclipse.smarthome.model.rule/OSGI-INF/rulesitemrefresher.xml
- bundles/model/org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/jvmmodel/RulesItemRefresher.java
- bundles/model/org.eclipse.smarthome.model.script/OSGI-INF/scriptitemrefresher.xml
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/jvmmodel/ScriptItemRefresher.java
Fixes https://github.com/eclipse/smarthome/issues/2448
> React on coming and going action extensions and refresh scripts and rules in such cases

- extensions/voice/org.eclipse.smarthome.voice.mactts/README.md
> added documentation for the MacTTS service

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
Close audio context once stream has ended.
fixes https://github.com/eclipse/smarthome/issues/2444
> Bug fix: PaperUI prevents Windows from sleeping

- bundles/automation/org.eclipse.smarthome.automation.module.media/.classpath
- bundles/automation/org.eclipse.smarthome.automation.module.media/.project
- bundles/automation/org.eclipse.smarthome.automation.module.media/.settings/org.eclipse.jdt.core.prefs
- bundles/automation/org.eclipse.smarthome.automation.module.media/.settings/org.eclipse.pde.core.prefs
- bundles/automation/org.eclipse.smarthome.automation.module.media/ESH-INF/automation/moduletypes/MediaActionTypeDefinitions.json
- bundles/automation/org.eclipse.smarthome.automation.module.media/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.module.media/OSGI-INF/MediaActionTypeProvider.xml
- bundles/automation/org.eclipse.smarthome.automation.module.media/OSGI-INF/mediamodulefactory.xml
- bundles/automation/org.eclipse.smarthome.automation.module.media/about.html
- bundles/automation/org.eclipse.smarthome.automation.module.media/build.properties
- bundles/automation/org.eclipse.smarthome.automation.module.media/pom.xml
- bundles/automation/org.eclipse.smarthome.automation.module.media/src/main/java/org/eclipse/smarthome/automation/module/media/handler/PlayActionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.media/src/main/java/org/eclipse/smarthome/automation/module/media/handler/SayActionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.media/src/main/java/org/eclipse/smarthome/automation/module/media/internal/MediaActionTypeProvider.java
- bundles/automation/org.eclipse.smarthome.automation.module.media/src/main/java/org/eclipse/smarthome/automation/module/media/internal/MediaModuleHandlerFactory.java
- bundles/automation/pom.xml
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioManager.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioManagerImpl.java
- features/karaf/src/main/feature/feature.xml
- features/org.eclipse.smarthome.feature.runtime.automation/feature.xml
> Initial contribution of audio and voice modules for automation engine

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
> Multiple parameter with no options

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
> Show channel UID only in advance mode

- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configuration.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/tests/setup.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
1) tests for setup page controllers
2) tests for configuration controllers
3) removed unused code
> Setup and config tests

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
> Redirect to thing view from control page

- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java
Fixes https://github.com/eclipse/smarthome/issues/2454
> avoid npe if state is not a number

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
> Align string item value on same row in ControlUI

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/StringTypeTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringType.java
> fixed NPE in StringType.equals()

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandlerFactory.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
> Enforce that handler of a bridge implements BridgeHandler interface.

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java
Fixes: https://github.com/eclipse/smarthome/issues/2495
> don't add non-transient logger field

- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/VoiceManager.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceConsoleCommandExtension.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java
Update the interpret method prototype in the voice manager
> Interpret console command: fix #2493 #2494

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
Define constants for few orefix URI
> Sonos binding: fix notification sound when line-in is selected (fix #2474)

- bundles/automation/org.eclipse.smarthome.automation.parser.gson/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/AbstractGSONParser.java
- bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ConfigurationDeserializer.java
- bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ConfigurationSerializer.java
- bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ModuleTypeGSONParser.java
- bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ModuleTypeParsingContainer.java
- bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/RuleGSONParser.java
- bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/TemplateGSONParser.java
- bundles/automation/org.eclipse.smarthome.automation.provider.file/.classpath
- bundles/automation/org.eclipse.smarthome.automation.provider.file/.project
- bundles/automation/org.eclipse.smarthome.automation.provider.file/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.provider.file/OSGI-INF/ModuleTypeFileProvider.xml
- bundles/automation/org.eclipse.smarthome.automation.provider.file/OSGI-INF/TemplateFileProvider.xml
- bundles/automation/org.eclipse.smarthome.automation.provider.file/about.html
- bundles/automation/org.eclipse.smarthome.automation.provider.file/build.properties
- bundles/automation/org.eclipse.smarthome.automation.provider.file/pom.xml
- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AbstractFileProvider.java
- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AutomationWatchService.java
- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/ModuleTypeFileProvider.java
- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/ModuleTypeFileProviderWatcher.java
- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/TemplateFileProvider.java
- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/TemplateFileProviderWatcher.java
- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/WatchServiceUtil.java
- bundles/automation/pom.xml
- docs/documentation/development/rules/ModuleTypes_schema.json
- docs/documentation/development/rules/Rules_schema.json
- docs/documentation/development/rules/Templates_schema.json
implements issue #1569
replace PR https://github.com/eclipse/smarthome/pull/1648
Signed-off-by: Ana Dimova a.dimova@prosyst.bg
> Implement a file system TemplateProvider and ModuleTypeProvider

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
fixes https://github.com/eclipse/smarthome/issues/2503
> Use 24 hour time format

- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
> workaround Yahoo weather API's confusion of units

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringType.java
...according to the late feedback in #2479
(thanks btw!)
> simplified value comparison in StringType

- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java
> fixed concurrency issue in XmlThingTypeProvider

- extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueBridgeNupnpDiscoveryOSGITest.groovy
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
> no need for polling nupnp in the background

- extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueBridgeNupnpDiscoveryOSGITest.groovy
> fix for nUPnP Tests

- bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java
> [HttpUtil] Fixes #2540

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/StringListTypeTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringListType.java
> fixed toFullString and added required valueOf method to StringListType

- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/.classpath
- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/OSGI-INF/SampleJavaDemoComponent.xml
- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/about.html
- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/build.properties
- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/pom.xml
- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/readme.txt
- bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/src/main/java/org/eclipse/smarthome/automation/sample/java/demo/SampleJavaDemo.java
- bundles/automation/pom.xml
This commit is releated to point 3 at:
https://github.com/eclipse/smarthome/issues/2220
> Automation Demos Java Api

- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AutomationWatchService.java
See https://github.com/eclipse/smarthome/pull/2557#issuecomment-263563044
Adapting the code of AutomationWatchService to use relative path.
This change was necessary after #2432 was merged.
> AutomationWatchService uses relative path.

- bundles/config/org.eclipse.smarthome.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchQueueReader.java
- bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java
It seems @kaikreuzer and me reviewed the PR #2432 parallel, as it has been merged as I added some comments.
This PR changes the commented stuff.
@svilenvul As my formatter does some additional cleanup (removing trailing whitespaces), I assume that your IDE is not set upped correctly.
> cleanup watch service rel. path

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/groovy/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerOSGiTest.groovy
Some minor improvements are made in order to achieve a consistent behavior of the tests.
> Fix FSInternetRadio Tests

- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/HTTP.java
> add optional timeout parameter to sendHttp*Request

- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java
Also-by: Jayson Kubilis <jekubili@ktechs.net>
> WeMo: Fix for 2446 in WemoHandler and WemoLightHandler

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/widget.multiselect.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
1) Support multiple input for items and things
2) Hide other open dropdowns when clicked on a dropdown.
3) Allow only integer value for type=number.
4) Ignore limitToOptions when no options are available.
Can be tested with following parameter configs:
`````xml
<parameter name="items" type="text" required="false" multiple="true">
<label>Item 1</label>
<description>List of items</description>
<context>item</context>
<limitToOptions>false</limitToOptions>
</parameter>
<parameter name="items1" type="text" required="false" multiple="true">
<label>Item 2</label>
<description>List of items</description>
<context>item</context>
</parameter>
<parameter name="things" type="text" required="false" multiple="true">
<label>Things 1</label>
<description>List of things</description> …
```
> multiple input support for items and things

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.bindinginfo.html
> Hide heading if no things available

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
> Removed rule json view and settings button

- extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
Just saw these NPEs during [test execution](https://api.travis-ci.org/jobs/179859466/log.txt?deansi=true):
```
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:245)
at java.util.Calendar.createCalendar(Calendar.java:1662)
at java.util.Calendar.getInstance(Calendar.java:1655)
at org.eclipse.smarthome.binding.ntp.handler.NtpHandler.refreshTimeDate(NtpHandler.java:196)
at org.eclipse.smarthome.binding.ntp.handler.NtpHandler.handleCommand(NtpHandler.java:101)
at org.eclipse.smarthome.core.thing.binding.ThingHandler$handleCommand$0.call(Unknown Source)
```
This PR should fix those.
> Prevent potential NPEs

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.module.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.remove.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.removeitem.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
> Remove rule dialog + hide script output subtext

- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java
Reverts eclipse/smarthome#2566 as it has failing unit tests.
@hmerk I reverted in order to take out the time pressure for a fix. Please provide a new PR as soon as you are ready to do so (not urgent), thanks!
> Revert "WeMo: Fix for 2446 in WemoHandler and WemoLightHandler"

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
> fix handler initialization if child registration takes too long

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchService.java
> reduced logging to debug

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
> removed sysouts in ThingManagerOSGiTest

- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/Voice.java
I recommend a serious review because the change was not tested (don't know exactly how to test it).
At least, everything is compiling and the change is small.
> New rule action: interpret with HLI parameter (enh #2501)

- .travis.yml
That is similar to #2598
I created that PR to get a Travis CI build.
> work around the travis build output limit

- features/org.eclipse.smarthome.feature.runtime.core/feature.xml
> Include json storage to feature so it can be available in eclipse

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/SafeMethodCaller.java
> SafeMethodCaller adaptions for SecuredContexts

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateProgressInfoEvent.java
A small change to include also the percentage progress in the FirmwareUpdateProgressInfoEvent#toString method
> Improve FirmwareUpdateProgressInfoEvent#toString

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/FirmwareUpdateConsoleCommandExtension.java
> Added cancel console command for firmware updates.

- bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtilTest.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtil.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeActionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeTriggerHandler.java
> Extends functionality of composite module type handler #2465

- bundles/automation/org.eclipse.smarthome.automation.sample.json.demo/.classpath
- bundles/automation/org.eclipse.smarthome.automation.sample.json.demo/ESH-INF/automation/rules/DemoRule.json
- bundles/automation/org.eclipse.smarthome.automation.sample.json.demo/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.sample.json.demo/about.html
- bundles/automation/org.eclipse.smarthome.automation.sample.json.demo/build.properties
- bundles/automation/org.eclipse.smarthome.automation.sample.json.demo/pom.xml
- bundles/automation/org.eclipse.smarthome.automation.sample.json.demo/readme.txt
- bundles/automation/pom.xml
This commit is related to point 2 at:
https://github.com/eclipse/smarthome/issues/2220
> Automation Demos Json

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
> Handle handler initialization correctly.

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/handler/BaseTriggerModuleHandler.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/AbstractCompositeModuleHandler.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeActionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeConditionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/composite/CompositeTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/GenericEventTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.timer/src/main/java/org/eclipse/smarthome/automation/module/timer/handler/TimerTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/handler/WelcomeHomeTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/handler/SampleTriggerHandler.java
CompositeXXXXXHandler ,when disposed, disposes its childHandlers Related to: #2550 
> CompositeXXXXXHandler now disposes its child handlers.

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.linkchannel.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html
1) Show complete item creation options while creating item during channel linking.
2) Allow linking Dimmer and Switch items for channel.itemType=Color and Switch items for channel.itemType=Dimmer. (In addition to original itemType)
3) Show category icon.
4) Suggest an item name based on channel uid.
> Full feature item creation

- docs/documentation/concepts/items.md
- docs/documentation/development/rules/rule-configuration.md
Signed-off-by: Georg Guba georg.guba@qaware.de
> json rule configuration documentation for common module types

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/widget.multiselect.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
fixes https://github.com/eclipse/smarthome/issues/2535
> Show selected values in multi dropdown

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
- bundles/automation/org.eclipse.smarthome.automation.providers/OSGI-INF/AutomationResourceBundlesTracker.xml
- bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/AutomationResourceBundlesTracker.java
> Fixes #2616 bind method not found

- features/karaf/src/main/feature/feature.xml
also keep the alphabetic order
> karaf features: use same naming scheme as from beginning

- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/Voice.java
say/interpret actions: fix inconsistent parameter type (fix #2610)
> New rule action "interpret" with audio sink parameter (enh #2588)

- features/karaf/src/main/feature/feature.xml
> add karaf feature for io.rest.log bundle

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
It concerns the update of the channels currenttitle, currentartist, currentalbum and currenttrack.
No need to request updated information every minute, the update is now based only on GENA notifications.
> Sonos binding: simplified update of media info (enh #2214)

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html
fixes https://github.com/eclipse/smarthome/issues/2640
> Itemname allow only alphanumeric chars and underscore

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
fixes https://github.com/eclipse/smarthome/issues/2638
> Show custom error while updating readonly items

- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/.classpath
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/ESH-INF/automation/moduletypes/CompareCondition.json
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/ESH-INF/automation/moduletypes/ConsolePrintAction.json
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/ESH-INF/automation/moduletypes/ConsoleTrigger.json
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/OSGI-INF/DemoCommandsPluggable.xml
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/OSGI-INF/HandlerFactory.xml
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/about.html
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/build.properties
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/pom.xml
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/readme.txt
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/commands/DemoCommand.java
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/commands/DemoCommandsPluggable.java
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/commands/PostEventCommand.java
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/factory/HandlerFactory.java
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/handlers/CompareCondition.java
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/handlers/ConsolePrintAction.java
- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/handlers/ConsoleTrigger.java
- bundles/automation/pom.xml
This commit is releated to point 1 in: https://github.com/eclipse/smarthome/issues/2220
> Automation Demos Module Type Demo

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/widget.multiselect.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
> Multi-select validation

- bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java
> updated is called async, sync. access to broker connections

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
> Show channel description

- extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/constants.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/navigation.menu.html
fixes https://github.com/eclipse/smarthome/issues/2651
> Customizable extensions label

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
fixes https://github.com/eclipse/smarthome/issues/2560
> Rollershutter state input

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> Sonos binding: update repeat/shuffle channels for all group

- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServlet.java
> increased timeout to 15 seconds

- bundles/core/org.eclipse.smarthome.core.extension.sample/src/main/java/org/eclipse/smarthome/core/extension/sample/internal/SampleExtensionService.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/extension/Extension.java
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
fixes https://github.com/eclipse/smarthome/issues/2653
> Use extensions link

- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/config/ConfigurationService.java
fixes https://github.com/openhab/openhab2-addons/issues/1575
> correctly handle arrays and collections in ConfigurationServices

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/constants.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/navigation.menu.html
> made extension-label-customization backwards compatible

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
Reported here: https://github.com/openhab/openhab2-addons/issues/1575#issuecomment-267764262
Lost because of: https://github.com/eclipse/smarthome/pull/2650
> Lost change: placeholder text for multiselect

- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> Sonos binding: add support for Playbar line-in (enh #2410)

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
> Fixes #2604. Stop execution of rule actions on the first action fail.

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
fixes https://github.com/eclipse/smarthome/issues/2614
> Item search options

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
fixes https://github.com/eclipse/smarthome/issues/2680
> thing search option

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/discovery/ZonePlayerDiscoveryParticipant.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> Sonos binding: fix issues #2667 #2669

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/util/ConnectionValidator.java
The rule didn't update their states when module type appear.
> Fixes #2694. Problem with rules at startup.

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
fixes https://github.com/eclipse/smarthome/issues/2707
> Copy itemname to clipboard

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosXMLParser.java
> Sonos binding: fix #2710

- docs/documentation/development/bindings/xml-reference.md
> Document label and description tags for a channel (fix #2716)

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html
Partially implements https://github.com/eclipse/smarthome/issues/2702
> Order inbox entries by label and flag

- bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericThingProviderTest.groovy
- bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
...in GenericThingProvider
fixes #2740
> fix NPE in case of an empty model

- extensions/ui/org.eclipse.smarthome.ui.paper/src/main/java/org/eclipse/smarthome/ui/paper/internal/PaperUIApp.java
Implements https://github.com/eclipse/smarthome/issues/2725
> change url of Paper UI from /ui to /paperui

- docs/documentation/features/rest.md
> fixed typos

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/RuleRegistry.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
- bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/groovy/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationTest.groovy
- bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java
- bundles/automation/org.eclipse.smarthome.automation.sample.rest.api/src/main/resources/res/rules.html
- docs/documentation/features/rules.md
Also fix bug in rule normalization. Default values defined in ConfigDescritptionParameter was not normalized.
> Implements RuleRegistry.runNow(ruleId) #689

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
fixes https://github.com/eclipse/smarthome/issues/2749
> Rule running option

- bundles/core/org.eclipse.smarthome.core.id.test/pom.xml
> fixed id project name in pom

- extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightDiscoveryServiceOSGITest.groovy
...once again.
Somehow the fix from #1298 got lost.
It's defeating the
java.lang.NoSuchFieldException: http
error.
> made hue tests more robust wrt timing

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
fixes https://github.com/eclipse/smarthome/issues/2752
> Text input fixed position

- extensions/ui/org.eclipse.smarthome.ui.basic/snippets/main.html
> BasicUI: add webapp resource references, add favicon 

- extensions/ui/org.eclipse.smarthome.ui.basic/README.md
> BasicUI: visibility changes are now supported. Update README

- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlChannelTypeProvider.java
> fixed ConcurrentModificationException in XmlChannelTypeProvider

- bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/ConfigUtilTest.groovy
- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/binding/BindingResource.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/service/ConfigurableServiceResource.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
...for normalization of configuration parameters.
fixes #2698
> obey thing specific configuration descriptions

- extensions/binding/org.eclipse.smarthome.binding.yahooweather/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
...for a few seconds when using an idential query
in order to avoid hitting their limits when changing
the configuration.
fixes #2779
> caching calls to the Yahoo Weather API

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
Format dateTime items according to pattern in stateDescription.
> Basic DateTime sprintf

- extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/search.filters.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html
Implements https://github.com/eclipse/smarthome/issues/2702 except for last point.
> Refactored filters from items for inbox and things

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
related to https://github.com/eclipse/smarthome/pull/2747
> Invalid watch and empty check for discovery results

- extensions/binding/org.eclipse.smarthome.binding.yahooweather/ESH-INF/thing/thing-types.xml
- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
...in case the API returns a valid but empty result so
that items don't switch between proper values and UNDEF
anymore.
fixes #2778
> [Yahoo] made Yahoo Weather binding keep old results

- bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/EventTriggersTypeDefinition.json
- bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/RuleEnableModuleType.json
- docs/documentation/development/bindings/xml-reference.md
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
fixes https://github.com/eclipse/smarthome/issues/2764
> Support Rule context

- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java
> added org.joda.time as an implicit import to scripts and rules

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
fixes https://github.com/eclipse/smarthome/issues/2763
> Rule page ui changes

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html
fixes https://github.com/eclipse/smarthome/issues/2702#issuecomment-271862706
> Bug fix: things/inbox search on uid

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
fixes https://github.com/eclipse/smarthome/issues/2777
> Bug fix: set accpedted language in request header

- extensions/binding/org.eclipse.smarthome.binding.yahooweather/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/internal/ExpiringCache.java
...as we ran into API incompatibilities between different versions.
fixes #2800
> replace the guava cache in the Yahoo weather binding

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.addmodule.html
> select module type labels

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/groovy/org/eclipse/smarthome/binding/fsinternetradio/test/RadioServiceMock.groovy
which contained some bogus that made my build fail. 
> cleanup imports in FSInternetRadio Binding Test

- bundles/automation/org.eclipse.smarthome.automation.module.core.test/src/test/groovy/org/eclipse/smarthome/automation/module/core/internal/RuntimeRuleTest.groovy
- bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/GenericConditions.json
- bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/ItemConditions.json
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/CompareConditionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemStateConditionHandler.java
> Implements #2816 GenericCompareCondition should support <= and >=

- extensions/ui/org.eclipse.smarthome.ui.basic/README.md
- extensions/ui/org.eclipse.smarthome.ui.classic/README.md
Add sitemap information for default setting, and passing parameter in URL in the Classic and Basic UIs.
Signed-off-by:: David McWhinnie <david@mcwhinnie.ca>
> Add sitemap info for Classic and Basic UIs

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
1) Send null values no day is selected
2) Use param label as heading.
3) Bug fix: remove red line when no option is selected and required=false
> Send null when no values are selected and use param label

- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AbstractFileProvider.java
> ignore hidden files on import

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/widget.multiselect.js
fixes issue reported here https://github.com/eclipse/smarthome/issues/2820#issuecomment-273418735
> Multiselect show label

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/widget.multiselect.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
Related comment:
https://github.com/eclipse/smarthome/issues/2820#issuecomment-273521507
Known issue: Multiselect does not show always on top of other content.
> Multiselect use input value if save clicked

- bundles/automation/org.eclipse.smarthome.automation.module.media/src/main/java/org/eclipse/smarthome/automation/module/media/internal/MediaActionTypeProvider.java
> added limitToOptions=true as the REST API provides the wrong default

- bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueConfigDescriptionProvider.groovy
> removed syserr output from hue test.

- features/org.eclipse.smarthome.feature.designer/feature.xml
- products/org.eclipse.smarthome.designer.product/org.eclipse.smarthome.designer.product.product
...in order to fix the registry population with elements.
fixes #2190
> added missing model runtime bundles to designer

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
https://github.com/eclipse/smarthome/issues/2883
> DateTime fix safari

- bundles/designer/org.eclipse.smarthome.designer.core/src/main/java/org/eclipse/smarthome/designer/core/config/PluginProjectCreator.xtend
...in the dynamically created project.
fixes #2190
> prevent duplicate package imports

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
fixes https://github.com/eclipse/smarthome/issues/2885
> Refresh control page

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/widget.multiselect.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
Fixes issues reported here: https://github.com/eclipse/smarthome/issues/2820#issuecomment-273814891
> Remove checkboxes from single select dropdown

- bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/service/AbstractWatchServiceTest.groovy
> fixed AbstractWatchServiceTest to work on OSes were case matters

- bundles/model/org.eclipse.smarthome.model.persistence/OSGI-INF/persistencemanager.xml
- bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/internal/PersistenceModelManager.java
Fixes https://github.com/openhab/openhab1-addons/issues/5046
> fixes potential NPE on shutdown by moving code to activate/deactivate methods

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
Initialization of ThingHandlers happens in the following order:
* Thing -> INITIALIZING
* BaseThingHandler gets the callback injected
* ThingHandler.initialize()
* Thing -> ONLINE/OFFLINE/UNKNOWN
The shudown however so far first removed the callback, and then called
ThingHandler.destroy(). As a result, the ThingHandler did not get the
chance to clean up first and could run into situations where it
tried to e.g. send events but the callback was already missing.
Hence the shudown process with this change becomes the exact reverse:
* Thing -> UNITIALIZED (so that it's not used anymore)
* ThingHandler.destroy()
* BaseThingHandler gets the callback "un"injected
* Thing -> UNINITIALIZED (HANDLER_MISSING)
fixes #2757
fixes #1338
> ThingHandler shutdown symmetric to initialization

- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
Added correct status code doc and add doc for sync/async deletion.
Signed-off-by: Sebastian Janzen <sebastian.janzen@innoq.com>
> Fix swagger doc: Thing Deletion

- bundles/core/org.eclipse.smarthome.core.extension.sample/src/main/java/org/eclipse/smarthome/core/extension/sample/internal/SampleExtensionService.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/extension/Extension.java
i.e.
* description
* image link
* background color
which are all optional.
implements #2922
> enhance Extension by additional properties

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js
fixes https://github.com/eclipse/smarthome/issues/2918
> Check for existing discoveryResults before adding

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
Fixes https://community.openhab.org/t/rules-not-working/20907/13
> Fixed logging statement

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
fixes https://github.com/eclipse/smarthome/issues/2884
> Masonry method call missing

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
fixes https://github.com/eclipse/smarthome/issues/2556#issuecomment-272153460
> use parameter.pattern in input and show error messages

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
fixes https://github.com/eclipse/smarthome/issues/2911
> Use channelTypeUID for channel types comparison

- distribution/smarthome/conf/persistence/logging.persist
> fixed example persist file

- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java
- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/normalization/NormalizerFactory.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/QueueingThreadPoolExecutor.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
See : https://github.com/eclipse/smarthome/pull/2440#pullrequestreview-19833425
Found by static code analysis tool.
> Replaced throwing NPE with IllegalArgumentException

- extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/DeviceHandler.java
- extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/structure/scene/sceneEvent/EventListener.java
See https://github.com/eclipse/smarthome/pull/2440#pullrequestreview-19833425
Found by static code analysis tool.
> Fix broken or missplaced null checks

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateProgressInfo.java
- extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/BridgeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java
See https://github.com/eclipse/smarthome/pull/2440#pullrequestreview-19833425
Found by static code analysis tool.
> Fixes incorrect comparison of objects.

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Rule.java
> Rule Class: typo fix

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java
> added state descriptions to some system channels

- bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtilTest.java
- bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/test/ConfigurationTest.groovy
- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java
- bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/inbox/InboxOSGITest.groovy
> Fix normalization of Number values. #2937

- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelGroupDefinition.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingTypeResource.java
- docs/documentation/development/bindings/xml-reference.md
> Label and description added for channel groups

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingTypeProvider.java
Corrected a tiny little typo in the Javadoc for ThingTypeProvider.
> Corrected a tiny little typo in the Javadoc for ThingTypeProvider.

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
> distinguish warnings where a handler might be hanging

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
fixes https://github.com/eclipse/smarthome/issues/2923
> Added card layout to extensions page

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
...when initializing Things.
fixes #2986
> remove double-wrapped safe method calling from ThingManager

- docs/documentation/development/bindings/docs.md
> added information about formatting requirements for Jekyll

- docs/documentation/development/guidelines.md
> added guidelines for logging

- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java
- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/console/InboxConsoleCommandExtension.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/RESTCoreActivator.java
> Fixed small bugs found by findbugs

- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/factory/ScriptModuleHandlerFactory.java
- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/handler/ScriptActionHandler.java
I would like to use an unique identifier in my rule scripts.
IMHO the rule UID could be a good one as it is unique per rule per definition.
What do you think about?
> inject the rule UID to the rule context 'ctx'

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> Sonos: fix #2998

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.inbox.html
> Wrong margin on inboxContainer

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
fixes https://github.com/eclipse/smarthome/issues/3010
> Send only one request per thingType on control page

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java
The discovery information was reported here:
https://community.openhab.org/t/internet-radio-i-need-your-help/2131
Signed-off-by: Patrick Koenemann <koenemann@itemis.de>
> [FS Internet Radio Binding]: discover information for further radios.

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
> Bug fix: Masonry ordering only applied to first tab

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
> Set extension cards width for medium and small devices

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/template/RuleTemplateRegistry.java
> Fix #3050 missing label and descrpion of trigger

- README.md
> adapted readme to Java 8 and the removed designer

- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AbstractFileProvider.java
> deactivate the WatchService-s when the provider.file bundle is uninstalled

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
fixes https://github.com/eclipse/smarthome/issues/3057
> Tabs issue on 4k screens

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/layout.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/dialog.ruletemplate.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
Not to be merged yet.
fixes https://github.com/eclipse/smarthome/issues/3027
> Extensions page in rules

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
> Call masonry only when cards are shown

- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
fixes https://github.com/eclipse/smarthome/issues/3087
> Load image item from item state endpoint

- bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/ModuleTypeResource.java
> Return action module types

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
> Hide dialog on thing remove failure

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/search.filters.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
> Clear type filter on group selection in items list

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
> Fixes #3050 Cannot create rule based on template

- docs/documentation/development/bindings/xml-reference.md
Fixes https://github.com/eclipse/smarthome/issues/3054
> Parameter context docs updated

- bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/validation/test/ConfigDescriptionValidatorTest.groovy
- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/MinMaxValidator.java
- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/PatternValidator.java
- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/internal/TypeIntrospections.java
> Change max / min value types to Object (for better handling of floats)

- extensions/transform/org.eclipse.smarthome.transform.jsonpath/README.md
- extensions/transform/org.eclipse.smarthome.transform.map/README.md
- extensions/transform/org.eclipse.smarthome.transform.regex/README.md
- extensions/transform/org.eclipse.smarthome.transform.xslt/README.md
> Fixes for transformation readmes

- docs/pom.xml
- extensions/binding/org.eclipse.smarthome.binding.digitalstrom/README.md
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md
- extensions/binding/org.eclipse.smarthome.binding.hue/README.md
- extensions/binding/org.eclipse.smarthome.binding.lifx/README.md
- extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
- extensions/binding/org.eclipse.smarthome.binding.sonos/README.md
- extensions/binding/org.eclipse.smarthome.binding.wemo/README.md
- extensions/binding/org.eclipse.smarthome.binding.yahooweather/README.md
- extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.md
- extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.sh
- extensions/ui/org.eclipse.smarthome.ui.basic/README.md
- extensions/ui/org.eclipse.smarthome.ui.classic/README.md
- extensions/ui/org.eclipse.smarthome.ui.paper/README.md
- extensions/voice/org.eclipse.smarthome.voice.mactts/README.md
- tools/archetype/binding/src/main/resources/archetype-resources/README.md
Related to https://github.com/openhab/openhab-docs/pull/355
> Move Jekyll preamble to doc build process (out of source files)

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js
fixes https://github.com/eclipse/smarthome/issues/3108
> Parsefloat instead if int

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.rules.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
fixes https://github.com/eclipse/smarthome/issues/3110
> Hide rule from catalog entry if no rule extensions exist

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
PaperUI is showing months in the range 0-11 instead of 1-12.
> Wrong month formatting

- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/CoreModuleHandlerFactory.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/RuleEnablementActionHandler.java
> Fix RuleEnablementHandler name

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java
@maggu2810 Can you give this a go? The adjusted test is not yet in the repo, hence I could not do the automated test, but I have manually tested the expressions you reported as faulty and they yield the correct output over here
> Fix https://github.com/eclipse/smarthome/issues/3132

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java
Improve the Cron Expression tests.
Related to: #3132
> improve cron expression tests

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/ActionTypeDTOMapper.java
- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/CompositeActionTypeDTO.java
- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/CompositeConditionTypeDTO.java
- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/CompositeTriggerTypeDTO.java
- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/ConditionTypeDTOMapper.java
- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/dto/TriggerTypeDTOMapper.java
- bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/ModuleTypeResource.java
> Extends Module Type DTOs with Composites

- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AbstractFileProvider.java
> fixes bug when ignoring hidden files

- bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
> Basic UI: fix update of group label with count (fix #3141)

- extensions/extensionservice/org.eclipse.smarthome.extensionservice.marketplace/src/main/java/org/eclipse/smarthome/extensionservice/marketplace/internal/MarketplaceProxy.java
> fixed retry mechanism for marketplace proxy

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> fixes some potential NPEs

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/rules.html
fixes https://github.com/eclipse/smarthome/issues/3158
> Set max width for extension label

- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java
...as correctly pointed out in #3169
relates to #3169
> reduced number of function calls

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.groovy
Our CI just found another funny little race condition...
> fix ThingManagerOSGiTest to wait for the correct event

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> reduced log level as this can occur in "normal" OFFLINE situations

- bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AbstractFileProvider.java
> Fix template resolution when template appears after rule creation.

- extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/servlet/WebAppServlet.java
> check the existence of the subscription

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
fixes https://github.com/eclipse/smarthome/issues/3187
> Extensions search on label and id field

- bundles/core/org.eclipse.smarthome.core.audio.test/.classpath
- bundles/core/org.eclipse.smarthome.core.audio.test/.settings/org.eclipse.jdt.groovy.core.prefs
- extensions/binding/org.eclipse.smarthome.binding.ntp.test/.classpath
- extensions/binding/org.eclipse.smarthome.binding.wemo.test/.classpath
> add groovy DSL support to classpath

- bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java
> Fix REST command PUT to use rule UID in the path. Solves #3203

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/RuleRegistry.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
- bundles/automation/org.eclipse.smarthome.automation.module.core.test/src/test/groovy/org/eclipse/smarthome/automation/module/core/internal/RunRuleModuleTest.groovy
- bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/RunRuleAction.json
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/factory/CoreModuleHandlerFactory.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/RunRuleActionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/RunRuleHandler.java
Implementation for issue:  "create a RunRuleAction #2964"
> Added RunRuleAction for AutomationComponent

- bundles/core/org.eclipse.smarthome.core.audio.test/.settings/org.eclipse.jdt.groovy.core.prefs
> set groovy compiler level to "I don´t care"

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
This PR consists of three parts:
1. it allows ModuleHandlerFactories to be initially empty. Before this PR, the factories are ignored even if they have types as it was not initially added to `moduleHandlerFactories`.
2. it reduces the iterations as instead of iterating multiple times over the same ModuleHandlerFactory,  each ModuleHandlerFactory is only asked once.
3. it allows explicitly updating the ModuleType by providing oldElement=null
> allow initially empty modulehandlerfactories

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
This adds handling of read-only parameters on inputs.
> Handle read-only parameter inputs in PaperUI

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
This updates PaperUI to allow editing of thing configuration parameters which is currently not possible.
> Fix PaperUI to allow editing of thing parameters

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/Constants.groovy
- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareRegistryOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/Firmware.java
> added properties for firmware domain object

- features/karaf/esh-core/src/main/feature/feature.xml
The latest changes of the automation.module.media bundle add a
dependency to the automation script module.
Related commit: c454d98995b352b8459bca0b3e1b90755e4cf2a8
Related PR: #3147
> fix automation module media feature

- features/karaf/verify/pom.xml
> enable feature verification

- features/karaf/verify/pom.xml
Related to: https://github.com/eclipse/smarthome/pull/3229#issuecomment-293477989
> add additional third party repos to feature verification only

- bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/groovy/org/eclipse/smarthome/config/setup/test/discovery/DiscoveryServiceRegistryOSGITest.groovy
- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java
- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/console/DiscoveryConsoleCommandExtension.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioManagerImpl.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/SafeMethodCaller.java
- bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/ConsoleInterpreter.java
- bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/exec/ExecUtil.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/DiscoveryResource.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
- bundles/io/org.eclipse.smarthome.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/internal/async/BlockingAsyncContextDelegateProvider.java
- bundles/model/org.eclipse.smarthome.model.script.runtime/src/org/eclipse/smarthome/model/script/runtime/internal/engine/ScriptImpl.java
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/internal/actions/TimerImpl.java
- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java
- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java
- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCurrentStateUpdater.java
- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightOnlineStateUpdater.java
- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightStateChanger.java
- extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/fields/MACAddress.java
- extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
- extensions/transform/org.eclipse.smarthome.transform.javascript/src/main/java/org/eclipse/smarthome/transform/javascript/internal/JavaScriptTransformationService.java
- extensions/transform/org.eclipse.smarthome.transform.jsonpath/src/main/java/org/eclipse/smarthome/transform/jsonpath/internal/JSonPathTransformationService.java
- extensions/transform/org.eclipse.smarthome.transform.map/src/main/java/org/eclipse/smarthome/transform/map/internal/MapTransformationService.java
- extensions/transform/org.eclipse.smarthome.transform.scale/src/main/java/org/eclipse/smarthome/transform/scale/internal/ScaleTransformationService.java
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
> Corrected some spelling error occured => occurred

- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
> aligned the API doc for the thing resource

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/RuleRegistry.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/RunRuleActionHandler.java
> RunRule with passing context

- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioFormat.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/FileAudioStream.java
> Audio: OGG and AAC formats added

- bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
There are feedback after this PR is merged https://github.com/eclipse/smarthome/pull/3001
This new PR is to address those feedback.
Bug: https://github.com/eclipse/smarthome/issues/1654
Signed-off-by: kceiw <hellomao@outlook.com>
> Address PR feedback

- bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/discovery/MDNSDiscoveryService.java
- extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
> MDNSDiscovery and HueNupnpDiscovery must be started asynchronous

- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
> Changed manual character replacement to java.net.URLEncoder

- bundles/core/org.eclipse.smarthome.core.audio.test/AudioOSGiTest.launch
- bundles/core/org.eclipse.smarthome.core.audio.test/pom.xml
- bundles/core/org.eclipse.smarthome.core.audio.test/src/test/groovy/org/eclipse/smarthome/core/audio/test/AudioOSGiTest.groovy
Property org.osgi.service.http.port renamed to jetty.home.
Fixes #3239
> Changed the port for Audio tests.

- bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
fixes #3128 and fixes openhab/openhab2-addons#1949
> Trigger Rule with multiple EventTriggers only for matching channel/event

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/ThingConsoleCommandExtension.java
> Fix renaming trigger-channel compilation error

- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/ScriptExecution.java
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/internal/actions/TimerExecutionJob.java
Ported from PR 1436 on openhab1-addons.This will add the createTimerWithArgument to be used in ESH and downstream in OH2.
@berndpfrommer - your code lives on!
> Closes #2718 - Add createTimerWithArgument to ESH

- docs/documentation/development/guidelines.md
...as I noticed that the documentation still has a restriction to java 7
> updated language levels in development guidelines

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/ThingConsoleCommandExtension.java
unsetsetEventPublisher -> unsetEventPublisher
relates to #3268
> fixed method name in ThingConsoleCommandExtension

- features/org.eclipse.smarthome.feature.runtime.binding/feature.xml
> added astro binding to p2 feature/repo

- docs/documentation/development/guidelines.md
> Remove Java5 code style restriction for Automation module.

- bundles/config/org.eclipse.smarthome.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java
- bundles/model/org.eclipse.smarthome.model.core.test/src/test/groovy/org/eclipse/smarthome/model/core/internal/folder/test/FolderObserverTest.groovy
- bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java
> Ignore hidden configuration files

- bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
> schedule timers for each cron expression

- bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java
> Catch NPE and do proper logging.

- bundles/ui/org.eclipse.smarthome.ui.test/META-INF/MANIFEST.MF
- bundles/ui/org.eclipse.smarthome.ui.test/org.eclipse.smarthome.ui.test.launch
- bundles/ui/org.eclipse.smarthome.ui.test/pom.xml
- bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
* fixed mockito dependencies
* added launch config
* included the tests in the maven build
* fixed a test
* fixed the behaviour when an item could not be found
> reactivated UI tests

- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
Do not set Thing to ONLINE before it is fully initialized.
> Yahoo improvements

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/ThingConsoleCommandExtension.java
> OSGI Console: ability to trigger channel with null event

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
Fixes https://github.com/eclipse/smarthome/issues/3257
> Use pattern in rollershutter state text

- bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
> Trigger rules without specific event on any event

- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/DialogProcessor.java
fixes https://github.com/eclipse/smarthome/issues/3347
> changed default of processing flag to false

- bundles/model/org.eclipse.smarthome.model.item.tests/src/org/eclipse/smarthome/model/item/tests/GenericItemProviderTest.groovy
- bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java
> Create ItemAddedEvents only for items within current file, not all item files

- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/KSpottedEvent.java
Closes #3348, as discussed.
Signed-off-by: Yannick Schaus <eclipse@schaus.net>
> Remove AudioSource from KSpottedEvent

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
fixes https://github.com/eclipse/smarthome/issues/2871
> Handle item add/update/remove events

- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/RuleSupportScriptExtension.java
...as discussed in #3361
relates to #3361
> reverted default scope in scripted rule support again

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java
> Re-added accidentially removed constructor

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java
> Soft fallback to plain GroupItem instead of IllegalArgumentException

- bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
> UI: "[]" at end of label to disable the display of value

- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/shared/RuleSupportRuleRegistryDelegate.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Registry.java
- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
This change enables usage of Predicates for filtering.
Signed-off-by: Victor Toni <victor.toni@gmail.com>
> Added Stream access to elements of registries.

- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java
- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SelectionRenderer.java
> Classic UI: mapped value displayed for a selection

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
If the cover art size is unknown or bigger than 500000 bytes, it is not downloaded and the image channel is set to UNDEF.
> Sonos binding: don't download too big or unknown sized cover arts

- features/karaf/esh-tp/src/main/feature/feature.xml
Related to: https://github.com/eclipse/smarthome/pull/1857#issuecomment-299477230
> add measurement feature to target platform

- third-party/pom.xml
See: https://github.com/jayway/JsonPath/issues/88
See: http://stackoverflow.com/questions/36964936/array-size-using-jsonpath-expression-stefan-goessner-jsonpath/36967669#36967669
Signed-off-by: Christian Häussler <c-n-i@web.de>
> Update to jsonpath 2.2.0

- bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/JsonStorage.java
Signed-off-by: Patrick Gottschaemmer <mail@gottschaemmer.net>
> look for jsondb backup files if a .json file is missing

- bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/GroupItemTest.groovy
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java
> A group without a function cannot have a state

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html
> Rearrange cards on search text change

- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/i18n/ConfigI18nLocalizationService.java
> fix verify in config description parameter localization

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/groovy/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerOSGiTest.groovy
All 'assertThat item.getState() is UnDefType.NULL' are removed since they cannot always be true.
see: https://github.com/eclipse/smarthome/issues/3377
Some small adaptions are made.
> Incorrect assertions are removed from FSInternetRadioHandlerOSGiTest.

- extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueBridgeHandlerOSGiTest.groovy
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueConfigStatusMessage.java
See https://github.com/openhab/openhab2-addons/pull/2009/files#r111239598
> simplified code by using normal constants instead of an enum

- docs/documentation/development/bindings/thing-definition.md
> added infos on the expected granularity of channel types

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java
> Add support for AUNA Connect 150 Radio

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/HSBTypeTest.java
- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java
- bundles/model/org.eclipse.smarthome.model.persistence.tests/src/test/java/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensionsTest.java
- extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java
...that I found throughout the code base.
Some were left in test cases from previous bug-huntings hence I simply deleted them. Others slipped through, so I turned them into log statements.
> [Housekeeping] cleaning up some System.???.println

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/delegates/SimpleActionHandlerDelegate.java
- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java
- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptEngineManagerImpl.java
> improved logging and naming of scripted rule support

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers/controller.firmware.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.firmware.html
* rename firmware update methods to installFirmware
* fixes #3432
> Fix Thing update in PaperUI

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/LinkConsoleCommandExtension.java
- bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/ItemConsoleCommandExtension.java
> Make help for console commands items, links, things consistent again

- extensions/ui/org.eclipse.smarthome.ui.classic/snippets/group.html
- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/GroupRenderer.java
> Classic UI: icon for group depending on state

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
as discussed here https://github.com/eclipse/smarthome/issues/1700#issuecomment-289928566
> Removes slider from number item on control page

- docs/documentation/concepts/items.md
Signed off by: Nikolay Kristev (n.kristev@prosyst.com)
> Comment on UpDownType usage in Rollershutter item (#3297)

- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/BundleProcessorVetoManager.java
> fix synchronization issue in BundleProcessorVetoManager

- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
> RollerShutter items are Sitemap-Switches but need PercentType state

- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
> terminate the scheduler upon deactivation

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceOSGiTest.groovy
> fix default locale configuration in firmware tests

- bundles/io/org.eclipse.smarthome.io.console/OSGI-INF/ItemConsoleCommandExtension.xml
- bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/ItemConsoleCommandExtension.java
> Added ConsoleCommand for adding/removing tags to/from items

- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
> Fixes #3459. WeMo Insight, register for additional UPnP events

- bundles/model/org.eclipse.smarthome.model.core.test/src/test/groovy/org/eclipse/smarthome/model/core/internal/folder/test/FolderObserverTest.groovy
> fix typo in FolderObserverTest

- bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/AutomationResourceBundlesEventQueue.java
- bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/HostFragmentMappingUtil.java
> Prevent NPE for PackageAdmin when uninstall automation bundles #3334

- bundles/io/org.eclipse.smarthome.io.rest.test/src/test/groovy/org/eclipse/smarthome/io/rest/test/filter/SatisfiableResourceFilterTest.groovy
- bundles/io/org.eclipse.smarthome.io.rest/OSGI-INF/satisfiableresourcefilter.xml
- bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/filter/SatisfiableResourceFilter.java
Repairs problems created by PRs #3436 #3452
> Readded and adapted SatisfiableResourceFilter

- bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
> Fix #2902 for Basic UI

- bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttSenderChannel.java
- bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttBrokerConnection.java
> An Interface method should not allow for throwing a generic Exception

- bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
> BasicUI: Treat Switch on NumberItem not as ON/OFF Switch

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/CoreItemFactoryTest.java
Adds a test case in addition to #3507.
> Add CoreItemFactoryTest

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
fixes https://github.com/eclipse/smarthome/issues/3516
> Bug fix: things not showing on control page

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/utility.js
fixes https://github.com/eclipse/smarthome/issues/3518
> Use % sign as default for dimmer items

- bundles/core/org.eclipse.smarthome.core.voice/ESH-INF/config/config.xml
- bundles/core/org.eclipse.smarthome.core.voice/OSGI-INF/VoiceManager.xml
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/VoiceManager.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/DialogProcessor.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java
Implments #3450.
Signed-off-by: Yannick Schaus <eclipse@schaus.net>
> Voice: send feedback to an item when listening for a command

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ItemUtil.java
null is not an accepted type so convert it to an accepted type
Overcomes NPE's in a places where the state is broadcasted to
Fixes #3520
> null is not an accepted type so convert it to an accepted type

- extensions/ui/org.eclipse.smarthome.ui.paper/.gitignore
- extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
- extensions/ui/org.eclipse.smarthome.ui.paper/karma.conf.js
- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configuration.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/tests/setup.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
> Fixed PaperUI tests + added test task to dev and prod mode

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
fixes https://github.com/eclipse/smarthome/issues/3519
> Send percent values for brightness

- features/karaf/esh-ext/src/main/feature/feature.xml
Related to https://github.com/eclipse/smarthome/pull/3140#issuecomment-300227905
> updated jsonpath to 2.2.0

- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java
> improves rule and module id definition os scripted rules

- targetplatform/smarthome.target
> removed specific version, but use what the p2 repo contains

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceOSGiTest.groovy
...wrt service registration
fixes #3533
> increased timing tolerance in firmware test

- features/karaf/esh-ext/src/main/feature/feature.xml
- targetplatform/smarthome.target
A follow-up on #3541. Let's see if Travis still has issues.
> changed back to jsonpath 2.0.0, added 3rd party sources and increased tp sequence no

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ColorItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/DimmerItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/RollershutterItem.java
Fixes #3520
Fixes #3530
Fixes #3539
> If state conversion fails use original value instead of null

- bundles/automation/org.eclipse.smarthome.automation.module.media/src/main/java/org/eclipse/smarthome/automation/module/media/internal/MediaScriptScopeProvider.java
- bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope/src/main/java/org/eclipse/smarthome/automation/module/script/defaultscope/internal/DefaultScriptScopeProvider.java
- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/RuleSupportScriptExtension.java
- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/ScriptExtensionProvider.java
- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptExtensionManager.java
Fixes: https://github.com/eclipse/smarthome/issues/3551
> fix case of 'unload' method

- bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/AbstractResourceBundleProvider.java
> replaced printStackTrace by proper logging

- extensions/transform/org.eclipse.smarthome.transform.jsonpath/META-INF/MANIFEST.MF
- features/karaf/esh-ext/src/main/feature/feature.xml
- targetplatform/smarthome.target
fixes https://github.com/eclipse/smarthome/issues/3548
> updated smart.target to include latest additions (jsonpath 2.1 and californium libs)

- bundles/model/org.eclipse.smarthome.model.script/OSGI-INF/scriptitemrefresher.xml
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/jvmmodel/ScriptItemRefresher.java
...which occasionally happened during shutdown.
While torturing the model runtime a little during analysis of #3563 I got this little friend here.
> fixed NPE in ScriptItemRefresher

- bundles/model/org.eclipse.smarthome.model.rule.runtime/OSGI-INF/runtime.xml
...as it effectively _is_ dependending on it (via scripts).
fixes #3562
> made rule model runtime dependent on the ScriptServiceUtil

- extensions/binding/org.eclipse.smarthome.binding.hue/README.md
Fixes #3573
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
> [HUE] Add configuration examples for Alert & Effect

- extensions/ui/org.eclipse.smarthome.ui.basic/snippets/chart.html
- extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ChartRenderer.java
> Basic UI: fix refresh of charts

- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
> Passed wrong identifier to ScriptEngine

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
> decrease severity of expected log message in ThingManager

- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptEngineManagerImpl.java
> Inform the user that a script module was successfully loaded

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAudioSink.java
> [sonos] Exchanged file extensions to existing constants

- bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java
- bundles/model/org.eclipse.smarthome.model.script/OSGI-INF/scriptserviceutil.xml
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/ScriptServiceUtil.java
In another attempt to hunt down #3562 I would like to suggest some additional logging which we can happily remove again once the issue got resolved.
> additional logging for ScriptServiceUtil

- extensions/binding/org.eclipse.smarthome.binding.wemo/ESH-INF/thing/thing-types.xml
- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/WemoBindingConstants.java
- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/discovery/WemoDiscoveryParticipant.java
- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoCoffeeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/internal/WemoHandlerFactory.java
> Closes #3345 - implement WeMo Coffee Maker

- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/GenericScriptEngineFactory.java
- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptEngineManagerImpl.java
> Inform the user only once for each loaded script engine

- bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/validation/SitemapValidator.xtend
> Use correct feature on error message so the correct message is shown

- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/servlet/WebAppServlet.java
> Classic UI: fix dynamic widget visibility and dynamic update of the page title

- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java
> Do not scan for lights if bridge is offline

- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java
> Add 2D as new chart period

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
fixes https://github.com/eclipse/smarthome/issues/3591
> Hide unavailable service error on rule page

- extensions/ui/org.eclipse.smarthome.ui.basic/snippets/sitemaps_list_empty.html
Resolves https://github.com/openhab/openhab-core/issues/118
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de>
> Clarify sitemaps list empty hint

- extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/parameterDescription.css
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers/controller.configurableService.dialog.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/directives/directive.parameterDescription.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/directive.parameterDescription.html
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html
> Reimplement ellipsis of parameter description.

- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
- extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/internal/connection/YahooWeatherConnection.java
Adresses the [comment](https://github.com/eclipse/smarthome/pull/3628/files#r121476711) from @martinvw in PR #3628.
> [Yahoo] Corrected some wrong uses of final and static

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
fixes https://github.com/eclipse/smarthome/issues/3620
> Mark all parameters advance if group is advance

- extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/channels.xml
- extensions/binding/org.eclipse.smarthome.binding.astro/README.md
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/calc/SunCalc.java
> Correction to Issue #3569

- bundles/model/org.eclipse.smarthome.model.script.tests/META-INF/MANIFEST.MF
See https://www.eclipse.org/forums/index.php/t/1086799/
> added missing dependency to slf4j

- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java
> [Hue] handle authentication failures during scan gracefully

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java
> fix latitude calculation in PointType

- bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
The object types simply did not match!
> fix map access in (old) rule engine

- bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandExport.java
- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/delegates/SimpleConditionHandlerDelegate.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingStatusInfoI18nLocalizationService.java
- bundles/io/org.eclipse.smarthome.io.rest.log/src/main/java/org/eclipse/smarthome/io/rest/log/internal/LogHandler.java
- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java
> fixed some happy little accidents

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js
> [PaperUI] provide group functions for Contact base item

- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
> PaperUI: Ignore unknown parameter context

- bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java
> avoid NPE if no service is found

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
also: reformat control HTML.
Fixes #3630.
> PaperUI: render all channel links

- bundles/config/org.eclipse.smarthome.config.discovery.test/META-INF/MANIFEST.MF
- bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/java/org/eclipse/smarthome/config/discovery/internal/PersistentInboxTest.java
- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java
> normalize config on inbox approval using the config description

- bundles/io/org.eclipse.smarthome.io.net/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
Sonos binding: download of cover art updated
Fix #3448 
> Utils to download WEB image

- bundles/ui/org.eclipse.smarthome.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/AbstractResourceIconProvider.java
> Icon servlet: take care of the case + additional debug log

- tools/archetype/binding.test/src/main/resources/archetype-resources/.classpath
- tools/archetype/binding.test/src/main/resources/archetype-resources/META-INF/MANIFEST.MF
- tools/archetype/binding.test/src/main/resources/archetype-resources/build.properties
- tools/archetype/binding.test/src/main/resources/archetype-resources/src/test/java/__bindingIdCamelCase__OSGiTest.java
- tools/archetype/binding/src/main/resources/archetype-resources/cfg/__bindingId__.cfg
> fixed a few issues in the archetypes

- extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
...or did I miss any special reason for having it? 
> [tradfri] remove double-slash from url

- bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/JSONResponse.java
> Dont use GSON API from version 2.5

- features/karaf/esh-tp/src/main/feature/feature.xml
> remove gson provider from karaf features

- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/handler/AstroThingHandler.java
> added doPriviledged to executor shutdown

- features/karaf/esh-tp/src/main/feature/feature.xml
> upgraded to latest JmDNS 3.5.2 patch release

- extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/internal/NtpHandlerFactory.java
> Remove unnecessary localeProviderHolder from NTP Binding

- extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/config/config.xml
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/calc/SunCalc.java
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/config/AstroThingConfig.java
> Remove altitude parameter from astro binding

- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/GroupRenderer.java
- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SelectionRenderer.java
- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SetpointRenderer.java
- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/TextRenderer.java
> Classic UI: escape characters for item state in icon URL for text widget

- bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/scheduler/CronHelperTest.groovy
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronHelper.java
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/handler/AstroThingHandler.java
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/Job.java
> Astro-Binding performance improvements and bug fix

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java
> fix concurrent modification of expressionParts in AbstractExpression

- extensions/binding/org.eclipse.smarthome.binding.astro/README.md
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/discovery/AstroDiscoveryService.java
> improved readme and logging

- bundles/core/org.eclipse.smarthome.core/ESH-INF/config/i18n.xml
> Location parameter: added format info and example, just like the other parameters

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/groovy/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerOSGiTest.groovy
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/handler/FSInternetRadioHandler.java
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadio.java
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java
Removed unused method.
Added test case.
Fixes: #3711
> Reuse same instance of HttpClient in FSInternetRadio

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java
Signed-off-by: Mark Herwege <mark.herwege@telenet.be>
> Added methods to find broadcastAddress(es), useful in bindings for discovery.

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheMapTest.java
- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheMap.java
> [core] Added "containsKey" method for ExpiringCacheMap

- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/test/SystemWideChannelTypesTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/SystemChannels.bundle/ESH-INF/i18n/SystemChannels_de.properties
- bundles/core/org.eclipse.smarthome.core.thing/ESH-INF/i18n/DefaultSystemChannels_de.properties
- bundles/core/org.eclipse.smarthome.core.thing/META-INF/MANIFEST.MF
- bundles/core/org.eclipse.smarthome.core.thing/OSGI-INF/DefaultSystemChannelTypeProvider.xml
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java
* Added german translations
Closes #3623 
> [core] Added support for translating default system channels

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Rule.java
- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/Template.java
- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ModuleType.java
- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/ChangeThingTypeOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/link/ItemChannelLinkOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/link/LinkEventOSGiTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/LinkConsoleCommandExtension.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/AbstractLink.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/AbstractLinkRegistry.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLink.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemThingLink.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ManagedItemChannelLinkProvider.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ManagedItemThingLinkProvider.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/LinkEventFactory.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractManagedProvider.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/DefaultAbstractManagedProvider.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Identifiable.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/ManagedProvider.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Registry.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/UniqueIdProvider.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/Item.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/link/ItemChannelLinkResource.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
Related to: https://github.com/eclipse/smarthome/pull/3670#discussion_r123556157
> add Identifiable interface - used by Registry and Provider

- bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java
> Improved formatting of position of validation errors

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Identifiable.java
Related to: https://github.com/eclipse/smarthome/pull/3762#discussion_r124725109
> fix outdated JavaDoc

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/storage/DeletableStorage.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/storage/DeletableStorageService.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/storage/DisposableStorage.java
- bundles/storage/org.eclipse.smarthome.storage.mapdb/OSGI-INF/mapdbstorage.xml
- bundles/storage/org.eclipse.smarthome.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/MapDbStorage.java
- bundles/storage/org.eclipse.smarthome.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/MapDbStorageService.java
> deletable storage, return set instead view

- bundles/test/org.eclipse.smarthome.magic.test/src/test/java/org/eclipse/smarthome/magic/binding/internal/MagicServiceImplTest.java
Related to: https://github.com/eclipse/smarthome/pull/3761#issuecomment-312215056
@sjka Can you have a look at?
> fix failing tests

- bundles/core/org.eclipse.smarthome.core.audio.test/src/test/groovy/org/eclipse/smarthome/core/audio/test/AudioManagerTest.groovy
- bundles/core/org.eclipse.smarthome.core.audio.test/src/test/groovy/org/eclipse/smarthome/core/audio/test/fake/AudioSinkFake.groovy
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioSink.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/UnsupportedAudioStreamException.java
- bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioManagerImpl.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/DialogProcessor.java
- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAudioSink.java
- extensions/io/org.eclipse.smarthome.io.javasound/src/main/java/org/eclipse/smarthome/io/javasound/internal/JavaSoundAudioSink.java
- extensions/io/org.eclipse.smarthome.io.webaudio/src/main/java/org/eclipse/smarthome/io/webaudio/internal/SSEAudioSink.java
> [audio] Added getSupportedStreams() and UnsupportedAudioStreamException

- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java
> added rules by scripts should always have a UID

- bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/OSGI-INF/ScriptedRuleProvider.xml
> Correct package name of ScriptedRuleProvider

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateService.java
> Reduce severity of FirmwareUpdateHandler Info to trace

- bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java
Signed-off-by: Andreas Reinhardt <andreas.reinhardt@novatec-gmbh.de>
> Fix MIME type detection of JPEG files (#3673)

- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/discovery/InboxResource.java
> Set content type application/json for /rest/inbox

- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/channels.xml
> Hue: fix #3805

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/CallItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ColorItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ContactItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/DateTimeItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/DimmerItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ImageItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/LocationItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/NumberItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/PlayerItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/RollershutterItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/StringItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/SwitchItem.java
> Better debug output if framework tries to set a wrong state

- extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/AbstractWidgetRenderer.java
> Basic UI: little optimization in backend

- bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/channel-types.xml
- bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml
- bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/MagicBindingConstants.java
- bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicContactHandler.java
- bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactory.java
This adds a contact sensor thing on the Magic bundle for UI tests.
> Magic Bundle: add basic contact sensor Thing

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/StringListTypeTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringListType.java
It'd be really nice to be able to pass a List<String> to construct a
StringListType. A parameterized array is great for testing but not
that useful in real life.
Signed-off-by: Jason Holmes <holmes.j@gmail.com>
> Simplify construction of StringListType(s)

- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/interpreter/ScriptInterpreter.xtend
> script interpreter gracefully handling null result

- bundles/core/org.eclipse.smarthome.core.extension.sample/src/main/java/org/eclipse/smarthome/core/extension/sample/internal/SampleExtensionService.java
> fixed potential ArrayIndexOutOfBoundsException in case index is -1

- docs/_includes/documentation-menu.html
> added missing bindings to the documentation menu

- extensions/binding/org.eclipse.smarthome.binding.lirc/.classpath
- extensions/binding/org.eclipse.smarthome.binding.lirc/ESH-INF/thing/bridge.xml
- extensions/binding/org.eclipse.smarthome.binding.lirc/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.lirc/OSGI-INF/LIRCHandlerFactory.xml
- extensions/binding/org.eclipse.smarthome.binding.lirc/README.md
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/LIRCBindingConstants.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/handler/LIRCBridgeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/handler/LIRCRemoteHandler.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/LIRCHandlerFactory.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/LIRCMessageListener.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/LIRCResponseException.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/config/LIRCBridgeConfiguration.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/config/LIRCRemoteConfiguration.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/connector/LIRCConnector.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/connector/LIRCEventListener.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/connector/LIRCStreamReader.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/discovery/LIRCRemoteDiscoveryService.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/messages/LIRCButtonEvent.java
- extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/messages/LIRCResponse.java
- features/karaf/esh-ext/src/main/feature/feature.xml
- features/org.eclipse.smarthome.feature.runtime.binding/feature.xml
* minor follow-ups from #2537
* fixed license headers
* added features
> LIRC binding follow-up

- bundles/automation/org.eclipse.smarthome.automation.module.core/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ChannelEventTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/GenericEventTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemCommandTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemStateTriggerHandler.java
As discussed [here](https://github.com/eclipse/smarthome/pull/3804#pullrequestreview-50601832)
> use new HashMap<>() instead of Maps.newHashMap()

- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/.classpath
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/.project
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/binding/binding.xml
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/thing/thing-types.xml
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/OSGI-INF/WeatherUndergroundHandlerFactory.xml
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/about.html
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/build.properties
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/pom.xml
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/WeatherUndergroundBindingConstants.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/config/WeatherUndergroundConfiguration.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonCurrent.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonData.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonError.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonForecast.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonForecastDay.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonLocation.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonResponse.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonSimpleForecast.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonUtils.java
- extensions/binding/pom.xml
- features/karaf/esh-ext/src/main/feature/feature.xml
- features/org.eclipse.smarthome.feature.runtime.binding/feature.xml
> Weather Underground binding: initial contribution

- bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
Fixes: https://github.com/eclipse/smarthome/issues/3590
@smerschjohann Could you have a look at?
> ruleUID should be part of 'ctx'

- bundles/storage/org.eclipse.smarthome.storage.json.test/src/main/java/org/eclipse/smarthome/storage/json/JSonStorageTest.java
- bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/JsonStorage.java
- bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java
- bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaTest.java
...and thereby factored out the non-OSGi related method from JavaOSGiTest into a new JavaTest class.
fixes #3854
> wait for file to be written in JsonStorageTest

- targetplatform/smarthome.target
Fixes #3868
Supersedes PR #3871 - Please close that one
> Scandium and Element-connector changed their names

- features/karaf/esh-tp/src/main/feature/feature.xml
> increase coap version in karaf features

- docs/_includes/documentation-menu.html
- features/karaf/esh-ext/src/main/feature/feature.xml
- features/org.eclipse.smarthome.feature.runtime.binding/feature.xml
* adding karaf feature
* adding it to the bindings feature
* adding it to the docu navigation
as a follow-up to #2748
> Weather Underground binding follow-up

- targetplatform/smarthome.target
> Added Findbugs JSR305 annotations to target platform

- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingRegistry.java
- bundles/core/org.eclipse.smarthome.core.transform/src/main/java/org/eclipse/smarthome/core/transform/TransformationHelper.java
- bundles/model/org.eclipse.smarthome.model.lazygen/src/main/java/org/eclipse/smarthome/model/lazygen/LazyGenerator.java
- bundles/model/org.eclipse.smarthome.model.lazygen/src/main/java/org/eclipse/smarthome/model/lazygen/LazyLanguageConfig.java
- bundles/model/org.eclipse.smarthome.model.lazygen/src/main/java/org/eclipse/smarthome/model/lazygen/LazyStandaloneSetup.java
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/AstroBindingConstants.java
- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioApiResult.java
The ESH code formatter is applied on some files, others are edited manually.
Found by https://github.com/openhab/static-code-analysis
> Replace tabs with spaces in .java files.

- bundles/io/org.eclipse.smarthome.io.monitor/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.rest.log/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.transport.mqtt/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.transport.upnp/META-INF/MANIFEST.MF
- bundles/model/org.eclipse.smarthome.model.core/META-INF/MANIFEST.MF
- bundles/model/org.eclipse.smarthome.model.item.runtime/META-INF/MANIFEST.MF
- bundles/model/org.eclipse.smarthome.model.sitemap.runtime/META-INF/MANIFEST.MF
- bundles/model/org.eclipse.smarthome.model.sitemap/META-INF/MANIFEST.MF
- bundles/model/org.eclipse.smarthome.model.thing.runtime/META-INF/MANIFEST.MF
- bundles/model/org.eclipse.smarthome.model.thing.tests/META-INF/MANIFEST.MF
- bundles/ui/org.eclipse.smarthome.ui/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.exec/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.javascript/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.jsonpath/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.map/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.regex/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.scale/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.xpath/META-INF/MANIFEST.MF
- extensions/transform/org.eclipse.smarthome.transform.xslt/META-INF/MANIFEST.MF
- extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/META-INF/MANIFEST.MF
- extensions/ui/org.eclipse.smarthome.ui.classic/META-INF/MANIFEST.MF
- extensions/ui/org.eclipse.smarthome.ui.paper/META-INF/MANIFEST.MF
> Service-Component header uses uniform wildcard

- extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriLightHandler.java
> [Tradfri] Avoid NPE while handling INCREASE/DECREASE commands

- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md
> WU binding: fix a typo in a channel name in documentation

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/groovy/org/eclipse/smarthome/core/thing/binding/ThingFactoryTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/groovy/org/eclipse/smarthome/core/thing/xml/test/ChannelTypesTest.groovy
- bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/ChannelTypesTest.bundle/ESH-INF/thing/thing-types.xml
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelGroupTypeConverter.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelGroupTypeXmlResult.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlChannelGroupTypeProvider.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlChannelTypeProvider.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelGroupType.java
- bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueChannelTypeProvider.java
- docs/documentation/development/bindings/categories.md
- docs/documentation/development/bindings/thing-definition.md
- docs/documentation/development/bindings/xml-reference.md
- docs/documentation/features/icons.md
> Added category to group channel types

- tools/archetype/binding.test/src/main/resources/archetype-resources/src/test/java/__bindingIdCamelCase__HandlerTest.java
- tools/archetype/binding.test/src/main/resources/archetype-resources/src/test/java/__bindingIdCamelCase__OSGiTest.java
- Added missing imports
- Adapted some codeing guidelines
- Applied code formatter
> [archetype] Added missing imports and applied code formatter in binding test

- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HttpClient.java
Fixes: https://github.com/eclipse/smarthome/issues/3919
> fix resource leak

- tools/archetype/binding/src/main/resources/archetype-resources/META-INF/MANIFEST.MF
> Import optional javax.annotation in binding archtype

- pom.xml
> Sync errors and warnings of null analysis in IDE and MVN

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java
> ignore the CronExpressionTest#findNext

- extensions/binding/org.eclipse.smarthome.binding.tradfri.test/org.eclipse.smarthome.binding.tradfri.test.launch
- extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/TradfriHandlerTest.java
- extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/discovery/TradfriDiscoveryParticipantOSGITest.java
- extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/discovery/TradfriDiscoveryServiceTest.java
Also: small cosmetic refactoring.
> Add launch config for the tradfri.test fragment

- tools/archetype/binding/src/main/resources/archetype-resources/META-INF/MANIFEST.MF
> Fix binding archetype MANIFEST.MF

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/Item.java
- bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
> UI: display mapped option value

- docs/documentation/development/guidelines.md
- docs/documentation/development/testing.md
Also: add "Require-Bundle" exception to coding guidelines.
> Update testing documentation

- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/SonosBindingConstants.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
Properties added: hardwareVersion, firmwareVersion, serialNumber, macAddress, ipAddress
> [Sonos] add few properties

- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/i18n/hue_fr.properties
> [Hue binding] partial translation in French

- pom.xml
> Temporarily deactivate Null analysis to fix build

- pom.xml
> Re-enable Null analysis in Maven

- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/DailyJobMoon.java
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/DailyJobSun.java
- extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/Job.java
> [Astro] Apply channel config before scheduling range events

- docs/documentation/development/bindings/xml-reference.md
> Fix typo in tag representation-property

- bundles/storage/org.eclipse.smarthome.storage.json.test/src/main/java/org/eclipse/smarthome/storage/json/JsonStorageServiceOSGiTest.java
> Add missing license header

- extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/MapviewRenderer.java
> Apply ESH code formatter

- extensions/binding/org.eclipse.smarthome.binding.tradfri/ESH-INF/i18n/tradfri_de.properties
> [Tradfri] Updated and added german translation

- tools/archetype/binding.test/src/main/resources/archetype-resources/META-INF/MANIFEST.MF
- tools/archetype/binding.test/src/main/resources/archetype-resources/build.properties
> [archetype] Minor changes in build.properties and META-INF/MANIFEST.MF to fulfill static-code-analysis tool

- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
> [PaperUI] fix decimal config parameter parsing

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
> [PaperUI] Drop swipe-left/-right support for control page tabs

- docs/documentation/concepts/things.md
> [documentation] Add basic explanation of channel modelling

- docs/documentation/development/guidelines.md
> [documentation] Update coding guidelines for OSGi DS annotations

- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryResultImpl.java
- bundles/io/org.eclipse.smarthome.io.rest.log/src/main/java/org/eclipse/smarthome/io/rest/log/internal/LogHandler.java
- bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/ModelRepositoryChangeListener.java
See #3995
Fix typos https://github.com/eclipse/smarthome/pull/3969#pullrequestreview-55226572
> Author tags added.

- bundles/io/org.eclipse.smarthome.io.monitor/src/main/java/org/eclipse/smarthome/io/monitor/internal/EventLogger.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/binding/BindingResource.java
- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/service/ConfigurableServiceResource.java
- bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSServiceImpl.java
- bundles/io/org.eclipse.smarthome.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/UpnpIOServiceImpl.java
- bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/DumbThingTypeProvider.java
- bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/test/hue/TestHueThingTypeProvider.java
- extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
- extensions/transform/org.eclipse.smarthome.transform.xslt/src/main/java/org/eclipse/smarthome/transform/xslt/internal/XsltTransformationService.java
> Add placeholder to logging messages

- tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java
> Fix wrong service name in bindings archtype

- bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java
- extensions/binding/org.eclipse.smarthome.binding.ntp.test/src/test/java/org/eclipse/smarthome/binding/ntp/server/SimpleNTPServer.java
- extensions/binding/org.eclipse.smarthome.binding.tradfri.test/META-INF/MANIFEST.MF
> Fix remaining errors reported by the analysis tool

- docs/documentation/features/events.md
> Doc: Fix rendering of channel table in events page

- docs/documentation/features/rules.md
> Doc: Corrected rest endpoint for rule templates

- extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/i18n/ntp_fr.properties
- extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/thing/thing-types.xml
- extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
Also add the unit to a configuration setting
> NTP binding: fix issue #3962 and add French translation

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/items/GroupItemTest.java
> Test for item registry update

- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/i18n/weatherunderground.properties
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/i18n/weatherunderground_fr.properties
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
> WU binding: localized thing status description

- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/i18n/sonos.properties
- extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/i18n/sonos_fr.properties
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> Sonos binding: localized thing status description

- bundles/core/org.eclipse.smarthome.core.binding.xml.test/src/test/groovy/org/eclipse/smarthome/core/binding/xml/test/BindingInfoI18nTest.groovy
> Wait until locale has been set before running the test

- tools/archetype/binding.test/src/main/resources/archetype-resources/META-INF/MANIFEST.MF
- tools/archetype/binding.test/src/main/resources/archetype-resources/build.properties
> [archetype] Minor changes in build.properties and META-INF/MANIFEST.MF

- bundles/test/org.eclipse.smarthome.magic/README.md
- extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
- extensions/binding/org.eclipse.smarthome.binding.sonos/README.md
- extensions/binding/org.eclipse.smarthome.binding.wemo/README.md
Signed-off-by: Erdoan Hadzhiyusein <3rdoan@gmail.com>
> Added some empty lines in README.md files after static code analysis

- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/i18n/hue.properties
- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/i18n/hue_de.properties
- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/i18n/hue_fr.properties
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
> Hue binding: localized thing status description

- extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/i18n/ntp.properties
- extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/i18n/ntp_fr.properties
- extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
> NTP binding: localized thing status description

- docs/documentation/development/bindings/thing-definition.md
> corrected and added some initial docs about tags

- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/net/internal/NetworkConfigOptionProvider.java
- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/net/NetUtilTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java
> Cleanup error messages in network address calculations

- tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/handler/__bindingIdCamelCase__Handler.java
> Archetype: Eliminate null warning

- bundles/ui/org.eclipse.smarthome.ui.test/META-INF/MANIFEST.MF
- bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServletServiceTest.java
- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServletService.java
> added support for URIs with user info but no password for the ProxyServlet

- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/i18n/hue_de.properties
> [Hue] Updated and added german translation

- extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/i18n/ntp_de.properties
> [NTP] Updated and added german translation

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/RuleTemplate.java
> Equals  and hashCode methods in RuleTemplate are implemented

- extensions/pom.xml
Fixes https://github.com/eclipse/smarthome/issues/4056
> added scr plugin to extension bundles

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/ResourceBundleTracker.java
Fixes https://github.com/eclipse/smarthome/issues/4058
> Ignore uninstalled bundles

- extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/i18n/ntp_de.properties
> [NTP] Updated german translations - fixed typo

- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/i18n/hue_de.properties
> [Hue] Updated german translations, fixed typo

- docs/.gitignore
- docs/_includes/footer.html
- docs/_includes/header.html
...so that the generated docu can also previewed locally.
> fixed materialize URLs and amended ignored folders

- bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtilTest.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/ReferenceResolverUtil.java
- bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/internal/actions/TimerExecutionJob.java
fix some if the "... is a raw type. References to generic type ... should be parameterized" errors
> fix generic type usage

- extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/discovery/TradfriDiscoveryParticipantOSGITest.java
- extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
- extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriLightHandler.java
- extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
- extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryService.java
1. Add device firmware information to the things
2. Improve some logging
3. Update vendor for the gateway to match the info for the bulbs
> Update tradfri binding

- bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/RulePredicates.java
- bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
- bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java
> All rules are returned if the tags parameter is null or empty list #3903

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nUtil.java
> Fix label/description localization for channel definition

- docs/documentation/features/internationalization.md
> [documentation] Changed binding translation example and added hint for translating error messages in custom keys section.

- extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/java/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerOSGiTest.java
...as its cleanup was failing occasionally. Now it uses the ManagedItemProvider instead of writing to the ItemRegistry directly. 
> fix item registry usage in FS internet radio tests

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManager.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
...in order to separate this concern from the rest of the diverse duties of the ThingManager.
Please note: the logic is simply moved from the ThingManager into the CommunicationManager as it is. There is no point in nitpicking it as I'm currently reworking it completely (will be in another PR).
> factored communication out of ThingManager into own component

- extensions/ui/org.eclipse.smarthome.ui.classic/META-INF/MANIFEST.MF
- extensions/ui/org.eclipse.smarthome.ui.classic/snippets/main.html
> ClassicUI: add favicon and webapp manifest

- tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java
> Set configurationPid instead of service name on archetype

- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessor.java
- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/UpnpDiscoveryService.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java
- bundles/core/org.eclipse.smarthome.core/OSGI-INF/.gitignore
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java
> Use configurationPid instead of name in OSGI services

- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
> PaperUI: force integer input for parameter type integer

- extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
> PaperUI: Allow negative integer input for parameters with default pattern

- bundles/core/org.eclipse.smarthome.core.transform/src/main/java/org/eclipse/smarthome/core/transform/TransformationHelper.java
Fixes https://github.com/openhab/openhab-core/issues/142
> Correctly handle IllegalFormatExceptions in TransformationHelper

- extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
The current timeout of 2 seconds is way to short on very first initialization of the CoapClient
According to https://tools.ietf.org/html/rfc7252#section-4.8.2 the initial timeout should be 93 seconds.
The proposal is to increase the timeout from 2 to 20 secs. This way it will be relatively small but still long enough for first initialization
> Change retrieving the firmware version to be async

- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStatusListener.java
Also added a few new log messages and fixed a compiler warning.
Fixes #2775.
Signed-off-by: Chris Carman namraccr@gmail.com
> [Hue] Added state updates for switch changes

- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/i18n/weatherunderground.properties
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/i18n/weatherunderground_fr.properties
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/thing/thing-types.xml
- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
> Fix Weatherunderground thing is stuck in Initializing state

- README.md
Thanks @kaikreuzer for [the info](https://github.com/eclipse/smarthome/pull/4148#issuecomment-325430137)! :-)
Signed-off-by: Kuba Wolanin <hi@kubawolanin.com> (github: kubawolanin)
> Updated README with skipTests flag

- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java
> ThingTypeI18nLocalizationService: fix issue #4152

- bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java
- bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/reconnect/AbstractReconnectStrategy.java
- bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/reconnect/PeriodicReconnectStrategy.java
A MQTT Broker Connection must be able to handle start and stop iterations.
Related to: https://github.com/eclipse/smarthome/pull/3980#issuecomment-326222638
> allows to start-stop-start-stop-... a reconnect strategy

- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
> removed duplicate operations (which are anyhow done within onLightStateChanged)

- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java
> Sonos: convert command with decimal value to expected integer value

- docs/documentation/features/index.md
- docs/getting-started.html
- extensions/binding/org.eclipse.smarthome.binding.hue/README.md
> fixed a few broken links in the documentation

- docs/_config.yml
- docs/_includes/documentation-menu.html
* fixed permalinks of pages
* included the icon sets in the nav structure
> fix link generation in the documentation

- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/AbstractDescriptionTypeConverter.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/BridgeTypeXmlResult.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeConverter.java
- bundles/core/org.eclipse.smarthome.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
- bundles/io/org.eclipse.smarthome.io.rest.optimize/build.properties
> fixed problems that were discovered by SAT

- bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java
> Select the TTS voice using locale matching based on RFC 4647.

- docs/documentation/development/bindings/thing-definition.md
> Documentation: Fix things vs channel typo

- bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessorTest.java
- bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessor.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
- extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
for the thing registry to handle REMOVED events correctly
Fixes: #4187
> AutomaticInboxProcessor registered as an RegistryListener 

- extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/i18n/hue_de.properties
- extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/i18n/ntp_de.properties
- extensions/binding/org.eclipse.smarthome.binding.tradfri/ESH-INF/i18n/tradfri_de.properties
> [bindings] Updated german translations, fixed typos

- extensions/binding/org.eclipse.smarthome.binding.lifx/META-INF/MANIFEST.MF
> removed unneeded and invalid JAXB dependency

- extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/i18n/weatherunderground_fr.properties
> WU: fix French translation

- bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/profiles/RawButtonToggleProfileTest.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManager.java
- bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawButtonToggleProfile.java
- docs/documentation/concepts/profiles.md
> improvements on profiles

- bundles/core/org.eclipse.smarthome.core.voice.test/src/test/java/org/eclipse/smarthome/core/voice/voiceconsolecommandextension/InterpretCommandTest.java
> fixes core voice tests (#4236, #2860)

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/DateExpression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionPart.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/RecurrenceExpression.java
> cleaned up list definitions in scheduler

- bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java
- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java
> Fix https://github.com/eclipse/smarthome/issues/3912 in CronExpression

- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
> Option mapping in UI: fix log message/level

- targetplatform/EclipseSmartHome.setup
> save-action: final modifiers on private fields

- bundles/io/org.eclipse.smarthome.io.console.karaf/META-INF/MANIFEST.MF
- bundles/io/org.eclipse.smarthome.io.console.karaf/src/main/java/org/eclipse/smarthome/io/console/karaf/internal/CommandWrapper.java
- bundles/io/org.eclipse.smarthome.io.console.karaf/src/main/java/org/eclipse/smarthome/io/console/karaf/internal/ConsoleSupportKaraf.java
> Karaf console: implement help command.

- bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope/src/main/java/org/eclipse/smarthome/automation/module/script/defaultscope/internal/ItemRegistryDelegate.java
- bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope/src/main/java/org/eclipse/smarthome/automation/module/script/defaultscope/internal/ScriptBusEvent.java
drop dependency to 'com.google.common.collect' and 'org.apache.commons.collections.keyvalue'
> cleanup automation.module.script.defaultscope dependencies

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
> PaperUI: Fix update thing when no config-description is given.

- bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/chart/ChartProvider.java
> fixed javadoc of ChartProvider

- bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java
...as they were replaced by the ItemChannelLinkResource.
Removing them should not do any harm as they were broken anyway (see #4273).
fixes #4273
> drop obsolete link resources from ThingResource

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
Clean up PaperUI rest services, related to #4276.
> PaperUI: remove unused REST methods

- extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
> Suppress 503 message for extension availability check

- extensions/binding/org.eclipse.smarthome.binding.sonos/META-INF/MANIFEST.MF
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAudioSink.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosBindingConstants.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/config/ZonePlayerConfiguration.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
- extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java
> Renamed a few packages to internal in the sonos binding.

- bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java
> Regional Settings are not applied due to missing service.pid

- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/META-INF/MANIFEST.MF
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/Activator.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/WelcomeHomeCommands.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/WelcomeHomeRulesProvider.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/handler/StateConditionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/handler/TemperatureConditionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/handler/WelcomeHomeActionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/handler/WelcomeHomeHandlerFactory.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/handler/WelcomeHomeTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/template/AirConditionerRuleTemplate.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/template/WelcomeHomeTemplateProvider.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/type/AirConditionerTriggerType.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/type/LightsTriggerType.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/type/StateConditionType.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/type/TemperatureConditionType.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/type/WelcomeHomeActionType.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/src/main/java/org/eclipse/smarthome/automation/sample/extension/java/internal/type/WelcomeHomeModuleTypeProvider.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/internal/handler/Activator.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/internal/handler/SampleActionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/internal/handler/SampleConditionHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/internal/handler/SampleHandlerFactory.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/internal/handler/SampleHandlerFactoryCommands.java
- bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/src/main/java/org/eclipse/smarthome/automation/internal/sample/json/internal/handler/SampleTriggerHandler.java
- bundles/automation/org.eclipse.smarthome.automation.sample.rest.api/src/main/java/org/eclipse/smarthome/automation/sample/rest/api/internal/Activator.java
> Renamed a few packages to internal in the sample bundles.

- bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/bindingresource.xml
- bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/channeltyperesource.xml
- bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/configdescriptionresource.xml
- bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/discoveryresource.xml
- bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/extensionresource.xml
- bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/itemresource.xml
Due to lack of time I didn't port them to annotations right now, but this at least fixes all the SCR errors I saw during startup.
fixes #4322
> fix the REST implementation locations
