docs/documentation/development/bindings/docs.md

mentioned the need for line breaks in docs

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriCoapClient.java

Send command to the bulb only if there is actually a change on the value for brightness or color temperature

Improve Tradfri binding

---

docs/documentation/development/bindings/thing-definition.md

Signed-off-by: Andre Fuechsel andre.fuechsel@telekom.de

Added explanation of the representation property

---

bundles/config/org.eclipse.smarthome.config.dispatch.test/src/test/java/org/eclipse/smarthome/config/dispatch/test/ConfigDispatcherOSGiTest.java

Adopt new component PID in OSGi test

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/storage/Storage.java
bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/internal/JsonStorage.java
bundles/storage/org.eclipse.smarthome.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java
bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/storage/VolatileStorage.java

A value of a key could be potential null. It depends on the respective implementation if it differs between a existing key that value is null or a nullable value states that the key does not exist.
Do you agree?

add nullness handling to storage and its implementations

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js

PaperUI: Add rollershutter groupType

---

tools/static-code-analysis/checkstyle/suppressions.xml

Suppressed PackageExportsNameCheck for models.

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java

MQTT: Fix wildcard subscribers

---

extensions/ui/org.eclipse.smarthome.ui.basic/ESH-INF/i18n/basic_de.properties

[Basic UI] Added german translations

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueBridge.java

Fixes #4339
Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

[hue] Fix incorrect usage of trailing slash in hue API call

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/groovy/org/eclipse/smarthome/binding/hue/test/HueLightHandlerOSGiTest.groovy
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/HueLightDiscoveryServiceOSGiTest.java

This adapts the Hue Tests to the changes made in #4363.
relates to #4363

adapt hue tests to Hue API docu

---

bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/channel-types.xml
bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/MagicBindingConstants.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicExtensibleThingHandler.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactory.java

Also: extend the color channel to be configurable.

Magic bundle: add extensible thing to the magic test bundle

---

bundles/model/org.eclipse.smarthome.model.thing.tests/src/org/eclipse/smarthome/model/thing/tests/GenericItemChannelLinkProviderJavaTest.java

see https://github.com/eclipse/smarthome/pull/4323#issuecomment-334218430
This just adds a regression test for it.

assert configuring multiple links works

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueBridge.java

Correctly handle IOExceptions

---

bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/OSGI-INF/SampleJavaDemoComponent.xml
bundles/automation/org.eclipse.smarthome.automation.sample.java.demo/src/main/java/org/eclipse/smarthome/automation/sample/java/demo/internal/SampleJavaDemo.java
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/OSGI-INF/DemoCommandsPluggable.xml
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/OSGI-INF/HandlerFactory.xml
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/demo/internal/commands/DemoCommand.java
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/demo/internal/commands/DemoCommandsPluggable.java
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/demo/internal/commands/PostEventCommand.java
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/demo/internal/factory/HandlerFactory.java
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/demo/internal/handlers/CompareCondition.java
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/demo/internal/handlers/ConsolePrintAction.java
bundles/automation/org.eclipse.smarthome.automation.sample.moduletype.demo/src/main/java/org/eclipse/smarthome/automation/sample/moduletype/demo/internal/handlers/ConsoleTrigger.java

Renamed a few packages in the demo bundles.

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryService.java

fixed the removal of discovery results for TradfriDiscoveryService

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ChartRenderer.java

fixed typo

---

targetplatform/smarthome.target

Fix oxygen repo URL in targetplatform

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/DynamicStateDescriptionProvider.java

Please see #4140 for the context.
Work in progress.
Signed-off-by: Pawel Pieczul <pieczul@gmail.com> (github: ppieczul)

Add dynamic state description provider (#4140)

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java

Sonos: fix discovery for old Sonos ZP80 and ZP100

---

extensions/ui/org.eclipse.smarthome.ui.paper/tests/setup.test.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers/controller.things.edit.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/directives/directive.thingConfiguration.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.things.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/directive.thingConfiguration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/setup.html

Fixes #4401.
Also: Refactor thing editor to directive.

PaperUI: Fix bridge selection on thing edit

---

bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/ModelServer.java
bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/RegistryProvider.java
bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/RuntimeServerModule.java
bundles/model/org.eclipse.smarthome.model.rule.ide/src/org/eclipse/smarthome/model/rule/ide/RulesIdeSetup.xtend
bundles/model/org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/RulesStandaloneSetup.xtend
bundles/model/org.eclipse.smarthome.model.script.ide/src/org/eclipse/smarthome/model/script/ide/ScriptIdeSetup.xtend

...doing it in a similar way as in #4278
relates to openhab/openhab-vscode#31

fix OSGi service injection into Language Server modules

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheAsync.java
bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/internal/ConfigurationDeserializer.java

Fixed the header of a few bundles

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java

Sitemap REST API: bypass proxy for HLS video playlist

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImplTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/i18n/TimeZoneProvider.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java

Fixes #4426.
Also: Adopt tests & small test refactoring.

Fix timezone config handling

---

features/karaf/esh-tp/src/main/feature/feature.xml

updated xtext version in karaf feature

---

bundles/core/org.eclipse.smarthome.core.thing/ESH-INF/i18n/DefaultSystemChannels_fr.properties

French translation for system channels

---

extensions/ui/org.eclipse.smarthome.ui.basic/web-src/_layout.scss

BasicUI: fix a regression in a CSS rule

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Rule.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/RulePredicates.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/Visibility.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/RuleTemplate.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/Template.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ActionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/CompositeActionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/CompositeConditionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/CompositeTriggerType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ConditionType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/ModuleType.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/type/TriggerType.java
bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/RuleEngineTest.java
bundles/automation/org.eclipse.smarthome.automation.core.test/src/test/java/org/eclipse/smarthome/automation/core/internal/RulePrefixTest.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleUtils.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuntimeRule.java
bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/shared/simple/SimpleRule.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/AbstractGSONParser.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ActionInstanceCreator.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/ConditionInstanceCreator.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/RuleGSONParser.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/RuleInstanceCreator.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/TemplateGSONParser.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/TemplateInstanceCreator.java
bundles/automation/org.eclipse.smarthome.automation.parser.gson/src/main/java/org/eclipse/smarthome/automation/parser/gson/internal/TriggerInstanceCreator.java
bundles/automation/org.eclipse.smarthome.automation.providers/src/main/java/org/eclipse/smarthome/automation/internal/core/provider/RuleResourceBundleImporter.java

Some nullness fixes for Automation

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/fields/MACAddress.java

...which is not CP2 and was also missing as an import in the manifest.

Removed dependency to javax.xml.bind

---

extensions/transform/org.eclipse.smarthome.transform.scale/README.md

This PR is moved from openHAB documentation.
Main discussion took part in:
https://github.com/openhab/openhab-docs/pull/486
_We already discussed there about a more handy example in the future,
but there are no details yet, so i wanted to finish this reworking on the current state._
For the record:
Related: #4439
Closes openhab/openhab-docs#486
Closes openhab/openhab-docs#484
_Since this is my first PR on a eclipse repo, feel free to comment if there is something missing.
I have done all the steps from the contribution guidelines.
(Eclipse Account, GitHub Settings in there, Contributor Agreement)
Most things should be ok this way._
Signed-off-by:  Jerome Luckenbach <github@luckenba.ch> (github: @Confectrician)

Improved the Scale Transformation article.

---

docs/documentation/development/ide.md
targetplatform/EclipseSmartHome.setup

... as they do not work on a fresh installation due to missing target platform artifact in the local maven repo

Removed UI setup tasks

---

bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/shared/simple/SimpleRule.java

Solves https://community.openhab.org/t/jsr223-jython-script-rule-loading-error-in-build-1071/35601
#4438 

Fix Simple Rule constructor

---

extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/ArtnetBridgeHandlerTest.java
extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/Lib485BridgeHandlerTest.java
extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/SacnBridgeHandlerTest.java
extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/internal/FadeActionTest.java
extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/internal/UtilTest.java
extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/multiverse/BaseChannelTest.java
extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/multiverse/ChannelTest.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/handler/ChaserThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/handler/DimmerThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/DmxBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/Util.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/action/ActionState.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/action/BaseAction.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/action/FadeAction.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/action/FadeDirection.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/action/ResumeAction.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/multiverse/BaseDmxChannel.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/multiverse/DmxChannel.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/multiverse/Universe.java

refactoring: rename class Channel to DmxChannel to avoid problems with  ESH-class Channel
add tests for FadeAction
make Chaser turn to off after completed with infinite holdTime (-1)

Improve DMX binding

---

docs/_config.yml

fix blog permalinks

---

extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java

Closes #4282
Signed-off-by: Hans-Jörg Merk hans-joerg.merk@t-online.de

Update WemoLightHandler subscription handling

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Identifiable.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java

The commits are separated, so rebase without squash should be okay.

Nullness fixes

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java

Sonos: cover art download in a separate thread

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java

In case of a Sonos group, the cover art is now downloaded only once.
Fix #4482

Sonos: optimization for cover art download

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java

Chart servlet: new optional setting to set a maximum chart width

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriCoapEndpoint.java

As discussed in https://github.com/eclipse/californium/pull/452#issuecomment-341703735.

Added logging for endpoint destruction

---

bundles/core/org.eclipse.smarthome.core.thing/META-INF/MANIFEST.MF
tools/static-code-analysis/checkstyle/suppressions.xml

export profiles package

---

bundles/config/org.eclipse.smarthome.config.discovery.mdns/src/main/java/org/eclipse/smarthome/config/discovery/mdns/internal/MDNSDiscoveryService.java

only pass services of the registered type to the participants

---

bundles/config/org.eclipse.smarthome.config.discovery.mdns/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery.mdns/src/main/java/org/eclipse/smarthome/config/discovery/mdns/MDNSDiscoveryParticipant.java
bundles/config/org.eclipse.smarthome.config.discovery.upnp/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery.upnp/src/main/java/org/eclipse/smarthome/config/discovery/upnp/UpnpDiscoveryParticipant.java

added null annotations to the discovery participant interfaces

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java

Added mac address to list of thing property keys

---

distribution/smarthome/logback_debug.xml
features/karaf/esh-core/src/main/feature/feature.xml
features/karaf/esh-tp/src/main/feature/feature.xml
targetplatform/smarthome.target

switched to latest JUPnP 2.3.0 release

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java

Net utils: optional timeout parameter for the downloadImage methods

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

...with the rest of the framework: The other entities (e.g.
Rule, ThingImpl,...) only check for the identity but not for
all properties.

aligned equals implementation of GenericItem

---

extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/internal/discovery/NtpDiscovery.java

[ntp] Fixed logging statements

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/ProgressStep.java

Minor fix in firmware ProgressStep enumeration java doc

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapperTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/ArithmeticGroupFunctionTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java

Fix group function requires StringType with regex as parameter

---

extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/TradfriHandlerTest.java
extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/discovery/TradfriDiscoveryParticipantOSGITest.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/ESH-INF/config/config.xml
extensions/binding/org.eclipse.smarthome.binding.tradfri/README.md
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/TradfriBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriCoapHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/config/TradfriGatewayConfig.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java

[Tradfri] Adapt binding to use DTLS identities #4479
~~[Tradfri] Exception occurred while informing handler:Task #3867 - eclipse/californium#452 (comment) - Use own executor~~

[Tradfri] General improvements

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriThingHandler.java

various lifecycle improvements and fixes on Tradfri

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js

Fixes #3684 
Signed-off-by: Jason Jones <jmsjones@gmail.com>

Fixed switch and contact group function labels in Paper UI.

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

fixed JavaDocs

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ProfileContextImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/ProfileContext.java

Use scheduled executor service in profile context

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/firmware/ModelRestrictedFirmwareUpdateServiceOSGiTest.java

...to not (illegally) return `null` things and thereby cause NPEs
in the FirmwareUpdateService.

fix ModelRestrictedFirmwareUpdateServiceOSGiTest

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceTest.java

...in order to ignore subsequent events.

fix testEvents in firmware update service test

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/ProfileTypeRegistryImpl.java

Fixes https://github.com/openhab/openhab-distro/issues/565

fixes cardinality of providers

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java

- fixed all warnings
- removed invalid (and unused) reference to DiscoveryServiceRegistry

Sonos code cleanup

---

docs/documentation/community/downloads.md

Removed links to the snapshots of the Designer from the website

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkProvider.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/Provider.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ItemProvider.java

Sometimes I would like to add one annotation, I end up with changing millions (okay, that's not really the correct number, but a lot of) files. :wink: 
So, let's do small steps.

annotate some provider interfaces

---

targetplatform/smarthome.target

Remove Apache Http Client from target platform

---

bundles/core/org.eclipse.smarthome.core.thing/ESH-INF/i18n/DefaultSystemChannels_de.properties
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/CommonTriggerEvents.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java
docs/documentation/development/bindings/thing-definition.md

Closes #4541
Signed-off-by: Jan Kemmler <kickass_kemmler@gmx.de>

Added system rocker channels and associated system events.

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/RegistryHook.java

clarify RegistryHook javadoc

---

docs/documentation/community/contributing.md
docs/index.html

Add link on the website for reporting a security vulnerability

---

pom.xml

Disable maven null analysis errors until tycho > 1.0 release

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java

Related to https://github.com/eclipse/smarthome/issues/4321#issuecomment-344996256

remove mandatory reference from nullness analysis

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseBridgeHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandlerFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BridgeHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ConfigStatusBridgeHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ConfigStatusThingHandler.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingConfigStatusSource.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandlerCallback.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingTypeProvider.java

Corrected null annotations in thing package

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/AbstractDiscoveryService.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryListener.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryResult.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryResultBuilder.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryService.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryServiceCallback.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryServiceRegistry.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/ExtendedDiscoveryService.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/ScanListener.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/UpnpDiscoveryParticipant.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/dto/DiscoveryResultDTO.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/dto/DiscoveryResultDTOMapper.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/Inbox.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/InboxListener.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/InboxPredicates.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessor.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryResultImpl.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/HueLightDiscoveryServiceOSGiTest.java
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/discovery/TradfriDiscoveryServiceTest.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoCoffeeHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoMakerHandler.java

This PR needs #4550 as a prerequisite.
Also-by: Markus Rathgeb <maggu2810@gmail.com>

Annotate discovery package

---

bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioManagerImpl.java
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceManagerImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingFactoryHelper.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/binding/BindingResource.java
bundles/io/org.eclipse.smarthome.io.rest.optimize/src/main/java/org/eclipse/smarthome/io/rest/optimize/internal/ResourceFilterImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/sensorJobExecutor/sensorJob/impl/SceneConfigReadingJob.java

See openhab/static-code-analysis#213
See openhab/static-code-analysis#217

Fixed a few loggers taking wrong class as parameter.

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/i18n/I18nConfigOptionsProvider.java

Sort timezones by offset and then by name

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/net/NetUtilTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java

Accept 32bit netmask in config for point-to-point connections

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/HueLightDiscoveryServiceOSGiTest.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStateConverter.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStatusListener.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HttpClient.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueBridge.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueThingHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/Util.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeDiscoveryParticipant.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java

Null annotations for hue binding

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java

Compare real netmasks not configured ip against netmask

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/ProfileCallbackImpl.java

use fresh thing instances within the profile callback

---

extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/moon.xml
extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/sun.xml
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/discovery/AstroDiscoveryService.java

[Astro] added support for duplicate identification to avoid unnecessary discovery results

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java

see https://github.com/eclipse/smarthome/pull/4624#issuecomment-346832973

correctly specify service properties as an array

---

extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECT.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/One.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY3.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY5.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAYBAR.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/ZonePlayer.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.sonos/README.md
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java

See https://github.com/eclipse/smarthome/issues/4570#issuecomment-345862380

removed zonegroup channel

---

bundles/model/org.eclipse.smarthome.model.lsp.test/.classpath
bundles/model/org.eclipse.smarthome.model.lsp.test/.project
bundles/model/org.eclipse.smarthome.model.lsp.test/.settings/org.eclipse.jdt.groovy.core.prefs
bundles/model/org.eclipse.smarthome.model.lsp.test/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.lsp.test/about.html
bundles/model/org.eclipse.smarthome.model.lsp.test/build.properties
bundles/model/org.eclipse.smarthome.model.lsp.test/pom.xml
bundles/model/org.eclipse.smarthome.model.lsp.test/src/test/java/org/eclipse/smarthome/model/lsp/internal/MappingUriExtensionsTest.java
bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/MappingUriExtensions.java
bundles/model/pom.xml

improve client path guessing & mapping in the language server

---

bundles/config/org.eclipse.smarthome.config.core/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery.mdns/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery.upnp/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.serial/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.xml/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.binding.xml/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing.xml/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.thing/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.transport.mqtt/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java
bundles/model/org.eclipse.smarthome.model.lsp/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.dmx.test/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.dmx/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.lifx/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.serialbutton/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.sonos/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/META-INF/MANIFEST.MF
tools/archetype/binding/src/main/resources/archetype-resources/META-INF/MANIFEST.MF

See https://github.com/openhab/openhab2-addons/pull/2880

Remove org.osgi.service.component.annotations import from manifests

---

docs/_includes/documentation-menu.html
docs/documentation/features/scene.md
docs/documentation/features/scenes.md

Added documentation for scene concept.

Scene documentation

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java

Show mac address in gateway discovery result

Add serial number to discovery result 

---

bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/ModelServer.java

...following the wording of dashboards and including the buzzword LSP. I know it's pretty minor :)
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de>

Update LSP started string

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/extensions/ExtensionResource.java

changed runnables to lambdas

---

docs/_config.yml
docs/blog/index.html

fixed paths for blog posts

---

targetplatform/smarthome.target

use http for target platform resolution consistently

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java

Correct null annotations on Thing class

---

docs/_posts/2017-11-30-nullannotations.md

Thanks for the great blog! 
Maybe someone can also create a project to stop hyperlink errors. :-)

Fix blog post link to lastNPE

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightDiscovery.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxSelectorContext.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxSequenceNumberSupplier.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/Packet.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/util/LifxMessageUtil.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/util/LifxNetworkUtil.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/util/LifxSelectorUtil.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/util/LifxThrottlingUtil.java

* Reuse selector logic between discovery and handlers to reduce code duplication
* Fix threads sometimes ending up in endless loop when sending packets (fixes #4665)
* Fix busy waiting of thread during discovery
* Add null annotations on selector and utility classes

[LIFX] Selector logic improvements

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/AbstractInvocationHandler.java

* eliminated empty line
* reduced severity of timeouts in order to not worry end-users looking at the logs

refined safe call logging

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageDTO.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java

Sitemap REST API: signal long polling timeout

---

docs/documentation/community/downloads.md

updated download links for 0.9.0 release

---

tools/static-code-analysis/checkstyle/ruleset.properties

Updated ESH version in Static Code Analysis config

---

docs/documentation/community/downloads.md

fixing download url

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java

Update log in downloadData

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java

Sitemap REST API: fix for the new timeout field

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java

Default 5s timeout replaced by a 30s timeout.
Fixes #4476

WU binding: fix timeout for icon download

---

bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java

fixed JavaOSGiTest to save multiple service registrations per interface name

fixed JavaOSGiTest

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/java/org/eclipse/smarthome/binding/fsinternetradio/test/TestPortUtil.java

Related to: https://github.com/eclipse/smarthome/pull/4719

improve test port util method

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

improved log message when resolving dynamic groups

---

bundles/config/org.eclipse.smarthome.config.discovery.test/src/test/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessorTest.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/InboxPredicates.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessor.java

Inbox: Compare thing type instead of binding id for auto ignore

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/internal/common/SafeCallerImplTest.java

...a little in order to facilitate for weak CI servers.
(see https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly-PR/22/console)
Thereby I of course extracted these times into constants to make it easier manageable.

[Tests] relaxed the time constraints in the SafeCallerTest

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java

MQTT: Use original topic for subscription and removal

---

bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/DTOMapperImpl.java

Fixed error found by the SAT tool

---

bundles/model/org.eclipse.smarthome.model.lsp/build.properties

include LSP config in build

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/WeatherUndergroundBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java

WU binding: reduce the number of warnings generated by the code analysis

---

extensions/ui/org.eclipse.smarthome.ui.classic/META-INF/MANIFEST.MF
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/WebAppActivator.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/WebAppConfig.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/PageRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/servlet/CmdServlet.java

Classic UI: reduce the warnings detected by code analysis

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java

This should be "theoretical" handle injected discovery service as soon as the component is activated.
@mhilbush Can you give it a try?
The previous implementation is really buggy. E.g. it clears the discovery service list on deactivate without handling the remove method. 
Fixes: https://github.com/eclipse/smarthome/issues/4751

handle discovery services if activated only

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Channel.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingStatusInfo.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ItemFactory.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/CoreItemFactory.java

Corrected null annotations in Channel and ItemFactory

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/README.md

Signed-off-by: Jakob Stenfeldt <jakob.stenfeldt@gmail.com>

Updated documentation. Number type is not allowed in Sitemap.

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy

The registerService methods of the base groovy class OSGiTest are now returning the service registration. Null assertions added into the methods as well as some javadoc

Method registerService of OSGiTest.groovy To Return Service Registrations

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java

Same widget ids as the ones in the sitemap SSE events
Fixes #4819

Fix widget ids generated by the sitemap REST API

---

extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.astro/README.md
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/handler/MoonHandler.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/calc/MoonCalc.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/model/MoonPhase.java

Astro: Added moon age in percent and degree

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java

Include exception text in error message of failed actions

---

extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/channels.xml

Astro: Updated moon age labels

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/BridgeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ChannelBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ThingBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ThingStatusInfoBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend

Corrected null annotations in binding builders

---

docs/documentation/concepts/index.md

- Numerous changes to improve grammar and reader comprehension
- Addresses #4659
Signed-off-by:Brad Gilmer <brad@gilmer.tv>

[Concepts] Changes that improve readability

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpressionPart.java

expression instead of epxression

edit syntax error in the documentation

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngine.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/normalization/DecimalNormalizer.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/normalization/IntNormalizer.java
bundles/core/org.eclipse.smarthome.core.id/src/main/java/org/eclipse/smarthome/core/id/InstanceUUID.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/service/ConfigurableServiceResource.java
bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/ZoneTemperatureControlHandler.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/discovery/DeviceDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/handler/ChaserThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/handler/DimmerThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/handler/Lib485BridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/dmxoverethernet/DmxOverEthernetHandler.java
tools/static-code-analysis/findbugs/suppressions.xml

See openhab/static-code-analysis#213
and openhab/static-code-analysis#237

Fixed few loggers with mismatching placeholder-parameter count

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html

This is supposed to fix #4759.

Reorder controll tab cards on tab select & minor refactoring

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java

Sonos: adjust log levels

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/WrappedScheduledExecutorService.java

Do not log information about canceled tasks

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryListener.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/HueLightDiscoveryServiceOSGiTest.java
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/discovery/TradfriDiscoveryServiceTest.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoCoffeeHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoMakerHandler.java

Allow null instead of empty list for removed discovery results

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/net/internal/NetworkConfigOptionProvider.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/net/NetUtilTest.java
bundles/core/org.eclipse.smarthome.core/ESH-INF/config/networkinterface.xml
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetworkAddressService.java

address.
See issue [#3054](https://github.com/openhab/openhab2-addons/issues/3054)
Signed-off-by: Mark Herwege <mark.herwege@telenet.be>

Allow configuration of a broadcast address

---

extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/discovery/test/WemoLinkDiscoveryServiceOSGiTest.groovy

Ignore failing wemo test until it is fixed

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java

...as Gson otherwise won't execute the field initializers.
fixes #4791

re-add default constructors in ThingImpl & BridgeImpl

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md

Signed-off-by: Markus Haack <markus.haack@gmail.com> (github: mhaack)

Add additional info how to configure the language parameter

---

bundles/automation/org.eclipse.smarthome.automation.sample.rest.api/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.sample.rest.api/src/main/java/org/eclipse/smarthome/automation/sample/rest/api/internal/Activator.java
extensions/transform/org.eclipse.smarthome.transform.map.test/src/test/java/org/eclipse/smarthome/transform/map/internal/MapTransformationServiceTest.java

See also: https://github.com/openhab/openhab2-addons/pull/3104 & https://github.com/openhab/static-code-analysis/pull/241
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>

No more e.printStackTrace();

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Bridge.java

Improve Bridge.getHandler() Javadoc

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy

fixed OSGiTest.groovy according to the changes of JavaOSGiTest

---

bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/OSGiTest.groovy
bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java

This is just a minor optimization - function-wise it was correct.
@maggu2810 sorry I saw your comment in #4715 too late, so I merged #4901 without requesting to change it. Therefore here the cleanup in both variants.

optimized map access in (Java)OSGITest

---

docs/documentation/concepts/index.md

-  Addresses openhab/openhab-docs/#604
-  Improves explanation
Signed-off-by: Brad Gilmer <brad@gilmer.tv>

Improve on addition of Binding to Concepts article

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapWidgetEvent.java
extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js

Sitemap SSE: provide unconverted item state

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/VideoRenderer.java

Basic UI: fix handling of MJPEG video

---

bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

Fixes #4898
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>

 [UI] Fix exec transformation in item label

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java

Fix GroupItem compilation error

---

bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/service/MagicMultiInstanceService.java

...which was introduced by #4847

fix log format in MagicMultiInstanceService

---

bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/validation/SitemapValidator.xtend

Sitemap: validate step, minValue and maxValue of Setpoints

---

extensions/extensionservice/org.eclipse.smarthome.extensionservice.marketplace/src/main/java/org/eclipse/smarthome/extensionservice/marketplace/internal/BindingExtensionHandler.java

added debug exception logging to get hold of details in case of marketplace installation failure

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/directive.control.location.html

Paper UI: Fix location item label

---

bundles/model/org.eclipse.smarthome.model.lsp.test/src/test/java/org/eclipse/smarthome/model/lsp/internal/MappingUriExtensionsTest.java
bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/MappingUriExtensions.java

...in order to get the same behavior on all platforms.
fixes #4868

fix path construction in LSP tests

---

extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java

...as it was ignoring the offset and only returned the local time when the
response was received
fixes #4867

fix NTP time calculation

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/java/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerJavaTest.java

...as SAXParser returns localized error message, which is nice generally but
a little annoying if the tests check for the english message string.

make FSInternetRadioHandlerJavaTest independent of the OS language

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.repositories.js

Paper UI: Update discovery results in inbox

---

extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js

Fixes #4558
Cleanup code for the long polling update method with dataModelLegacy suppressed
and common code created in AbstractChangeListener
Signed-off-(by: Laurent Garnier <lg.hc@free.fr>

Basic UI with long polling update: management of dynamic widget visibility

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java

Allow netmask 32bit for point-to-point

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/CompositeJob.java

made debug logs about scheduled jobs readable again

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/discovery/AstroDiscoveryService.java

See https://github.com/eclipse/smarthome/pull/4079#issuecomment-359023592

[Astro] Do not restart but reconfigure discovery service with new config

---

docs/documentation/development/guidelines.md

See https://github.com/eclipse/smarthome/pull/4967#issuecomment-359793047

[Documentation] Always use @Activate, @Deactivate and @Modified

---

bundles/model/org.eclipse.smarthome.model.item.tests/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider2Test.java
bundles/model/org.eclipse.smarthome.model.item.tests/src/org/eclipse/smarthome/model/item/internal/GenericItemProviderTest.groovy
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java

GenericItemProvider: Compare GroupItems if an Item was changed

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/GenerateItems.mwe2

...which slipped through in #4122
fixes #4978

Bring back unique item name validation

---

docs/documentation/development/guidelines.md

small corrections on formatting and formulations

---

bundles/test/org.eclipse.smarthome.magic/META-INF/MANIFEST.MF

Export package in magic bundle

---

docs/documentation/development/bindings/xml-reference.md

Documentation: Fix xml-reference typo and table

---

extensions/transform/org.eclipse.smarthome.transform.exec/README.md

Added transformation examples as somehow nobody really knows how it works.

[EXEC transformation] Update README.md

---

targetplatform/SmartHome-Runtime.launch

See also https://github.com/openhab/openhab-distro/pull/638

added "-Djava.awt.headless=true" to launch config

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryService.java

Correctly support "TRADFRI bulb E12 WS opal 400lm"

---

docs/documentation/features/dsl.md

Documentation for textual service configuration

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingTypeMigrationService.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/BridgeType.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingTypeBuilder.java

Remove some wrong @NonNull annotations in core.thing

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/ThingTypeMigrationService.java

Missing @Nullable in ThingTypeMigrationService

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java

This is a fix for #4791 which became obvious by #5016

Fix ThingImpl.setConfiguration to accept @Nullable

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/ReadyMarker.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/ReadyMarkerFilter.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/service/ReadyService.java

Fix nullannotations in ReadyMarkers

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/firmware/FirmwareUpdateHandler.java

Add NonNull to firmware handler

---

bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/TestItem.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/items/GroupItemTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/ArithmeticGroupFunctionTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/ActiveItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/Item.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/StateChangeListener.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/CallItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ColorItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ContactItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/DateTimeItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/DimmerItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ImageItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/LocationItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/NumberItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/PlayerItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/RollershutterItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/StringItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/SwitchItem.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap.test/src/test/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResourceTest.java
bundles/model/org.eclipse.smarthome.model.persistence.tests/src/test/java/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensionsTest.java

Annotated Item API with nullannotations

---

bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/ModifiablePersistenceService.java
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/PersistenceService.java
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/QueryablePersistenceService.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheAsync.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/CidrAddress.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetworkAddressService.java
bundles/model/org.eclipse.smarthome.model.persistence.tests/src/test/java/org/eclipse/smarthome/model/persistence/tests/TestPersistenceService.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicConfigurableThingHandler.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicExtensibleThingHandler.java
bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/internal/java/MissingServiceAnalyzer.java

Replace some @NonNull occurences with @NonNullByDefault on class level

---

bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/RuleStatusInfo.java
bundles/automation/org.eclipse.smarthome.automation.api/src/main/java/org/eclipse/smarthome/automation/template/TemplateRegistry.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescription.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameter.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameterBuilder.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionProvider.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionRegistry.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/dto/ConfigDescriptionDTOMapper.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusInfo.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusMessage.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusProvider.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusService.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/ConfigDescriptionValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/validation/ConfigValidationException.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/AbstractDiscoveryService.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryListener.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryResultBuilder.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryServiceRegistry.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/UpnpDiscoveryParticipant.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/Inbox.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/InboxFilterCriteria.java
bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/events/InboxEventFactory.java
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/discovery/MDNSDiscoveryParticipant.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStateConverter.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/handler/LIRCBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java

Fixed issues found by Static Code Analysis Tool (JavadocMethodStyleCheck)

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java

add time-only and date-only parsing from string

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers/controller.things.view.js

Signed-off-by: Arne Plöse <aploese@gmx.de>

BUG:  fix #5033

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/Products.java

* Adds support for new LIFX products such as Tile and Beam
* Adds chain feature capability to new and existing products
Based on: https://github.com/LIFX/products/blob/master/products.json

[LIFX] Update Products enumeration

---

bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/channel-types.xml
bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/MagicBindingConstants.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicDelayedOnlineHandler.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactory.java

Magic bundle: Added thing that schedules a job to go ONLINE after a delay

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/parameterDescription.css

Paper UI: expand config parameter description to 3 lines

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/ThreadPoolManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/WrappedScheduledExecutorService.java

Reactivate WrappedScheduledExecutorService that logs Exceptions of scheduled tasks

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java

ChannelItemprovider: Shutdown executor in deactivate

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionRegistry.java

see https://github.com/eclipse/smarthome/pull/5021#discussion_r166457342

continue searching config descriptions for aliases until found

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/firmware/FirmwareUpdateServiceTest.java
docs/documentation/development/guidelines.md

...and cleaned up the ArgumentMatcher mess from #5056

removed require-bundle from docu

---

bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/channel-types.xml
bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/MagicBindingConstants.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicLocationThingHandler.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactory.java

This adds a thing with one location channel to the magic bundle.

Add Location thing to the magic bundle

---

extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js

Basic UI: fix live update (Microsoft Edge)

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/mapview.html
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/MapviewRenderer.java

Basic UI: show label and icon for Mapview widgets

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java

WU binding: convert system language to WU language

---

extensions/ui/org.eclipse.smarthome.ui.basic/web-src/_layout.scss

Basic UI: home icon non-clickable

---

bundles/ui/org.eclipse.smarthome.ui/ESH-INF/config/config.xml
bundles/ui/org.eclipse.smarthome.ui/OSGI-INF/chartservlet.xml
bundles/ui/org.eclipse.smarthome.ui/build.properties

Chart service: settings available in Paper UI

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheAsync.java
pom.xml

Tycho 1.1.0 has been released (2018-02-02).
Will add a revert for #4604 the next days.

bump tycho (1.1.0) and enable nullness checks again

---

extensions/ui/org.eclipse.smarthome.ui.classic/snippets/mapview.html
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/MapviewRenderer.java

Classic UI: show label and icon for Mapview widgets

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/i18n/weatherunderground_fr.properties
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonCurrent.java
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonForecastDay.java

WU binding: add new channels containing the icon key

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.extension.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.services.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/configuration.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/extensions.html

Paper UI: Remember selected tab in URL query parameter

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/item.config.html

Paper UI: force group function for base type <> None

---

bundles/config/org.eclipse.smarthome.config.dispatch.test/src/test/java/org/eclipse/smarthome/config/dispatch/test/ConfigDispatcherFileWatcherTest.java
bundles/config/org.eclipse.smarthome.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcherFileWatcher.java

@svilenvul @kaikreuzer Shouldn't SAT complain about that ones?

fix licenses by running license:format

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth.test/pom.xml

fix inconsistent indentation on the go
Fixes: #5094

fix missing version by different group id

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/persistence/PersistenceResource.java
bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensions.java
bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/internal/PersistenceModelManager.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServletService.java

Related to #4738
@lpapazow Can you check your formatter, it seems to work not reliable.
There are missing spaces `immediate=true`, tabs are used for intention instead of spaces, ...
@kaikreuzer Shouldn't SAT break the build if tabs are used for indentation?

for annotated methods the cardinality is implicit mandatory

---

extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/NtpBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java
extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/internal/NtpHandlerFactory.java

@maggu2810 I opened this new PR since I had reverted and force-pushed the changes considering #4747, so the old PR can be deleted.
Changes include:
- `NtpBindingConstants.java` - Added a private constructor to hide the implicit public one.
- `NtpHandlerFactory.java` - little logical improvement.
- `NtpHandler.java` - got rid of simple `(String)` casting.

Did little improvements to the NTP binding (correct)

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js

Paper UI: Update item state on state changed events

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/service/ReadyServiceImpl.java

These million log entries are annoying me since months when running in debug/ide mode.
Don't try to negotiate this PR with me. 💣 

Reduce ready markers to trace logging

---

docs/index.html

FTR: I replaced zooautomation as their "store" is not available since years and there is no trace of a real product that uses ESH.

added Mixtile Hub to ESH references

---

docs/index.html

fixed link to issue tracker

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManager.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/RegistryChangeListener.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/events/EventSubscriber.java

Fix nullannotations in CommunicationManager

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/QueueingThreadPoolExecutor.java

* changed the name from `lock` to `queueThreadLock` for better indication what it is used for
* move the check of the thread pool name variable to the place that is used by all constructors and so factory methods
* the factory methods and the protected constructor add defaults for the missing fields on calling the private constructor instead of using one place for that defaults
* introduce variable constants to access the class specific this reference and the super.execute method to make its usage simpler to read

small code cleanups of QueueingThreadPoolExecutor

---

bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/FilterCriteria.java

make methods null safe

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingRegistryImpl.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java

relates to #5112, #4565 and others

include providers in duplicate element warning

---

extensions/transform/org.eclipse.smarthome.transform.exec/README.md

Update Exec Readme

---

bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/validation/test/ConfigDescriptionValidatorTest.groovy
bundles/config/org.eclipse.smarthome.config.core.test/src/test/groovy/org/eclipse/smarthome/config/core/validation/test/ConfigValidationExceptionTest.groovy
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/net/NetworkConfigOptionProvider.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/ConfigDescriptionParameterValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/ConfigDescriptionParameterValidatorFactory.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/ConfigDescriptionValidatorImpl.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/MessageKey.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/MinMaxValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/PatternValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/RequiredValidator.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/TypeIntrospections.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/validation/TypeValidator.java

fixed internal package names

---

extensions/transform/org.eclipse.smarthome.transform.jsonpath/README.md

Update JsonPath Readme

---

extensions/transform/org.eclipse.smarthome.transform.xpath/README.md

Added an example which adresses basic operation of the xpath transformation.

Update XPATH README.md

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java

Fix NPE in rare cases that VPN software creates interfaces without IP address

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

marked internal services as deprecated to make developers aware that those must not be used

---

extensions/transform/org.eclipse.smarthome.transform.regex/README.md

Update REGEX README.md

---

extensions/transform/org.eclipse.smarthome.transform.xslt/README.md

Added simple example with explanation.

Update XSLT README.md

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

- Added `isLinked` method with parameter `channelUID`

[core] Added 'isLinked' method with parameter 'channelUID'

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java

Fix nullannotations in ItemResource and possible NPEs in ItemDTOMapper

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/thing/ThingResource.java

...in the same manner as with Thing configurations.
fixes #4910

normalize channel configurations in ThingResource

---

bundles/model/org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/jvmmodel/RulesJvmModelInferrer.xtend

Do not inject previousState var into rules multiple times

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java

Fix NPE in NetUtil if interface does not have a broadcast address

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/util/UnitUtils.java

Fixes the compile error introduced by #5194.

Fix UnitUtils compile error

---

docs/_includes/documentation-menu.html

Added Bluetooth binding to the menu

---

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java

defensive comparison in archetype's handler factory

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java

let ChartServlet component expose a service

---

docs/_config.yml
docs/_posts/2018-02-22-units-of-measurement.md

Fix link to QuantityType in UoM blog post

---

extensions/binding/org.eclipse.smarthome.binding.ntp.test/src/test/java/org/eclipse/smarthome/binding/ntp/test/NtpOSGiTest.java

ignore NTP binding tests until they are fixed

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/util/HexUtilsTest.java
bundles/core/org.eclipse.smarthome.core/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/util/HexUtils.java
docs/documentation/development/bindings/dependencies.md
extensions/binding/org.eclipse.smarthome.binding.bluetooth.bluez/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.bluetooth.bluez/src/main/java/org/eclipse/smarthome/binding/bluetooth/bluez/BlueZBluetoothDevice.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/BeaconBluetoothHandler.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/BluetoothUtils.java
tools/archetype/binding/src/main/resources/archetype-resources/META-INF/MANIFEST.MF

- added support for manufacturer data scan notifications in BlueZ
- only update RSSI if a value is set
- introduced a Utils class for some generally useful methods when dealing with Bluetooth data

Some Bluetooth binding improvements

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeGroupFunctionTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/GroupFunctionHelper.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeGroupFunction.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
docs/documentation/concepts/items.md
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/items/controllers.items.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/shared.properties.js

Fixes: #5177
Signed-off-by: Robert Michalak <rbrt.michalak@gmail.com>

added LATEST and EARLIEST group functions for DateTime groups

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpClientFactory.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/SecureHttpClientFactory.java

Signed-off-by: Michael Bock <mbock@gmxpro.de>

don't start custom client

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiJavaTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

Whenever there was a ThingHandler which failed to initialize,
e.g. because of a missing/non-configured bridge, then the framework
would not updated this ThingHandler's Thing reference as soon
as there was an update on that Thing. As a result, the ThingHandler
operated on the old Thing instance with all its consequences.
fixes #5215

fix reference mess when updating uninitialized things

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/Items.xtext
bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/Thing.xtext
distribution/smarthome/conf/items/demo.items

added Image item type again

---

extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java

Prevent NPEs if no configuration is available

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/SoftwareUpdate.java

Removed TODO comment in SoftwareUpdate

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/QuantityTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/QuantityType.java

This addresses the remaining issues from #5268.

QuantityType: parse exponential values more stable

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java

removed UUID from label and added representation property instead

---

bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml

Magic: Fix thing-description xsd location

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerBuilderImpl.java

...in order to do so with o.e.sh.core bundle's permissions.
fixes #5288

switch security context when creating dynamic proxy in SafeCaller

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
extensions/binding/org.eclipse.smarthome.binding.yahooweather/README.md

Also:
* Adopt state descriptions for WU channels to reflect dynamic unit conversion.
* Create QuantityType states for all channels.

UOM: Update YahooWeather & WeatherUnderground binding docs

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/ESH-INF/thing/blukii.xml
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/BlukiiBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/handler/BlukiiHandler.java

- switched to UoM support
- removed "switch" channel as updates are too slow
- removed todo for magnetic values (fixes #5257)

Improvements on Blukii support

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/scheduler/CronExpressionTest.java

The current test execution depends on the TimeZone and current time of
the system the test is executed. That is not optimal as tests could
succeed on the one machine but fail on the other one.
Added another test (currently ignored, too), that uses the TimeZone and
start time the error occurs.
Related to: https://github.com/eclipse/smarthome/issues/5294

CronExpression: start using fixed test input

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java

Also fixed previously added radios to properly check model number (not model name).
Source: https://community.openhab.org/t/internet-radio-i-need-your-help/2131

Further radio models added to auto discovery.

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/BeaconBluetoothHandler.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/ConnectedBluetoothHandler.java

prevent potential NPE on dispose

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/QuantityTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/QuantityType.java

QuantityType: Add default constructor

---

bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/ConfigMapper.java

See https://github.com/eclipse/smarthome/pull/5292#issuecomment-376770020.

ConfigMapper: Add author tag & JavaDoc

---

bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicServiceImpl.java

fix logging in magic service

---

extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js

* Fix memory leaks in BasicUI from ESH code. Without proper event listeners cleanup, DOM nodes were left hanging detached in heap. This should improve long-term UI stability.
* Pause any media elements before navigation

BasicUI: properly destroy controls before navigation

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/util/HexUtilsTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/util/HexUtils.java

Relates to https://github.com/openhab/openhab2-addons/pull/3430
openHAB needs this because we want to get rid of using the javax DatatypeConverter

Extend hex utils to include the reverse operation

---

bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/ConfigDescriptionConverter.java
bundles/core/org.eclipse.smarthome.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/BindingInfoConverter.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java
bundles/core/org.eclipse.smarthome.core.transform/src/main/java/org/eclipse/smarthome/core/transform/TransformationHelper.java
bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/DialogProcessor.java
bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/text/ExpressionSequence.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/exec/ExecUtil.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/thing/ThingResource.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java
bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/JSONResponse.java
bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java
bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaTest.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/util/PropertyUtils.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/src/test/java/org/eclipse/smarthome/binding/fsinternetradio/test/FSInternetRadioHandlerJavaTest.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueBridge.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/internal/http/WemoHttpCall.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/PageRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/servlet/WebAppServlet.java
tools/static-code-analysis/pmd/suppressions.properties

Fixed pmd issues found is smarthome - AvoidCatchingNPE and AvoidThrowingRawExceptionTypes.

Fixed AvoidCatchingNPE and AvoidThrowingRawExceptionTypes issues found by PMD

---

docs/documentation/development/guidelines.md

Clarify reasons for null annotations in coding guidelines

---

docs/documentation/development/guidelines.md

Fix typo in coding guidelines

---

bundles/core/org.eclipse.smarthome.core.transform/src/main/java/org/eclipse/smarthome/core/transform/AbstractFileTransformationService.java

Related to:
* https://github.com/eclipse/smarthome/pull/5365#discussion_r179615514
* https://github.com/eclipse/smarthome/pull/5365#discussion_r179616640

file transformation: harden watch service handling

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java

Chart servlet: define configurationPid

---

extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/moon.xml
extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/sun.xml

Fixes #5310
Is this a proper fix for the issue @lolodomo ?

[Astro] Add channel group descriptions

---

features/org.eclipse.smarthome.feature.runtime.core/feature.xml

added new serial bundles to p2 feature

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

...but on the other hand making sure that the handler gets the blame.
relates to #5375

Handle missing callbacks gracefully in BaseThingHandler

---

docs/_includes/documentation-menu.html
docs/documentation/development/conventions.md
docs/documentation/development/guidelines.md

Documentation: Move null annotation explanation section into separate page

---

bundles/ui/org.eclipse.smarthome.ui.test/META-INF/MANIFEST.MF
bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

make ui label and value coloring compatible with QuantityType

---

pom.xml

Found during review in https://github.com/openhab/openhab2-addons/pull/3087#issuecomment-379549320

Nullannotation warnings: Sync maven settings with IDE settings again

---

extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoCoffeeHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoHandler.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/handler/WemoMakerHandler.java

[WeMo] remove implementation of DiscoveryListener from handler. Fixes #4662

---

bundles/automation/org.eclipse.smarthome.automation.commands/src/main/java/org/eclipse/smarthome/automation/internal/commands/AutomationCommandExport.java

fixed NPE in automation export command

---

bundles/automation/org.eclipse.smarthome.automation.sample.extension.java/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery.mdns.test/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.discovery.usbserial.test/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.rest.sitemap.test/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.transport.serial.javacomm/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.transport.serial/META-INF/MANIFEST.MF
bundles/test/org.eclipse.smarthome.test/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.bluetooth.bluez/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.bluetooth.test/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.bluetooth/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.serialbutton/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.yahooweather/META-INF/MANIFEST.MF

See openhab/static-code-analysis#285
See openhab/static-code-analysis#295

Fixed occurrences of lines bigger than 72 bytes in some manifest files.

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpClientInitializationException.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/SecureHttpClientFactory.java

Signed-off-by: Michael Bock <mbock@gmxpro.de>

review comments for jetty client factory

---

extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml

fixes #5266 <- let's be optimistic 😉 

[Paper UI / Infra] upgrade to NPM 5.8.0

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/HSBTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/PointTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

PointType and HSBType: Trim whitespaces from constructor arguments

---

bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/ZoneTemperatureControlHandler.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/DeviceStateUpdate.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/structure/devices/impl/DeviceImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/structure/scene/SceneDiscovery.java

As discussed with the authors in the linked issues.
Fixes #5259
Fixes #5272
Fixes #5271
Fixes #5269
Fixes #5263
Fixes #5275

Removed TODOs from Digitalstrom binding and XmlDocumentBundleTracker

---

docs/documentation/development/ide.md

Doc: Mention python dependency for UI builds

---

extensions/io/org.eclipse.smarthome.io.javasound/src/main/java/org/eclipse/smarthome/io/javasound/internal/AudioPlayer.java

Nothing really todo in the code as it works well, so removing the according comment.
fixes https://github.com/eclipse/smarthome/issues/5286

removed todo in AudioPlayer

---

docs/index.html

added COQON to the references on the homepage

---

docs/_includes/documentation-menu.html

[docu] added Bose SoundTouch binding to the menu

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerImpl.java
bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/ModelServer.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.bluez/src/main/java/org/eclipse/smarthome/binding/bluetooth/bluez/internal/BlueZHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/BlukiiHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/internal/BluetoothHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/test/DmxTestHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/DmxHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/FSInternetRadioHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java

It's not necessary to add ConfigurationPolicy.OPTIONAL because it is defined in the `@interface Component` as:
```java
ConfigurationPolicy configurationPolicy() default ConfigurationPolicy.OPTIONAL;
```

Remove default configurationPolicy = ConfigurationPolicy.OPTIONAL

---

extensions/io/org.eclipse.smarthome.io.mqttembeddedbroker.test/pom.xml
extensions/io/org.eclipse.smarthome.io.mqttembeddedbroker.test/src/test/java/org/eclipse/smarthome/io/mqttembeddedbroker/internal/MqttEmbeddedBrokerServiceTest.java
extensions/io/org.eclipse.smarthome.io.mqttembeddedbroker/pom.xml
extensions/io/pom.xml
features/karaf/esh-ext/src/main/feature/feature.xml
features/org.eclipse.smarthome.feature.runtime.core/feature.xml

added embedded MQTT broker to features

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/types/SmartHomeUnitsTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java

Add the units mmHg and knot

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/AstroHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.dmx/src/main/java/org/eclipse/smarthome/binding/dmx/internal/DmxHandlerFactory.java

added missing configurationPid parameters

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/SitemapSubscriptionService.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/sitemap/SitemapProvider.java
bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/sitemap/internal/SitemapProviderImpl.java

This partially reverts #3846.
fixes #5522

refresh internal widget collection on sitemap change

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/ThingManagerTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java

delay usage of ThingHandlerFactories until ThingManager is active

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/handler/AstroThingHandler.java
tools/static-code-analysis/checkstyle/suppressions.xml

Fixes #5519 
Signed-off-by: Mark Hilbush <mark@hilbush.com>

[astro] Fix time drift of positional job

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/i18n/UnitProvider.java

Fix JavaDoc for UnitProvider

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

Fix obsolete unit reported to UIs

---

bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java
bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerManager.java
bundles/model/org.eclipse.smarthome.model.rule.tests/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.rule.tests/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleExecutionTest.java
bundles/model/org.eclipse.smarthome.model.rule.tests/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerTest.java

fixes https://github.com/eclipse/smarthome/issues/5578

check for null in trigger states and added execution tests

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/SitemapSubscriptionService.java
bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java

Sitemap SSE: check that the subscription is linked to a page

---

extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/ESH-INF/config/config.xml
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/ESH-INF/thing/SoundTouch10.xml
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/ESH-INF/thing/SoundTouch20.xml
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/ESH-INF/thing/SoundTouch30.xml
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/README.md
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/BoseSoundTouchBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/BoseSoundTouchConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/handler/BoseSoundTouchHandler.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/BoseSoundTouchNotificationChannelConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/CommandExecutor.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/PresetContainer.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/discovery/SoundTouchDiscoveryParticipant.java

Add support for the Notification API described here:
https://developer.bose.com/soundtouch-audio-notification-api/apis

Add Notification API support

---

docs/documentation/development/bindings/faq.md

Documentation: FAQ: Explain how to path images through channels via RawType

---

bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java

Sitemap SSE: fix for visibility/color attribute handling

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/QuantityTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java

This fixes the exception that has been [reported here](https://community.openhab.org/t/openhab-2-3-release-candidate-available/45318/8?u=kai).

fixes handling of IRRADIANCE unit

---

bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/extension/ScriptEngineConsoleCommandExtension.java

fixes https://github.com/openhab/openhab-distro/issues/695

[Core] Renamed script console command from ">" to "script"

---

bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java

Fixes: https://github.com/eclipse/smarthome/issues/5616

xml document bundle tracker: execute submitted task only if opened

---

bundles/io/org.eclipse.smarthome.io.net/META-INF/MANIFEST.MF

Fixes: https://github.com/eclipse/smarthome/issues/5613

io.net: fix missing package import

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java

reduce log level for warnings about optional dependencies

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/repositories/repositories-module.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.view.js

Also: Fix a null reference on channel linking.
Fixes #5604.

Paper UI: Fix dupes error on controll page.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.edit.js

PaperUI: Fix NPE in Thing Editor

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriCoapClient.java

...by cancelling previous observers and restarting the endpoint whenever the connection got lost.
fixes #5622

[Tradfri] Fixed memory leak

---

docs/_includes/documentation-menu.html
docs/documentation/development/bindings/profiles.md

Add documentation about How to implement Profiles

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/items/controllers.items.js

Paper UI: always resolve promise for metadata update

---

extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/OperationModeType.java

fix issue described in
https://github.com/eclipse/smarthome/issues/5636
Signed-off-by: Thomas Traunbauer thomas.traunbauer@gmail.com

fix issue 5636

---

bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/java/org/eclipse/smarthome/io/rest/core/internal/item/MetadataSelectorMatcherTest.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/MetadataSelectorMatcher.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/items/directive.metadata-details.js

Fix item resource metadata retrieval

---

docs/documentation/development/bindings/discovery-services.md

Document re-discovery of things

---

bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/ItemConsoleCommandExtension.java

Now consistent with output for smarthome things list
Fixes #5641

ItemConsoleCommand: Distinguish between no item found and no item for pattern

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/Metadata.java
bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/MetadataConsoleCommandExtension.java

added metadata console command

---

bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/ItemConsoleCommandExtension.java

Fix ItemConsoleCommand duplicate null check

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HttpClient.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/HueBridge.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/StateUpdate.java

This commit solves the problem described in [this issue](https://github.com/eclipse/smarthome/issues/4794) by implementing a message delay [as suggested by Philips](https://developers.meethue.com/documentation/hue-system-performance).
Signed-off-by: David Masshardt <david@masshardt.ch> (github: TheNetStriker)

Implement message delay

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/handler/HueBridgeHandlerOSGiTest.java

Add scheduler to HueBridgeHandlerOSGiTest

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.test/pom.xml
extensions/io/org.eclipse.smarthome.io.mqttembeddedbroker.test/pom.xml

Fixes: https://github.com/eclipse/smarthome/issues/5655

fix tycho maven plugin version reference

---

docs/documentation/concepts/units-of-measurement.md

Typo of Hektopascal

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/thing/ThingResource.java

Fixes: https://github.com/eclipse/smarthome/issues/5674
Please check if this really fixes your issue...

use media type json for thing's config status REST response

---

extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/ContentItem.java

BoseSoundtouch: Fix NPE

---

bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/MetadataConsoleCommandExtension.java

Also changed "remove" command to get it working even if the item is no longer existing. 

added "dump" to metadata command

---

bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/MetadataConsoleCommandExtension.java

fixed a bug in metadata command line parsing for configuration arguments

---

bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/bridge-types.xml
extensions/binding/org.eclipse.smarthome.binding.mqtt/ESH-INF/binding/binding.xml
extensions/binding/org.eclipse.smarthome.binding.mqtt/ESH-INF/thing/thing-types.xml

Fixed indentation of some xml files.

---

bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/extensions/AbstractConsoleCommandExtension.java
bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/extensions/ConsoleCommandExtension.java
bundles/io/org.eclipse.smarthome.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/MetadataConsoleCommandExtension.java

Related to: https://github.com/eclipse/smarthome/pull/5647/files#r193361449

add nullness annotations to metadata console command extension and bases

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SelectionRenderer.java

Basic UI: consider item options for selection widget when no mapping is defined

---

docs/documentation/development/ide.md
targetplatform/EclipseSmartHome.setup

Also: Rename project label to "Runtime".

Install groovy support from 4.8 snapshot branch (Photon)

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/QuantityTypeArithmeticGroupFunction.java

Consider GroupItem's base dimension in arithmetic group functions

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/setup/setup.html

[Paper UI] Sort bindings in inbox scan alphabetically

---

bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/sitemap/internal/SitemapProviderImpl.java

[Core] Prevented exceptions when dealing with empty sitemap models

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java

...i.e. if no other metadata provider already provided them.
fixes #5670

Only write tags if needed

---

bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/ModelRepositoryChangeListener.java
bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/sitemap/SitemapProvider.java
bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/sitemap/internal/SitemapProviderImpl.java

Also add the annotations to the related files.

add nullness annotations to SitemapProvider

---

bundles/core/org.eclipse.smarthome.core.autoupdate/src/main/java/org/eclipse/smarthome/core/autoupdate/AutoUpdateBindingConfigProvider.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/AutoUpdateGenericBindingConfigProvider.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/BindingConfigReader.java
bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java

Also add the annotations to the related files.

add nullness annotations to AutoUpdateBindingConfigProvider

---

extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js

Basic UI: fix selection of buttons (switch widget)

---

bundles/config/org.eclipse.smarthome.config.discovery.mdns/src/main/java/org/eclipse/smarthome/config/discovery/mdns/internal/MDNSDiscoveryService.java
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/MDNSClient.java
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSClientImpl.java

MDNS discovery fix

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/StateUpdate.java

Hue: Cache sentColortemperature and sentBrightness in all cases 

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/app.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/rules/controllers.rules.js

[Paper UI] fixed drag & drop order in rules editor

---

features/karaf/esh-core/src/main/feature/feature.xml
features/karaf/esh-ext/src/main/feature/feature.xml
features/karaf/esh-tp/src/main/feature/feature.xml
features/karaf/verify/pom.xml
pom.xml

This replaces #5577
The feature handling has been improved by removing injection of multiple target platform features in the base one.
The Swagger feature usage needs to be checked again, but ATM there are at least no hard dependencies (AFAI can identify).

improve karaf target platform feature repository

---

extensions/binding/org.eclipse.smarthome.binding.sonos/README.md

Add warning for advanced network configurations

---

extensions/ui/org.eclipse.smarthome.ui.basic/.gitignore

[BasicUI] gitignore updated

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java

Sonos: update alarm properties only when alarm state changes

---

bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/thing/ThingResource.java

Fixed HTTP 500 Internal Server Error thrown by /{thingUID}/status
Signed-off-by: YordanDZhelev <zhelev.yordan@gmail.com>

Fixed HTTP 500 Internal Server Error thrown by /{thingUID}/status

---

docs/documentation/development/bindings/profiles.md

Documentation: Explain SystemFollowProfile

---

bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/BindingConfigParseException.java

related to https://github.com/openhab/openhab-core/pull/359

added constructor that allows adding the root cause

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/types/SmartHomeUnitsTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/dimension/ArealDensity.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java

In prevision of OpenUV binding

Adding Dobson Unit to SmarthomeUnits

---

extensions/voice/org.eclipse.smarthome.voice.mactts/META-INF/MANIFEST.MF
extensions/voice/org.eclipse.smarthome.voice.mactts/README.md
extensions/voice/org.eclipse.smarthome.voice.mactts/src/main/java/org/eclipse/smarthome/voice/mactts/internal/MacTTSService.java
extensions/voice/org.eclipse.smarthome.voice.mactts/src/main/java/org/eclipse/smarthome/voice/mactts/internal/MacTTSVoice.java

rename MacOS TTS to macOS TTS

---

extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/BridgeHandler.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/setup/controllers.setup.js

Unkown -> Unknown

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SwitchRenderer.java

Render a switch widget with buttons when the linked item has a maximum of 4 state options

[Basic UI] Consider item options for switch widget

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/SecureHttpClientFactory.java

reduced logging level of framework internal code

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManager.java

See https://community.openhab.org/t/openhab-2-4-weird-error-messages-while-triggering-some-items/46607

fix NPE in case the channel doesn't define an accepted item type

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/AsyncProxyServlet.java
bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServletService.java

Disable timeout for proxied video widgets
Avoid browser caching for video widgets
Fixes #4873
Fixes #5111

Proxy service: adjustments for video widgets

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java

Add advanced logging to ChannelItemProvider

---

docs/index.html

fixed link to Smart Visu Server

---

extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/SwitchRenderer.java
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SwitchRenderer.java

Render a switch widget with buttons when the linked item has a maximum of 4 state options
Fix Basic UI to use the special character representing "..."

[Classic UI] Consider item options for switch widget

---

features/karaf/esh-tp/src/main/feature/feature.xml
targetplatform/smarthome.target

New JUPnP version has been released: https://github.com/jupnp/jupnp/releases/tag/2.4.0

upgraded to JUPnP 2.4

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/configuration.thingproperties.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.view.js

Maybe `getKeysArray` can move to a more reusable place or perhaps you know of an even better way to do this? :-)

[Paper UI] Sort Thing properties by key name alphabetically

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/setup/controllers.setup.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/setup/dialog.scan.html

[Paper UI] Sort bindings in 'Scan for Things' dialog alphabetically

---

pom.xml

Fix Build: xtend-maven-plugin requires equinox.common > 3.10

---

features/karaf/esh-ext/src/main/feature/feature.xml
features/org.eclipse.smarthome.feature.runtime.binding/feature.xml

added homematic binding to features

---

docs/documentation/development/conventions.md

Documentation: Nullannotations should be written before the type

---

docs/documentation/concepts/units-of-measurement.md

Signed-off-by: Vincent Regaud <vzorglub@gmail.com>

Added list of Units and Prefixes

---

extensions/transform/org.eclipse.smarthome.transform.scale/src/main/java/org/eclipse/smarthome/transform/scale/internal/ScaleTransformationService.java

Fix ScaleTransformationService is unavailable

---

bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSClientImpl.java

Using the network address change listener, this change allow new jmdns instances to be created for new network interfaces; and delete jmdns instances of which the network interfaces have been removed.
This will allow mDNS discovery to function seamlessly when WiFi stick is added or removed. 
jmDNS actually has a jmmDNS implementation (extra m), which takes care of multiple network interfaces.  However, that implementation is uncharted territory.  I wish to keep everything that already works well in jmDNS as-is.

Bugfix jmDNS cannot cope with network changes

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/types/SmartHomeUnitsTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java

Signed-off-by: Vincent Regaud <vzorglub@gmail.com>

Added bar unit to SmartHomeUnits.java

---

bundles/automation/org.eclipse.smarthome.automation.module.media/src/main/java/org/eclipse/smarthome/automation/module/media/internal/MediaScriptScopeProvider.java

fix voice/audio script extension provider

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/items/ItemRegistryOSGiTest.java

Addresses #5844, since this can not be reproduced locally lets give it a shot.

Fix random failing ItemRegistryOSGiTest

---

docs/documentation/concepts/units-of-measurement.md

Signed-off-by: Vincent Regaud <vzorglub@gmail.com>

Added bar to units docs and corrected typos

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/type/ThingTypeBuilderTest.java

Fix typo in test method names

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/type/ChannelTypeBuilderTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/AbstractChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/IChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/StateChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/StateChannelTypeBuilderImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/TriggerChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/TriggerChannelTypeBuilderImpl.java
docs/documentation/development/bindings/thing-definition.md

Also includes a ChannelTypeBuilder for more readability on creating
ChannelTypes.
Fixes #3756

Implement new SystemChannelTypes

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/internal/items/ItemRegistryOSGiJavaTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java
bundles/model/org.eclipse.smarthome.model.item.tests/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.item.tests/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider2Test.java
bundles/model/org.eclipse.smarthome.model.item.tests/src/org/eclipse/smarthome/model/item/internal/GenericMetadataProviderTest.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java
bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericMetadataProvider.java

Notify item registry change listeners with tags from metadata

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/type/AbstractChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/type/IChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/type/StateChannelTypeBuilderImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/type/TriggerChannelTypeBuilderImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/StateChannelTypeBuilder.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/TriggerChannelTypeBuilder.java

Move implementation of ChannelTypeBuilder to internal package

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/type/IChannelTypeBuilder.java

Fix typo in Javadoc of ChannelTypeBuilder interface

---

docs/documentation/concepts/audio.md
docs/documentation/concepts/categories.md
docs/documentation/concepts/discovery.md
docs/documentation/concepts/items.md
docs/documentation/concepts/profiles.md
docs/documentation/concepts/things.md
docs/documentation/concepts/units-of-measurement.md

For reference: openhab/openhab-docs#728
I have also thrown all markdown tables in the tablesgenerator.
Also some spelling errors, but only the ones i recognized while scrolling.
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

Capitalized smarthome concept terms

---

docs/_includes/documentation-menu.html

added homematic binding to the docu menu

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/SystemWideChannelTypesTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java

See https://github.com/eclipse/smarthome/pull/5855#issuecomment-404187310

Add new SystemChannels to channelType list of DefaultSystemChannelTypeProvider

---

bundles/io/org.eclipse.smarthome.io.transport.serial.javacomm/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortImpl.java
bundles/io/org.eclipse.smarthome.io.transport.serial.rxtx/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortImpl.java
bundles/io/org.eclipse.smarthome.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/SerialPort.java
bundles/io/org.eclipse.smarthome.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/UnsupportedCommOperationException.java

Related to https://github.com/eclipse/smarthome/pull/5885#issuecomment-404875046

added further methods to SerialPort

---

.travis.yml

Activate Travis cache for m2, p2 & npm_cache directories

---

bundles/config/org.eclipse.smarthome.config.discovery.upnp/src/main/java/org/eclipse/smarthome/config/discovery/upnp/internal/UpnpDiscoveryService.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/net/NetworkAddressChangeListener.java
bundles/io/org.eclipse.smarthome.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSClientImpl.java

Added primary address change to the NetworkAddressChangeListener
Signed-off-by: Tim Roberts <troberts@bigfoot.com> (github: tmrobert8)

Added primary address change to the NetworkAddressChangeListener

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java

Sonos: fix discovery with firmware 9.0

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/SystemWideChannelTypesTest.java
bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/java/org/eclipse/smarthome/core/thing/xml/test/SystemWideChannelTypesTest.java

Follow up to #5934
See https://github.com/eclipse/smarthome/pull/5934#pullrequestreview-139066837

SystemWideChannelTypesTests get specific service

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java

when an appropriate storage service is not (yet) registered
Addresses #5920 
Signed-off-by: Jan Hendriks <Jan.Hendriks@telekom.de>

Addresses a NPE in PersistentInbox

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/internal/items/ItemTagTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/items/ItemRegistryOSGiTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java

tags are compared case insensitive

---

features/karaf/esh-core/src/main/feature/feature.xml
features/karaf/esh-ext/src/main/feature/feature.xml
features/karaf/esh-tp/src/main/feature/feature.xml

and bump version from 3.2 to 3.3
Related to: https://github.com/eclipse/smarthome/issues/5974#issuecomment-408781639

move commons-net from base TP feature to separate one

---

targetplatform/smarthome.target

switched commons-net from 3.2 to 3.3 in smarthome.target

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/TradfriBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriPlugHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/discovery/TradfriDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/model/TradfriLightData.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/model/TradfriPlugData.java

Fixes https://github.com/eclipse/smarthome/issues/5935

added support for OnOff Plugs to TRADFRI binding

---

tools/archetype/binding.test/src/main/resources/archetype-resources/src/test/java/__bindingIdCamelCase__HandlerTest.java
tools/archetype/binding.test/src/main/resources/archetype-resources/src/test/java/__bindingIdCamelCase__OSGiTest.java

fixed tests generated by archetype

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/StringListTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/StringListType.java

This fixes the issue discussed in #5972

fix StringListType construction with empty constituents

---

bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java

- Consider default persistence service
- Added dependency to `PersistenceServiceRegistry` instead of collecting the services on its own
Closes #5993 
// CC @triller-telekom 

[UI / Charts] Consider default persistence service

---

extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/PacketFactory.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/protocol/PacketHandler.java
extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/util/LifxSelectorUtil.java

* Fix null analysis warnings
* Suppress resource warning false positives

[LIFX] Fix null analysis warnings, suppress resource warning false positives

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/discovery/AstroDiscoveryService.java

Astro: remove dead code

---

extensions/binding/org.eclipse.smarthome.binding.astro.test/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.astro.test/src/test/groovy/org/eclipse/smarthome/binding/astro/test/cases/AstroParametrizedTestCases.groovy
extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/channels.xml
extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/sun.xml
extensions/binding/org.eclipse.smarthome.binding.astro/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.astro/README.md
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/calc/MoonCalc.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/calc/SunCalc.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/model/MoonDistance.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/model/MoonPhase.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/model/Position.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/model/Radiation.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/model/Range.java
extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/util/PropertyUtils.java

- Incorporated new QuantityType (Units of Measurement)
Please add the APIBreaking label. The `kilometer` and `miles` channels have been replaced by a new  `distance` channel.
Closes #5775

[astro] Incorporated new QuantityType (Units of Measurement)

---

extensions/binding/org.eclipse.smarthome.binding.yahooweather/ESH-INF/i18n/yahooweather_de.properties
extensions/binding/org.eclipse.smarthome.binding.yahooweather/ESH-INF/thing/thing-types.xml

Yahoo weather: Fix item-type for UoM channels

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.js

Paper UI: allow linking plain Number items on UoM channels

---

extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/message/XmlRpcResponse.java

removed "since" annotation

---

extensions/binding/org.eclipse.smarthome.binding.yahooweather/ESH-INF/i18n/yahooweather_de.properties
extensions/binding/org.eclipse.smarthome.binding.yahooweather/ESH-INF/thing/thing-types.xml

YahooWeather: switch to the new system channels

---

bundles/core/org.eclipse.smarthome.core.test/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/internal/items/ItemUpdaterOSGiTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/items/ItemRegistryImplTest.java

Refactor ItemRegistryOSGiTest to plain unit test

---

bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/java/org/eclipse/smarthome/io/rest/core/internal/profile/ProfileTypeResourceTest.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/profile/ProfileTypeResource.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.profile-edit.dialog.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.spec.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.view.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/dialog.link-edit.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/dialog.linkchannel.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/directive.profile-selection.js

Filter profiles by ChannelTypeUID and ItemType

---

extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/channel.xml

Lifx: channel type category fixed for 2 channels

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.configDescription.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.configDescription.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.locationParameter.js

TODO: Refactor multiSelect with additional options. Its still broken.

Paper UI: refactor config description to component API

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/mapview.html
extensions/ui/org.eclipse.smarthome.ui.basic/snippets/webview.html
extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/WebviewRenderer.java

- Added label and icon for Webview widgets 
- Removed deprecated HTML attributes in Mapview snippet

[Basic UI] Show label and icon for Webview widgets

---

extensions/ui/org.eclipse.smarthome.ui.paper/pom.xml

Also: reformat o.e.s.ui.paper/pom.xml

Paper UI: clean node_modules & npm cache during mvn clean

---

extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html.template

Paper UI: move index.html to template & ignore generated index.html

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java

Fixes #6047 
Signed-off-by: Theo Giovanna <theo.giovanna@gmail.com>

[WU] Fix NPE in thing initialization

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleEngineImpl.java
bundles/automation/org.eclipse.smarthome.automation.integration.test/src/test/java/org/eclipse/smarthome/automation/integration/test/AutomationIntegrationTest.java

Fixes https://github.com/eclipse/smarthome/issues/6084

[Automation] Consider rule updates from the registry in the rule engine

---

bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java

Additionally compareToIgnoreCase is used for sorting so macOS TTS is not sorted at the end of the list.

Sort all voice parameter options with streams

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingDTOMapper.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/thing/ThingResource.java

Fixes: https://github.com/eclipse/smarthome/issues/6088

create correct type (bridge vs. thing) also if factory is not available

---

features/karaf/esh-tp/src/main/feature/feature.xml

upgrade feature to jmDNS 3.5.4

---

extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/structure/devices/impl/DeviceImpl.java

Without knowing much about the digitalSTROM code base, I am pretty sure that this PR fixes https://github.com/eclipse/smarthome/issues/6090

[digitalSTROM] fixes potential NPEs

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java

Add the CoreItemFactory and do not only depend on it

---

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java

Signed-off-by: Björn Brings <bjoernbrings@web.de>
Position literal first (review comment from openhab/#2990) and small extension of template to help start development
(there could be done much more, but I've no experience in this script language)

Position literals first in String comparison and small enhancement

---

extensions/binding/org.eclipse.smarthome.binding.onewire/README.md

fixed table layout

---

bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/channel-types.xml
bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml
bundles/test/org.eclipse.smarthome.magic/META-INF/MANIFEST.MF
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/MagicBindingConstants.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicImageHandler.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicPlayerHandler.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicRolllershutterHandler.java
bundles/test/org.eclipse.smarthome.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactory.java

Also add an extensible `choosy` channel which offers some options.

magic bundle: add image, player, rollershutter things

---

extensions/ui/org.eclipse.smarthome.ui.paper/package.json
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/color/component.control.color.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.item.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.item.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.tab.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.tab.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/contact/component.control.contact.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/control.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/controllers.control.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/dimmer/component.control.dimmer.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/image/component.control.image.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/player/component.control.player.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/rollershutter/component.control.rollershutter.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/rollershutter/component.control.rollershutter.js

Also:
* Fix font sizes, fix some minor stuff
* Fix thing link, fix #6142
Along with the refactoring the control page font sizes were reduced and some small layout changes made.
before:
update:

Paper UI: further control page refactoring

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/console/InboxConsoleCommandExtension.java

Console: command to remove inbox entries by thing UID or thing type

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/WrappedScheduledExecutorService.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/OnOffType.java

- Improved log warning, added space: exception was append to last word. 
- Added util methods to OnOffType to easy convert boolean/String to OnOffType.

Minor fixes

---

bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope.test/META-INF/MANIFEST.MF
bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope.test/pom.xml
bundles/automation/pom.xml

Reactivate DefaultScriptScope tests

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/color/component.control.color.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.item.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.tab.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/contact/component.control.contact.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/dimmer/component.control.dimmer.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/image/component.control.image.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/number/component.control.number.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/player/component.control.player.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/rollershutter/component.control.rollershutter.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/string/component.control.string.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/switch/component.control.switch.html

* Align item labels
* fix channel group names

Paper UI: fix control page style

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.configDescription.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.locationParameter.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.locationParameter.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/directive.validation.location.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/map/component.control.map.js

Paper UI: validate location input

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundHandler.java
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java

WU: automatic handling of French Canadian and British English

---

targetplatform/smarthome.target

added metrics API to target platform

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth.bluegiga/src/main/java/org/eclipse/smarthome/binding/bluetooth/bluegiga/internal/factory/BlueGigaHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.lirc/src/main/java/org/eclipse/smarthome/binding/lirc/internal/LIRCHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/OwHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.wemo/src/main/java/org/eclipse/smarthome/binding/wemo/internal/WemoHandlerFactory.java

Fix discovery service unregistration/deactivate order

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/AutoUpdateManagerTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/AutoUpdateManager.java

Fixed handling of OFFLINE things in case of multiple links in AutoUpdateManager

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/map/component.control.map.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/map/component.control.map.js

Paper UI: Allow multiple map widgets on the same page

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/AutoUpdateManager.java

removed invalid comment

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/PointType.java

- Added default pattern for formatting 'PointType' values
Closes #6110 

[core] Added default pattern for formatting 'PointType' values

---

bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/MetadataDTO.java
bundles/io/org.eclipse.smarthome.io.rest.core.test/src/test/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/items/controllers.items.js

* Fixed Paper UI to not persist empty metadata values.
* Fixed ItemResource to not accept empty metadata values.
Fixes #6201.

 Fix empty autoupdate metadata value

---

bundles/model/org.eclipse.smarthome.model.item/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/MappingUriExtensions.java
bundles/model/org.eclipse.smarthome.model.persistence/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.rule/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.script/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.sitemap/META-INF/MANIFEST.MF
bundles/model/org.eclipse.smarthome.model.thing/META-INF/MANIFEST.MF
features/karaf/esh-core/src/main/feature/feature.xml
features/karaf/esh-tp/src/main/feature/feature.xml
pom.xml
targetplatform/EclipseSmartHome.setup
targetplatform/smarthome.target

Closes: https://github.com/eclipse/smarthome/issues/6199

Xtext bump (2.14.0)

---

extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/discovery/AstroDiscoveryService.java

Astro: reduce useless high discovery search time

---

extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/internal/discovery/NtpDiscovery.java

NTP: reduce useless high discovery search time

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java

WU: reduce useless high discovery search time

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java

Hue: reduce useless high discovery search time for lights

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/types/util/UnitUtilsTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/util/UnitUtils.java

allow pure unit strings to be parsed

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheMapTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCache.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheMap.java

- Added methods to push a new value manually into the cache
See https://github.com/eclipse/smarthome/pull/4838#issuecomment-419378952

[cache] Added methods to push a new value manually into the cache

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/QuantityTypeTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/types/util/UnitUtilsTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/library/unit/UnitInitializer.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/QuantityType.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/types/util/UnitUtils.java
bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java

Initialize custom UoM unit parser

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/types/util/UnitUtilsTest.java

added test for imperial unit parsing

---

extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/handler/BoseSoundTouchHandler.java

When the player is OFFLINE and a command is received (usually this is REFRESH command)
there is a huge websocket client leak. Proposed fix:
1. Make openConnection and closeConnection calls synchronous.
2. Once the connection to the player is closed - set the commandExecutor to NULL
3. On each received command - check if the commandExecutor is NULL and if it is - skip the command

[Bose SoundTouch]: Fix websocket client leak

---

extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/i18n/astro_de.properties

[astro] Add german translation for moon eclipses

---

extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js

Paper UI: add test case for THING context & filter

---

extensions/ui/org.eclipse.smarthome.ui.basic/snippets/main_static.html

Basic UI: fix favicon for sitemap list

---

extensions/ui/org.eclipse.smarthome.ui.paper/tests/configService.test.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

Fixes #6274.
Also: slightly refactored configuration service for better readybility.

Paper UI: retain given options for contexts ITEM, THING, CHANNEL, RULE

---

pom.xml

Relates to https://github.com/openhab/openhab-core/pull/408.

Set maven-install-plugin version to 2.5.2

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java

- Fixed caching of ColorTemperature value and changed spelling

[Hue] Fixed caching of ColorTemperature value

---

extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/discovery/SoundTouchDiscoveryParticipant.java

Fix discovery for Bose SoundTouch 300

Fix discovery for Bose SoundTouch 300

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandlerTest.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/LightStateConverter.java

- Send XY command combined with a brightness command
Fixes #6299 

[Hue] Send XY command combined with a brightness command

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/views.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/component.control.item.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/string/component.control.string.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/string/component.control.string.js

Paper UI: fix string control

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java

Fixes: https://github.com/eclipse/smarthome/issues/6331
@davidgraeff Can you have a look at, too?

MQTT broker connection: allow to set persistence path

---

bundles/test/org.eclipse.smarthome.test/src/main/java/org/eclipse/smarthome/test/java/JavaOSGiTest.java

Signed-off-by: Victor Toni <victor.toni@gmail.com>

Added methods to JavaOSGiTest to retrieve multiple instances of a service.

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/configuration/directive.locationParameter.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/component.control.location.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/location/directive.validation.location.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/control/map/component.control.map.js

Paper UI: fix location validation

---

extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/handler/BoseSoundTouchHandler.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/ContentItem.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/XMLHandlerState.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/XMLResponseHandler.java
extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/src/main/java/org/eclipse/smarthome/binding/bosesoundtouch/internal/XMLResponseProcessor.java

Add containerArt to ContentItem when available

[Bose SoundTouch] Improve Content Item

---

features/karaf/esh-core/src/main/feature/feature.xml

Also rename the io-transport-http-auth-basic feature to io-http-auth-basic to reflect the bundle name.

move http auth bundle from esh-base to separate feature

---

bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemStateTriggerHandler.java

Resolves #6317 
Signed-off-by: Scott Rushworth openhab@5iver.com (github: openhab-5iver)

Changed ItemStateTriggerHandler to properly filter relevant topics

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/bindings/directive.binding-details.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/bindings/directive.binding-thingtypes.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/repositories/repositories-module.js

Fixes #6356.
Also minor cosmetics.

Paper UI: Fix binding details view

---

extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/OwBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/device/OwSensorType.java

Signed-off-by: Michal Wojcik <mgwojcik@interia.pl>

[One-Wire] Support for DS1420

---

extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/MultisensorThingHandler.java

Signed-off-by: Michal Wojcik <mgwojcik@interia.pl>

[One-Wire] Fixed refresh issue, was 10 seconds instead of 300

---

bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java

The future would not complete if the internal paho connection was not established yet.
That locked up the discovery in #6339.

MqttBrokerConnection: Subscribe future never completed in some circumstances

---

extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/DeviceHandler.java

[digitalstrom] safe guard percent values on state update

---

extensions/binding/org.eclipse.smarthome.binding.onewire.test/src/test/java/org/eclipse/smarthome/binding/onewire/owserver/OwserverConnectionTest.java
extensions/binding/org.eclipse.smarthome.binding.onewire.test/src/test/java/org/eclipse/smarthome/binding/onewire/test/OwserverTestServer.java

[onewire] Fix randomly failing OwserverConnectionTest

---

bundles/ui/org.eclipse.smarthome.ui.icon.test/META-INF/MANIFEST.MF
bundles/ui/org.eclipse.smarthome.ui.icon.test/src/test/java/org/eclipse/smarthome/ui/icon/internal/AbstractResourceIconProviderTest.java
bundles/ui/org.eclipse.smarthome.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/AbstractResourceIconProvider.java

Fix icon lookup for string type states including spaces

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/ruleengine/WrappedRule.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemStateConverterImpl.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/NumberItem.java

Signed-off-by: Jochen Hiller <jo.hiller@googlemail.com>

Fixed type casts where JDK compiler complained

---

docs/documentation/development/bindings/thing-definition.md

Documentation for DynamicStateDescriptionProvider

---

extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/event/EventListener.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/ConnectionManagerImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/StructureManagerImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/serverconnection/impl/HttpTransportImpl.java
extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/providers/DsChannelTypeProvider.java

- fix #6195 by ignoring HTTP-Status 500 and only use the JSON-Error-Message
- change new ChannelType(..) to ChannelTypeBuilder
- remove some more warnings
Signed-off-by: Michael Ochel <michael.ochel@koeln.de>

Fix #6195 and a bit more

---

extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/common/HomematicConfig.java
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/AbstractHomematicGateway.java
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/client/RpcClient.java
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/model/HmGatewayInfo.java

see https://community.openhab.org/t/homematic-binding-fails-with-hmip-only-raspberrymatic/54554

[Homematic] Added support for HMIP only gateways

---

extensions/ui/org.eclipse.smarthome.ui.classic/snippets/setpoint.html
extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/SetpointRenderer.java

[Classic UI] Dynamic icon for Setpoint widget

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriCoapClient.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriCoapHandler.java

- Added logging for CoAP requests
Addresses #6065 

[TRADFRI] Added logging for CoAP requests

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriLightHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriCoapClient.java

- Removed delay for color command handling to have a smoother transition (default delay is 600ms)
See https://community.openhab.org/t/setting-color-temp-causes-first-color-to-change-is-this-by-design/54037

[TRADFRI] Removed delay for color command handling to have a smoother transition

---

bundles/io/org.eclipse.smarthome.io.transport.serial.javacomm/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.transport.serial.javacomm/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/JavaCommPortProvider.java
bundles/io/org.eclipse.smarthome.io.transport.serial.rxtx/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.transport.serial.rxtx/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/RxTxPortProvider.java
bundles/io/org.eclipse.smarthome.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortManagerImpl.java

Serial framework; few logs added

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/CommunicationManagerTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManager.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/AbstractLinkRegistry.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java

link registry improvements

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/QuantityTypeTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java

add unit mbar

---

extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/AbstractHomematicGateway.java

see https://github.com/eclipse/smarthome/issues/6446

[Homematic] BINRPC changed to XMLRPC protocol due to CCU firmware 3.41.x

---

bundles/io/org.eclipse.smarthome.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortManagerImpl.java
bundles/io/org.eclipse.smarthome.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortRegistry.java

Fixes: https://github.com/eclipse/smarthome/issues/6444

harden the serial port manager for port provider errors

---

bundles/core/org.eclipse.smarthome.core.persistence/META-INF/MANIFEST.MF
bundles/core/org.eclipse.smarthome.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceManagerImpl.java

Fixes https://github.com/openhab/openhab-distro/issues/801

use safe caller for querying persistence service

---

extensions/binding/org.eclipse.smarthome.binding.mqtt/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.mqtt/README.md

MQTT Brokers: Add publishTrigger to readme

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java

Fixes: https://github.com/eclipse/smarthome/issues/6466

set of thing handlers for factory could be missing

---

bundles/config/org.eclipse.smarthome.config.core.test/META-INF/MANIFEST.MF
bundles/config/org.eclipse.smarthome.config.core.test/src/test/java/org/eclipse/smarthome/config/core/ConfigurationTest.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/ConfigMapper.java

Fixes #6448.
Also: Adds ConfigMapper test.

Map single values to List properties

---

bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/MappingUriExtensions.java

Fixes #6430 
I tested this in 2 scenarios
- VS Code and ESH on same host
- VS Code and ESH on different hosts using Samba share
It would be great if @sjka could look this over.
Signed-off-by: Mark Hilbush <mark@hilbush.com>

Fix for VS Code when using Samba share.

---

extensions/binding/org.eclipse.smarthome.binding.onewire.test/src/test/java/org/eclipse/smarthome/binding/onewire/device/DS1923Test.java
extensions/binding/org.eclipse.smarthome.binding.onewire/README.md
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/OwBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/device/DS1923.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/device/OwSensorType.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/MultisensorThingHandler.java

Another approach to DS1923 support.
@J-N-K Not sure how to complete it without introducing `th` type and dedicated handler.

[One-Wire] DS1923 support (second approach)

---

bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/ModuleImpl.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/util/ModuleBuilder.java
bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/util/RuleBuilder.java
bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java

Fixes: https://github.com/eclipse/smarthome/issues/6477

configuration should be copied not reused

---

bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheMapTest.java
bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/cache/ExpiringCacheTest.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCache.java
bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheMap.java
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/AbstractHomematicGateway.java

- Added null annotations to `ExpiryCache` and `ExpiryCacheMap`
- Add constructors with a Duration
Also-by: Martin van Wingerden martin@martinvw.nl

Added null annotations to ExpiryCache

---

extensions/transform/org.eclipse.smarthome.transform.regex/README.md

Fix regex README

---

extensions/binding/org.eclipse.smarthome.binding.homematic/README.md
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/AbstractHomematicGateway.java

closes https://github.com/eclipse/smarthome/issues/6493

[Homematic] Changed CUxD back to BIN_RPC

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/ThingConsoleCommandExtension.java
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.rest.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/configuration.things.view.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.view.js

Console command and Paper UI support for Thing disabled feature

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/CommunicationManagerTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManager.java

Addresses https://github.com/openhab/openhab2-addons/issues/4147.

Convert command to QuantityType for new UoM channel

---

extensions/binding/org.eclipse.smarthome.binding.weatherunderground/README.md

added info that the free api will be ended by end of 2018.

Updated readme.md

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth/src/main/java/org/eclipse/smarthome/binding/bluetooth/BeaconBluetoothHandler.java

We are using "@NonNullByDefault" and "@Nullable" but we do not use "@NonNull" annotations.

we do not use "@NonNull"

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/handler/BlukiiHandler.java

There is no need to fetch the data multiple times as it has already been stored to a local variable.

reuse already fetched variable reference

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/convention/homie300/Property.java
extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/generic/ChannelConfig.java
extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/generic/ChannelConfigBuilder.java
extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/generic/ChannelState.java

This PR fixes the problem described in the #6497 issue.
Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

Fix Homie trigger channels (fixes #6497)

---

bundles/core/org.eclipse.smarthome.core.thing.test/src/test/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemOffsetProfileTest.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemFollowProfile.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemOffsetProfile.java

- Fixed handling of state updates in system profiles
See https://github.com/eclipse/smarthome/pull/6451#issuecomment-439598333

Fixed handling of state updates in system profiles

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js

This was broken with PR #6398.
Also corrects channel and thing selection is certain cases.
Fixes #6557

Fix PaperUI item selection

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/handler/BlukiiHandler.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/data/Accelerometer.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/data/BlukiiData.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/data/BlukiiDataDecoder.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/data/Environment.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/data/Magnetometer.java

The split allows us to inspect that data decoding (e.g. add some unit tests later) separated without the need of the whole handler support stuff.

blukii: split handler and data decoding

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/data/BlukiiDataDecoder.java

Fixes: https://github.com/eclipse/smarthome/issues/6532

blukii: fix temperature decoding

---

features/karaf/esh-tp/src/main/feature/feature.xml
targetplatform/smarthome.target

Requires https://github.com/eclipse/smarthome/pull/6581
Fixes https://github.com/eclipse/smarthome/issues/6112

updated Paho client to 1.2.0

---

bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java

[Core] used the shared threadpool for the shared client

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerPlayPauseProfile.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactory.java
bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/SystemProfiles.java

Closes #6590
Signed-off-by: Daniel Weber <uni@fruggy.de>

Added PlayerItem profile for system raw rocker channels.

---

bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java

Fixes: https://github.com/eclipse/smarthome/issues/6534

harden the open / close handling

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/README.md

Signed-Off-By: David Graeff <david.graeff@web.de>

Readme: Add bridge definition to example

---

targetplatform/smarthome.target

related to https://github.com/eclipse/smarthome/pull/6596

removed source artifact of paho

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerPlayPauseProfile.java

Related to: https://github.com/eclipse/smarthome/pull/6591#discussion_r237471769

fix comment (copy 'n' paste error)

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/generic/ChannelState.java

[MQTT] fix connection handling for command-only channels

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/items/controllers.items.js

Fixes https://github.com/eclipse/smarthome/issues/6592
Signed-off-by: Henning Treu <henning.treu@googlemail.com>

Paper UI: Fix group item creation for base type None

---

extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/components.css
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/component.thing.statusInfo.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/component.thing.statusInfo.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/component.things-list-entry.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/component.things-list-entry.js
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/configuration.things.view.html
extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/things/controller.things.view.js

Signed-off-by: Henning Treu <henning.treu@googlemail.com>

Paper UI: move disabled button to thing list

---

extensions/binding/org.eclipse.smarthome.binding.openweathermap/README.md
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/handler/OpenWeatherMapAPIHandler.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/utils/ByteArrayFileCache.java

- Store / cache image files in a local folder
- Reduced discovery timeout
- Minor code improvements

[OWM] Store / cache icon files in a local folder and minor code improvements

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.test/src/test/java/org/eclipse/smarthome/binding/mqtt/handler/AbstractBrokerHandlerTest.java
extensions/binding/org.eclipse.smarthome.binding.mqtt/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.mqtt/src/main/java/org/eclipse/smarthome/binding/mqtt/handler/AbstractBrokerHandler.java
extensions/binding/org.eclipse.smarthome.binding.mqtt/src/main/java/org/eclipse/smarthome/binding/mqtt/handler/SystemBrokerHandler.java

fixes #6600 
Also-by: David Graeff <david.graeff@web.de>

[MQTT] added brokerid to configuration

---

NOTICE

updated contributor list

---

features/karaf/esh-tp/src/main/feature/feature.xml
targetplatform/smarthome.target

upgraded to JUPnP 2.5.0

---

features/karaf/esh-tp/src/main/feature/feature.xml
targetplatform/smarthome.target

upgraded to JmDNS 3.5.5

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/META-INF/MANIFEST.MF
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/LightStateConverterOSGiTest.java
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/LightStateConverterTest.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/State.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/handler/LightStateConverter.java

- Fixed brightness / saturation of 1 shown as off
Closes #6617 

[Hue] Fixed brightness of 1 shown as off

---

extensions/binding/org.eclipse.smarthome.binding.sonyaudio/src/main/java/org/eclipse/smarthome/binding/sonyaudio/handler/SonyAudioHandler.java
extensions/binding/org.eclipse.smarthome.binding.sonyaudio/src/main/java/org/eclipse/smarthome/binding/sonyaudio/internal/protocol/SonyAudioConnection.java

reduced some logging to debug level

---

extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/virtual/StateContactVirtualDatapointHandler.java

closes https://github.com/eclipse/smarthome/issues/5786

[Homematic] Added STATE_CONTACT support for all HMIP-SWDO devices

---

bundles/auth/org.eclipse.smarthome.auth.oauth2client/src/main/java/org/eclipse/smarthome/auth/oauth2client/internal/OAuthClientServiceImpl.java

When a call is made for a new access token it might not return the refresh token in the data.
This was the case with Spotify Api, only to find it out after 2 hours running. Because the first save is from the authorization and that contains the refresh token. The first call to refresh the access token (after 1 hour, expire time is 3600 sec.) sets the refresh token to null. And then after access token expires again (2nd hour) it gives the exception no refresh token available.
Some minor changes: Moved creating OAuthConnector after checks which throw exceptions.

[OAuth2] Fix storing empty refresh token on refreshToken call.

---

docs/documentation/development/bindings/thing-handler.md

Corrected documentation for channelLinked method

---

bundles/io/org.eclipse.smarthome.io.net.test/META-INF/MANIFEST.MF
bundles/io/org.eclipse.smarthome.io.net.test/src/test/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerTest.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManager.java

Signed-off-by: Martin van Wingerden <martin@martinvw.nl>

[io.net] Added test for null subject-alternative-names and fixed the NPE

---

bundles/automation/pom.xml
targetplatform/smarthome.target

removed outdated json dependencies

---

extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/handler/BlukiiHandler.java
extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii/src/main/java/org/eclipse/smarthome/binding/bluetooth/blukii/internal/data/BlukiiDataDecoder.java

Related to: https://github.com/eclipse/smarthome/issues/6532#issuecomment-446127455

blukii data decoding: add checks for valid data

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/ESH-INF/thing/generic-thing.xml

add missing channels to extensible in the thing-type xml
Signed-off-by: davidgraeff <david.graeff@web.de>

MQTT: thing-type xml, add channels to extensible

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/console/ThingConsoleCommandExtension.java

Follow up on #6604.
Signed-off-by: Henning Treu <henning.treu@googlemail.com>

Console: do not store enabled status for unknown thing

---

features/karaf/esh-tp/src/main/feature/feature.xml
targetplatform/smarthome.target

See https://github.com/jupnp/jupnp/releases/tag/2.5.1

Upgraded to JUPnP 2.5.1

---

bundles/io/org.eclipse.smarthome.io.net.test/src/test/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerTest.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManager.java

When a common-name is not found handle this more gracefully
When any CertificateParsingException is caught, log it and fallback to the defaultTrustManager
Fine tuned the handling of the `null` for `getSubjectAlternativeNames`
See also: https://community.openhab.org/t/sendhttpgetrequest-not-working-under-oh-2-4-m7-after-update-from-2-3/58967
See also: https://github.com/eclipse/smarthome/issues/6681 (this does not fix it btw)

[io.net] handle errors in certificates more gracefully

---

extensions/binding/org.eclipse.smarthome.binding.mqtt/README.md

Signed-off-by: davidgraeff <david.graeff@web.de>

MQTT: Readme, textual configuration, sub bindings

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/README.md

Signed-off-by: davidgraeff <david.graeff@web.de>

MQTT Readme:Blockquote instead of code.Fix example

---

extensions/binding/org.eclipse.smarthome.binding.mqtt/src/main/java/org/eclipse/smarthome/binding/mqtt/handler/AbstractBrokerHandler.java

Fixes https://github.com/openhab/openhab2-addons/issues/4393

MQTT: Fix recreating a Broker Thing future

---

extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/handler/AbstractMQTTThingHandler.java

MQTT: Code documentation

---

bundles/auth/org.eclipse.smarthome.auth.oauth2client.test/.project
bundles/auth/org.eclipse.smarthome.auth.oauth2client.test/pom.xml
bundles/auth/org.eclipse.smarthome.auth.oauth2client.test/src/test/java/org/eclipse/smarthome/auth/oauth2client/test/internal/cipher/CipherTest.java
bundles/auth/pom.xml

fixes https://github.com/eclipse/smarthome/issues/6678

added oauthclient tests to build

---

extensions/binding/org.eclipse.smarthome.binding.tradfri/README.md

Added Tradfri E1704 wireless control outlet

Add Tradfri Control Output wireless plug

---

extensions/binding/org.eclipse.smarthome.binding.homematic/ESH-INF/thing/bridge.xml
extensions/binding/org.eclipse.smarthome.binding.homematic/README.md
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/handler/HomematicBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/common/HomematicConfig.java
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/server/BinRpcNetworkService.java
extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/communicator/server/XmlRpcServer.java

closes https://github.com/eclipse/smarthome/issues/6547

[Homematic] Added bindAddress bridge parameter

---

pom.xml

Fixes https://github.com/eclipse/smarthome/issues/6717

pinned emf.codegen version

---

extensions/binding/org.eclipse.smarthome.binding.hue/README.md

- Fixed syntax and spelling in examples

[hue] Fixed syntax and spelling in examples

---

extensions/binding/org.eclipse.smarthome.binding.onewire.test/src/test/java/org/eclipse/smarthome/binding/onewire/test/OwserverTestServer.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/device/DS2406_DS2413.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/device/DS2408.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/owserver/OwserverConnection.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/owserver/OwserverPacket.java

Fixes #6720 
reported to work in OH forum

[OneWire] fix digitalio write

---

extensions/binding/org.eclipse.smarthome.binding.mqtt/README.md

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de>

[MQTT] Fix typo

---

extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md

Signed-off-by: Sven Festersen <sven@sven-festersen.de>

Added Auna KR200 to list of tested devices.

---

extensions/binding/org.eclipse.smarthome.binding.openweathermap/ESH-INF/config/config.xml
extensions/binding/org.eclipse.smarthome.binding.openweathermap/ESH-INF/i18n/openweathermap.properties
extensions/binding/org.eclipse.smarthome.binding.openweathermap/ESH-INF/i18n/openweathermap_de.properties
extensions/binding/org.eclipse.smarthome.binding.openweathermap/ESH-INF/i18n/openweathermap_fr.properties
extensions/binding/org.eclipse.smarthome.binding.openweathermap/ESH-INF/thing/channel-types.xml
extensions/binding/org.eclipse.smarthome.binding.openweathermap/ESH-INF/thing/thing-types.xml
extensions/binding/org.eclipse.smarthome.binding.openweathermap/README.md
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/config/OpenWeatherMapUVIndexConfiguration.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/factory/OpenWeatherMapHandlerFactory.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
extensions/binding/org.eclipse.smarthome.binding.openweathermap/src/main/java/org/eclipse/smarthome/binding/openweathermap/internal/model/OpenWeatherMapJsonUVIndexData.java

- Added support for UV Index API

[OWM] Added support for UV Index API

---

README.md

remove references to Designer and add VSCode extension instead reformatting for easier review in the future

updates to start page readme

---

docs/documentation/concepts/items.md

Signed-off-by: Chris Carman &lt;namraccr@gmail.com>

[Documentation] Grammar/structure cleanup for items.md section on Item Metadata

---

extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java

[Sonos] Tune-in radio started by Amazon Echo

---

bundles/io/org.eclipse.smarthome.io.net.test/src/test/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerImplTest.java
bundles/io/org.eclipse.smarthome.io.net.test/src/test/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryTest.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/ExtensibleTrustManager.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/TlsCertificateProvider.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/TlsProvider.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/TlsTrustManagerProvider.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/TrustAllTrustMananger.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerImpl.java
bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java

Also-by: Matthew Bowman <github@otr.mx>
Signed-off-by: Martin van Wingerden <martin@martinvw.nl>

[io.net] Add support for acting based on the hostname/port as supplied by sslEngine

---

extensions/binding/org.eclipse.smarthome.binding.mqtt/README.md

Added space for unsecure broker between host and secure=false.

Fix unsecure broker example

---

extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/OwBaseThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/owserver/OwserverConnection.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/owserver/OwserverPacket.java

[OneWire] improve connection handling and fix sensor id parsing error

---

bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java
extensions/binding/org.eclipse.smarthome.binding.mqtt.generic.test/src/test/java/org/eclipse/smarthome/binding/mqtt/generic/internal/convention/homeassistant/HaIDTests.java
extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/convention/homeassistant/HaID.java
extensions/binding/org.eclipse.smarthome.binding.mqtt.test/src/test/java/org/eclipse/smarthome/binding/mqtt/internal/MQTTTopicDiscoveryServiceTest.java
extensions/binding/org.eclipse.smarthome.binding.mqtt/src/main/java/org/eclipse/smarthome/binding/mqtt/discovery/TopicSubscribe.java

The first error on #6749 is caused by an error in HaID.
I created tests cases for HaID and fixed the problem.

Solve parts of #6749

---

extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/LightStateConverterTest.java
extensions/binding/org.eclipse.smarthome.binding.hue.test/src/test/java/org/eclipse/smarthome/binding/hue/internal/handler/HueLightHandlerTest.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/State.java
extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/handler/LightStateConverter.java

Fixes https://github.com/eclipse/smarthome/issues/6788

[hue] make sure that hue in HSBType is never >=360

---

extensions/binding/org.eclipse.smarthome.binding.onewire/ESH-INF/thing/bridge.xml
extensions/binding/org.eclipse.smarthome.binding.onewire/README.md
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/OwBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/OwBaseBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/OwserverBridgeHandler.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/owserver/OwfsDirectChannelConfig.java

Closes #6728. 
This adds direct access to OWFS nodes if an `owserver` bridge is used.

[OneWire] new  feature: OWFS-direct access

---

docs/documentation/index.md

remove reference to designer and point to VS code extension in doc

---

bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java

- Create channelUID instead of searching for the channel

[core] Create channelUID instead of searching for the channel

---

extensions/binding/org.eclipse.smarthome.binding.mqtt/ESH-INF/thing/thing-types.xml

update the parameter name to fix the issue

[mqtt] Updated thing-types to fix clientId

---

bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope/src/main/java/org/eclipse/smarthome/automation/module/script/defaultscope/internal/DefaultScriptScopeProvider.java

Signed-off-by: sprehn <sebastian.prehn@gmx.de>

Making queuedBeforeActivation in DefaultScriptScopeProvider non-nullable

---

extensions/binding/org.eclipse.smarthome.binding.onewire.test/src/test/java/org/eclipse/smarthome/binding/onewire/internal/CompletenessTest.java
extensions/binding/org.eclipse.smarthome.binding.onewire.test/src/test/java/org/eclipse/smarthome/binding/onewire/internal/SensorIdTest.java
extensions/binding/org.eclipse.smarthome.binding.onewire/ESH-INF/thing/bridge.xml
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/OwBindingConstants.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/SensorId.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/Util.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/device/OwSensorType.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/AdvancedMultisensorThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/BasicMultisensorThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/EDSSensorThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/OwBaseThingHandler.java
extensions/binding/org.eclipse.smarthome.binding.onewire/src/main/java/org/eclipse/smarthome/binding/onewire/internal/handler/TemperatureSensorThingHandler.java

- better dynamic channel handling
- add test to make sure all sensors types have associated thing-types
- add test to make sure all thing types have labels for auto-discovery

[OneWire] code improvements

---

extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/handler/HueBridgeHandler.java

- Changed polling strategy, skip polling for lights or sensors if no things were defined

[hue] Changed polling strategy
